### ISSUE TITLE
Move a FileSet to a different work - Wire Frame

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1000]
Create a wireframe and flow for moving a FileSet from one work to the other

This could be similar to moving files between collections.

**Comment by mjgiarlo** [comment]
@mtribone Would you say this is in scope for the Sufia UI WG, or more a parking lot item?

**Comment by mtribone** [comment]
@mjgiarlo I'd say parking lot item, perhaps. We've committed to upload and editing, dashboard, and creating collections. It could be a part of editing, but we haven't broken them down just yet. Also might be an opportunity for an individual assignment to get code moving. I don't see it in the sprint wireframes.

**Comment by mjgiarlo** [comment]
OK, I'm moving this to the 7.1.0 milestone instead of 7.0.0 to reflect that this is parking lotted. Thanks, @mtribone!

**Comment by mjgiarlo** [comment]
Refs #1074.
