### ISSUE TITLE
Access Rights Should be copied to All the files in the work

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1001]
When I change access rights on a work
Then all files in work should get the new permissions copied to them

**Comment by cam156** [comment]
dependent on #996

**Comment by hectorcorrea** [comment]
This ticket includes updating the controller to update all files within a work with the permissions set at the work level.

For this iteration we will implement this inline (i.e. not via a batch job) because we want to make sure permissions changes are applied immediately.
