### ISSUE TITLE
Wire frame the show page of a GenercWork

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1002]
Should show the files attached
Should show the descriptive metadata

Could be similar to collection

**Comment by elrayle** [comment]
See wireframes for creating a work at...

[Sufia Sprint UI Design](https://wiki.duraspace.org/x/HqQOB)
* section Actions -> Show Pages
 * depositor view
  * View Work Detail Page
 * non-depositor view
  * View Work Detail Page
