### ISSUE TITLE
Change Featured Items to Works

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1004]
Featured Items should reference Works

In the homepage controller the Featured Items now filters for GenericFiles and Collections, it should now show works and collections

**Comment by cam156** [comment]
dependant on #996

**Comment by hectorcorrea** [comment]
This does not include the workflow to make a Work a Featured Work. That will be handled via a separate ticket.

**Comment by hectorcorrea** [comment]
See also #1049

**Comment by grosscol** [comment]
I'll work on this.
