### ISSUE TITLE
Recently Uploaded Should Show Works

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1005]
Recently Uploaded should return the recent GenericWorks
Recently uploaded should not include GenericFiles

In the homepage controller the Recently uploaded now filters for GenericFiles and Collections, it should now show works and collections

**Comment by cam156** [comment]
Dependent on #996

**Comment by hectorcorrea** [comment]
Change the query to fetch recent *files* to fetch recent *works*. We shouldn't need to change the view that renders the recent files (as long as we can populate all the fields from a work)
