### ISSUE TITLE
Convert GenericWork to PCDM

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1007]
Convert the GenericWork (created in ticket #996) to model the Hydra::PCDM::Object

Use the new structure with indirect containers so the correct LDP will get generated.

dependent on projecthydra-labs/hydra-pcdm#4

This ticket includes converting the mock generic work (ticket #996) to the new official class. We will assume that the hydra class will have been implemented and tested.

**Comment by mjgiarlo** [comment]
Done.
