### ISSUE TITLE
Determine how we will identify the Thumbnail File in the GenericFile

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1010]
How will we identify which hasFile is the thumbnail to display for each object

**Comment by awead** [comment]
@cam156 this might a good one for @escowles and I pair on.

**Comment by cam156** [comment]
:+1:

**Comment by cam156** [comment]
@awead I wonder if this should be a ticket on hydra-works instead of sufia.

**Comment by awead** [comment]
@cam156 I have no opinions on that, so sure?

**Comment by mjgiarlo** [comment]
:+1: for hydra-works

**Comment by grosscol** [comment]
Any movement on this?  It's related to #1150.  As soon as `hasFiles :files ...` is substituted for `contains 'content'` and `contains 'thumbnail'` there are going to be problems with the calls to GenericWork.content.

**Comment by escowles** [comment]
@grosscol: We've added a file use vocab to PCDM ext directory: https://github.com/duraspace/pcdm/blob/master/pcdm-ext/use.rdf

So we should use those classes to figure out which files are which.  So the thumbnail should have rdf:type <http://pcdm.org/use#ThumbnailImage>, the original file should have rdf:type <http://pcdm.org/use#OriginalFile>, etc.

**Comment by mjgiarlo** [comment]
This does not seem to be an issue in Sufia master. Closing.
