### ISSUE TITLE
Change Transfer to transfer Works instead of files

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1011]
Change the transfer to allow transferring of works not files

**Comment by cam156** [comment]
dependent on #996

**Comment by cam156** [comment]
Transferring all files and the work to the new user.   This means depositor would be changed on all files and the work.

**Comment by val99erie** [comment]
In PR #1093, I added skips for several specs because the specs were failing and the transfer work wasn't done yet.

For this story please either fix these specs, or delete them if they are no longer appropriate.  The specs are in this file:
spec/features/ownership_transfer_spec.rb

**Comment by grosscol** [comment]
I fixed the ownership transfer specs in the course of this work.  However, the specs that deal with the UI of transfering a work have all but gutted and replaced with pending as the UI was not implemented.  I plan on undertaking the UI of transferring works next.
