### ISSUE TITLE
Wireframe GenericFile Show page to brand it as part of the work

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1018]
Make sure that the user knows this is part of a whole if they somehow get to the GenericFile Show  via a direct link.

**Comment by mjgiarlo** [comment]
:+1:

**Comment by mtribone** [comment]
Is this similar to #1002?

**Comment by mtribone** [comment]
Similar to current Sufia GenericFile, but needs to indicate it's part of a work. So if someone follows a URL from before that they now see the reference to the new model.

**Comment by elrayle** [comment]
The  wireframes do not have a Show page for GenericFile  that is separate from the work.  Additional information on the GenericFile is gathered by expanding it on the Work Show page.

See wireframes...
[Sufia Sprint UI Design](https://wiki.duraspace.org/x/HqQOB)
* section Actions -> Show Pages

**Comment by elrayle** [comment]
RE: Mikes question about this being similar to #1002.  That is describing the show page for a Work which does have wireframes and as mentioned above, the Work Show page includes GenericFile metadata in the expansion section for each file.

**Comment by elrayle** [comment]
If others agree with this approach, the ticket can be closed.
