### ISSUE TITLE
Update the GenericFile Show page to only show Title and technical metadata

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1019]
Update the GenericFile show page to remove most of the descriptive metadata.
This metadata will be applied at the work level and not the GenericFile level.

Fits Characterization and File label/title should still be shown

**Comment by cam156** [comment]
@mjgiarlo This corresponds to what we discussed last night.  Did I capture it correctly?

**Comment by mjgiarlo** [comment]
Sounds good to me!

**Comment by cam156** [comment]
This is specifically removing information from the generic_file/descriptive_metadata partail
