### ISSUE TITLE
sufia_events uses PidBasedJob examples

### ISSUE THREAD

**Issue by narogers** [projecthydra/sufia#1025]
Anybody who tries to copy the examples in config/initializer/sufia_events.rb will get an error if they wrote an ActiveFedoraIdBasedJob instead because it takes one argument. Once PidBasedJobs are completely deprecated it would be helpful to update this.

**Comment by mjgiarlo** [comment]
The jobs that are listed in sufia_events.rb are subclasses of `EventJob`, though, which still take two arguments (other than the restored version event job, which takes three):

https://github.com/projecthydra/sufia/blob/master/app/jobs/event_job.rb

Are you seeing breakages that seem to be related to sufia_events.rb?

**Comment by narogers** [comment]
Once I fixed my method signature everything was fine. It may have had been the way that I was using the event hooks to do additional metadata extraction (https://github.com/ClevelandArtGIT/cma-archives/blob/master/config/initializers/sufia_events.rb).

**Comment by mjgiarlo** [comment]
OK.  Related: did adding that file to cma-archives blow away the default Sufia behavior?  That is, when you create content, is this still happening:

```ruby
  Sufia.queue.push(ContentDepositEventJob.new(generic_file.id, user.user_key))
```

:question:
