### ISSUE TITLE
My Collections should be overriable

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1026]
Currently the my collections is just in a class.  It does not have a backing behavior.
To override/enhance the behavior the entire class needs to be copied

I suggest moving the current code into a behavior and including that in the class to make for easier overrides.

**Comment by grosscol** [comment]
This appears to already be done.  https://github.com/projecthydra/sufia/blob/7eaeef5e197b14b401e01fc52d55b1125a787f94/sufia-models/app/models/sufia/collection.rb
