### ISSUE TITLE
sufia.gemspec should exclude sufia-models from the files directive

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1035]
https://github.com/projecthydra/sufia/blob/master/sufia.gemspec#L11

**Comment by mjgiarlo** [comment]
Can you say why?  Is it causing bugs?  Performance issues?  Bloat?  Confusion?  etc.

**Comment by awead** [comment]
@mjgiarlo this https://gist.github.com/hackmastera/52361c91226a857ceb61

**Comment by mjgiarlo** [comment]
Thanks!

**Comment by jcoyne** [comment]
@mjgiarlo we're already shipping sufia-models as its own gem. We don't want the same code to be in the sufia gem.

**Comment by mjgiarlo** [comment]
You've already submitted the PR, so no worries. :)
