### ISSUE TITLE
Test and its opposite both pass

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#1038]
To recreate this bug, negate line 22 of spec/features/ingest_upload_files
https://github.com/projecthydra/sufia/blob/master/spec/features/ingest_upload_files_spec.rb#L22

e.g.,
        expect(page).not_to have_content "Please accept Deposit Agreement before you can upload."

run the test
$ bundle exec rake spec SPEC=spec/features/ingest_upload_files_spec.rb

I am seeing the test pass both ways. Appreciate an attempt to replicate.

**Comment by jcoyne** [comment]
`#find()` doesn't take a block, or it doesn't yield it anyway.

**Comment by hackmastera** [comment]
Yes thank you that totally fixes it! I could submit a PR but waiting on the license agreement paperwork.
