### ISSUE TITLE
"Select files..." button in Upload should not require double-click in IE

### ISSUE THREAD

**Issue by mephillips-durham** [projecthydra/sufia#1039]
If you go to Upload Files on the first screen there is the "My Computer" tab where you can select files to upload. On Internet Explorer 10 operting in standards mode, it requires a double-click on the "Select files" button to open the Windows file selector window.  With Chrome and Firefox this button only requires a single mouse click, which is what I would have expected.  Indeed, I thought it was completely broken in IE for some while before I accidentally double-clicked.
![image](https://cloud.githubusercontent.com/assets/3178149/7164139/36ffca8a-e396-11e4-842a-10c0ae5077fb.png)

**Comment by TimPacker** [comment]
This looks like the same issue as https://github.com/tors/jquery-fileupload-rails/issues/33 .

Much as suggested on that issue, adding the following to the site javascript seems to solve it, though it's a bit hacky:

```javascript
$(function () {
    if (navigator.userAgent.indexOf("MSIE 10") > 0) {
        $(".fileinput-button input").bind('mousedown',function(event) {
            $(this).trigger('click')
        });
    }
});
```

**Comment by atz** [comment]
I suggest we just wait for the upload library to fix it upstream.  It is certainly more important to them than it is to us, and I would rather not have to back out hacks later.

**Comment by mjgiarlo** [comment]
Agree with @atz. Thanks, all.
