### ISSUE TITLE
Solrconfig.xml refers to ExtractingRequestHandler but source isn't provided

### ISSUE THREAD

**Issue by pgwillia** [projecthydra/sufia#1041]
[rake sufia:jetty:config](https://github.com/projecthydra/sufia/blob/master/sufia-models/lib/tasks/sufia-models_tasks.rake#L52-L65) doesn't downloading solr-cell-4.10.4.jar when getting the other extraction jars.  solr-cell.jar is not included in hydra-jetty and contains ExtractingRequestHandler. [ExtractingRequestHandler](https://github.com/projecthydra/sufia/blob/master/sufia-models/lib/generators/sufia/models/templates/config/solrconfig.xml#L156-L167) is one of the request handlers in the solrconfig.xml provided by the Sufia generator. 

Error from log:
```
org.apache.solr.common.SolrException: lazy loading error
...
Caused by: java.lang.ClassNotFoundException: solr.extraction.ExtractingRequestHandler
```

**Comment by pgwillia** [comment]
I'm wrong.  It's [there](https://github.com/projecthydra/sufia/blob/master/sufia-models/lib/tasks/sufia-models_tasks.rake#L16).

**Comment by pgwillia** [comment]
Local problem, corrupted download from maven.

**Comment by mjgiarlo** [comment]
I've seen corrupted downloads from maven before, too.  I wonder if this method could use a check to make sure the file is a valid jarfile?  https://github.com/projecthydra/sufia/blob/master/sufia-models/lib/tasks/sufia-models_tasks.rake#L67-L81

**Comment by mjgiarlo** [comment]
:arrow_up: @pgwillia

**Comment by pgwillia** [comment]
Yeah a check would be a good idea.  This is the value of all the extraction jars:
```
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/0.8.55</center>
</body>
</html>
```

**Comment by pgwillia** [comment]
Some of this has been addressed recently: https://github.com/projecthydra/sufia/commit/997d59614e3b5aa2284a021e3c9c92f595a0db8c and https://github.com/projecthydra/sufia/commit/15794ebb8b364424ca2cfa3b39c7514cf823a1e5.

**Comment by mjgiarlo** [comment]
Thanks, yeah, those are related.  https://github.com/projecthydra/sufia/commit/997d59614e3b5aa2284a021e3c9c92f595a0db8c was put in because *all* jars came back as 150ish-byte HTML files.  The latter was put in because the rake task wouldn't even work in some environments (https://gist.github.com/jhallida/2c9603ea782dc6a16a52). If you're seeing that *some* jars come back OK and some do not, we may need more work done to validate what comes back from Net::HTTP.

**Comment by pgwillia** [comment]
The manual test for a valid jar I was doing is:
```jar -tf path/to/jarfile.jar``` a valid jar won't respond in error.

Does this translate to ruby/rake?

**Comment by mjgiarlo** [comment]
@pgwillia There's a Ruby library called `mimemagic` that may be able to help.  I took the HTML above and created a file called test.jar, and copied a real jar called jmx.jar, and tested this library on them. See the output here:

```ruby
[1] pry(main)> require 'mimemagic'
true
[2] pry(main)> MimeMagic.by_magic(File.open('test.jar'))
=> #<MimeMagic:0x0000000113ed08 @mediatype="text", @subtype="html", @type="text/html">
[3] pry(main)> MimeMagic.by_magic(File.open('jmx.jar'))
=> #<MimeMagic:0x0000000190cd78 @mediatype="application", @subtype="zip", @type="application/zip">
```

**Comment by mjgiarlo** [comment]
Pinging @jcoyne and @terrellt for their thoughts on the above.

**Comment by terrellt** [comment]
@mjgiarlo: Mimemagic looks shiny, I've used https://github.com/blackwinter/ruby-filemagic before but it requires magic(4) be installed, which can get interesting.

**Comment by mjgiarlo** [comment]
Yeah, boo on another system dependency.

**Comment by mjgiarlo** [comment]
How about something like this:

```ruby
require 'mimemagic'

# ...

def download_from_maven url, dst
  full_url = '/remotecontent?filepath=' + url
  file = File.open(dst, "wb")
  endpoint = Net::HTTP.new('search.maven.org', 443)
  endpoint.use_ssl = true
  endpoint.start do |http|
    puts "Fetching #{full_url}"
    http.request_get(full_url) do |resp|
      resp.read_body { |segment| file.write(segment) }
    end
    retry if MimeMagic.by_magic(file).type == 'text/html'
  end
ensure
  file.close
end
```

**Comment by cam156** [comment]
@pgwillia @mjgiarlo Can this issue be closed?

**Comment by mjgiarlo** [comment]
I defer to @pgwillia

**Comment by pgwillia** [comment]
I'm going to close it. The bug that made this an issue has been resolved so no use going to far with something that's not really a major issue.
