### ISSUE TITLE
'Please fill out this field' notification not working Safari 8.0.3

### ISSUE THREAD

**Issue by paluchas** [projecthydra/sufia#1042]
Safari 8.0.3 does not guides users in "Apply Metadata" submission screen with respect to mandatory fields (e.g.Keyword etc.). 

When pressing "Save" button I would expect to see (like in Firefox) 'Please fill out this filed' pop out presented alongside the empty mandatory filed with switched focus. I'll be encouraged to fill missing information. Instead pressing "Save" button in Safari does not trigger any action and submission screen has no change. This is very confusing and it is not obvious to me what I should done to save resource.

Note attached screen shot was taken in Firefox and presents expected behaviour:
![screen shot 2015-04-17 at 12 31 49](https://cloud.githubusercontent.com/assets/1863245/7201513/f9921d54-e4ff-11e4-9194-2a7707452782.png)

**Comment by cam156** [comment]
@paluchas it looks like safari does not support html5 validation that we are using. http://caniuse.com/#feat=form-validation

Once safari supports html5 validation this should work.
