### ISSUE TITLE
Mark a Work as Featured Work

### ISSUE THREAD

**Issue by hectorcorrea** [projecthydra/sufia#1049]
Implement workflow to mark a Work as a "Featured Work" (this would be to replace the "Featured Files" feature once we implement PCDM)

**Comment by cam156** [comment]
This is dependent on #1065.

**Comment by cam156** [comment]
The feature option is currently on the show page of a file in the action list:

![screen shot 2015-04-29 at 10 44 35 am](https://cloud.githubusercontent.com/assets/1599081/7393618/da95e794-ee5c-11e4-9257-5de3b3977cd4.png)

**Comment by gordonleacock** [comment]
Should the feature/unfeature action show on the works list under "My works" or on each work's individual page?

**Comment by gordonleacock** [comment]
Or on the work's edit page?

**Comment by mjgiarlo** [comment]
@gordonleacock I incline towards doing what 6.x does, and leaving it on the show page. Once it's working and 7.0.0 is out, we can chat about changing the behavior.

**Comment by hectorcorrea** [comment]
@gordonleacock @mjgiarlo For now I've added the Feature/Unfeature buttons on the Work Show page. Only one of them is displayed at a time (if at all) 

![screen shot 2016-01-07 at 11 54 31 am](https://cloud.githubusercontent.com/assets/568286/12176486/9c1aa2ac-b535-11e5-94b4-0f31a54aa2a2.png)

**Comment by gordonleacock** [comment]
Thanks for the heads up Hector!


----------------
Gordon Leacock (cell phone)
