### ISSUE TITLE
Make Collection Show page load regardless of collection size

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1055]
In ScholarSphere we have overridden Sufia since the current implementation can take more than an hour to load a collection.  This was causing our passenger server to spin out of control when a user or bot access a collection. 

https://github.com/psu-stewardship/scholarsphere/commit/cef7d387e5f52f9ef7e589297ea4ba87179c4506

**Comment by narogers** [comment]
Once I get enough content ingested to do some scaling tests I will take a look into this problem. It seems to affect even collections with only about 25 members (which may be partially due to my server environment).

**Comment by cam156** [comment]
@narogers yes it does not take many files before there is an issue.  a few large files would also do the trick.

**Comment by narogers** [comment]
This fix should resolve the issue but may need to be cleaned up a little if there is an easier way to make the Solr query happen

https://github.com/narogers/sufia/commit/002b279aa205016e33160bd6ba8a322069717dd5

**Comment by mjgiarlo** [comment]
I believe CurationConcerns is already handling this.
