### ISSUE TITLE
Implement Work Creation Page

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1067]
As described by the wireframe: https://wiki.duraspace.org/pages/viewpage.action?pageId=68070083#mockup_action_create_work

We may want to skip the upload into a collection for the initial implementation.  A collection is not required for a work to be uploaded.

dependent on #998

**Comment by hortongn** [comment]
@cam156 In case this can be easily answered before our 2:30 meeting, here is the problem I'm having with the create work form:

In app/views/curation_concern/base/_form.html.erb this line 
`<%= simple_form_for [:curation_concern, curation_concern], html: { multipart: true } do |f| %>`

is giving me the error **undefined method curation_concern_generic_works_path** and I'm not sure why.  It seems like curation_concern is what we should be passing.

**Comment by cam156** [comment]
@hortongnI would suggest this:   [generic_works, @form]  It does not match up with the worthwhile pattern though.

**Comment by hortongn** [comment]
@cam156 I had tried that.  Tried it again and it gives me 
Undefined local variable or method `generic_works`

**Comment by hortongn** [comment]
I’ll miss today’s stand up due to another meeting.  So I’ll give an update here.  Once @cam156 and @mjgiarlo helped me get past my routing blocker Friday afternoon, I got the create work page rendering.  I can create and edit works, but I need to get the page layout to better match the wireframe and get permissions working correctly.  I’ll be able to work more on that this afternoon.

**Comment by hortongn** [comment]
In https://github.com/projecthydra/sufia/blob/fix-1067/spec/views/curation_concern/base/_form.html.erb_spec.rb I'm not sure why I'm geting the error below when I run the test.  What am I missing?

1) curation_concern/base/_form.html.erb should draw the metadata fields for a work
     Failure/Error: render
     ActionView::Template::Error:
       undefined method `authenticate' for nil:NilClass

**Comment by cam156** [comment]
I'm guessing it is related to can can.  Try adding something similar to: https://github.com/projecthydra/sufia/blob/pcdm/spec/views/catalog/sort_and_per_page.html.erb_spec.rb#L5-L6

**Comment by hortongn** [comment]
@cam156 That worked.  Thanks!

**Comment by hortongn** [comment]
I just noticed that the wireframe has the `title` field as being a single field instead of a multi-value.  Should I modify the generic work model to use a scalar value for `title` instead of an array?  Will that break other things?  Or should I try to deal with it in the view/simpleform?

**Comment by cam156** [comment]
@hortongn If you handle it at the model layer, simple form should do the correct thing.
Collection has it set to multiple:false here: https://github.com/projecthydra/hydra-collections/blob/master/app/models/concerns/hydra/collections/metadata.rb#L16
