### ISSUE TITLE
Implement work Add Files

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1068]
Implement the work File upload page.
https://wiki.duraspace.org/pages/viewpage.action?pageId=68070264#mockup_action-create_work-add_files

Currently there are no tickets for the work controller.  Do the files get filtered through the work controller, or do they get passed to the GenericFile controller with a work_id.  I might lean toward the latter, but it could be done any way.  We should look at worthwhile for a good pattern here.

**Comment by cam156** [comment]
dependent on #996

**Comment by mjgiarlo** [comment]
We now have a working "add files to work" page. Closing.
