### ISSUE TITLE
GenericFile forms and presenters should use Work

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1075]
Rename GenericFilePresenter and GenericFileEditForm to reference GenericWork.

**Comment by cam156** [comment]
@awead This ticket seems a bit off.  Wouldn't we want forms and presenters for both Generic Work and Generic File?

**Comment by awead** [comment]
@cam156 I was thinking we were using Work as a replacement for File, but really we just need to have forms and presenters for both.

**Comment by cam156** [comment]
@awead I'm going to close this since #1091 basically coverd this issue.
