### ISSUE TITLE
Where does the Batch go?

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1076]
The Batch object is currently linked to the GenericFile. If we proceed by moving it to the GenericWork, it could present issues when moving files to other works, or adding new files to existing works. One solution could be to attach pcdm:File objects to the batches. This would enable files to retain their original batch designations regardless of what work they're moved or added to.

**Comment by cam156** [comment]
For the current sprint I'm punting on this issue.  I think leaving them at the GenericFile until we figure out if they really have meaning in the new world makes sense.

I will leave the ticket open though so we do not lose sight of the issue.

**Comment by mjgiarlo** [comment]
GenericWorks now belong to UploadSets (née Batches). Closing!
