### ISSUE TITLE
Change Highlighted Files to Highlighted Works

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1079]
Show Highlighted works in the My Highlights List and allow a Highlight action on Works.

This will include moving the highlight action from files to works in the controllers.

Additionally Highlights on the user profile will need to show works.

**Comment by cam156** [comment]
This is still be in the code (not at the UI) as trophy.  So instance of trophies or highlighted files both need to move to works.

**Comment by tingtingjh** [comment]
Is there a separate ticket involving remodeling trophy in generic file? Then this ticket will have dependency on that. Or this ticket involves both UI and remodeling?

**Comment by tingtingjh** [comment]
Need to make a new migration for trophies to be included in ./sufia_models/lib/generators/sufia/models/upgrade700_generator.rb, as pcdm migration is likely to be in sufia 7.0
