### ISSUE TITLE
Full Text Search of a Work

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1084]
Make sure that a full text search of a work will produce files contained in works. 

I upload a file with foo in the contents
That File is part of a work work1
When I search for foo
Then I should see work1 in the search results.

**Comment by cam156** [comment]
depends on #994

**Comment by mjgiarlo** [comment]
Verify that this is working before closing.

**Comment by njaffer** [comment]
@cam156, @mjgiarlo: I created a file with 'foo' as content and saved as pdf. Uploaded the file, it gave me an error saying 'Internal server error', but still it did upload the file. Not sure the internal server error means that Full Text Extraction failed? When I search for foo, I do not get the Work that has this file.

**Comment by mjgiarlo** [comment]
Is it a valid PDF? (For instance, if you run it through FITS.) If so, you shouldn't see an error and the full-text search should work.

**Comment by njaffer** [comment]
I created the file using Word and saved as pdf. I can run it through FITS and did not get any error, but when I upload it through dashboard, I get this error, although it is uploaded and I can see it in Test Work
![screen shot 2016-01-14 at 4 00 52 pm](https://cloud.githubusercontent.com/assets/12487929/12337424/0e611e8e-bad8-11e5-9ee1-e8baaab5fc5e.png)

**Comment by njaffer** [comment]
![screen shot 2016-01-14 at 4 02 58 pm](https://cloud.githubusercontent.com/assets/12487929/12337482/52b81b64-bad8-11e5-9c10-0c499be10c48.png)

**Comment by cam156** [comment]
@njaffer Do you get an error in the server logs?  That might help to determine where the issue is happening.  Does it always fail on this file?  Do other files work?

**Comment by njaffer** [comment]
@cam156 , here is the log
https://gist.github.com/njaffer/5f6d75f15fb99f36ca7c
The error is about MiniMagick in Hydra Derivatives

**Comment by cam156** [comment]
@njaffer That would lead me to believe it is having issues with the thumbnail generation, but it is hard to be certain.

**Comment by grosscol** [comment]
I wonder if it's a pdf formatted in such a way that it causes some parsers to barf.  I'm not surprised that  FITS doesn't throw errors, but I wonder what FITS thinks the file actually is.  I've passed files with bad magic numbers to FITS and the tools, such as jhove, that it uses still managed to return valid data.

I think this brings up a different problem in that we need to handle files that get uploaded and look like a kosher version of some type that we handle, but causes some tool to barf.  Maybe a backlog issue of "Handling pathological files and filetypes."  I know that is something I'll have to tackle at some point anyhow.

**Comment by mjgiarlo** [comment]
Are you still working on this ticket, @njaffer, or is it available for someone else to pick up?

**Comment by njaffer** [comment]
@mjgiarlo:  No I'm not. Sorry I didn't realize that it was still assigned to me!

**Comment by mjgiarlo** [comment]
np!

**Comment by mjgiarlo** [comment]
Closing.
