### ISSUE TITLE
Move Sufia::Works:GenericWork to GenericWork

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1086]
The namespaces are giving us issues.

**Comment by scherztc** [comment]
We left the model outside of the main model directory in curate and used FactoryGirl to simulate the creation of new works in our specs: https://github.com/projecthydra-labs/curate/blob/develop/spec/factories/generic_works_factory.rb

**Comment by grosscol** [comment]
I'm going to take a stab at this.  It would be nice to be able to do GenericWork.new from the rails console in the same way that GenericFile.new can be called.  Additionally, I expect it will make calls such as create(:generic_work) in the specs function as expected.

As per @scherztc suggestion, I'll take a look a look at how Curate is doing things.

**Comment by cam156** [comment]
comment from flyingzumwalt
3:54 cam156 it would be great if you make GenericWork in sufia-models/app/models/generic_work.rb and have it include a module that is a single point of entry for mixing in the necessary behavior.  That will make it much easier for us to refactor the modules to use Hydra::Works wherever relevant.

**Comment by cam156** [comment]
I put in a PR that includes the controller from worth while too.  I had to make a couple of concessions for where the work is located (like adding a last command here https://github.com/projecthydra/sufia/pull/1087/files#diff-0f0bba919cece2f949a5df16e5f32c32R109)

**Comment by grosscol** [comment]
Okay.  So I'll have to convert Sufia::Works::Work from a class to a module.  That way, the Sufia::GenericFile class can have a single module include for the Sufia::Works::GenericFile module.... which will in turn include the Sufia::Works::Work module.

Then see what that all breaks.

**Comment by grosscol** [comment]
Got the GenericWork class and Sufia::Works Concerns sorted out. The specs are failing on the generic work actors due to calls to attach_file which is attempting to attach an uploaded file.   I don't know if this is a new failure, or one that was just uncovered by shuffling things around.  Hopefully, @cam156 will be able to help me out or point me in the right direction with the failing generic work actor spec. 

https://gist.github.com/grosscol/9590c30a642d4c88202f

**Comment by cam156** [comment]
I will pull your branch in the morning.  We have some brittle test, so it could be that, or a bug has been uncovered.  Thanks Colin

-- Carolyn
