### ISSUE TITLE
Visibility badge/link on "My Files" dashboard

### ISSUE THREAD

**Issue by val99erie** [projecthydra/sufia#1103]
The "My Files" page on the dashboard has been changed to show works instead of files.  On the old "My Files" page, each file had a visibility badge that was a link to the "permissions_display" tab on the edit form.  We'll need a similar visibility badge for the GenericWorks on the page.

Acceptance criteria for this story:
- [x] Add a visibility badge for each GenericWork listed on the "My Files" page.
- [ ] The visibility badge should be a link to the permissions edit page for the GenericWork 

The visibility badge renders A-OK for each GW in the "My Works" view, but the link is wrong. Currently it's pointing at `/concern/file_sets/{id}/edit#permissions_display` instead of `/concern/generic_works/d791sg234/edit#permissions_display`. On top of that, the latter URL is no longer a tabbed display, the so `#permissions_display` could/should be an anchor on the `<h2>Permissions</h2>` instead.

**Comment by val99erie** [comment]
Do we have a screenshot for how the GenericWork edit page will look?  Will it have the same kind of permissions_display tab that the GenericFile edit page has?

This story is blocked until the edit form for GenericWorks is done.

**Comment by cam156** [comment]
Here is a wire frame for the permissions portion of the Work Edit: https://wiki.duraspace.org/pages/viewpage.action?pageId=68071269

**Comment by mjgiarlo** [comment]
The visibility badge renders A-OK for each GW in the "My Works" view, but the link is wrong. Currently it's pointing at `/concern/file_sets/{id}/edit#permissions_display` instead of `/concern/generic_works/d791sg234/edit#permissions_display`. On top of that, the latter URL is no longer a tabbed display, the so `#permissions_display` could/should be an anchor on the `<h2>Permissions</h2>` instead.

**Comment by njaffer** [comment]
By changing this line : https://github.com/projecthydra/sufia/blob/206a268bdeca453bfe071cf64695b7983d625ff6/app/helpers/sufia/sufia_helper_behavior.rb#L118
to generic_work path, I can see the page to edit the permissions @mjgiarlo , is there something else needed to be done for this issue for the tabbed display you mentioned?

**Comment by mjgiarlo** [comment]
@njaffer That helper method uses the `permissions_display` anchor to focus the page on the part related to permissions. Does that anchor exist in the page that's rendered?

**Comment by njaffer** [comment]
No it does not, the page http://localhost:3000/concern/generic_works/5m60qr88b/edit#permissions_display
is displayed as 
http://localhost:3000/concern/generic_works/5m60qr88b/edit

Ok so the other change needed is to add anchor tag to the Permissions heading.. Thank you @mjgiarlo

**Comment by mjgiarlo** [comment]
Are you still working on this ticket, @njaffer, or is it available for someone else to pick up?

**Comment by njaffer** [comment]
@mjgiarlo: I would say it can be closed with #1505

**Comment by mjgiarlo** [comment]
Whoever takes this ticket, please verify this can be closed.

**Comment by mjgiarlo** [comment]
This is done.
