### ISSUE TITLE
Collection Size

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1120]
Collection Size must include the size of a work.

At this line: https://github.com/projecthydra/sufia/blob/master/sufia-models/app/models/concerns/sufia/collection_behavior.rb#L21

Works do not have content to determine size from bytes.  Need to add in a work size, and allow the collection to get the size.

**Comment by awead** [comment]
This could potentially be a resource-intensive task if there are multiple works and files. Could this be a value stored in Solr and updated when the collection's contents are updated? And then, updated via a batch job?

**Comment by cam156** [comment]
@awead  I have been thinking on this.  It would be best if the size was store in the work, and updated when the work changes.  For ScholarSphere I changed the collection size to be a solr query, but storing it in the solr document so it was only one query would be best.  

I'm thinking work to_solr includes a size and the size gets stored in the object and only gets recalculated when the files in the work change.

Does that seem  right?

**Comment by cam156** [comment]
@awead the same approach could be used for the collection.
