### ISSUE TITLE
processing a work

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1122]
We currently do not have a concept of processing at the work level.  
The collection show page breaks here: https://github.com/projecthydra/sufia/blob/master/app/views/collections/_show_document_list_row.html.erb#L6-L10

We should remove the lines of code for processing I think in the short term from the view.

**Comment by grosscol** [comment]
Would stubbing the processing or having the processing call inspect the child generic files for processing be viable options?

**Comment by cam156** [comment]
@grosscol yes that would be a viable first step too.

**Comment by mjgiarlo** [comment]
The `#processing?` method is now available on works. It's declared in this module:
