### ISSUE TITLE
Processing on a work

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1123]
Should a work have the concept of in process in the dashboard?

If so do we collect up the file processing.  Does the work have it on it's own?

**Comment by mjgiarlo** [comment]
Works now have the concept of processing.

**Comment by mjgiarlo** [comment]
Mark a work as uneditable -- we used to use a magic wand icon to show that a work was still processing -- if it's still processing. There is commented-out code that you can start with:

https://github.com/projecthydra/sufia/blob/master/app/views/collections/_show_document_list_row.html.erb#L5-L9
