### ISSUE TITLE
Edit action in Collection for work

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1133]
Edit action should edit a work not a GenericFile
Additionally it should match with the wireframe and  only say "Edit"
https://wiki.duraspace.org/pages/viewpage.action?pageId=68069887

**Comment by cam156** [comment]
Remove Edit File in view below and add edit action that routes to the work edit
![screen shot 2015-05-11 at 2 05 24 pm](https://cloud.githubusercontent.com/assets/1599081/7571830/27f1c6fe-f7e8-11e4-9d0d-d677f28722c4.png)

**Comment by yinlinchen** [comment]
This ticket is covered by #1152

**Comment by rotated8** [comment]
@yinlinchen Almost. The edit action in #1152 still points to the edit_generic_file_path

**Comment by cam156** [comment]
They are two separate edits.  One (#1133) if for the Work, and one (#1152) is for the collection.

**Comment by yinlinchen** [comment]
![screen shot 2015-05-14 at 3 38 24 pm](https://cloud.githubusercontent.com/assets/7999195/7640125/51a07b9e-fa4f-11e4-854b-c37987c9c01a.png)
