### ISSUE TITLE
When works are added to a collection they need to be re-indexed

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1135]
When a work gets added to a collection we need to re-index that work.  This will allow render_collection_links( https://github.com/projecthydra/sufia/blob/pcdm/app/helpers/generic_work_helper.rb#L3) to work

**Comment by jcoyne** [comment]
It's much faster from an indexing standpoint to just do a second lookup from solr at display time if possible. Otherwise you also have to handle when the collection label changes.

**Comment by cam156** [comment]
@jcoyne: Are you suggesting that we should query solr in render_collection_links instead of indexing the data into the file?

**Comment by jcoyne** [comment]
@cam156 If we can do that, I think it simplifies things.
