### ISSUE TITLE
Allow a user to highlight a work from the my work listing

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1140]
The action in the my works listing has a todo.
We need to put this back in and allow users the ability to highlight works from the dashboard.

**Comment by cam156** [comment]
See TODO for highlight in action menu drop down
![screen shot 2015-05-12 at 9 34 48 am](https://cloud.githubusercontent.com/assets/1599081/7588297/36e2bac2-f88a-11e4-9d7b-24f2250f3af4.png)

**Comment by mjgiarlo** [comment]
This may have potential migration issues: assuming the migration path of "transmogrify your GFs into GWs with the same IDs, and create new FSs to contain binary content", we should make sure that the "trophies" feature works for GFs that are turned into GWs. Marking this as epic to wrap up this other work (which perhaps should be broken into smaller tickets).

**Comment by mjgiarlo** [comment]
Related to #1139.
