### ISSUE TITLE
Fix misleading Deprecation Warning

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra/sufia#1145]
initialize_fields is deprecated in controllers AND on GenericFile, but the deprecation warning on the controller method tells you to use the method on GenericFile.  It should, instead, simply tell you not to use the method at all.

Example:
https://github.com/projecthydra/sufia/blob/pcdm/app/controllers/concerns/sufia/files_controller_behavior.rb#L241

**Comment by jcoyne** [comment]
Just remove that method. It was deprecated 2 years ago here: https://github.com/projecthydra/sufia/commit/973daa80c5ef7b044f7072372bba5465d42dec6e
