### ISSUE TITLE
Sufia should use the directly contained hasFiles

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1150]
Instead of the current basic container implementation:
https://github.com/projecthydra/sufia/blob/b5e67274eb3964f763dd4e93fdc537cc829f090b/sufia-models/app/models/concerns/sufia/generic_file/content.rb#L7-L8

Don't begin until https://github.com/projecthydra/sufia/pull/1149 has been merged.

**Comment by mjgiarlo** [comment]
Done.
