### ISSUE TITLE
Fix aggregation delete (unpend tests)

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1170]
On the `pcdm` branch there are three tests marked pending in #1168 due to projecthydra-labs/activefedora-aggregation#21 being unresolved:

https://github.com/projecthydra/sufia/pull/1168/files#diff-f52248c0a760281c9b64bc71668cf8d7R169
https://github.com/projecthydra/sufia/pull/1168/files#diff-5f1733922b7f1bda59de5258c5655940R198
https://github.com/projecthydra/sufia/pull/1168/files#diff-5f1733922b7f1bda59de5258c5655940R217

Once projecthydra-labs/activefedora-aggregation#21 is closed, unpend these tests

**Comment by mjgiarlo** [comment]
No longer relevant.
