### ISSUE TITLE
Clean up/fix generator templates 

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1174]
There are three files in the https://github.com/projecthydra/sufia/tree/master/sufia-models/lib/generators/sufia/models/templates/config directory that are not present in the same form in the dummy app: 

* mailboxer.rb, which is present but looks different, probably because the mailboxer:install generator creates a newer version
* setup_mail.rb, which looks possibly useful but has a PSU-specific value
* clamav.rb, which causes the ClamAV feature to be broken in the dev and prod environments

I suspect that mailboxer.rb should be deleted, setup_mail.rb should be copied via the install generator with a non-PSU-specific default, and clamav.rb should be copied via the install generator (and added to the latest upgrade generator(s)).

**Comment by cam156** [comment]
@mjgiarlo I'm looking into this ticket.  clamav portion is fairly straight forward and a created a PR.
What were you thinking for the setup_mail?

**Comment by mjgiarlo** [comment]
@cam156 I'd probably change the default SMTP server to something not @ psu.edu (like smtp.example.org or another dummy value).
