### ISSUE TITLE
What does External Key mean in the Marketing Text Edit block

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1185]
What is the Text box below the editor for?  Anyone know?

![screen shot 2015-06-09 at 9 13 14 am](https://cloud.githubusercontent.com/assets/1599081/8058505/dacf22e8-0e87-11e5-9108-bb52158e6d21.png)

**Comment by mjgiarlo** [comment]
@hectorcorrea @awead @jcoyne do y'all know? If so, write a blurb here and feel free to close the issue. Thx!

**Comment by jcoyne** [comment]
I've never seen that

**Comment by hectorcorrea** [comment]
This seems to have been added by @val99erie back in Jan/Feb and it looks to me that it was related to the featured researcher but I have no idea if it is needed or not. 

For reference, look at git blame on these two files: 

https://github.com/projecthydra/sufia/blame/master/app/models/content_block.rb
https://github.com/projecthydra/sufia/blob/master/app/helpers/content_block_helper.rb

**Comment by mjgiarlo** [comment]
Good catch, @hectorcorrea. Here's the commit where the external_key came in:

https://github.com/projecthydra/sufia/commit/2b00e44e1d29b0407593a81152586d255e5838cc

From the generator: "This allows you to associate a user_key with a featured_researcher entry." There we go. Closing!
