### ISSUE TITLE
Admin Stats: Users by College or Campus

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1190]
As an administrator, I would like to determine the number of users in Sufia from each college or perhaps campus, who have deposited files.

I can input a college(s) or campus(s) and the total number of ScholarSphere users who’ve deposited files from that college or campus is displayed.

Link to export to csv

**Comment by cam156** [comment]
I wonder if this can entirely go into Sufia, since the filtering information would be coming out of the ldap.  Maybe we could do the basics in Sufia and add configuration in ScholarSphere.

**Comment by cam156** [comment]
Department, And Admin area might be possible

**Comment by mjgiarlo** [comment]
Maybe the feature is to organize users by some user attribute, and that code goes in Sufia.  And in ScholarSphere we use that code to organize by one or more LDAP attrs?  Maybe this is exactly what you had in mind. :)

**Comment by cam156** [comment]
@mjgiarlo This one may just be done in ScholarSphere for the moment, since these attributes are specific to scholarsphere.  I think I may have put the ticket in the wrong spot.

**Comment by mjgiarlo** [comment]
:ok:

**Comment by mjgiarlo** [comment]
Closing because this work went into ScholarSphere.
