### ISSUE TITLE
Actions in Collections Edit are in the wrong location

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1219]
Actions are hard to find in their current location.  Maybe they should be split.

![screen shot 2015-07-01 at 9 40 35 am](https://cloud.githubusercontent.com/assets/1599081/8455811/4ceb4524-1fd5-11e5-8d97-556cca9d3104.png)

**Comment by mtribone** [comment]
https://github.com/projecthydra/sufia/pull/1247
