### ISSUE TITLE
Uploaded file actions drop down menu obscured when screen width shrinks

### ISSUE THREAD

**Issue by Mahria** [projecthydra/sufia#1238]
Happened to notice a bug in the responsive design response to a narrower screen on the dashboard/files page. If clicking the "Select an action" dropdown menu for an uploaded file while browser is the width of laptop screen, six actions appear in dropdown. If browser's width is limited to half screen (maybe about tablet size), the dropdown menu is completely obscured within and behind its div "documents". A scroll bar does not appear to let you move down to see the menu.

This is in firefox.

![screenshot from 2015-07-09 11 35 23](https://cloud.githubusercontent.com/assets/9702586/8603677/9cef6230-262e-11e5-8c7c-046c73b1316e.png)

**Comment by mtribone** [comment]
It's a bit of a bugger, but I've adapted a similar solution.

https://github.com/twbs/bootstrap/issues/11037

![screen shot 2015-07-13 at 10 33 45 am](https://cloud.githubusercontent.com/assets/4163828/8652103/d91e2c2c-294a-11e5-9b84-cc612d2f16f7.png)

**Comment by mjgiarlo** [comment]
Fixed!  Will be available in next Sufia release. Closing this issue.  Thanks @Mahria!
