### ISSUE TITLE
Is there a way to pin the version of hydra-jetty?

### ISSUE THREAD

**Issue by kerchner** [projecthydra/sufia#1253]
Although I do realize that hydra-jetty is not a critical dependency of sufia (as production deployments are likely to use instances of Solr and Fedora that are separated from the app server), the hydra-jetty bundle is useful for development.  I was not able to easily discern a way of pinning the version of hydra-jetty (e.g. v8.3.1 vs. v8.4.0) so that the sufia:jetty:config will install a specific version.  Is there a currently a place to specify the hydra-jetty release to use?

This may be a relevant issue for others who want to more deliberately upgrade from pre-Fedora-4.2, which supports Java 7, to Fedora-4.2, which requires Java 8 - rather than upgrading by accident, so to speak.  Refer to https://github.com/projecthydra/hydra-jetty/issues/36

**Comment by mjgiarlo** [comment]
Here's the pattern:

https://bitbucket.org/uwlib/druw/src/882d102f64043db27b990f130ebbe337f28d4122/Rakefile?at=master#cl-7

Perhaps this should be in the README.

**Comment by kerchner** [comment]
Thanks.  I did notice that in an older version of sufia-dev.rake and tried it, but it didn't seem to work for me.  It may be worth another try, now that you're confirming I was on the right track.

Given that any new ```rake sufia:jetty:config``` will now result in hydra-jetty with Fedora 4.2 (as long as ```Jettywrapper.hydra_jetty_version``` is left unspecified), do you agree that it's safe to simply add to the sufia README that hydra-jetty requires Java 8?

**Comment by mjgiarlo** [comment]
That seems reasonable to me, @kerchner
