### ISSUE TITLE
undefined method 'depositor' for nil:NilClass

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#1254]
I'm seeing a bug while testing my production setup that I have never encountered in my development environment.

Sufia 6.2.0.

Action taken: upload a single file. The upload screen shows success and batches/ks65hc23n/edit begins to load, then gives a "something went wrong" error screen.

@jcoyne suggests that https://github.com/projecthydra/sufia/commit/d852947ba50876177a96e3f2b86d0b6714b28269 might be related.

stack trace is as follows:

I, [2015-07-15T19:42:26.553111 #24314]  INFO -- :   Rendered batch/_more_metadata.html.erb (343.4ms)
I, [2015-07-15T19:42:26.553182 #24314]  INFO -- :   Rendered batch/_metadata.html.erb (552.2ms)
I, [2015-07-15T19:42:26.567617 #24314]  INFO -- :   Rendered /opt/sufia-project/shared/bundle/ruby/2.2.0/gems/sufia-6.2.0/app/views/generic_files/_permission_form.html.erb (4.0ms)
I, [2015-07-15T19:42:26.567752 #24314]  INFO -- :   Rendered /opt/sufia-project/shared/bundle/ruby/2.2.0/gems/sufia-6.2.0/app/views/batch/edit.html.erb within layouts/sufia-one-column (572.3ms)
I, [2015-07-15T19:42:26.568027 #24314]  INFO -- : Completed 500 Internal Server Error in 1296ms (ActiveRecord: 1.4ms)
F, [2015-07-15T19:42:26.570526 #24314] FATAL -- : 
ActionView::Template::Error (undefined method `depositor' for nil:NilClass):
    1: <% depositor = f.object.depositor || batch.generic_files.first.depositor %>
    2: <% public_perm = f.object.permissions.map { |perm| perm.access if perm.agent_name == "public"}.compact.first %>
    3: <% public_perm = true if params[:controller] == 'batch' %>
    4: <% registered_perm = f.object.permissions.map { |perm| perm.access if perm.agent_name == "registered"}.compact.first %>
  sufia (6.2.0) app/views/generic_files/_permission_form.html.erb:1:in `__opt_sufia_project_shared_bundle_ruby_______gems_sufia_______app_views_generic_files__permission_form_html_erb__1117891131986023667_46492860'

**Comment by hectorcorrea** [comment]
What's the value of `f` when the view is being rendered? I would guess `f.object` is nil and hence the error.

Also, what's the value of `batch.generic_files` ?

**Comment by hackmastera** [comment]
@hectorcorrea I really wish the stack trace would tell me these things. I will try to log them.

**Comment by hackmastera** [comment]
@hectorcorrea I can say that my suspicion is that f.object is fine, but its depositor is nil. This is because the stack trace shows metadata templates rendering successfully, and they also refer to f.object.

**Comment by hackmastera** [comment]
Okay I got some info. Here's what I put in to log:
    1: <% Rails.logger.info "VARS: f.object: #{f.object.inspect}"  %>
    2: <% Rails.logger.info "VARS: f.object.depositor: #{f.object.depositor}"  %>
    3: <% Rails.logger.info "VARS: batch: #{batch.inspect}"  %>
    4: <% Rails.logger.info "VARS: batch.generic_files: #{batch.generic_files.inspect}"  %>
    5: <% Rails.logger.info "VARS: batch.generic_files.first: #{batch.generic_files.first}"  %>

Result:

I, [2015-07-16T15:19:44.795352 #25755]  INFO -- : VARS: f.object: #<BatchEditForm:0x007efe5d88e6d8 @model=#<GenericFile id: nil, mime_type: nil, format_label: [], file_size: [], last_modified: [], filename: [], original_checksum: [], rights_basis: [], copyright_basis: [], copyright_note: [], well_formed: [], valid: [], status_message: [], file_title: [], file_author: [], page_count: [], file_language: [], word_count: [], character_count: [], paragraph_count: [], line_count: [], table_count: [], graphics_count: [], byte_order: [], compression: [], color_space: [], profile_name: [], profile_version: [], orientation: [], color_map: [], image_producer: [], capture_device: [], scanning_software: [], exif_version: [], gps_timestamp: [], latitude: [], longitude: [], character_set: [], markup_basis: [], markup_language: [], bit_depth: [], channels: [], data_format: [], offset: [], frame_rate: [], label: nil, depositor: nil, arkivo_checksum: nil, relative_path: nil, import_url: nil, part_of: [], resource_type: [], title: [], creator: ["admin@chemheritage.org"], contributor: [], description: [], tag: [], rights: [], publisher: [], date_created: [], date_uploaded: nil, date_modified: nil, subject: [], language: [], identifier: [], based_near: [], related_url: [], bibliographic_citation: [], source: [], proxy_depositor: nil, on_behalf_of: nil, genre_string: [], artist: [], author: [], creator_of_work: [], interviewee: [], interviewer: [], manufacturer: [], photographer: [], date_original: [], date_published: [], extent: [], medium: [], physical_container: nil, place_of_interview: [], place_of_manufacture: [], place_of_publication: [], provenance: nil, rights_holder: nil, batch_id: nil>, @attributes={"id"=>nil, "mime_type"=>nil, "format_label"=>[], "file_size"=>[], "last_modified"=>[], "filename"=>[], "original_checksum"=>[], "rights_basis"=>[], "copyright_basis"=>[], "copyright_note"=>[], "well_formed"=>[], "valid"=>[], "status_message"=>[], "file_title"=>[], "file_author"=>[], "page_count"=>[], "file_language"=>[], "word_count"=>[], "character_count"=>[], "paragraph_count"=>[], "line_count"=>[], "table_count"=>[], "graphics_count"=>[], "byte_order"=>[], "compression"=>[], "color_space"=>[], "profile_name"=>[], "profile_version"=>[], "orientation"=>[], "color_map"=>[], "image_producer"=>[], "capture_device"=>[], "scanning_software"=>[], "exif_version"=>[], "gps_timestamp"=>[], "latitude"=>[], "longitude"=>[], "character_set"=>[], "markup_basis"=>[], "markup_language"=>[], "bit_depth"=>[], "channels"=>[], "data_format"=>[], "offset"=>[], "frame_rate"=>[], "label"=>nil, "depositor"=>nil, "arkivo_checksum"=>nil, "relative_path"=>nil, "import_url"=>nil, "part_of"=>[], "resource_type"=>[""], "title"=>[""], "creator"=>["admin@chemheritage.org"], "contributor"=>[""], "description"=>[""], "tag"=>[], "rights"=>[""], "publisher"=>[""], "date_created"=>[], "date_uploaded"=>nil, "date_modified"=>nil, "subject"=>[""], "language"=>[""], "identifier"=>[""], "based_near"=>[], "related_url"=>[""], "bibliographic_citation"=>[], "source"=>[], "proxy_depositor"=>nil, "on_behalf_of"=>nil, "genre_string"=>[""], "artist"=>[""], "author"=>[""], "creator_of_work"=>[""], "interviewee"=>[""], "interviewer"=>[""], "manufacturer"=>[""], "photographer"=>[""], "date_original"=>[""], "date_published"=>[""], "extent"=>[""], "medium"=>[""], "physical_container"=>nil, "place_of_interview"=>[""], "place_of_manufacture"=>[""], "place_of_publication"=>[""], "provenance"=>"", "rights_holder"=>nil, "batch_id"=>nil}>
I, [2015-07-16T15:19:44.804127 #25755]  INFO -- : VARS: f.object.depositor: 
I, [2015-07-16T15:19:44.804758 #25755]  INFO -- : VARS: batch: #<Batch id: "ks65hc31b", creator: [], title: [], status: []>
I, [2015-07-16T15:19:44.804925 #25755]  INFO -- : VARS: batch.generic_files: []
I, [2015-07-16T15:19:44.805083 #25755]  INFO -- : VARS: batch.generic_files.first:

**Comment by hectorcorrea** [comment]
The fact that `depositor` is `nil` and `batch.generic_files` is empty explains why this line `<% depositor = f.object.depositor || batch.generic_files.first.depositor %>` blows up. 

But that still leaves the question on why in the world is the depositor nil and the array of generic_files empty (if there was no error uploading them)?! I wonder if there is an error saving the batch and its files that we are missing.

**Comment by hackmastera** [comment]
In my development environment f.object.depositor continues to be nil, but batch.generic_files is populated.

**Comment by hackmastera** [comment]
So from looking at my dev instance, it seems f.object should have way more stuff. For example a BatchEditForm object ID as well as a model attribute. Somehow the form itself is missing these things..

f.object: #<BatchEditForm:0x007fbb50b86a38 @model=#<GenericFile id: nil, mime_type: nil, format_label: [], file_size: [], last_modified: [], filename: [], original_checksum: [], rights_basis: [], copyright_basis: [], copyright_note: [], well_formed: [], valid: [], status_message: [], file_title: [], file_author: [], page_count: [], file_language: [], word_count: [], character_count: [], paragraph_count: [], line_count: [], table_count: [], graphics_count: [], byte_order: [], compression: [], color_space: [], profile_name: [], profile_version: [], orientation: [], color_map: [], image_producer: [], capture_device: [], scanning_software: [], exif_version: [], gps_timestamp: [], latitude: [], longitude: [], character_set: [], markup_basis: [], markup_language: [], bit_depth: [], channels: [], data_format: [], offset: [], frame_rate: [], label: nil, depositor: nil, arkivo_checksum: nil, relative_path: nil, import_url: nil, part_of: [], resource_type: [], title: ["turtle_sweater.jpg"], creator: ["aheadley@chemheritage.org"], contributor: [], description: [], tag: [], rights: [], publisher: [], date_created: [], date_uploaded: nil, date_modified: nil, subject: [], language: [], identifier: [], based_near: [], related_url: [], bibliographic_citation: [], source: [], proxy_depositor: nil, on_behalf_of: nil, genre_string: [], artist: [], author: [], creator_of_work: [], interviewee: [], interviewer: [], manufacturer: [], photographer: [], date_original: [], date_published: [], extent: [], medium: [], physical_container: nil, place_of_interview: [], place_of_manufacture: [], place_of_publication: [], provenance: nil, rights_holder: nil, batch_id: nil>, @attributes={"id"=>nil, "mime_type"=>nil, "format_label"=>[], "file_size"=>[], "last_modified"=>[], "filename"=>[], "original_checksum"=>[], "rights_basis"=>[], "copyright_basis"=>[], "copyright_note"=>[], "well_formed"=>[], "valid"=>[], "status_message"=>[], "file_title"=>[], "file_author"=>[], "page_count"=>[], "file_language"=>[], "word_count"=>[], "character_count"=>[], "paragraph_count"=>[], "line_count"=>[], "table_count"=>[], "graphics_count"=>[], "byte_order"=>[], "compression"=>[], "color_space"=>[], "profile_name"=>[], "profile_version"=>[], "orientation"=>[], "color_map"=>[], "image_producer"=>[], "capture_device"=>[], "scanning_software"=>[], "exif_version"=>[], "gps_timestamp"=>[], "latitude"=>[], "longitude"=>[], "character_set"=>[], "markup_basis"=>[], "markup_language"=>[], "bit_depth"=>[], "channels"=>[], "data_format"=>[], "offset"=>[], "frame_rate"=>[], "label"=>nil, "depositor"=>nil, "arkivo_checksum"=>nil, "relative_path"=>nil, "import_url"=>nil, "part_of"=>[], "resource_type"=>[""], "title"=>["turtle_sweater.jpg"], "creator"=>["aheadley@chemheritage.org"], "contributor"=>[""], "description"=>[""], "tag"=>[], "rights"=>[""], "publisher"=>[""], "date_created"=>[], "date_uploaded"=>nil, "date_modified"=>nil, "subject"=>[""], "language"=>[""], "identifier"=>[""], "based_near"=>[], "related_url"=>[""], "bibliographic_citation"=>[], "source"=>[], "proxy_depositor"=>nil, "on_behalf_of"=>nil, "genre_string"=>[""], "artist"=>[""], "author"=>[""], "creator_of_work"=>[""], "interviewee"=>[""], "interviewer"=>[""], "manufacturer"=>[""], "photographer"=>[""], "date_original"=>[""], "date_published"=>[""], "extent"=>[""], "medium"=>[""], "physical_container"=>nil, "place_of_interview"=>[""], "place_of_manufacture"=>[""], "place_of_publication"=>[""], "provenance"=>"", "rights_holder"=>nil, "batch_id"=>nil}>

**Comment by hackmastera** [comment]
scratch that i think i have a github formatting problem.

**Comment by hackmastera** [comment]
Okay I fixed the formatting on my debug output. You can now see the BatchEditForm object ID and the GenericFile model object

**Comment by hackmastera** [comment]
Batch contains has_many for its generic_files. This makes me wonder if what I have is a solr issue.

**Comment by hackmastera** [comment]
The problem turned out to be a missing base_path line in the fedora.yml config. It was causing the fedora url to look like fedora/rest//pa/th/to/re/resource (double slashes) which was messing things up. Unfortunately I didn't even cut-and-paste that part of the log into this issue so we couldn't have known!! Thanks to all those who helped me troubleshoot this.
