### ISSUE TITLE
Rescue is swallowing all errors rather than specific ones

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1261]
This code: https://github.com/projecthydra/sufia/blob/master/app/controllers/concerns/sufia/files_controller_behavior.rb#L101

Allows this test to pass:  https://github.com/projecthydra/sufia/blob/master/spec/controllers/generic_files_controller_spec.rb#L611-L618

Even though that code hits a nil pointer error here: 
https://github.com/projecthydra/sufia/blob/master/app/controllers/concerns/sufia/files_controller_behavior.rb#L269-L270

Sufia-core/worthwhile only trap RSolr::Error::Http. So that test doesn't work for them.

**Comment by mjgiarlo** [comment]
We're no longer swallowing all errors in that controller behavior. Closing.
