### ISSUE TITLE
Get solr error for files larger than 2GB

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1267]
When uploading files larger than 2GB we get a solr error: RSolr::Error::Http - 400 Bad Request Error: {'responseHeader'=>{'status'=>400,'QTime'=>625},'error'=>{'msg'=>'ERROR: [doc=1c18dg263] Error adding field \'file_size_is\'=\'2147483648\' msg=For input string: "2147483648"','code'=>400}}

The reason for this error is we are indexing the file size as an integer.  The maximum szie for a valid integer is 2G.  If solrizer allowed for longs this would be the best fix (projecthydra/solrizer/#33).  Otherwise we should use a symbol to index the file size as that does not cause an issue.

**Comment by mjgiarlo** [comment]
As long as that doesn't break https://github.com/projecthydra/sufia/blob/master/sufia-models/app/models/concerns/sufia/collection_behavior.rb#L29-L37 I'm OK with that.

**Comment by cam156** [comment]
@mjgiarlo I have put in a local fix in ScholarSphere, and it seems to work fine.  The to_i here: https://github.com/projecthydra/sufia/blob/master/sufia-models/app/models/concerns/sufia/collection_behavior.rb#L37 would allow it to be any type.

**Comment by mjgiarlo** [comment]
:clap:

**Comment by mjgiarlo** [comment]
Sufia indexes collection size as a symbol:

https://github.com/projecthydra/sufia/blob/master/app/services/sufia/collection_size_service.rb#L33

But CurationConcerns uses integers:

https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/models/concerns/curation_concerns/collection_behavior.rb#L64
https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/indexers/curation_concerns/collection_indexer.rb#L9
https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/indexers/curation_concerns/file_set_indexer.rb#L15

Move to CurationConcerns.

**Comment by mjgiarlo** [comment]
This issue was moved to projecthydra-labs/curation_concerns#559
