### ISSUE TITLE
Ordering of collection lists

### ISSUE THREAD

**Issue by ojlyytinen** [projecthydra/sufia#1272]
I was trying to figure out why the ordering of collections in various places is different and discovered a few issues with how collections are ordered. 

The My Collections page seems to order collections in Solr using date_uploaded in descending order. However, date_uploaded is never set for collections, thus the ordering here is unspecified but seems to be based on creation time in ascending order. Hydra::Collections::Actions has the before filters to set date_uploaded, but this file is deprecated and not used anywhere. I wonder what the history here is, has this file been used before and why has it been deprecated?

The My Collections page has a column for Date Uploaded, but this is always blank because it's never set for collections. Either the column should be removed or the date uploaded field used in collections.

The header of that column is clickable and will toggle between ascending and descending ordering, but the link for this takes you to My Files, even when clicked on My Collections page. Furthermore, the form above the table that you can use to select ordering or page size always takes you to the My Files page as well. So you can't change any of that for My Collections page. This should be fixed regardless anything else.

In My Files page if you add files to a collection you get a list where you can select which collection to add the files to. This list seems to do the sorting in the view template (views/collections/_form_for_select_collection.html.erb) and uses ascending order of date_modified. Date modified also is never set for collections. And even if it were, it would be confusing as this is a different sorting criterion compared to the My Collections page.

I was going to fix this in our version but if this all sounds good, I might as well make it a pull request upstream. As I see it, there are two options, enable the before filters that set date uploaded and modified for collections and then make everything use date uploaded consistently. Or don't set them and use something else for ordering (Solr has at least timestamp), but do it consistently. In this case the date uploaded column could be removed from My Collections page.

**Comment by cam156** [comment]
@ojlyytinen Hello!  This is a good find.  I believe the choice to use last modified in the selection collection list was decided based on the user wanting add files to the collection they were last updating.

That said consistency would be fantastic.  Please do create a PR.
:clap:

**Comment by ojlyytinen** [comment]
@cam156 Should I enable the before filters to set the date_uploaded and date_modified for collections then? I assume there must have been some reason to deprecate the class in the first place so I wasn't sure if that would be the way to fix this.

Or the alternative solution is to remove the date uploaded column for collections and use something else for sorting.

**Comment by jcoyne** [comment]
created_date and modified_date are automatically set on all ActiveFedora
objects. Can you use those?

https://github.com/projecthydra/active_fedora/blob/master/lib/active_fedora/fedora_attributes.rb#L14-L15

-Justin

**Comment by ojlyytinen** [comment]
I think I need something which is stored in Solr in its own field so that the sorting can be done in a Solr query. created_date and modified_date don't seem to be indexed in Solr. And oddly they don't seem to be in the object_profile either. In fact ```Collection.load_instance_from_solr('xxxx').create_date``` raises an exception whereas ```Collection.find('xxxx').create_date``` works as expected.

I can see system_create_dtsi and system_modified_dtsi in Solr. Are these set by Solr itself automatically? There's also a timestamp. And those three seem to be the only time related fields in Solr that are set for collections. I think any of these would work, the question is just if we want to sort based on modified or created date.

**Comment by jcoyne** [comment]
created_date and modified_date are indexed in solr respectively as system_create_dtsi and system_modified_dtsi.  See the indexer:

https://github.com/projecthydra/active_fedora/blob/1db3d1f986d5d733772e9016e076c066f24730b7/lib/active_fedora/indexing_service.rb#L30-L31

**Comment by ojlyytinen** [comment]
Ah, I see. One of those is then probably perfect for this.
