### ISSUE TITLE
Rights field should be single-valued by default, and overrideable

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1287]

**Comment by jcoyne** [comment]
I'm not sure this is *always* true. Probably for the 99% though.

**Comment by mjgiarlo** [comment]
I suspect it's always true for folks who aren't overriding any of the select values for that field.  And if they're already overriding that... :smile: 

I don't think it makes any sense to let folks select multiple CC licenses, or to select a CC license and "All rights reserved." The default select values suggest single-valued field to me.

**Comment by vantuyls** [comment]
The only places I've seen someone assign multiple (CC) licenses to an object, I'm pretty sure they screwed up. I've been racking my brain for the past week trying to think of a case where one could actually assign multiple CC licenses and i've come up with nothing.

**Comment by jcoyne** [comment]
Yes, my exception case was licenses from the library, not CC licenses.

**Comment by mjgiarlo** [comment]
I spent a day or two hacking on this but I need to move onto other things.

**Comment by vantuyls** [comment]
Hrm. We just made this happen locally.

**Comment by mjgiarlo** [comment]
Maybe the magic incantation is in here: https://github.com/osulp/Scholars-Archive/commit/746e02a0e5fccc85217450ae560d0191500900b9

Thanks for the heads-up, @vantuyls 

@straleyb if you want to toss a fix upstream, that'd be great!

**Comment by straleyb** [comment]
Yeah, I'll update and send a PR. If not this afternoon, tomorrow morning. +1

**Comment by vantuyls** [comment]
INTERNET!

**Comment by mjgiarlo** [comment]
:clap: :fireworks:  @vantuyls @straleyb

**Comment by mjgiarlo** [comment]
Are you still interested in working on this @straleyb?

**Comment by mjgiarlo** [comment]
Paging @straleyb and @vantuyls. :)

If you are interested in contributing this work back, please do issue the PR against the `6.x-stable` branch.

**Comment by newmanld** [comment]
We're taking a look at making this field single valued in our local implementation.  Multiple rights statements didn't make sense to us, and seemed a good use case for multi-part works.  I'll refer the developer who has taken our local issue to this thread.
