### ISSUE TITLE
Update fileupload plugin to a more recent version

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#1290]
It looks like this was added > 3 years ago and hasn't been updated since. The major version has moved from 5 to 9 in that time; the earliest available release is 8.1.0 and I've been unable to find any changelogs. Could be an annoying process. Thoughts on the necessity??

See https://github.com/projecthydra/sufia/blob/master/vendor/assets/javascripts/fileupload/jquery.fileupload.js

**Comment by mjgiarlo** [comment]
This has been on our wishlist for while, but no one's ever given it the time it deserved.  I would love if someone wanted to take a crack at it!  Not *necessary*, no, but it is one area where we have not kept up with our dependencies.

**Comment by mjgiarlo** [comment]
This file has been updated in https://github.com/projecthydra-labs/curation_concerns/issues/301: https://github.com/projecthydra-labs/curation_concerns/blob/master/vendor/assets/javascrips/fileupload/jquery.fileupload.js

We should use the same version as CC does.

See related: https://github.com/projecthydra-labs/curation_concerns/issues/558
