### ISSUE TITLE
Dropdown inside My Files list renders beneath containing frame

### ISSUE THREAD

**Issue by kerchner** [projecthydra/sufia#1291]
As noted by @mtribone in #1282, ```overflow-x: auto``` causes the "Select an Action" dropdown to be rendered beneath the containing frame (in both Firefox and Chrome).  #1282 was merged because without this change, the 6.3.0 release caused more severe display problems for Firefox users.  However, the fix implemented in #1282 creates this problem, which should still be addressed.

![9299c994-4657-11e5-8878-24ccbccf011a](https://cloud.githubusercontent.com/assets/3451175/9430343/8553f2bc-49bf-11e5-8345-f395d3f017a4.png)

**Comment by mjgiarlo** [comment]
Thanks for the excellent write-up, @kerchner!  Who's inclined to take this on?

**Comment by mtribone** [comment]
It's gonna be a tricky one because the Bootstrap responsive table is heavy-handed. We might be able to do a "drop up" on the last few rows in the table and not fight the overflow.

**Comment by awead** [comment]
Good idea, @mtribone!

**Comment by mtribone** [comment]
Be like water @awead . Find a block and go around it!

**Comment by kerchner** [comment]
@studiozut is this something you might be able to solve?

**Comment by kerchner** [comment]
@studiozut is looking into this.

**Comment by mjgiarlo** [comment]
:+1:

**Comment by StudioZut** [comment]
I think I have this worked out. Testing it now, but basically changing overflow-x to 'initial' and adding display: inline-block.

**Comment by hackmastera** [comment]
@StudioZut looks great! Still working for you? would you be able to PR that business?

**Comment by awead** [comment]
awesome. @StudioZut can you sign iCLA, or have you already?  We've got a cCLA on file for GW, we'd just need one from you and then we could merge this fix in.

**Comment by mjgiarlo** [comment]
:clap:

**Comment by mjgiarlo** [comment]
Awesome, @StudioZut! In order for us to merge any upcoming pull requests, we'll need to have a signed Contributor License Agreement on file for you as an individual. You can read more about our [CLA processes on the Hydra wiki](https://wiki.duraspace.org/display/hydra/Hydra+Project+Intellectual+Property+Licensing+and+Ownership).

The process itself is fairly simple -- you just need to print out the Hydra Project iCLA, sign it, and send it to legal@projecthydra.org. (I'm guessing @kerchner and @kilahimm may be able to help since they have already been through this process.) Let me know if you have any questions about this process, and I'd be happy to help too.

**Comment by awead** [comment]
@mjgiarlo is there an echo in here? :smile:

**Comment by kerchner** [comment]
@mjgiarlo and @awead - the CLA update to include @StudioZut is getting its final signature so we should be able to "PR that business" next week (hopefully).

**Comment by mjgiarlo** [comment]
@awead Heh! It's not always obvious where to find our CLAs or where to send 'em, so... yeah, kinda. :laughing:

**Comment by mtribone** [comment]
:metal:

**Comment by mjgiarlo** [comment]
FYI, we're going to wait on cutting another release (6.4.0 probably) 'til we have a PR for this because we want this badly!

**Comment by StudioZut** [comment]
Just waiting on the CLA. My browser tests so far are all good.

**Comment by mjgiarlo** [comment]
Great, @StudioZut! Is there anything I can do to help along the CLA process?

**Comment by StudioZut** [comment]
Thanks @mjgiarlo, looks like we're just waiting for 1 final signoff

**Comment by mjgiarlo** [comment]
:cool: :exclamation:
