### ISSUE TITLE
list_files.html.erb partial has JPG hard coded.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1309]
Introduced here: https://github.com/projecthydra/sufia/commit/725b718a8db8213f5a842c516cf80c63d323b5c3#diff-f049bd0f0675eb5fceea916a59db0d31L57

@mtribone any idea why?

**Comment by jcoyne** [comment]
See https://scholarsphere.psu.edu/collections/8623j3982
<img width="1146" alt="screen shot 2015-09-02 at 8 45 03 am" src="https://cloud.githubusercontent.com/assets/92044/9632798/f48d9aac-514e-11e5-9515-bdd6d3cb23ec.png">

**Comment by mtribone** [comment]
Hmmmm...not a clue why it is there.

**Comment by mjgiarlo** [comment]
I don't believe this partial exists anymore. Closing.
