### ISSUE TITLE
Divide metadata display into two columns (with characterization terms in the right column)

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1310]
https://scholarsphere.psu.edu/files/x346dx728

![screen shot 2015-09-02 at 11 03 46 am](https://cloud.githubusercontent.com/assets/92044/9636696/6ba74daa-5162-11e5-9a78-f00b62168453.png)

/cc @mtribone

**Comment by jcoyne** [comment]
Ah, I see, that's all extensions of the characterization.

**Comment by jcoyne** [comment]
Seems like an awkward column break.

**Comment by mtribone** [comment]
Yeah the two column layout using CSS only was a way to get more info farther up the page. However since it tries to make equal columns, breaking can be at odd places for any of the metadata fields. It was a middle step. It can be removed for the technical metadata.

**Comment by mjgiarlo** [comment]
I wonder if we should start moving towards the approach to techMD proposed by @elrayle here:

https://wiki.duraspace.org/pages/viewpage.action?pageId=68070440#mockup_detail-single-part_work-d_nh_x

**Comment by mtribone** [comment]
If I'm seeing the visual correctly, @elrayle 's  mockup is based on the same code so it will have a similar problem. The middle step was to affect the display usind CSS only. We would need to output each metadata field individually, me thinks, and in either the left or right column. Right now it outputs everything from generic file?

**Comment by mjgiarlo** [comment]
My eyes deceived me, and they showed me what I wanted to see and not what's there. ;) I should have added: I could see the file metadata divided into two columns where column 1 holds all the characterization-unrelated stuff (depositor, dates, filename, audit status) and column 2 holds all the characterization.  Silly :eyes:

**Comment by mtribone** [comment]
Yes. yes. Divide the metadata into two columns and it will eliminate the need for the CSS and the odd breaking issue. +1

**Comment by mjgiarlo** [comment]
Would that be totes ugs and unbalanced, potentially though?

**Comment by mtribone** [comment]
It could be a little uneven, but maybe a better solution.We've even talked about only showing metadata fields that have entries. It's hard to gauge the amount of metadata a person would add and split things evenly.

**Comment by mjgiarlo** [comment]
I'm a fan of hiding empty fields, yeah.
