### ISSUE TITLE
Collection should be assigned in Actor#create_metadata

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1311]
Rather than Actor#create_content as the content is just the bitstream, where the metadata is the GenericFile properties.

See https://github.com/projecthydra/sufia/pull/1307#issuecomment-137891935

**Comment by mjgiarlo** [comment]
Actors are no longer defined in Sufia. Pls move to CC if it's still relevant.

**Comment by mjgiarlo** [comment]
This issue was moved to projecthydra-labs/curation_concerns#557
