### ISSUE TITLE
Update FULLTEXT_JARS

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1318]
https://github.com/projecthydra/sufia/blob/master/sufia-models/lib/tasks/sufia-models_tasks.rake#L39-L70
These need updating:
commons-compress-1.7.jar, fontbox-1.8.4.jar, icu4j-53.1.jar, jempbox-1.8.4.jar, jhighlight-1.0.jar, metadata-extractor-2.6.2.jar, pdfbox-1.8.4.jar,  poi-3.10.1.jar, poi-ooxml-3.10.1.jar , poi-ooxml-schemas-3.10.1.jar, poi-ooxml-schemas-3.10.1.jar, tika-core-1.5.jar, tika-parsers-1.5.jar, tika-xmp-1.5.jar, xmlbeans-2.6.0.jar, xmpcore-5.1.2.jar xz-1.4.jar

**Comment by cam156** [comment]
and solr-cell-4.10.4.jar

**Comment by awead** [comment]
Is this still relevant? FULLTEXT_JARS is in hydra-works now.

**Comment by mjgiarlo** [comment]
Please move to hydra-works if still relevant. Closing in Sufia.

**Comment by mjgiarlo** [comment]
This issue was moved to projecthydra-labs/hydra-works#256
