### ISSUE TITLE
add locking for batch upload to collection

### ISSUE THREAD

**Issue by elrayle** [projecthydra/sufia#1324]
Since each file uploads individually and when a collection is identified, all files are added to that collection, there is potential for multiple threads to attempt to update the collection at the same time.  Jcoyne ran into something similar and used the following code to lock the entity before update.

https://github.com/projecthydra-labs/curation_concerns/commit/ef15d9250707c63f953bc580006dee584f13780c

Something similar needs to be done for Sufia and batch upload to a collection.

Related PRs:
* https://github.com/projecthydra/sufia/pull/1307
* https://github.com/projecthydra/sufia/pull/1312

**Comment by mjgiarlo** [comment]
Wait on this to be closed before releasing 6.4.0.

**Comment by elrayle** [comment]
Fixed by PR https://github.com/projecthydra/sufia/pull/1346
