### ISSUE TITLE
Download link area extends beyond thumbnail on GenericFile 'show' page

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#1335]
There's a bunch of whitespace to the right of an image wherein, if I click, I initiate an unintended download. Observed in firefox and chrome.

In this screenshot, clicking anywhere in the peach-colored area initiates download:

![screen shot 2015-10-28 at 10 42 17 am](https://cloud.githubusercontent.com/assets/845363/10791879/cec939be-7d60-11e5-971c-7ecaccfdd469.png)

**Comment by hackmastera** [comment]
Looks like this is related to the image being display:block

**Comment by mtribone** [comment]
https://github.com/psu-stewardship/scholarsphere/issues/194

**Comment by mtribone** [comment]
Perhaps a bug in Chrome

Firefox 41.0.2 - works as expected

![screen shot 2015-10-28 at 3 35 22 pm](https://cloud.githubusercontent.com/assets/4163828/10800722/c83cc6fa-7d89-11e5-829f-fe617ad47b5c.png)

**Comment by mtribone** [comment]
Safari 9.0.1 (11601.2.7.2)

![screen shot 2015-10-28 at 3 38 31 pm](https://cloud.githubusercontent.com/assets/4163828/10800759/085b887a-7d8a-11e5-9c2e-e678f9b9f008.png)

**Comment by mtribone** [comment]
Nope. Totally wrong. Using width: 100% pixellates the image. The declaration max-width: 100% keeps it within the intrinsic range of the image.

**Comment by hackmastera** [comment]
@mtribone using inline-block, results in chrome

![screen shot 2015-10-30 at 2 30 37 pm](https://cloud.githubusercontent.com/assets/845363/10854568/e1a7329e-7f12-11e5-80d1-bfa38d188cf8.png)

**Comment by mtribone** [comment]
@hackmastera @narogers 

![screen shot 2015-10-30 at 3 30 32 pm](https://cloud.githubusercontent.com/assets/4163828/10856021/41f5110e-7f1b-11e5-8da5-fee65e4488d9.png)

**Comment by hackmastera** [comment]
resolved via #1337
