### ISSUE TITLE
configs added through generators are in sufia.rb initializer twice

### ISSUE THREAD

**Issue by elrayle** [projecthydra/sufia#1347]
Following the pattern for adding configs established by https://github.com/projecthydra/sufia/commit/9fd48874f034299f07fafab893f44172a1f52121, configs are added to `config/initializers/sufia.rb` twice.

Config added by…
* generator specific to new config -- sufia-models/lib/generators/sufia/models/citation_config_generator.rb
* adding directly to sufia.rb -- sufia-models/lib/generators/sufia/models/templates/config/sufia.rb

Recommendation per @mjgiarlo...

> It should be sufficient to:
> 1. Add the config to sufia.rb (covers the test app and new installs);
> 2. Write a generator for an upgrade generator to call. The upgrade generator can be written at time of next release;
> 3. Do *not* call the new generator from the install generator.

**Comment by elrayle** [comment]
Known duplicate configs are...
* citations 
added via https://github.com/projecthydra/sufia/commit/9fd48874f034299f07fafab893f44172a1f52121)
* upload_to_collection (added via https://github.com/projecthydra/sufia/pull/1307)
* lock_retry_count, lock_time_to_live, lock_retry_delay (added via https://github.com/projecthydra/sufia/pull/1346)

**Comment by mjgiarlo** [comment]
I also left a comment on #1338 so that we don't propagate this bug in existing PRs.
