### ISSUE TITLE
Consider updating 6.4.0 release notes to include running GeonamesUsernameConfigGenerator

### ISSUE THREAD

**Issue by kerchner** [projecthydra/sufia#1351]
Suggested insertion so users don't lose geonames functionality and can take advantage of https://github.com/projecthydra/sufia/pull/1338 -- something like:

_The geonames integration no longer uses a default username and now requires configuration of a username in ```sufia.rb```.  To enable geonames username configuration, run:_

_```rails g sufia:models:geonames_username_config```_

@awead I don't have edit rights to the Release Notes (nor would I edit it without coordinating, even if I could!) so perhaps you want to take this one.

**Comment by mjgiarlo** [comment]
I just noticed the same and fixed it. Have another look at the release notes for 6.4.0 and let me know if I got it right. If so, feel free to close the issue, and if not, let me know how I can make it better. Thanks, @kerchner! Good :eyes:

**Comment by kerchner** [comment]
@mjgiarlo wow that's some impressive serendipity/synchronicity we had there.  Your edit looks :+1: and I will close the issue.
