### ISSUE TITLE
'All rights reserved' should not display twice on record show page

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#1356]
![all-rights-twice](https://cloud.githubusercontent.com/assets/845363/11339535/f3bc802a-91c7-11e5-9f45-2654c9c81936.png)

Here's a code trace:
* cc_licenses hash is designed to hold a label => url, but for 'all rights reserved' it just holds the label in both places, since there isn't a url. Note the url is the part that's saved as metadata: https://github.com/projecthydra/sufia/blob/master/sufia-models/lib/generators/sufia/models/templates/config/sufia.rb#L20
* template calls iconify_auto_link on the url: https://github.com/projecthydra/sufia/blob/master/app/views/records/show_fields/_rights.html.erb#L2
* which just passes a block to create the icon: https://github.com/projecthydra/sufia/blob/master/app/helpers/sufia/sufia_helper_behavior.rb#L116
* in the the rails_autolink [1] plugin.

Autolink doesn't do anything if it doesn't find any links; There's no link in 'all rights reserved' so it just returns the text. Blocks passed to autolink are applied on every link found; not on the text as a whole.

So I know what's happening but I don't really know the best way to fix it. Ideally we'd have a url for 'all rights reserved.' Otherwise, I guess the best place to fix it is in show_fields/_rights.html.erb with a hack that makes sure the value is a url before calling iconify_auto_link. I guess with a simple regex?

[1] https://github.com/tenderlove/rails_autolink/blob/master/lib/rails_autolink/helpers.rb

**Comment by mjgiarlo** [comment]
@hackmastera How about this URL I chanced upon the other day? https://github.com/projecthydra-labs/curation_concerns/blob/master/lib/generators/curation_concerns/templates/config/authorities/rights.yml#L18

**Comment by hackmastera** [comment]
@mjgiarlo that looks like a great find. not my area of expertise, though. @catlu what do you think?

**Comment by catlu** [comment]
@hackmastera @mjgiarlo I think that would work great!

**Comment by mjgiarlo** [comment]
@hackmastera @catlu :clap:

**Comment by mjgiarlo** [comment]
@hackmastera @catlu This should be fixed in Sufia 7.0.0. Do you think we need a fix in the 6.x line or meh?

**Comment by hackmastera** [comment]
@mjgiarlo We've talked about this more here. 

We're feeling less excited about http://www.europeana.eu/portal/rights/rr-r.html as a good match for 'All rights reserved.' All rights reserved is I guess sort of specific to US copyright law so europeana's statement is somewhat different.

If the europeana URI is going to be in there, it would probably be a good idea to use a different label -- 'rights reserved' instead of 'all rights reserved.'

If as a project sufia does replace 'all rights reserved' (currently stored when a person selects that dropdown option) with this URI, I believe there are upgrade implications for records already containing 'all rights reserved'. Plus it's not a straightforward matter of code -- it's a decision that institutions will need to make regarding their actual rights policies.

And so now I'm thinking that 'all rights reserved' is probably still needed generally, circling this back around to my initial issue report.

Locally we are excited about http://rightsstatements.org/ and hoping this will allow us to move away from 'all rights reserved' as a general rule. We'll probably start using their URIs even though their work isn't finalized.

**Comment by catlu** [comment]
@mjgiarlo Yeah, ultimately we feel like http://www.europeana.eu/portal/rights/rr-r.html is most appropriate when matched to its own label, which is still slightly different than "All rights reserved." On a personal level, I prefer the Europeana statement, but "All rights reserved" is so widely used that it seems sensible to keep it around for people that would like it.

**Comment by mjgiarlo** [comment]
Thanks, @catlu and @hackmastera! So for now, let's not make changes to All Rights Reserved. Just to confirm: is it still appearing twice? If so, we should fix that independent of the URI conversation.

**Comment by mtribone** [comment]
![screen shot 2015-12-16 at 1 42 49 pm](https://cloud.githubusercontent.com/assets/4163828/11850385/fd4b28e0-a3fa-11e5-8c28-55a5724d6dcd.png)

**Comment by mjgiarlo** [comment]
Alright, thanks, @mtribone!

**Comment by jcoyne** [comment]
I think that is fixed if you configure a URL for All Rights Reserved ( I don't think it matters which one you actually use)

**Comment by mjgiarlo** [comment]
https://en.wikipedia.org/wiki/All_rights_reserved ? :wink:

**Comment by hackmastera** [comment]
ha. Is that persistent enough to store as a data value?

**Comment by mjgiarlo** [comment]
I don't really love that workaround, tbh.

**Comment by hackmastera** [comment]
i was going to say 'maybe this is a job for opaquenamespace' but the URL is not just a data value -- it's also presented to the end user as a clickable link for more information.

i sort of lean toward the hack I initially proposed. At least it won't make weird choices for anyone or present migration issues. Worth rethinking the change made in curation concerns as well IMO.

**Comment by mjgiarlo** [comment]
@hackmastera Just to clarify, you mean this?

> I guess the best place to fix it is in show_fields/_rights.html.erb with a hack that makes sure the value is a url before calling iconify_auto_link. I guess with a simple regex?

**Comment by hackmastera** [comment]
@mjgiarlo Yes.

**Comment by mjgiarlo** [comment]
@hackmastera Do you think a patch to `iconify_auto_link` could work?

**Comment by hackmastera** [comment]
@mjgiarlo yes you could have that method return '' if there was no url. But it would be changing the behavior of a public method and so I'm not sure I would advocate for that.

**Comment by hackmastera** [comment]
I would probably try adding is_url? into the sufia helper and then change the template to   
```
<%= link_to_field('rights', r, RightsService.label(r)) %><%= (" " + iconify_auto_link(r, false)) if is_url(r) %><br />
```

**Comment by hackmastera** [comment]
resolved for 6.x in #1492; does this need to be applied to master as well?

**Comment by mjgiarlo** [comment]
@hackmastera I believe the behavior in master is what we inherit from CurationConcerns, which uses the Europeana URL. I know that that's not a great solution for everyone, so perhaps we can cover this in one or both of these tickets? https://github.com/projecthydra/sufia/issues/1373, #997. Whaddya think?

That said, it's :a:-:ok: to *also* port the patch in #1492 to master. Are you inclined to take a hack, or meh?

**Comment by jcoyne** [comment]
CurationConcerns uses whatever URLs you have configured in `config/authorities/rights.yml` (https://github.com/projecthydra-labs/curation_concerns/blob/master/lib/generators/curation_concerns/templates/config/authorities/rights.yml)

**Comment by hackmastera** [comment]
Those tickets are good. Intellectually I think since the 'all rights reserved' string was a default in sufia it's data we can assume will exist and the bugfix should be carried forward.

I'm meh on actually doing it because since creating this issue we've decided to use rightsstatements.org urls and not have an all rights reserved option at all. I also do not have a local setup for the master branch and I don't think I could run tests, etc, so it seems like it should be trivial but will actually end up being super time-consuming.

**Comment by mjgiarlo** [comment]
@hackmastera OK, so let's handle this in migration and consider this a "wontfix" in master for now. Thanks for raising it!
