### ISSUE TITLE
"update generic files" button should just say "save"

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#1359]
Based on user feedback both at my institution and U. Alberta, I think this is a better default for sufia.

**Comment by jcoyne** [comment]
You should be able to adjust this locally with i18n

**Comment by mjgiarlo** [comment]
@jcoyne This is part of the Sufia UI WG's work, so we'll want to do this in Sufia proper (preferably after the merger w/ sufia-core).

**Comment by mtribone** [comment]
@mjgiarlo It did say just "Save" in the past. I believe that this labeling gets reintroduced from time-to-time.

**Comment by mjgiarlo** [comment]
@jcoyne It did, you're right. No idea when that crept in!

**Comment by hackmastera** [comment]
resolved in https://github.com/projecthydra/sufia/commit/dd93f2bc685553661f24dc97604b53b9bddf8968
looks like I just missed it due to local override.
