### ISSUE TITLE
Sufia 7 should not break GF permalinks

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1361]
After sufia-core is merged into Sufia and Sufia 7.0.0 is out, we can expect folks to begin upgrading and migrating their content over.

Links to http://sufia.host/files/abcxzy123 should route to the same GenericWork with that ID in Sufia 7. 

I am assuming here that the common migration path from Sufia 6.x to 7.x will be each GenericFile becoming:

1. a Sufia::GenericWork object bearing the same identifier and descriptive metadata as the GenericFile 
1. with one attached FileSet bearing the same content files

**Comment by barmintor** [comment]
@mjgiarlo this should probably be a priority ticket for remaining 2015 work.

**Comment by mjgiarlo** [comment]
:+1:
