### ISSUE TITLE
Search Builder depends on GenericFile having generic_work_id_ssim, but it's not present.

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1368]
_From @jcoyne on July 14, 2015 19:15_

In SearchBuilder#join_for_works_from_files

I suspect we need to do a join using `object_ssim` as indexed on GenericWork instead.

_Copied from original issue: projecthydra-labs/sufia-core#32_

**Comment by mjgiarlo** [comment]
@jcoyne Does this still need to be done? I instantiated a random FileSet in my repo and called `to_solr` on it and I see this in the document: `"generic_work_ids_ssim"=>["7s75dc50s"`

**Comment by njaffer** [comment]
@jcoyne , @mjgiarlo , can this issue be closed? or is there some work left?

**Comment by mjgiarlo** [comment]
Let's close it. Thanks, @njaffer!
