### ISSUE TITLE
create icons that differentiate works from files

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1369]
_From @jcoyne on July 16, 2015 16:34_

Update the `SufiaHelperBehavior#work_thumbnail` with a better icon. 
https://github.com/projecthydra-labs/sufia-core/blob/master/app/helpers/sufia/sufia_helper_behavior.rb#L202

Refs projecthydra-labs/sufia-core#46

_Copied from original issue: projecthydra-labs/sufia-core#50_

**Comment by mjgiarlo** [comment]
Thoughts @mtribone ?

**Comment by mjgiarlo** [comment]
_From @mtribone on July 16, 2015 17:18_

If you can't find something "acceptable" using Bootstrap, I'd be more than happy to create an icon. I use the stylus on my graphics tablet to scratch my head these days, so it would be good to sketch and make some vectors.

**Comment by mjgiarlo** [comment]
@jcoyne suggested the briefcase. Decent starting point?

**Comment by mjgiarlo** [comment]
_From @mtribone on July 16, 2015 17:24_

Go for it and see what the people think about it!

**Comment by mjgiarlo** [comment]
We should follow the CurationConcerns approach to thumbnailing. See: https://github.com/projecthydra-deprecated/sufia-core/commit/be8bba249abf39ba0481bff597e1100ba4c01f2d

**Comment by cam156** [comment]
We should be able to take icons for bootstrap or font awesome.  That would mean changing the thumbnail to display a span with an icon for a work.

**Comment by mjgiarlo** [comment]
@cam156 :+1:

**Comment by mjgiarlo** [comment]
@mtribone You inclined to take this one on?

**Comment by mtribone** [comment]
@mjgiarlo Absolutely :+1:

**Comment by mtribone** [comment]
@mjgiarlo We do have the representative icons in the top tool bar, so I'll just make sure they are reflected throughout the system.

**Comment by mtribone** [comment]
@mjgiarlo Thinking about the default graphics and wondering about a) work without files b) file types that don't generate a thumbnail c) audio. I believe that we get the blue folder from Curation Concerns. I see an audio graphic in Sufia's assets. Gonna test some file types and see what I get. Thoughts?

**Comment by mjgiarlo** [comment]
@mtribone Let's either discuss in stand-up today, or bring this over to the `#software-development` channel in Hydra slack.

**Comment by mjgiarlo** [comment]
@mtribone Let's not display the big blue icon/folder thing if the Work has no thumbnail or representative media.

**Comment by mjgiarlo** [comment]
@mtribone Have you started in on this ticket yet?

**Comment by mtribone** [comment]
@mjgiarlo Yes a little bit, but dropped it to work on the sidebar thing again. I can un-assign myself if someone wants to pick it up

**Comment by mjgiarlo** [comment]
@mtribone I think we should ship the sticky sidebar widget this week in whatever form it's in -- the sidebar is probably not a big enough deal to spend more time on making it poifect -- which makes me think you can get back to this ticket soon, so I'm inclined to say you should keep this assigned to you. Thanks!
