### ISSUE TITLE
Ensure that Collections are always public

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1370]
_From @flyingzumwalt on July 16, 2015 20:6_

I'm not sure if sufia-core's tests will catch this, so recording a ticket.

In sufia (at least until now) Collections were always public.  This was enforced by Sufia::CollectionBehavior in https://github.com/projecthydra/sufia/blob/master/sufia-models/app/models/concerns/sufia/collection_behavior.rb#L15

While CurationConcerns::CollectionBehavior is based on Sufia::CollectionBehavior we removed this particular behavior from curation_concerns.  Make sure that Sufia::CollectionBehavior adds it back in.

_Copied from original issue: projecthydra-labs/sufia-core#52_

**Comment by jcoyne** [comment]
It does. Test is here: https://github.com/projecthydra/sufia/blob/master/spec/models/collection_spec.rb#L11-L14
