### ISSUE TITLE
Revisit how upgrade-only migrations are handled

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1371]
_From @grosscol on November 4, 2015 18:22_

In the upgrade600 the migration `'change_audit_log_pid_to_generic_file_id.rb'` does not need to be run for the install as curation concerns generates the correct column name (`generic_file_id`) right off the bat.  However, I expect that this migration would be required for an upgrade from the 5.x to 6.x series of Sufia.

I think this is a consequence of curation concerns.  The install process will not need all of the same migrations as an upgrade.  Is there a decent method of keeping the migrations that are only needed for upgrades separate?
- Conditionals in the migrations should work, but that seems like it could be a code smell.
- Keeping a separate set of upgrade only migrations

_Copied from original issue: projecthydra-labs/sufia-core#97_

**Comment by mjgiarlo** [comment]
This migration already includes a conditional:

```ruby
    rename_column :checksum_audit_logs, :pid, :generic_file_id  unless ChecksumAuditLog.column_names.include?('generic_file_id')
```

Does that not take care of the need to skip this migration if CC has already done the right thing?

**Comment by mjgiarlo** [comment]
No, it does not, because the conditional checks the wrong name. I've suggested two small changes in #98 that should allow us to move forward without substantially changing our generator strategy while we focus on getting the build working. Maybe we should rework this ticket so it's more, "Revisit the install/upgrade generation strategy after 7.0 is released" ?

**Comment by grosscol** [comment]
I concur.  Lets get the 7.0 going in the existing fashion.  I would rather not see any of the upgrade generators run during a fresh install.

**Comment by mjgiarlo** [comment]
The upgrade generators are poorly named, I suspect. Let's do revisit this after 7.0 is out the door.

**Comment by mjgiarlo** [comment]
Not a high priority for Sufia.
