### ISSUE TITLE
DRY up EventJob and subclasses.

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1372]
_From @grosscol on November 5, 2015 22:45_

Refactor EventJob to have the following functions:
```ruby
# return event
def make_event(action, depositor)

def log_event(event, depositor)

def distribute_event(event, depositor)
```

Refactor all subclasses of EventJob to use these instead of the copy pasta that currently exists.

pending #106.

_Copied from original issue: projecthydra-labs/sufia-core#107_

**Comment by mjgiarlo** [comment]
_From @grosscol on November 10, 2015 18:38_

With #128 merged, this should be doable.

**Comment by mjgiarlo** [comment]
_From @awead on December 1, 2015 15:58_

@grosscol did the above commit address this, or did you have something more in mind?

**Comment by mjgiarlo** [comment]
_From @grosscol on December 1, 2015 21:9_

@awead Nope.  I just noticed a lot of repeated lines of code in the EventJob derived classes.  The #176 was addressing this, but never got taken to completion.

**Comment by mjgiarlo** [comment]
_From @awead on December 1, 2015 21:54_

I think there's some improvements to this coming up in #377. After that's merged, we can revisit.

**Comment by mjgiarlo** [comment]
_From @jcoyne on December 2, 2015 0:28_

Yes, I think #377 fixes this.

**Comment by mjgiarlo** [comment]
_From @awead on December 2, 2015 13:15_

@grosscol Take a look at this and see if we can close it.

**Comment by jcoyne** [comment]
@grosscol I'm closing this now. Reopen if you think necessary.
