### ISSUE TITLE
Upgrade guidance for rights statements

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1373]
_From @jcoyne on November 10, 2015 21:18_

It used to be in the sufia config and is now an QA authority

_Copied from original issue: projecthydra-labs/sufia-core#158_

**Comment by mjgiarlo** [comment]
Should be sufficient to include a blurb on how to carry forward `config.cc_licenses` overrides in the 7.0.0 release notes.

**Comment by mjgiarlo** [comment]
_From @jcoyne on November 10, 2015 21:37_

The new config location is `config/authorities/rights.yml`

**Comment by mjgiarlo** [comment]
Part of #997.

**Comment by hackmastera** [comment]
Note in the blurb that at least one default (the one for 'all rights reserved') has changed. People who have used that value need to either make sure to maintain it in the config file or change all instances of that value in existing data to use the new default url.

**Comment by mjgiarlo** [comment]
@hackmastera @cam156 Do y'all think this has been sufficiently covered in the migration docs/tools y'all have been doing such excellent work on? If so, feel free to close!

**Comment by cam156** [comment]
@mjgiarlo I do not think this has been covered.  @hackmastera?

**Comment by hackmastera** [comment]
I think it has been. The change in config file location is noted in the 7.0.0 release notes and the change in the "All rights reserved" field (from string to URI) is noted in the data migration wiki page.
