### ISSUE TITLE
Add Google Scholar and Twitter meta tags to Work show view.

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1374]
_From @jcoyne on November 11, 2015 2:50_

See: 
https://github.com/projecthydra/sufia/blob/master/spec/views/generic_file/show.html.erb_spec.rb#L120-L194

Should this go in CurationConcerns?  (I think so)

_Copied from original issue: projecthydra-labs/sufia-core#164_

**Comment by mjgiarlo** [comment]
@jcoyne :speech_balloon:
> Should this go in CurationConcerns? (I think so)

@jpstroop @tpendragon :arrow_heading_up: :question:

**Comment by mjgiarlo** [comment]
_From @jpstroop on November 18, 2015 17:1_

Princeton doesn't have a use case (at least yet), but if it makes more sense to others to have it here, I'm :ok_hand: with it.

**Comment by barmintor** [comment]
@mjgiarlo is this satsified by:
https://github.com/projecthydra/sufia/blob/5f7098d70849358828680cd7468570d577098176/app/views/curation_concerns/file_sets/show.html.erb#L1
https://github.com/projecthydra/sufia/blob/5f7098d70849358828680cd7468570d577098176/app/views/citations/work.html.erb#L1

needs test if so.

**Comment by mjgiarlo** [comment]
@barmintor I don't think folks should have to "enable" citations to get GScholar and Twitter meta tags.

**Comment by mjgiarlo** [comment]
Related: #1394 & #1460.
