### ISSUE TITLE
Visibility badge on the show page should have translatable text and title

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1376]
_From @jcoyne on November 11, 2015 3:7_

https://github.com/projecthydra/sufia/blob/master/spec/views/generic_file/show.html.erb_spec.rb#L289-L297

This should go into curation_concerns

_Copied from original issue: projecthydra-labs/sufia-core#166_

**Comment by mjgiarlo** [comment]
@jcoyne :speech_balloon:
> This should go into CurationConcerns

@jpstroop @tpendragon :arrow_heading_up: :question:

**Comment by barmintor** [comment]
https://github.com/projecthydra-labs/curation_concerns/issues/509
 and
https://github.com/projecthydra-labs/curation_concerns/pull/531

**Comment by mjgiarlo** [comment]
Already fixed in CC, so closing this issue.
