### ISSUE TITLE
Should Sufia::FilesControllerBehavior be Sufia::FileSetsControllerBehavior

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1379]
_From @grosscol on November 12, 2015 17:18_

It looks like the functionality there is being mixed into the FileSetsController.  Is this naming a hold over from the GenericFile history?

_Copied from original issue: projecthydra-labs/sufia-core#187_

**Comment by mjgiarlo** [comment]
Yes, IMO, it should be FileSetsControllerBehavior to match what's in CC. FilesControllerBehavior is indeed a holdover from the GF days.

**Comment by jcoyne** [comment]
:+1: to rename

**Comment by awead** [comment]
See related question #1424
