### ISSUE TITLE
Make files controller class method instance methods and resolve calls.

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1380]
_From @grosscol on November 12, 2015 23:0_

Within sufia/app/controllers/concerns/sufia/files_controller_behavior.rb the UploadCompleteBehavior is mixed in a class methods using `extend`.  The methods should be instance methods and mixed in using `include`.
```
   extend Sufia::FilesController::UploadCompleteBehavior
```

https://github.com/projecthydra/sufia/blob/master/app/controllers/concerns/sufia/files_controller/browse_everything.rb#L21

https://github.com/projecthydra/sufia/blob/master/app/controllers/concerns/sufia/files_controller_behavior.rb#L20

_Copied from original issue: projecthydra-labs/sufia-core#198_

**Comment by mjgiarlo** [comment]
_From @flyingzumwalt on November 13, 2015 9:21_

Filling in some background from when we looked at this yesterday (to jog your memory when you get to it.

## What's Wrong
Sufia::FilesController::UploadCompleteBehavior defines `upload_complete_path ` and `destroy_complete_path `.  For some reason, [this line in files_controller/browse_everything.rb](https://github.com/projecthydra/sufia/blob/master/app/controllers/concerns/sufia/files_controller/browse_everything.rb#L21) calls 
```ruby
self.class.upload_complete_path
``` 
instead of just calling `upload_complete_path`.  Because of that, [this line in files_controller_behavior.rb](https://github.com/projecthydra/sufia/blob/master/app/controllers/concerns/sufia/files_controller_behavior.rb#L20) has to call 
```ruby
extend Sufia::FilesController::UploadCompleteBehavior
``` 
instead of 
```ruby
include Sufia::FilesController::UploadCompleteBehavior
``` 
in order to force those methods to be class methods (available at `self.class.xxx`) instead of instance methods.  That's strange.  

## How to Fix
It seems like you should be able to change  [this line in files_controller/browse_everything.rb](https://github.com/projecthydra/sufia/blob/master/app/controllers/concerns/sufia/files_controller/browse_everything.rb#L21) to call `upload_complete_path` instead of calling `self.class.upload_complete_path` and then switch [this line in files_controller_behavior.rb](https://github.com/projecthydra/sufia/blob/master/app/controllers/concerns/sufia/files_controller_behavior.rb#L20) to call `include` instead of `extend`.

To test, try making this change in regular sufia (whose tests are passing), then apply it to sufia-core if it works.

**Comment by atz** [comment]
Why closed?  Seems like issue is still there.
