### ISSUE TITLE
Rename FileSet URLs to match the Sufia URL aesthetic

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1382]
_From @mjgiarlo on November 18, 2015 22:58_

Rather than `/concern/file_sets/...`, should be `/concern/files/...`. May require work in CurationConcerns to implement. (@jcoyne said so.)

@mjgiarlo should probably review _all_ the routes in Sufia once the tests are passing and ticketize other such changes, before Sufia 7.0.0 ships.

_Copied from original issue: projecthydra-labs/sufia-core#257_

**Comment by mjgiarlo** [comment]
_From @jcoyne on November 23, 2015 20:3_

@mjgiarlo  This change obfuscates the fact that the controller is dealing with `FileSet`s and not `PCDM::File`s could cause confusion for developers working on Sufia in the future.  Perhaps you can give your rationale for this request.

**Comment by mjgiarlo** [comment]
The rationale is simple but highly speculative: our users don't know what `FileSet`s are but presumably know what files are. And I don't like underscores. ;) Your point is well taken about Sufia users that are PCDM-aware devs.

**Comment by mjgiarlo** [comment]
_From @barmintor on December 2, 2015 20:43_

What is the state of this ticket?

**Comment by mjgiarlo** [comment]
Still under discussion, @barmintor. Personally, I'd like to see this happen but perhaps given @jcoyne's point it's a lower priority?

**Comment by awead** [comment]
Related to #1424

**Comment by mjgiarlo** [comment]
I kinda don't care anymore.
