### ISSUE TITLE
Sufia::Ability#file_set_abilities conflicts with CurationConcerns::Ability#everyone_can_create_curation_concerns

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1383]
_From @jcoyne on November 24, 2015 21:45_

Probably just remove the Sufia one.

_Copied from original issue: projecthydra-labs/sufia-core#308_

**Comment by jcoyne** [comment]
Change curation_concerns to say `return unless registered_user?` here:
https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/models/concerns/curation_concerns/ability.rb#L39-L43

Then we can remove this line from sufia: https://github.com/projecthydra/sufia/blob/master/sufia-models/app/models/concerns/sufia/ability.rb#L40

**Comment by jcoyne** [comment]
Also move this method to curation_concerns: https://github.com/projecthydra/sufia/blob/master/sufia-models/app/models/concerns/sufia/ability.rb#L65-L67
