### ISSUE TITLE
Move feature/unfeature to GenericWork show page

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1384]
_From @jcoyne on November 25, 2015 15:50_

Presently it's commented out on the FileSet show page and doesn't exist on the GenericWork show page.
See https://github.com/projecthydra-labs/sufia-core/commit/bce04b2f8df690cf3c06d96daf1127538a4e9544

Also add these:
https://github.com/osulp/sufia/commit/bcaff5a81cd7d47af74c8e29c738b1216cc18933
https://github.com/osulp/sufia/commit/7f2dbbede3ca40f4dccccc415a48f922285c967f
https://github.com/osulp/sufia/commit/a28076809944637d3cff611cd1a82677585ab856

_Copied from original issue: projecthydra-labs/sufia-core#323_

**Comment by mjgiarlo** [comment]
Related to #1049

**Comment by hectorcorrea** [comment]
Done as part of PR #1503
