### ISSUE TITLE
TODO in _script_templates.html.erb 

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1385]
_From @hectorcorrea on December 3, 2015 17:4_

Update the FileSet presenter to include the `upload_set_id`

View `app/views/curation_concerns/file_sets/upload/_script_templates.html.erb` has a TODO showing where this value is needed.

_Copied from original issue: projecthydra-labs/sufia-core#389_

**Comment by mjgiarlo** [comment]
_From @jcoyne on December 3, 2015 17:9_

One thought i have is that generating a NOID for every view of the work is going to chew through a lot of noids (most won't get used).  How does everyone feel about using UUIDs for upload_set_ids instead? cc @mjgiarlo

**Comment by mjgiarlo** [comment]
I'm OK with it given our limited usage of UploadSets, partly because I don't have time at the moment to look into why we'd need to generate a NOID for every view of a work.

**Comment by hectorcorrea** [comment]
Now handled via: https://github.com/projecthydra/sufia/pull/1395

**Comment by hectorcorrea** [comment]
Closed eventually by PR #1391

**Comment by hackmastera** [comment]
Confused. Was the NOID vs UUID question resolved? If so, how did it fall out? @jcoyne @mjgiarlo

**Comment by hackmastera** [comment]
And, will I have migration problems if my batch_ids are currently NOIDs?

**Comment by jcoyne** [comment]
I don't think you'll have migration problems. In Sufia 7 the only thing batch_ids are used for is copying metadata to multiple newly created works.  I don't think it even makes sense for us to migrate batch_id from GenericFile to GenericWork.

**Comment by jcoyne** [comment]
@hackmastera and yes, it's a UUID https://github.com/projecthydra/sufia/blob/b0e3cf172d01814ea1dfc879736374564fd8f007/app/controllers/concerns/sufia/file_sets_controller_behavior.rb#L31

**Comment by hackmastera** [comment]
thanks!
