### ISSUE TITLE
Unable to create a 'generic work'

### ISSUE THREAD

**Issue by spr7b** [projecthydra/sufia#1390]
Using the Sufia master branch with the 7.0.0 Alpha on it (SHA 2796fa21ec57580d0953614f4fe8ff7b342d42fe  from 12/7/15), I built a new application using it. 
When I click to Create Work on my dashboard, I get an error:
```
Completed 500 Internal Server Error in 89ms
ActionView::Template::Error (undefined method `generic_works_path' for #<ActionDispatch::Routing::RoutesProxy:0xb5a26e20>):
    1: <%= simple_form_for [main_app, @form], html: { multipart: true } do |f| %>
    2:   <div id="works_edit">
    3:     <h2 class="non lower">Describe Your Work</h2>
    4:     <p>The more descriptive information you provide the better we can serve your needs.</p>
  actionpack (4.2.0) lib/action_dispatch/routing/routes_proxy.rb:36:in `method_missing'
  actionpack (4.2.0) lib/action_dispatch/routing/polymorphic_routes.rb:220:in `polymorphic_method'
  actionpack (4.2.0) lib/action_dispatch/routing/polymorphic_routes.rb:134:in `polymorphic_path'
  actionview (4.2.0) lib/action_view/helpers/form_helper.rb:466:in `apply_form_for_options!'
  actionview (4.2.0) lib/action_view/helpers/form_helper.rb:434:in `form_for'
  simple_form (3.1.1) lib/simple_form/action_view_extensions/form_helper.rb:26:in `block in simple_form_for'
  simple_form (3.1.1) lib/simple_form/action_view_extensions/form_helper.rb:45:in `with_simple_form_field_error_proc'
  simple_form (3.1.1) lib/simple_form/action_view_extensions/form_helper.rb:25:in `simple_form_for'
```
So I created a new work type:   rails generate curation_concerns:work Thesis
And I tried to create a work again, but still no success.

**Comment by mjgiarlo** [comment]
Thank you, @spr7b!

**Comment by hectorcorrea** [comment]
@spr7b I think this has been fixed. I tested with commit e61cf1e08ebb49195a0780158217ca8da3fe6ea9 and it looks OK. Could you confirm before I close this ticket?

**Comment by spr7b** [comment]
I have the latest sufia master code locally and created a fresh app using that and now I get something different:
'''
NoMethodError (undefined method `registered_user?' for #<Ability:0xb5e1f7e8>):
  /home/spr7b/Work/sufia/sufia-models/app/models/concerns/sufia/ability.rb:23:in `proxy_deposit_abilities'
  /home/spr7b/Work/sufia/sufia-models/app/models/concerns/sufia/ability.rb:16:in `sufia_abilities'
  hydra-access-controls (9.5.0) lib/hydra/ability.rb:52:in `block in hydra_default_permissions'
  hydra-access-controls (9.5.0) lib/hydra/ability.rb:51:in `each'
  hydra-access-controls (9.5.0) lib/hydra/ability.rb:51:in `hydra_default_permissions'
  hydra-access-controls (9.5.0) lib/hydra/ability.rb:30:in `initialize'
  cancancan (1.13.1) lib/cancan/controller_additions.rb:357:in `new'
  cancancan (1.13.1) lib/cancan/controller_additions.rb:357:in `current_ability'
  /home/spr7b/Work/sufia/app/controllers/concerns/sufia/controller.rb:12:in `current_ability'
  hydra-core (9.5.0) app/controllers/concerns/hydra/controller/search_builder.rb:6:in `block in search_builder'
  hydra-core (9.5.0) app/controllers/concerns/hydra/controller/search_builder.rb:6:in `tap'
  hydra-core (9.5.0) app/controllers/concerns/hydra/controller/search_builder.rb:6:in `search_builder'
  blacklight (5.16.4) app/controllers/concerns/blacklight/search_helper.rb:101:in `search_results'
  /home/spr7b/Work/sufia/app/controllers/concerns/sufia/homepage_controller.rb:29:in `recent'
  /home/spr7b/Work/sufia/app/controllers/concerns/sufia/homepage_controller.rb:22:in `index'
  actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
'''
Should I not be using my own app which uses Sufia, but instead just using Sufia itself raw?

**Comment by hectorcorrea** [comment]
@spr7b I would be curious if you get the same error using the test app that Sufia creates when you run `bundle exec rake engine_cart:generate` 

We should also try to figure out why your own app does not work. This might point to a missing step in the upgrade. 

@jcoyne Does the `undefined method `registered_user?' for #<Ability:0xb5e1f7e8>` error rings any bells?

**Comment by jcoyne** [comment]
@spr7b you need to `bundle update curation_concerns` to get the latest version of CurationConcerns. That'll fix the no method error.

**Comment by spr7b** [comment]
```bundle update curation_concerns``` did not yield any better results, same error.  I'm trying to use the Sufia as the usage instructions on the Readme page suggest.  I've got the latest sufia pulled from github master branch and have pointed to its path in the app's gemfile.

**Comment by jcoyne** [comment]
@spr7b do you have 
```
gem 'curation_concerns', github: 'projecthydra-labs/curation_concerns', branch: 'master'
```
in your Gemfile?  The master branch of sufia only works with the master branch of curation_concerns.

**Comment by spr7b** [comment]
Thank you.   That was the missing piece.  Sufia's gemfile was pointing to ```gem.add_dependency 'curation_concerns', '~> 0.3'```.  
I can now create a generic work from an app built to use Sufia.
