### ISSUE TITLE
CollectionBehavior#bytes

### ISSUE THREAD

**Issue by hectorcorrea** [projecthydra/sufia#1392]
There is an issue in CollectionBehavior#bytes that is causing Sufia to throw error 

```
"undefined method `content' for #<GenericWork:0x007fe9dea48ba0>""
```

@grosscol seems to know the root cause of this. 

See https://github.com/projecthydra/sufia/blob/master/sufia-models/app/models/concerns/sufia/collection_behavior.rb#L20

**Comment by jcoyne** [comment]
Sorry to yank your ticket, but I think I've fixed this in https://github.com/projecthydra/sufia/pull/1393  While this is normally impolite, I hope you will excuse the trespass as the builds were all broken.

**Comment by grosscol** [comment]
Works for me.
