### ISSUE TITLE
A work should have a representative thumbnail

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1394]
As a result of decomposing the GenericFile from Sufia < 7 into separate FileSet and Work concerns, the embedded metadata that drives Twitter cards is now out of step with the implementation of Sufia 7's domain model.

To continue supporting rich Twitter card snippets, a work should have a representative thumbnail:

https://github.com/projecthydra/sufia/blob/master/app/views/shared/_citations.html.erb#L9

The model should already support selecting a representative thumbnail via CurationConcerns, and the CC UI already supports this.

See a suggested wireframe here: https://wiki.duraspace.org/pages/viewpage.action?pageId=68070466

**Comment by mjgiarlo** [comment]
There's a bunch left unsaid still but I don't have cycles to write this up fully, @barmintor. It's a start.

**Comment by jcoyne** [comment]
we already have a representative thumbnail in the model (and in the CC ui).  We ought to have a wireframes made to figure out how that fits into the Sufia UI.  I'm not sure what a citable full-text PDF would be for something like an Image or a Video.

**Comment by mjgiarlo** [comment]
Right, and perhaps it's OK for the embedded metadata to be broken since those things aren't good fits for GScholar. Thanks for the note on rep. thumbnails in CC, too.

**Comment by jcoyne** [comment]
I'm not sure this ticket is actionable right now.  Can this be improved or closed?

**Comment by mjgiarlo** [comment]
@jcoyne Since we already have a rep. thumb in CC, I'd like to see us get Twitter card support working. I will re-focus this ticket on that, and create another (probably unactionable issue) to come up with a solution for GScholar integration.

**Comment by mjgiarlo** [comment]
See https://github.com/projecthydra/sufia/issues/1460 for the related issue which was broken out of this one.

**Comment by mjgiarlo** [comment]
Yes, this can be closed.
