### ISSUE TITLE
Redirect to appropriate batch upload page

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1398]
When uploading files that have default works created for them, the page should redirect to a batch upload page where metadata can be added and subsequently applied to all the default works created during the upload process.

A workaround was introduced in 1995d19ff21ef6ee684a2c1748e50edab00aada0 which should be remove once this ticket is closed.

Relates to: projecthydra-labs/curation_concerns#541 and #1397

**Comment by jcoyne** [comment]
Blocked by https://github.com/projecthydra-labs/curation_concerns/pull/547
