### ISSUE TITLE
Upload on work show page should be on edit page

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1416]

**Comment by jcoyne** [comment]
I disagree.  Putting this on the edit page means

1) when files are done uploading it redirects and  it won't save any other edits the user made
2) if the user clicks "save" for the edits before the files are done uploading, then the files won't complete.

**Comment by mjgiarlo** [comment]
I'm :+1: on removing the "Attach File" button from the work show page but leaving the "add files" widget for the reasons @jcoyne mentions.
