### ISSUE TITLE
On a work show page analytics blows up

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1419]
Missing Template: stats/work

**Comment by njaffer** [comment]
I started working on this and copied the file stats to work template to see what information we can use from file stats. But the question is what information (if any) is collected and saved?

**Comment by hectorcorrea** [comment]
You can find the information that is collected and saved for Files in the SQL database. Tables 'file_view_stats' and 'file_download_stats' are used to track both views and downloads.
