### ISSUE TITLE
sufia-models no longer needs to be a gem

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1423]
Remove the bits around managing the sufia-models gem (such as rake tasks), and reorganize the code such that we no longer have a sufia-models directory.

**Comment by mjgiarlo** [comment]
37 failures: https://gist.github.com/mjgiarlo/79f16d618435ff73d99d

**Comment by awead** [comment]
:ship: :fire:

**Comment by mjgiarlo** [comment]
:laughing:
