### ISSUE TITLE
Sufia::FilesController versus CurationConcerns::FileSetsController

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1424]
With the change from `Files` to `FileSets` in the curation_concerns gem, what is the different between the Sufia::FilesController and the CurationConcerns::FileSetsController? Is the latter supposed to replace the former? If not, what's the distinction between the two?

**Comment by mjgiarlo** [comment]
Sufia's FilesControllerBehavior is Sufia-specific stuff that we inject into https://github.com/projecthydra/sufia/blob/master/app/controllers/curation_concerns/file_sets_controller.rb to make selective overrides and additions to the FileSetsController provided by CC. But that's not obvious by looking at the behavior in Sufia because there's no mention of CC in that file.

**Comment by awead** [comment]
@mjgiarlo ok, that makes sense now, but isn't immediately obvious. Given the questions raised in #1427, I'm wondering if there's a way to make this clearer in the code. Renaming any instance of FilesController to FileSetsController might help, but also maybe some re-kajiggering of modules includes too?

**Comment by mjgiarlo** [comment]
Renaming would be a good start. Re-kajiggering is OK by me too if we can make it the override a bit clearer.

**Comment by awead** [comment]
My only thought on the re-kajiggering was moving the FileSetsController to app/controllers/file_sets_controller.rb so that:
``` ruby
class FileSetsController
  include CurationConcerns::FileSetsController
  include Sufia::Controller
  include Sufia::FileSetsControllerBehavior
end
```
As it stands now, it's burried under app/controllers/curation_concerns

**Comment by mjgiarlo** [comment]
I thought it was in that directory intentionally, taking advantage of Ruby namespacing to effectively inject our concerns into CC's FileSetsController. There are other ways to do that of course.

**Comment by awead** [comment]
Oh, ok, that makes sense then. I think I'm down with the further `Files` to `FileSets` renaming. I'll take that up. I think ideally, with also the Files versus Works distinction, there should be little occurrence of the word "file" or "files" in the final released gem.

**Comment by mjgiarlo** [comment]
Agree that "file" in Sufia codebase should only be used in the pcdm:File context. OTOH, I think we should still label FileSets as "files" in the UI because our users have no idea what a FileSet is and (IMO) shouldn't need to. You probably meant this but I wanted to tease that out.

**Comment by awead** [comment]
Yeah, good clarification!

**Comment by grosscol** [comment]
@mjgiarlo for the UI, should the keys in the localizations be ui_file or something to that effect to explicitly delineate between where we mean "file as in pcdm::file" and "file as in the word the user will read" ?

**Comment by mjgiarlo** [comment]
@grosscol I don't feel strongly about that at the moment. ¯\_(ツ)_/¯ (but thanks for raising it, and PRs welcome from folks who feel more strongly about it than I do.)
