### ISSUE TITLE
Do Events go on FileSets or Works?

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1437]
To close this ticket we should investigate what events are currently being created, where they are being created and then ticket the differences from the following specification. There are six content-related event jobs at the moment. Here's how they should break down between FileSets and Works:

1. ContentDepositEvent: Work & FileSet
1. ContentUpdateEvent: Work & FileSet
1. ContentDeleteEvent: Work & FileSet
1. ContentDepositorChangeEvent: Work
1. ContentNewVersionEvent: FileSet, since we're only versioning content at this point
1. ContentRestoredVersionEvent: FileSet, since we're only versioning content at this point

**Comment by grosscol** [comment]
Looking at the list of EventJobs, all the content jobs take a file_set.id as the first parameter.   It would make sense to display the event notification on the work show page possibly in the list of FileSets.

@jcoyne what did you have in mind?

**Comment by jcoyne** [comment]
Not all of the jobs actually. Some events are for works.

**Comment by mjgiarlo** [comment]
@jcoyne @grosscol 

One **could** argue that all events should just go on the work, but PCDM allows FileSets to move between Works, which would complicate the move. Though Sufia does not currently permit this behavior, I think we can expect people to ask for it in the near future at which point we'll have a lot to figure out and perhaps it's best NOT to just toss all events on the Work.

There are six content-related event jobs at the moment. Here's how I see them breaking down between FileSets and Works:

1. Deposit: Work
1. Update: Work
1. Delete: Work
1. Depositor Change: Work
1. New Version: FileSet, since we're only versioning content at this point
1. Restored Version: FileSet, since we're only versioning content at this point

Given that GFs turned into Ws and FSs, I suspect we could use some new event jobs to tease this out, and those might be:

1. File Attached: FileSet
1. File Deleted: FileSet

That way we can track and publish major lifecycle events around both FileSets and Works. Thoughts?

cc: @cam156 @awead @hectorcorrea @mtribone

**Comment by mjgiarlo** [comment]
(The above would need to be expanded when we allow copying/moving FileSets between Works, and when we allow creating component Works. I suspect we should also generate events around creating, updating, and deleting Collections but that's going above and beyond this particular issue.)

**Comment by jcoyne** [comment]
We also need UI wire frames that show where we display the events for the FileSet and where the events for the Work are displayed.

**Comment by mjgiarlo** [comment]
:speech_balloon: @jcoyne:
> We also need UI wire frames that show where we display the events for the FileSet and where the events for the Work are displayed.

Hey, @mtribone, do you see :arrow_heading_up: as being in scope for what the Sufia UI WG is doing now? Or might that be a good parking lot item to tackle after the current work is delivered?

**Comment by mtribone** [comment]
@mjgiarlo mmmmmmmaybe? My gut says parking lot based on the focus and velocity of the group. However, it could be something done individually to aid the developers with an existing problem.

**Comment by mjgiarlo** [comment]
@jcoyne Given what @mtribone says, is this a thing we can make a provisional call on now/soon and iterate when the Sufia UI WG has more time to give to this?

**Comment by mjgiarlo** [comment]
Alternatively... @mtribone re: your "individually" comment, might you have cycles to take a gander in the coming weeks?

**Comment by mtribone** [comment]
@mjgiarlo Yeah man. I have a meeting with the library this afternoon and will know more about what is coming my way.

**Comment by mjgiarlo** [comment]
@mtribone :highfive: :tada:

**Comment by mjgiarlo** [comment]
Any updates, @mtribone?

**Comment by mtribone** [comment]
@mjgiarlo Work on LibGuides TBD in January, so I'd say that I have some time this week to give it a go. Otherwise, I'll see ya'll in 2016. :tada:

**Comment by mjgiarlo** [comment]
LIBGUIDES. ack. ;)

Thanks, @mtribone

**Comment by cam156** [comment]
To close this ticket we should investigate what events are currently being created, where they are being created and then ticket the differences from what Mike G suggested as the goal for events.

**Comment by mjgiarlo** [comment]
@cam156 :clap: :+1:

**Comment by awead** [comment]
Penn State using ContentEventJob to do things like show a SHARE Notify event. For example, I just shared my file with SHARE Notify... for that, we put it on the work.

**Comment by mjgiarlo** [comment]
# Desired state

1. Content Deposit: Work & FileSet
1. Content Update: Work & FileSet
1. Content Delete: Work & FileSet
1. Content Depositor Change: Work
1. Content New Version: FileSet
1. Content Restored Version: FileSet

# Actual state

1. Content Deposit: FileSet
1. Content Update: FileSet
1. Content Delete: FileSet
1. Content Depositor Change: Work
1. Content New Version: FileSet
1. Content Restored Version: FileSet

# Work to be done

- [ ] When a Work is deposited, a ContentDepositEvent should be logged.
- [ ] When a Work's metadata is deposited, a ContentUpdateEvent should be logged.
- [ ] When a Work is deleted, a ContentDeleteEvent should be logged.
- [ ] Verify ContentNewVersionEvents and ContentRestoredVersionEvents are working when #1933 is fixed.

**Comment by mjgiarlo** [comment]
I believe this requires work to be done in CurationConcerns. Following up with a ticket there.
