### ISSUE TITLE
File set show page is broken

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1456]
when I visit this URL: http://localhost:3000/concern/file_sets/6969z1096 an error occurs

within `sufia/app/views/shared/_citations.html.erb `
```
undefined method `first' for nil:NilClass

  <meta name="twitter:data2" content="<%= @presenter.rights.first %>"/>

Trace of template inclusion: /Users/justin/workspace/sufia/app/views/curation_concerns/file_sets/show.html.erb
```

**Comment by mjgiarlo** [comment]
Same as #1464, which has a bit more detail. @hectorcorrea

**Comment by jcoyne** [comment]
Closing as duplicate of #1465
