### ISSUE TITLE
When you click "Attach a file", the file is not attached to the work

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1459]
On the work show page if you click "Attach a file", then upload files, the file is not attached to the work.  However if from the work show page you click "Select file..." then "Start upload" it works.

My recommendation is to remove the "Attach a file" path.

**Comment by grosscol** [comment]
I concur.  Is this related to #1415?

**Comment by mjgiarlo** [comment]
:+1:, let's remove the "Attach a file" path.
