### ISSUE TITLE
Date uploaded is not being displayed for works on the dashboard

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1467]
http://localhost:3000/dashboard/works

**Comment by njaffer** [comment]
@jcoyne: I noticed that the date is not displayed when the work was created with the option of 'Attach a File', which is not an option any more. If I create a work from dashboard, the date uploaded is always displayed.

**Comment by hectorcorrea** [comment]
@njaffer thanks for the heads up, it helped me find the culprit rather easily.
