### ISSUE TITLE
Collector and editor roles in view

### ISSUE THREAD

**Issue by hectorcorrea** [projecthydra/sufia#1477]
View `app/views/curation_concerns/base/_show_actions.html.erb` depends on two variables (`collector` and `editor`) that are not defined. There is a TODO in the view at the moment indicating that this needs to be fixed (see PR #1476). It's possible that this code will be replaced with calls to `ability`

**Comment by mjgiarlo** [comment]
@hectorcorrea one component I'm missing is the "why" piece. I get that this is a TODO that fell out of #1476, but this ticket doesn't say why we should do this work. (Is this a bug or an enhancement or an alignment with CC or... ?) For now, assigning to the backlog but I'm happy to reclassify it based on your feedback!

**Comment by hectorcorrea** [comment]
@mjgiarlo The "why" would be to render certain features (e.g delete this, edit this) to only certain users and not to unauthenticated users. 

It is possible that we don't need all these features for FileSets and/or that we need a separate `_show_actions.html.erb` page from the one shared with Works.

**Comment by mjgiarlo** [comment]
I agree too that we probably just need an ability here, e.g., `current_user.can? :edit, curation_concern` or some such. So are we currently letting unauthenticated users see features (delete, edit) they can't use? If so, I'm inclined to mark this a bug and move it from the backlog to the 7.0.0 milestone.
