### ISSUE TITLE
Call to export_as_openurl_ctx_kev

### ISSUE THREAD

**Issue by hectorcorrea** [projecthydra/sufia#1479]
View `views/curation_concerns/base/_show_actions.html.erb` calls `export_as_openurl_ctx_kev` that passes `FileSetPresenter` as the parameter but the function expects a `work` which causes an error. See PR #1476 

Not sure if we need to pass a different value, refactor `export_as_openurl_ctx_kev` to allow a presenter, remove the call to it from this view, or something else.

**Comment by mjgiarlo** [comment]
I would like to see us sort this out in the 7.0.0 release, since the export functions are so visible.
