### ISSUE TITLE
show_collections.html.erb and parent_collections

### ISSUE THREAD

**Issue by hectorcorrea** [projecthydra/sufia#1480]
The logic in view `/views/curation_concerns/file_sets/_show_collections.html.erb` to handle "parent collections" is busted. See PR #1476.

Not sure what we need to do here. Perhaps look at the code in Curation Concerns and see how this is done there. Do we even have "parent collections" in Sufia 7?

**Comment by mjgiarlo** [comment]
No, I don't believe we expose in the UI a way for folks to create nested collections. We should support nested collections in 7.x, but I don't want this to block 7.0.0, so assigning to 7.1.0.

**Comment by jcoyne** [comment]
This should probably involve updating `CurationConcerns` so that the `WorkShowPresenter` has an in_collections method that returns an array of `CollectionPresenters`

**Comment by atz** [comment]
Rationale for milestone promotion?

**Comment by jcoyne** [comment]
@atz for parity with sufia 6
