### ISSUE TITLE
Descriptions in FileSet Show 

### ISSUE THREAD

**Issue by hectorcorrea** [projecthydra/sufia#1481]
There is a TODO in `views/curation_concerns/file_sets/show.html.erb` to discuss whether we want to render descriptions in FileSets or not. See PR #1476 

Talk to @mjgiarlo before tackling this ticket, or wait for this ticket to be updated with a clear path of whether this is needed or not.

**Comment by mjgiarlo** [comment]
I'd like to see this tackled in 7.1.0, to enable some small amount of descriptive metadata on FileSets (which will include work on the show view, edit views, etc.).
