### ISSUE TITLE
Fix error  "uninitialized constant Sufia::GenericFile::Actor::Collection" during upload to collection

### ISSUE THREAD

**Issue by elrayle** [projecthydra/sufia#1487]
A problem was noted that in a Linux environment with Apache and Passenger, sometimes an error would occur when attempting to upload files directly to a collection.  The error:  uninitialized constant Sufia::GenericFile::Actor::Collection.  This is intermittent.  Some uploads will succeed and others will fail.

It is unclear why rails sometimes can find Collection and other times not.  The fix is to more specifically address the Collection class with ::Collection to avoid the prepending of Sufia::GenericFile::Actor.

Additionally, it was noted that apps may have their own FacetsHelper class.  To aid apps to use the facet helpers required for collection faceting, the method for determining whether to show the collection facet was moved to a concern.  This allows apps with there own facet helpers can do a simple include of Sufia::FacetsHelperBehavior in their FacetsHelper class.

**Comment by mjgiarlo** [comment]
Thanks for reporting this, @elrayle !

**Comment by mjgiarlo** [comment]
@elrayle I see you've pushed a branch related to this issue. How close do you think you are to creating a PR? I ask because I'm wondering whether to cut a 6.5.1 release soon, or just wait on this PR to cut 6.6.0.

**Comment by elrayle** [comment]
Fixed by PR https://github.com/projecthydra/sufia/pull/1501
