### ISSUE TITLE
Users should be allowed to assert a resource type on collection

### ISSUE THREAD

**Issue by njaffer** [projecthydra/sufia#1498]
Missing Resource Type error on create a new Collection and view a collection

**Comment by mjgiarlo** [comment]
I'm not sure I understand this one. This would be a change -- you were able to have resource types on collections in Sufia 6.x. What's the error? Can you include information about how to reproduce the error, and include a traceback? Thanks, @njaffer

**Comment by njaffer** [comment]
Here is the traceback: https://gist.github.com/njaffer/98bd33804ecc41027434

**Comment by mjgiarlo** [comment]
OK, thx.

Folks can assert resource_type on collections in Sufia 6.x, so I'm reluctant to change this in 7.x. I'm open to discussing changes to the underlying metadata in the future.

**Comment by mjgiarlo** [comment]
@njaffer Are you working on this one, or were you just reporting it for now?

**Comment by njaffer** [comment]
@mjgiarlo, I was planning to, if it is only to remove the resource type from new collection. @jcoyne, also mentioned in the chat that there is only one type of Collections. I am not an expert on Collections, so I will leave it on you to decide if we need to make it work with resource type or remove resource type!

**Comment by mjgiarlo** [comment]
@njaffer Yeah, let's make it work since it's a continuation of 6.x functionality. Thanks! I'll add you as assignee.

**Comment by njaffer** [comment]
Comparing with Sufia 6, the Collection presenter in Sufia 7 has few extra includes: https://github.com/projecthydra/sufia/blob/master/app/models/concerns/sufia/solr_document_behavior.rb#L5-L8

Any ideas if that could be the issue? The collection is saved in the solr doc, but when view is called, it is not able to find the resource_type

**Comment by mjgiarlo** [comment]
@njaffer I don't see anything in those extra modules that should cause this.

I notice that the work presenter delegates more terms to its solr document:

https://github.com/projecthydra/sufia/blob/master/app/presenters/sufia/work_show_presenter.rb#L4

I wonder if the collection presenter should do the same?

**Comment by njaffer** [comment]
@mjgiarlo, yep you got it! It is working, when I add the delegate for resource_type. Do you think I should add all the ones (based_near, depositor...) from work_show_presenter?

**Comment by mjgiarlo** [comment]
woohoo!

I'd say add them one-by-one as we see failures/errors, adding test coverage along the way.
