### ISSUE TITLE
Featured Works - migration

### ISSUE THREAD

**Issue by hectorcorrea** [projecthydra/sufia#1506]
Implement code to migrate "Featured Files" to "Featured Works"

Keep in mind that the SQL table `featured_works` was named `featured_works` (not `featured_generic_files`) since before Sufia 7. However, this table used to have a `generic_file_id` field that now has been replaced with `generic_work_id`

**Comment by mjgiarlo** [comment]
See related comment here: https://github.com/projecthydra/sufia/issues/1140#issuecomment-165265743

**Comment by gordonleacock** [comment]
Hi Hector, please see my comment on #1455 about "@presenter.display_feature_link?" and "@presenter.display_unfeature_link?".

**Comment by hectorcorrea** [comment]
@gordonleacock I've added a comment with the link on where those methods were introduced: https://github.com/projecthydra/sufia/issues/1455#issuecomment-171447413
