### ISSUE TITLE
Default minter-state file location in /tmp is likely to cause problems

### ISSUE THREAD

**Issue by ojlyytinen** [projecthydra/sufia#1510]
I originally accidentally posted something in here which was meant for our internal github and then deleted it. But since this has now sparked a bit of a discussion, I'll just summarise here what it was about.

Sufia saves ID minter state in /tmp/minter-state by default. Because this is under /tmp, it's very likely that it gets deleted by something at some point. A new minter state will automatically be generated but it will generate same IDs that have already been used, unless you have a really small number of records (as in less than a hundred). This may then cause various problems, although a new version of Active Fedora will skip over IDs if they exist (or have existed) in Fedora before.

**Comment by jcoyne** [comment]
I've had this exact problem before. Maybe /tmp is a bad default.

**Comment by ojlyytinen** [comment]
Meant to post this in our internal Github but accidentally got the wrong Github page open and it ended up here.

But yes, I think /tmp is maybe a bad default. Or alternatively installation instructions could say that it should be changed in production systems.

**Comment by mjgiarlo** [comment]
I'm happy to change to default if y'all have suggestions. Is there a sensible, reliable location within the Rails directory structure we should be using?

**Comment by mjgiarlo** [comment]
There is a mention of changing the location here but I agree it's not prominent (and not at all mentioned in Sufia proper): https://github.com/projecthydra-labs/active_fedora-noid#minter-state-for-replayability

**Comment by hectorcorrea** [comment]
Perhaps by default we should create the file inside the application folder with a name like "changeme" so that the existence of the file and the need to do something about it would be more prominent.

**Comment by mjgiarlo** [comment]
I like the idea of putting it in the application folder, but I'd incline more towards a name like "dontchangeme" so people don't accidentally delete, or blithely rename, their minter state files. :stuck_out_tongue_winking_eye:

**Comment by jcoyne** [comment]
Putting it in the application folder is better than /tmp, but not much.  If you use capistrano to deploy, you'll blow it away on every deploy.  I think a better solution is to prompt the user for the statefile location in the sufia:install generator.

**Comment by grosscol** [comment]
At the very least, the option could be explicitly written into the default config.  I think I'm currently adding `CurationConcerns.minter_statefile='my/minter/path'` in config/initializers/curation_concerns.rb.  I don't recall if adding it to the sufia initializer works anymore.

**Comment by mjgiarlo** [comment]
@jcoyne I'm cool with that if we can specify a sensible default so that people who don't know or care about such things can just hit "enter."

@grosscol You don't see a line like `# config.minter_statefile = '/tmp'` in `.internal_test_app/config/initializers/sufia.rb`?

**Comment by ojlyytinen** [comment]
I see my accidental posting sparked quite a discussion. I guess that's what always happens to please ignore posts. I'll reopen this since it is an actual issue in Sufia  and there's some good comments in here.

Regardless of the new default location, I think a few words about it would be in order in README.md or some other prominent location. Just something which points out that this is probably something you need to pay attention to when setting up a production system. We have two servers in our production system and any default location is going to cause them to mint same IDs.

**Comment by mjgiarlo** [comment]
@ojlyytinen I'll add a blurb to the README and solicit contributions on the mailing lists.

**Comment by mjgiarlo** [comment]
Took a crack at that here: https://github.com/projecthydra/sufia#identifier-state

**Comment by mjgiarlo** [comment]
@ojlyytinen @hectorcorrea 

A spontaneous conversation about this just popped up in Slack with @grosscol & @jcoyne and here's the proposal we came up with. What do y'all think about this?

> The basic tension here is that we're shooting for dev/test environments to "just work" -- where the best options are to use a reliably common, writable directory like `/tmp/` or to place the file in the Rails directory structure -- and for prod environments not to break on reboot, or on Cap deployment, or on /tmp autoclean.
> 
> Here's what we propose. Let's keep using `/tmp` in dev, and require in our documentation that folks either use the `/var/sufia/` location for this file (a new default in prod envs) or override the value of `config.minter_statefile` themselves. We can support the documentation by changing the Sufia initializer to something like: `config.minter_statefile = Rails.env.production? ? '/var/sufia/minter-state' : '/tmp/minter-state'`
> 
> A reasonable next step would be to have the install generator, and an appropriate upgrade generator, to attempt to do this for you (and print out a message if it doesn't work).

Did I capture that right, @jcoyne @grosscol? Thoughts, folks?

**Comment by jcoyne** [comment]
I'm not sure if this is correct:
> A reasonable next step would be to have the install generator, and an appropriate upgrade generator, to attempt to do this for you (and print out a message if it doesn't work).

I don't think any generators are necessary. We just need to change the default in `engine.rb`

**Comment by grosscol** [comment]
People will have to be aware that the default changed, but I don't think this will affect any production instances.  None of those should have been using /tmp anyway.  Unless their uptime was the lifetime of the application.

I think that captures the conversation @mjgiarlo

**Comment by mjgiarlo** [comment]
@jcoyne I could see a generator saying "Hey, if you want to run this in production, let's sudo create that directory now." If it succeeds, everything just works. If it fails, it complains at you and lets you know to go create this directory ASAP if you plan to use the production environment, but otherwise continues doing its thing. I'm assuming here that Thor has some utility for sudo'ing that isn't going to be, or be perceived as, a security threat.

**Comment by hectorcorrea** [comment]
+1

I would suggest un-commenting  `config.minter_statefile = '/tmp/minter-state'` in sufia.rb to make it more obvious that we are using a file under `tmp` unless an action is taken.

**Comment by jcoyne** [comment]
@mjgiarlo people don't run generators in the production environment.  Generators are for generating changes to the source code, not for provisioning servers.

**Comment by hectorcorrea** [comment]
I wouldn't complicate the generator. As @jcoyne said people don't run them in production.

**Comment by jcoyne** [comment]
@hectorcorrea No. If you do that, then it will never use our defaults from environment.rb

**Comment by mjgiarlo** [comment]
@grosscol Agree that people will need to be made aware of this. I'm less confident that it won't affect current implementations. /tmp cleanup can be handled in many different ways. (Is /tmp a local FS or an in-memory FS? If the former, files will hang around, and you can configure your /tmp cleaner such that it only deletes files that haven't been touched for n days.) I'm not saying lots of folks have done this, but I'd be more comfy if we assumed that this *will* break lots of people and communicate it accordingly.

**Comment by jcoyne** [comment]
@mjgiarlo most distros drop /tmp when the server restarts.  If you have good uptime, then you'd only need to worry about a /tmp cleaner script.  But let's assume worst case (someone's in the server room and pulls the wrong cords), then the server is down and /tmp is gone.

**Comment by mjgiarlo** [comment]
@jcoyne I mean, I don't run generators in production. But people do **weird** things, man, especially when they're new to Rails. I don't think it'd add a lot of code to do this, and I don't see much of a downside at the moment. (I don't see this adding complexity, @hectorcorrea, just a few extra lines of code. Am I underestimating the effort/complexity here?)

**Comment by hectorcorrea** [comment]
@mjgiarlo I mean for the **user** of the generator, now they have to make a decision at a time where they probably won't be ready for it (Noid generation is probably not in the developer's mind when they are first starting with Sufia.)

**Comment by jcoyne** [comment]
@mjgiarlo we certainly wouldn't add it to any existing generators. So, why make it a generator?  Why not check when you try to start up the app (like in an initializer)?

**Comment by mjgiarlo** [comment]
@jcoyne I'd add it to the install generator. To be clear, I see this as gravy, not necessary behavior. I like Sufia to be as friendly to its users as is manageable.

I do think @hectorcorrea has a good point about confusing new Sufia devs, who are like "why is this thing asking me for my root password, and what the hell is a minter statefile? I just want to upload files." So based on that, I can be OK with striking the idea of handling this automagically via generator. (I am down with the initializer approach, still.)

**Comment by jcoyne** [comment]
@mjgiarlo but the install generator is something you only run one time, and in dev mode (on your developer box).  It's not run on the server.

**Comment by mjgiarlo** [comment]
> @jcoyne I mean, **I** don't run generators in production. But people do **weird** things, man, especially when they're new to Rails. I don't think it'd add a lot of code to do this, and I don't see much of a downside at the moment

But I'm no longer advocating for this, so :clap:

**Comment by mjgiarlo** [comment]
Replaced the generator text with `The initializer should check that the path exists and complain and fail if not at runtime.`

**Comment by jcoyne** [comment]
:+1: I *think* we're in agreement. :hamburger:

**Comment by mjgiarlo** [comment]
:speech_balloon: @jcoyne 

> :+1: I *think* we're in agreement. :hamburger: 

UNTIL I EDIT THE TEXT ABOVE AND SNEAK THE GENERATOR BACK IN, MWAHAHAHA

-Generator Mike

**Comment by mjgiarlo** [comment]
There's a lot of back and forth here, so I'm going to close this ticket and have #1532 focus on the code changes. Thanks a bunch, @ojlyytinen, for reporting tihs, and thanks to @jcoyne, @hectorcorrea, and @grosscol for coming up with the solution.

**Comment by ojlyytinen** [comment]
I think the plan you came up with works great. For development it's handy to have something that requires minimum config changes, even if it's not the ideal location otherwise, so /tmp is fine.

My only problem was that it was easy to set up a production environment and not notice that you need to pay attention to this detail. So even just a little something in the readme, like we have now, solves that. If you make the production default be /var/sufia when it exists or force a manual configuration otherwise is even better.
