### ISSUE TITLE
Generic Works Edit Page: Redundant Visibility Text box 

### ISSUE THREAD

**Issue by njaffer** [projecthydra/sufia#1513]
The generic_works edit page has a Visibility text box under 'Describe Your Work' section. Since there is Visibility under permissions section, this seems to be redundant. Also when I tried to enter some text and saved the work, but the text was not saved for Visibility text box. 

![screen shot 2016-01-14 at 1 52 40 pm](https://cloud.githubusercontent.com/assets/12487929/12334108/292856c2-bac6-11e5-81a5-a7a098ae0d92.png)

**Comment by mjgiarlo** [comment]
Can you include in the description of this ticket what the error is? Looking at the screenshot it's not obvious what's wrong. (Maybe I'm not looking closely enough.)  Thx for reporting this!

**Comment by njaffer** [comment]
@mjgiarlo, updated the comments!

**Comment by njaffer** [comment]
@mjgiarlo, question is do we need to make it work or delete that text box?

**Comment by mjgiarlo** [comment]
Can you include a screenshot that shows the other  text box? and what doesn't save?

**Comment by njaffer** [comment]
@mjgiarlo, if you look at the screenshot I have shared, there is 'Visibility' under 'Thumbnail'. When I put some text in that text box under Visibility, it does not save

**Comment by mjgiarlo** [comment]
Ah! Yes, that form field should not be there. Thanks again, @njaffer
