### ISSUE TITLE
GenericWork and UploadSet relationship

### ISSUE THREAD

**Issue by hectorcorrea** [projecthydra/sufia#1523]
In Sufia when a `Work` is associated to an `UploadSet` the relationship is

```
<workA> <isPartOf> <uploadSetB>  
```

This looks backwards. Shouldn't the relationship be

```
<uploadSetB> <isPartOf> <workA>
```

This would reflect better than an `UploadSet` can be associated with a single `Work`, but a `Work` can have multiple `UploadSets`

Another approach would be to use `hasUploadSet` instead of `isPartOf` if we wanted to keep the predicate in the `Work`.

Thoughts?

**Comment by hectorcorrea** [comment]
![screen shot 2016-01-20 at 4 43 39 pm](https://cloud.githubusercontent.com/assets/568286/12464191/d314ad88-bf95-11e5-8eb2-5ef9edb10e55.png)

**Comment by mjgiarlo** [comment]
An UploadSet is a special kind of collection of GenericWorks, so saying that the UploadSet is part of the work seems backwards to me.

I don't object to changing the predicate -- I'm guessing that we use `isPartOf` because it continues the former relationship between GenericFiles and Batches.

**Comment by hectorcorrea** [comment]
I took a look at how `UploadSets` are used in Curation Concerns
and it seems that we are significantly changing their behavior in
Sufia.

In Curation Concerns the relation is between `FileSets` and `UploadSets`
whereas in Sufia we are making the relationship between `Works` and `UploadSets`.

For example, in CC a work with two files uploaded at once is represented as
follows (notice that the FileSets `fs` and `fs2` are related to the UploadSet `us1`):

```
  <gw1> hasMember <fs1>, <fs2> .
  <fs1> isPartOf <us1> .
  <fs2> isPartOf <us1> .
```

If a third file is added to the work in CC we will have the following
(notice that the new `FileSet` `fs3` points to a different 
`UploadSet` `us2` even thought it belongs to the same work as the others)

```
  <gw1> hasMember <fs1>, <fs2> <fs3>.
  <fs1> isPartOf <us1> .
  <fs2> isPartOf <us1> .
  <fs3> isPartOf <us2> .
```

However in Sufia we are doing something totally different. In Sufia we 
are linking `Works` directly to `UploadSets` and bypassing the `FileSet`.

In Sufia, the scenario depicted above will look as follows
(notice that although we can tell that the work has two upload sets we
cannot tell which file came on each upload set, effectively making the 
concept of upload set useless)

```
  <gw1> hasMember <fs1>, <fs2> <fs3> .
  <gw1> isPartOf <us1> <us2> .
```

I suspect this change in the way upload sets are related betwen Sufia
and Curation Concerns was made to accomodate for the concept of a
"Batch" in Sufia 6.

However, I think we could use `UploadSet` concept in Sufia in the
way it was intended in Curation Concerns (FileSet->UploadSet) and
still preserve the idea of a "Sufia 6 batch".

For example, let's say that we have two Sufia 6 generic files
uploaded in a single batch. These two files will be migrated to
Sufia 7 as two works with one file set each. The file sets in turn
will be linked to a single upload set to preserve the fact that
they both were uploaded in a single batch.

```
  <gwA> hasMember <fsA> .
  <gwB> hasMember <fsB> .
  <fsA> isPartOf <usX> .
  <fsB> isPartOf <usX> .
```

If users add a new file to either of these works the data would look
as follows:

```
  <gwA> hasMember <fsA> <fsC>.
  <gwB> hasMember <fsB> .
  <fsA> isPartOf <usX> .
  <fsB> isPartOf <usX> .
  <fsC> isPartOf <usY> .
```

We still can tell which files were uploaded together (`fsA` and `fsB` 
both belong to the same upload set) and which file belongs to a different
upload (`fsC` is part of a different upload set)

I would suggest we make Sufia handle UploadSets the same way Curation 
Concern does (FileSets -> UploadSets) rather than the way we are 
currently doing it in Sufia (Work -> UploadSet). This will buy us two 
things: 

1. the use of UploadSets in both projects will be the same and lead to less confusion 
2. we won't lose information because the files will know what upload set they belong to.

**Comment by awead** [comment]
This makes sense to me. So you're saying that from a single upload (Batch) you'll be creating multiple works, one per file? So a Batch of 50 files from Sufia 6 would result in 50 Works, each with one FileSet?

Question: which upload interface were you using? If you're using the old Sufia 6 upload, I would expect this to create 1:1 works to files. The discrepancy you're seeing between CC and Sufia resulted from the fact that we treated the old Sufia 6 GenericFile as the new Sufia 7 work, so everything including the upload set got attached to that. What is sounds like we need to do is tweak it so that the upload set gets attached to the FileSet and not the work. So, if I upload two files via the old Sufia 6 interface, I'd get:

```
  <gw1> hasMember <fs1> .
  <fs1> isPartOf <us1> .
  <gw2> hasMember <fs2> .
  <fs2> isPartOf <us1> .
```

Now, if I used the new "Add to Work" upload interface, I'd expect the same behavior as CC, since that's taken directly from the gem. I suspect that's this is the case currently, and what we're seeing is a result of trying to have two workfows: one that's data first, and another that's metadata first.

**Comment by hectorcorrea** [comment]
>  So you're saying that from a single upload (Batch) 
>  you'll be creating multiple works, one per file? So a Batch of 50 files from 
>  Sufia 6 would result in 50 Works, each with one FileSet?

Yes, that's what I understood Carolyn had suggested since most of our batches are single file. But if we were to do something different the same idea (FileSet->UploadSets) would apply.

> Question: which upload interface were you using? If you're using the old 
> Sufia 6 upload, I would expect this to create 1:1 works to files. 

It does (the old interface goes 1:1 works to files), but it links the Work (rather than the FileSet) to the UploadSet.

I agree with you. This is probably the result of us mentally mapping the Work to the GenericFile (which makes sense for most data). But I think we should preserve the UploadSet at the FileSet rather than the work.

If you upload a file directly to a work in Sufia 7 with the new interface the upload set is not being set. I think this is a bug. In Curation Concerns a new upload_set_id is set every time you go to the upload page (I think as soon as you click Select Files) but it seems that we broke that in Sufia somewhere.

**Comment by awead** [comment]
> I agree with you. This is probably the result of us mentally mapping the Work to the GenericFile (which
> makes sense for most data). But I think we should preserve the UploadSet at the FileSet rather than
> the work.

Right. That's what I was saying too. This would involve fixing the current upload behavior in master, and making the appropriate decisions when we migrate to PCDM. It's probably going to require us re-making the resources again, like we did when we migrated to Fedora 4.

Regarding uploading to a word, you've probably found a bug! Whatever the case is, uploading a file to an existing work should behave exactly like it does in CC.

**Comment by mjgiarlo** [comment]
@awead @hectorcorrea AFAIK, there is no UploadSet functionality in CurationConcerns. This was removed a while back and shifted back into Sufia. (If you're seeing UploadSets in CC, I'm guessing they're vestigial and ripe for removal.)

**Comment by mjgiarlo** [comment]
I believe we changed this relationship intentionally ([here[(https://github.com/projecthydra/sufia/pull/1408)) to set up the migration path that we've converged upon: 

https://github.com/projecthydra/sufia/blob/master/README.md#migrating-data-to-pcdm-in-sufia-7

Given that we don't have any use cases (that I know of, anyway) for using UploadSets after uploading a bunch of works together (legacy-style upload workflow), I'm not sure the "but we may move files later" is a blocker. We used to use it for "related files" functionality which was ill defined and I don't think we ever really capitalized on it. And now files are related to one another within a work, and I'm not aware of any "relate files to one another across works" use cases. So the one use I can see for UploadSets after initial upload is to relate a series of *works* to one another. I'm inclined to leave the implementation the way it is for the moment. Happy to keep discussing, though!

**Comment by hectorcorrea** [comment]
@mjgiarlo I understood that UploadSet functionality in CC was what it sounds like (what files were uploaded together) and not something that they were thinking as "vestigial or ripe for removal". @tpendragon @escowles Could you confirm one way or another?

@mjgiarlo my objection with the current implementation is that we are losing data. If works are related to upload sets (rather than filesets to upload sets) we cannot tell what files were part of each upload which I thought was the intended functionality. This is true regardless of whether we address Sufia 6 to Sufia 7 migration.

**Comment by mjgiarlo** [comment]
@hectorcorrea I just looked through the CC codebase and this was all I could find for UploadSets:

```shell
$ egrep -ri '(uploadset|upload_set)' .
./app/views/curation_concerns/file_sets/upload/_form.html.erb:    <%= render 'curation_concerns/file_sets/upload/form_fields', presenter: @presenter, upload_set_id: ActiveFedora::Noid::Service.new.mint %>
./app/views/curation_concerns/file_sets/upload/_form_fields.html.erb:      <%= hidden_field_tag(:upload_set_id, upload_set_id) %>
./spec/actors/curation_concerns/file_set_actor_spec.rb:    let(:upload_set_id) { nil }
./spec/lib/curation_concerns/messages_spec.rb:  let(:upload_set_id) { '1' }
./spec/lib/curation_concerns/messages_spec.rb:      node = Capybara::Node::Simple.new(message.single_success(upload_set_id, single))
./spec/lib/curation_concerns/messages_spec.rb:      node = Capybara::Node::Simple.new(message.multiple_success(upload_set_id, multiple))
./spec/lib/curation_concerns/messages_spec.rb:      node = Capybara::Node::Simple.new(message.single_failure(upload_set_id, single))
./spec/lib/curation_concerns/messages_spec.rb:      node = Capybara::Node::Simple.new(message.multiple_failure(upload_set_id, multiple))
./lib/curation_concerns/rails/routes.rb:      resources :upload_sets, only: [:edit, :update]
```

And here's the PR that removed UploadSets: https://github.com/projecthydra-labs/curation_concerns/pull/571

**Comment by mjgiarlo** [comment]
The intended functionality of UploadSets (née Batches) was to group uploaded things together so that bulk metadata could be applied immediately thereafter. GenericWork is the primary holder of metadata in Sufia 7 -- the bulk metadata from the UploadSet edit view is being applied to GenericWorks, not FileSets. In both of Sufia's upload paths, users are uploading GenericWorks not just FileSets (or files). After that point, I don't think users ever see an UploadSet again.

**Comment by hectorcorrea** [comment]
Turns out I had an old version of Curation Concerns that still had the UploadSet functionality. Arrgg!!! It's a bummer we removed that functionality from CC (given that it was useful to track what files came together) and half re-implemented it in Sufia. 

Oh well, I'll work with what we currently have then.

**Comment by mjgiarlo** [comment]
@hectorcorrea Doh!
