### ISSUE TITLE
'Select Folder' option unavailable in Safari and Firefox

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1528]
It seems we can't upload folders' worth of files in Safari and Firefox:
![buttons](https://cloud.githubusercontent.com/assets/312085/12495632/d05cdaba-c05e-11e5-912e-44e1044bab1d.png)

**Comment by awead** [comment]
This is in Sufia's current master branch, as well as Sufia 6 apps.

**Comment by hectorcorrea** [comment]
This seems to be intentional: https://github.com/projecthydra-labs/curation_concerns/blob/master/app/views/curation_concerns/file_sets/upload/_form_fields.html.erb#L16

Not sure why, though.

**Comment by awead** [comment]
Must not be supported, I guess. @mjgiarlo do you know why?

**Comment by mjgiarlo** [comment]
The feature is only supported in Chrome: https://github.com/blueimp/jQuery-File-Upload/wiki/Browser-support#folder-selection
