### ISSUE TITLE
The minter statefile default should work in dev and prod environments

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1532]
Building off the very good discussion in #1510: in Sufia, we want dev/test environments to "just work" and prod environments not to break on reboot, or on Cap deployment, or on `/tmp` autoclean.

Let's keep using /tmp in dev, and require in our documentation that folks either use the /var/sufia/ location for this file (a _new_ default in prod envs) or override the value of `config.minter_statefile` themselves. This change should also be in the release notes of the release that contains this change (7.0.0).

We should support the documentation change above by changing the Sufia initializer to something like: `config.minter_statefile = Rails.env.production? ? '/var/sufia/minter-state' : '/tmp/minter-state'`. The initializer should also check that the path exists and, if it doesn't, complain **and fail** during initialization at runtime.
- [ ] Change the initializer to set the statefile default depending on environment
- [ ] Add logic to the initializer to complain and fail in production if `/var/sufia/minter-state` doesn't exist
- [ ] Test the above with new specs
- [ ] Update README
- [ ] Update/create release notes text

**Comment by hectorcorrea** [comment]
@mjgiarlo Is there a particular reason we keep the state of the minter outside of Fedora?

**Comment by mjgiarlo** [comment]
@hectorcorrea historical accident, for one. the noid minter tools have never supported Fedora integration. here's the minter we use: https://github.com/projecthydra-labs/active_fedora-noid/blob/master/lib/active_fedora/noid/synchronized_minter.rb

**Comment by hectorcorrea** [comment]
@mjgiarlo I wonder if the ability to lock a file was the reason that for the decision. 

If I remember correctly you couldn't do the same in Fedora 3 but I *think* you can do transactions in Fedora 4. I wonder if that would remove that constrain (and/or of that was the real reason we ended up using a file rather than storing it within the Fedora repo). Food for thought.

**Comment by mjgiarlo** [comment]
Food for :thought_balloon: indeed! Thanks, @hectorcorrea.

**Comment by mjgiarlo** [comment]
@hectorcorrea @awead @ojlyytinen @jcoyne @grosscol 

As much as I'd like to fix this sooner rather than later, I am inclined to push this into a post-7.0.0 release (perhaps 7.1.0?) rather than have this block the 7.0.0 release. Is that OK by y'all?

**Comment by grosscol** [comment]
Sure.  This is a minor pain point and can be pushed to after 7.0.

Currently I do this in `config/initializers/curation_concerns.rb`
```
config.minter_statefile = ENV['MINTER_FILE'] || "/tmp/umrdr-minter-#{Time.now.min}#{Time.now.sec}"
```
So the deployment process can set where the minter file goes via the startup environment.  This allows multiple deployments to live side by side.

**Comment by mjgiarlo** [comment]
OK, thanks, all. Pushed to 7.1.0 for now.

**Comment by atz** [comment]
Why isn't this stored in DB?  The requirement of local storage prevents horizontal scaling like we would want in HyBox.  The setting of any hardcoded (production) path prevents multi-tenancy.  Also, we already have a DB in all environments and this seems like a simple thing to use a DB for, so this is confusing to me.

**Comment by jcoyne** [comment]
That seems like a good place. I think the problem is that by default the noid gem doesn't assume a database. https://github.com/microservices/noid

**Comment by cbeer** [comment]
It doesn't assume a filesystem either; `ActiveFedora::Noid` is providing that.

**Comment by mjgiarlo** [comment]
I'm not sure the above provides quite the right seam for what we want, though. Perhaps CC or Sufia should provide a configuration option that allows for easier swapping of custom minters.

**Comment by atz** [comment]
Is there a reason Sufia would *not* want to default to DB?

**Comment by grosscol** [comment]
Starting to use a DB would be good move for scaling.  Simple approach, the minter just creates a unique index for each minter request?

Eventually scaling might be a block allocation solution? Allocate large blocks of ids prospectively, and mark + return the next 'unused' so long as you've got a db that guarantees consistency.  That way there can be an allocator node that makes blocks of ids and hands them out to populate the leaf instances.  After X number of allocation attempts, a leaf requests another block.

@atz how much throughput are you expecting?

**Comment by atz** [comment]
Interesting idea about "pages" of IDs.  I don't think the current implementation does anything like that, since it just retains a single "last" value and generates a "next" value deterministically off of that.  

During a migration, we would hope to be creating tens of thousands of records per hour.

**Comment by mjgiarlo** [comment]
Minting batches of IDs is a great idea, and a feature that other minters (including noid minters implemented in Go and Perl, IIRC) already use.

**Comment by ojlyytinen** [comment]
What we ended up doing with this was having each of our servers use a separate minter-state file with a unique noid prefix. This effectively gave each server its own id namespace so they could all mint ids independently without clashing with each other.

But putting the minter-state in DB instead does sound like a good idea, at least as the default option.

**Comment by jeremyf** [comment]
At Notre Dame we have a small NOID server (written in Go) and a Ruby client
for that application. This allows us to mint noids from multiple places. It
also provides a configuration point in which in development and test I
replace the NOID minter with a lambda that calls a UUID genration method.

So our NOID state is tracked in a DB, we have different pools if we need
(UND:, SEASIDE:, etc). We also have a clear interface point to allow
dependency injection. And we allow NOIDs to be minted in pre production
that can be reused in production (e.g. practice a batch with relationships
in preprod then run it again in production using the same noids).

Jeremy Friesen

**Comment by mjgiarlo** [comment]
I don't believe this is needed now that AF::Noid allows implementers to use a database-backed minter. Closing.
