### ISSUE TITLE
Update to CurationConcerns 0.6.0

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1533]
So that we pick up Blacklight 6 in the Sufia 7 release.

- [x] Pin CC to `'~> 0.6'` in the [gemspec](https://github.com/projecthydra/sufia/blob/master/sufia.gemspec#L19).
- [x] Remove [this line](https://github.com/projecthydra/sufia/pull/1534/files#diff-ecd1dd1b80675e908c68203a9071bf1d) from the gemspec; it was added as a workaround to get the build working until CC 0.6.0 was released.
- [x] Get the test suite passing. For help, see [the commit in CC that brought Blacklight 6 compatibility](https://github.com/projecthydra-labs/curation_concerns/commit/8d22616d8288e5e57d000e30781a6136434c57c7) and the [Blacklight 6.0.0 upgrade guide](https://github.com/projectblacklight/blacklight/releases/tag/v6.0.0).

**Comment by awead** [comment]
Fixed in da8d642c2b5e27697be3e4f35633b9fdc95f763e
