### ISSUE TITLE
Various fields are not displayed correctly if they contain a less than character

### ISSUE THREAD

**Issue by ojlyytinen** [projecthydra/sufia#1546]
Several fields are not shown correctly in the details page if they contain data with a less than character (<). Fields that are having problems include at least description, publisher and language and possibly others. In Sufia 6 title is also not shown correctly in the details page. Sufia 7 has no issues with title containing a less than character but the other fields still are having problems.

In our Sufia 6 based system we have a Generic File with title "something something with <30kHz frequency something" and it's displayed as "something something with" in the details page. The title is fine in the record itself if you look at it from the console. And it's displayed correctly in the Blacklight based pages too.

The problem seems to be ActionView::Helpers::TextHelper#auto_link. It will choke on the < character and drop off anything following that. You can pass sanitize: false to auto_link and then it'll accept the < character but then the output will not be html_safe. 

I think this same thing affects CurationConcerns.

**Comment by ojlyytinen** [comment]
I have opened a pull request in CurationConcerns which fixes part of this. Sufia also has references to auto_link that need a similar treatment. I think I can make a pull request for Sufia as well next week.

**Comment by mjgiarlo** [comment]
:clap:

Thanks, @ojlyytinen!
