### ISSUE TITLE
Having issues running Sufia with JRuby

### ISSUE THREAD

**Issue by ammar-yousuf** [projecthydra/sufia#1549]
I am trying to use JRuby with Sufia and running into issues.
I am running Redhat and jruby-9.0.4.0.  I had to make some changes to the Gemfile:

Removed:
byebug
better-errors
binding_of_caller

Added:
gem 'pg', '0.17.1', :platform => :jruby, :git => 'git://github.com/headius/jruby-pg.git', :branch => :master

Also in the sufia.gemspec I had to comment out   #spec.add_dependency 'posix-spawn'
If I don't do this I get issues trying to do a bundle install. 

Got the error:
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

/home/ayousufa/.rvm/rubies/jruby-1.7.19/bin/jruby -r ./siteconf20160128-16007-iepnn6.rb extconf.rb
NotImplementedError: C extension support is not enabled. Pass -Xcext.enabled=true to JRuby or set JRUBY_OPTS.

(root) at /home/ayousufa/.rvm/rubies/jruby-1.7.19/lib/ruby/shared/mkmf.rb:8
require at org/jruby/RubyKernel.java:1071
(root) at /home/ayousufa/.rvm/rubies/jruby-1.7.19/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
(root) at extconf.rb:1

I tried to set the JRUBY_OPTS env variable like it said in the error, but still JRuby had issues.
export JRUBY_OPTS="--1.9 -Xcext.enabled=true"

If I run the sufia app with posix commented out in the gemspec then I get another error:

NoMethodError: undefined method `blacklight_for' for #ActionDispatch::Routing::Mapper:0x691e74c3
block in (root) at /home/ayousufa/fcrepo-admin/rails_app/config/routes.rb:4
instance_exec at org/jruby/RubyBasicObject.java:1670
eval_block at /home/ayousufa/.rvm/gems/jruby-9.0.4.0@sufia/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:434
draw at /home/ayousufa/.rvm/gems/jruby-9.0.4.0@sufia/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:412
<top> at /home/ayousufa/fcrepo-admin/rails_app/config/routes.rb:1
load at org/jruby/RubyKernel.java:957

Has anyone been able to run Sufia successfully with JRUBY?

**Comment by grosscol** [comment]
We had been running hydra heads on JRuby prior to the 9.0.0.0 release.  There were similar modifications to the requirements that we had to discover and add to our standard setup.

The error messages regarding c extensions look like they're calling jruby-1.7.19.  Whatever is causing an old jruby to be called may be the source of those errors.

**Comment by ammar-yousuf** [comment]
so currently what is the version of Jruby that I should be using?

**Comment by grosscol** [comment]
I don't think the older version, jruby 1.7.x, works anymore.  We switched to MRI after it became apparent that torquebox wasn't moving forward.  JRuby 9.x is worth a try, but the first two errors in your post are from the old jruby.

> (root) at /home/ayousufa/.rvm/rubies/**jruby-1.7.19**/lib/ruby/shared/mkmf.rb:8
require at org/jruby/RubyKernel.java:1071
(root) at /home/ayousufa/.rvm/rubies/**jruby-1.7.19**/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1

**Comment by ammar-yousuf** [comment]
ok i'll try to clean up my rubies directory in RVM maybe somehow it's loading the older JRuby

**Comment by ammar-yousuf** [comment]
so when I put back in the posix-spawn gem I get the following during a bundle install:

```
Installing posix-spawn 0.3.11 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /home/ayousufa/.rvm/rubies/jruby-9.0.4.0/bin/jruby -r ./siteconf20160202-21991-1hvj6s4.rb extconf.rb
NotImplementedError: C extensions are not supported
    <top> at /home/ayousufa/.rvm/rubies/jruby-9.0.4.0/lib/ruby/stdlib/mkmf.rb:1
  require at org/jruby/RubyKernel.java:939
   (root) at /home/ayousufa/.rvm/rubies/jruby-9.0.4.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
    <top> at extconf.rb:1

extconf failed, exit code 1

Gem files will remain installed in /home/ayousufa/.rvm/gems/jruby-9.0.4.0@sufia/gems/posix-spawn-0.3.11 for inspection.
Results logged to /home/ayousufa/.rvm/gems/jruby-9.0.4.0@sufia/extensions/universal-java-1.7/2.2.0/posix-spawn-0.3.11/gem_make.out
```

But if I remove posix-spawn form the sufia.gemspec and rebuild then I get the following when the app is starting:
```

[ayousufa@sufia-sandbox rails_app_jruby]$ rails s -b 0.0.0.0
=> Booting WEBrick
=> Rails 4.2.5 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
NotImplementedError: fork is not available on this platform
       fork at org/jruby/RubyKernel.java:1728
  daemonize at /home/ayousufa/.rvm/gems/jruby-9.0.4.0@sufia/gems/resque-pool-0.6.0/lib/resque/pool/cli.rb:62
        run at /home/ayousufa/.rvm/gems/jruby-9.0.4.0@sufia/gems/resque-pool-0.6.0/lib/resque/pool/cli.rb:15
      <top> at /home/ayousufa/.rvm/gems/jruby-9.0.4.0@sufia/gems/resque-pool-0.6.0/bin/resque-pool:7
       load at org/jruby/RubyKernel.java:957
     <eval> at /home/ayousufa/.rvm/gems/jruby-9.0.4.0@sufia/bin/resque-pool:1
       eval at org/jruby/RubyKernel.java:978
      <top> at /home/ayousufa/.rvm/gems/jruby-9.0.4.0@sufia/bin/jruby_executable_hooks:15
Exiting
NoMethodError: undefined method `blacklight_for' for #<ActionDispatch::Routing::Mapper:0x7425f8da>
                             block in (root) at /home/ayousufa/fcrepo-admin/rails_app_jruby/config/routes.rb:4
                               instance_exec at org/jruby/RubyBasicObject.java:1670
```

**Comment by grosscol** [comment]
Looks like resque depends on posix-spawn, and you're having an issue installing posix-spawn with JRuby 9.x.  I don't know how to resolve that off hand.
