### ISSUE TITLE
Transfer work gives an error if cancelled

### ISSUE THREAD

**Issue by njaffer** [projecthydra/sufia#1552]
1. I tried to transfer the work ownership to another user and then cancelled the request 
2. Logged in as the second user, it showed me the notification that the work transfer request was initiated and cancelled
3. When I click on the work name, I get an error: undefined method `human_readable_type' for nil:NilClass in unauthorized.html.erb

**Comment by njaffer** [comment]
![screen shot 2016-02-03 at 2 59 15 pm](https://cloud.githubusercontent.com/assets/12487929/12795249/078d9722-ca87-11e5-8354-91e1bcd0bdf0.png)

**Comment by mjgiarlo** [comment]
Good find! Thanks, @njaffer

**Comment by njaffer** [comment]
closed with #1557
