### ISSUE TITLE
Should the user be allowed to edit thumbnail for a generic work

### ISSUE THREAD

**Issue by njaffer** [projecthydra/sufia#1553]
When I try to edit a work, I can change the Thumbnail and Representative fields which results in an error when I save the work. Attached are the screenshots:
![screen shot 2016-02-04 at 1 53 58 pm](https://cloud.githubusercontent.com/assets/12487929/12826414/eefcb324-cb48-11e5-9b3e-a2352d2ecc93.png)

<img width="1130" alt="screen shot 2016-02-04 at 2 10 22 pm" src="https://cloud.githubusercontent.com/assets/12487929/12826477/2625778c-cb49-11e5-8ae7-181d9991db98.png">

**Comment by mtribone** [comment]
I'll pull the latest version of Hydra Sufia and take a peek.

**Comment by jcoyne** [comment]
I think curation_concerns uses select inputs to allow the user to make these selections. You should either do that or remove these fields from the form.

**Comment by mtribone** [comment]
@jcoyne okay. thanks! Running Sufia 7 now to see how it works :smirk_cat:
