### ISSUE TITLE
Adding tags to a collection results in a NoMethod error when creating or edit/saving the coll

### ISSUE THREAD

**Issue by gordonleacock** [projecthydra/sufia#1556]
*Having this problem in our deep blue data repository test instance and I'm seeing it in my desktop sufia instance too:*

**Adding tags to a collection results in a NoMethod error when creating or edit/saving the coll**

NoMethodError in Collections#show
Showing /quod-dev/dev/grosscol/umrdr/.bundle/ruby/2.3.0/bundler/gems/sufia-ea5e0eeec618/app/views/records/show_fields/_tag.html.erb where line #1 raised:

undefined method `tag' for #<Sufia::CollectionPresenter:0x007fc8f6750050>
Extracted source (around line #1):
             
<% record.tag.each do |t| %>
 <span itemprop="keywords"><%= link_to_facet(t, Solrizer.solr_name("tag", :facetable)) %></span><br />
<% end %>

Trace of template inclusion: .bundle/ruby/2.3.0/bundler/gems/sufia-ea5e0eeec618/app/views/collections/_show_descriptions.html.erb, .bundle/ruby/2.3.0/bundler/gems/sufia-ea5e0eeec618/app/views/collections/show.html.erb(edited)

**Comment by cam156** [comment]
@gordonleacock can we close this issue?

**Comment by hectorcorrea** [comment]
@gordonleacock Was this closed by PR https://github.com/projecthydra/sufia/pull/1561 ?

**Comment by mjgiarlo** [comment]
Closing.
