### ISSUE TITLE
Legato uninitialized constant error in production environment

### ISSUE THREAD

**Issue by grosscol** [projecthydra/sufia#1558]
For application built on Sufia, `RAILS_ENV=development bundle exec rails s` starts without a problem. `RAILS_ENV=production bundle exec rails s` exits with the error:

```home/grosscol/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/sufia-ea5e0eeec618/app/models/sufia/download.rb:3:in `<class:Download>': uninitialized constant Sufia::Download::Legato (NameError)```

quick and dirty fix is to add `gem 'legato'` to the application Gemfile.

**Comment by awead** [comment]
@grosscol can you use Sufia master? This was fixed here:
https://github.com/projecthydra/sufia/commit/da8d642c2b5e27697be3e4f35633b9fdc95f763e#diff-688520bc6a95a92bb234c46f3317c2f4R4

**Comment by mjgiarlo** [comment]
@grosscol I believe this commit should have fixed it already: https://github.com/projecthydra/sufia/commit/d740a37ffa3dd04958ecc12b34d1e16290c47afd
