### ISSUE TITLE
UI Create _save_work_widget partial

### ISSUE THREAD

**Issue by elrayle** [projecthydra/sufia#1562]
### Wireframes:
* [in context of New Work](https://wiki.duraspace.org/display/hydra/New+Work+-+Metadata+Tab+-+Phase+1+-+UI+Wireframes)
* [in context of Edit Work](https://wiki.duraspace.org/display/hydra/Edit+Work+-+Metadata+Tab+-+Phase+1+-+UI+Wireframes)
* [in context of Batch Upload](https://wiki.duraspace.org/display/hydra/Batch+New+Works+-+Phase+1+-+UI+Wireframes#mockup_p1-works-batch_new-step1_upload_files)
* [variants](https://wiki.duraspace.org/display/hydra/New+Work+-+Phase+1+-+UI+Wireframes#NewWork-Phase1-UIWireframes-VariantsofSaveWorkwidget) - initial state, error state, success state, embargo options, lease options, active acceptance of deposit agreement

### Usage - Right Hand Side widget to control saving of new/changed works
* Add New Work -- menu:  top-bar-> Works -> New
* Edit Work -- menu: My Dashboard -> work's Action select-menu -> Edit
* Batch Upload -- menu: top-bar -> Works -> Batch New

NOTE: Primary differences between usage on these screens.
* if new_work or batch_upload, then do not show 'Last saved on' under widget; shown for editing only
* if new_work or edit_work, title=Save Work
* if batch_upload, title=Save Works

### Implementation:
* File: app/views/generic_works/_save_work_widget.html.erb
* create a partial view to display the Save Work widget

### Actions:
* Save button - Hook into the existing save process and save all information across all tabs.  Move files uploaded prior to save from tmp area to permanent location.  Finish uploading any files that did not complete prior to the save.  After save, go to the Show page for the new work.
 * Does work already exist?  
   * If yes, update existing work.
    * If no, create work.
 * Were files uploaded to tmp area? If yes, move to permanent location for work.
 * Have all files completed the upload process? Wait for files already partially uploaded to complete loading and move to permanent location of work.  Upload remaining files directly to work.  (Can this be done in background?)
 * Hook into the existing save process and save all information across all tabs.
 * After save, go to Show page for the new/changed work.

* Cancel button
 * Do not create or save new/changed work.  If new work was created as start of create work process, then remove it.
 * Remove any files uploaded to the tmp area.

**Comment by elrayle** [comment]
NOTES:
* This widget will always be visible on the right hand side.  It will move with the screen as the user scrolls up and down.
* Requires new configurations for...
  * config.active_deposit_agreement_acceptance
    * if true, show checkbox and active acceptance message for Deposit Agreement (see [variant](https://wiki.duraspace.org/display/hydra/New+Work+-+Phase+1+-+UI+Wireframes#NewWork-Phase1-UIWireframes-VariantsofSaveWorkwidget)); Also show in Requirements area and set to red exclamation if acceptance is not checked or green check if acceptance is checked.  Needs to be able to be changed if user checks/unchecks acceptance.
    * if false, do not show checkbox and do show passive acceptance message for Deposit Agreement (see in main [New Work](https://wiki.duraspace.org/display/hydra/New+Work+-+Phase+1+-+UI+Wireframes#mockup_p1-works-new-step1) wireframe)
  * config.work_requires_files
    * if true, show in Requirements area and set to red exclamation icon if 0 files attached or green check if at least 1 file attached.  Needs to be able to be changed if number of files changes.
    * if false, do not show in Requirements

**Comment by jcoyne** [comment]
> This widget will always be visible on the right hand side. It will move with the screen as the user scrolls up and down.

How should this look on a mobile/tablet sized viewport?

**Comment by mtribone** [comment]
I think that we can keep the two columns side-by-side for the landscape tablet view and adjust the width of each column. However, we might need to drop the right hand column to the bottom for portrait and mobile.

**Comment by cam156** [comment]
How is the status going to be determined by this widget.  Do the other panels publish a status?  Does this widget calculate the status based on the current work state?  It seems like this should be defined so that the panels and save widget work together.

**Comment by jcoyne** [comment]
> This widget will always be visible on the right hand side. It will move with the screen as the user scrolls up and down.

I can't get this to work when the widget is taller than the screen. If it's pinned to the screen, I can't see it all.

**Comment by mtribone** [comment]
Hrmmmm...so let's say you just create a work with a title and very little metadata and zero files. The widget is longer than the content and since it is an "independent" column, the screen collapses to the content column. 

Sooo one idea is to set a minimum height for the containg element to the length of the sidebar widget. Another idea depending on how the sidebar is coded would be to change strategy with how it is positioned; for example, absolute versus floats.

**Comment by jcoyne** [comment]
@mtribone Attaching the sidebar is not something I want to put a lot of time into. So we should probably make a new ticket for it and if you would like to work on it, assign it to yourself.

**Comment by jcoyne** [comment]
@mtribone lets continue the conversation on #1719

**Comment by mtribone** [comment]
@jcoyne  Sounds good.
