### ISSUE TITLE
UI Create _find_work_widget partial

### ISSUE THREAD

**Issue by elrayle** [projecthydra/sufia#1563]
### Wireframes:
- [in context of New Work](https://wiki.duraspace.org/display/hydra/New+Work+-+tab+Relationships+-+Phase+1+-+UI+Wireframes#mockup_p1-work-new-tab_relationships) - Relationship Tab - sections This Work in Other Works, Other Works in This Work, Related Works
- [in context of Edit Work](https://wiki.duraspace.org/display/hydra/Edit+Work+-+Relationships+Tab+-+Phase+1+-+UI+Wireframes) - Relationship Tab - sections This Work in Other Works, Other Works in This Work, Related Works
- [in context of Batch Upload](https://wiki.duraspace.org/display/hydra/Batch+New+Works+-+tab+Relationships+-+Phase+1+-+UI+Wireframes) - Relationship Tab - sections These New Works in Other Works, Other Works in These New Works, Related Works
### Usage:

Used to find and select an existing work.  Options for finding a work:
- user begins typing the name of the work and auto-complete suggests works
- user chooses to search for works and can browse a list of all works with pagination
### Implementation:
- File: /app/views/generic_works/_find_work_widget.html.erb
- Create a partial for a view that includes the find_work_widget.
  - need to be able to name the field associated with the widget
  - need to be able to return a value for the field based on the user's selection
- Add class/methods that support auto-complete
- Add class/methods that support browse and select

**Comment by jcoyne** [comment]
@mjgiarlo backlog this?

**Comment by andjsmit** [comment]
For the autocomplete: Would the right/desired approach be to create new local authority which returns the available works? Something like `Qa::Authorities::Local::FindWorks`. This class could then do a Solr query to return available works.

**Comment by jcoyne** [comment]
Sounds like a good idea to me.

**Comment by andjsmit** [comment]
After hitting some road blocks, looks like QA is not the way to go after all.  In search of new direction.

**Comment by jcoyne** [comment]
@andjsmit why would you not use QA for this?

**Comment by tap87** [comment]
What is the status of work on this issue? Our team is interested in this feature as well. @andjsmit @dlpierce

**Comment by andjsmit** [comment]
There is working code, but I have so far not been able (lack of experience) to write required tests to push code through to a merge. Hope to revamp code to latest master branch and then look for assistance it creating proper test.

**Comment by tap87** [comment]
Let me know if you need a hand with that, I can put in some time this week

**Comment by andjsmit** [comment]
@tap87 I've replaced the pull request with some refreshed code. I would greatly appreciate any help you could provide in adding additional test. Thx.

**Comment by tap87** [comment]
@andjsmit I pushed a commit which adds some tests. Let me know how things are looking. This is also my first commit to Sufia 😄 .
