### ISSUE TITLE
View File crashes for zipped file

### ISSUE THREAD

**Issue by njaffer** [projecthydra/sufia#1567]
When I upload a zip file in a work, and try to view the file, it crashes with this error:

![screen shot 2016-02-10 at 3 44 46 pm](https://cloud.githubusercontent.com/assets/12487929/12961221/4d9fd046-d00d-11e5-8d57-8f56a74bff32.png)

**Comment by grosscol** [comment]
That's a problem for all files that lack a date_created.  You can get the same behavior for plain text.

**Comment by gordonleacock** [comment]
Fix is to modify _citations.html.erb L22 to be:

<meta name="citation_publication_date" content="<%=
@presenter.date_created.first unless @presenter.date_created.nil?
%>"/>

**Comment by gordonleacock** [comment]
Unless others have a better approach I'll put in a PR tomorrow.

**Comment by cam156** [comment]
Seems to be related to #1584

**Comment by cam156** [comment]
@gordonleacock can we close this?

**Comment by gordonleacock** [comment]
Yes!

**Comment by hectorcorrea** [comment]
Gordon indicated this can be closed.
