### ISSUE TITLE
Order in generated application.css is reversed

### ISSUE THREAD

**Issue by justcolin** [projecthydra/sufia#1571]
The application.css file that the latest version of Sufia generates requires Sufia's styles after `require_tree .`. This should be reversed so the default is application styles override the Sufia engine styles.

Thanks!

**Comment by mjgiarlo** [comment]
Thoughts on this? cc: @jcoyne

**Comment by jcoyne** [comment]
Sure, sounds good to me. I always prefer to remove `require_tree .` anyway and require the stuff I want, in the order I want it.

**Comment by mjgiarlo** [comment]
Thx, @jcoyne.

@justcolin Thanks for reporting this! Are you inclined to submit a PR for this change, and if so, are you covered by Hydra's contributor license agreements yet? Happy to help with that process if you'd like.

**Comment by justcolin** [comment]
I would be happy to submit a PR, but I haven't signed the contribute
agreements yet and I will be busy with U-M's upcoming Sufia 7 release for
the next two weeks.

On Wed, Feb 17, 2016 at 2:05 PM, Michael J. Giarlo <notifications@github.com

**Comment by mjgiarlo** [comment]
OK, @justcolin. I've put this issue on the backlog for now, and I'm happy to wait on a PR. But before I suggest that road, is this bug going to complicate your application release?

**Comment by jcoyne** [comment]
Alternatively, if we mark this as blocking the Sufia 7 release, then @justcolin will have the proper motivation to get his contributors agreement signed.  :wink:

**Comment by justcolin** [comment]
@mjgiarlo, @jcoyne: Short term we just overwrote the application.css file in our app (we were likely to overwrite it later anyways) but I'll hopefully get you a PR late next week so others don't have to do the same.

**Comment by mjgiarlo** [comment]
@justcolin Much obliged! Since Michigan already has a corporate CLA in place, you just need to send an individual CLA to legal@projecthydra.org to be covered. If you have any questions about that process, like I said I'm happy to help.

**Comment by cbeer** [comment]
Fixed by #1701?

**Comment by mjgiarlo** [comment]
@cbeer @justcolin I believe what #1701 gave us is:

```
*= require_tree .
*= require sufia
*= require_self
```
 Is that sufficient to satisfy this ticket, or do we want the sufia line at the top?

**Comment by justcolin** [comment]
I can double check later, but I believe `require sufia` had to go first to fix all our problems.

**Comment by mjgiarlo** [comment]
Hasn't come up since April. Closing.
