### ISSUE TITLE
UI Create _find_collection_widget partial

### ISSUE THREAD

**Issue by elrayle** [projecthydra/sufia#1572]
### Wireframes:
- [in context of New Work](https://wiki.duraspace.org/display/hydra/New+Work+-+tab+Relationships+-+Phase+1+-+UI+Wireframes#mockup_p1-work-new-tab_relationships) - Relationship Tab - section This Work in Collections
- [in context of Edit Work](https://wiki.duraspace.org/display/hydra/Edit+Work+-+Relationships+Tab+-+Phase+1+-+UI+Wireframes) - Relationship Tab - section This Work in Collections
- [in context of Batch Upload](https://wiki.duraspace.org/display/hydra/Batch+New+Works+-+tab+Relationships+-+Phase+1+-+UI+Wireframes) - Relationship Tab - sections These New Works in Collections
### Usage:

Used to find and select an existing collections.  Options for finding a collection:
- user begins typing the name of the collection and auto-complete suggests collections
- user chooses to search for collections and can browse a list of all collections with pagination
### Implementation:
- File: app/views/collections/_find_collection_widget.html.erb
- Create a partial for a view that includes the find_collection_widget.
  - need to be able to name the field associated with the widget
  - need to be able to return a value for the field based on the user's selection
- Add class/methods that support auto-complete
- Add class/methods that support browse and select

**Comment by cam156** [comment]
@elrayle how is the user going to interact with searching for a collection? From the wireframes I can see how auto complete would work.  Is the searching something for another time/ticket?

**Comment by mtribone** [comment]
@cam156 Good question. This needs to be addressed.

**Comment by jcoyne** [comment]
@mjgiarlo I think this can be backlogged. We can use a simple dropdown for 7.0.0
