### ISSUE TITLE
UI create _share_tab partial

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#1573]
Replaces app/views/generic_files/_permission_form.html.erb in sufia 6.

### Wireframes
* [in context of New Work](https://wiki.duraspace.org/display/hydra/New+Work+-+tab+Share+-+Phase+1+-+UI+Wireframes) - Share Tab - contents of tab
* [in context of Edit Work](https://wiki.duraspace.org/display/hydra/Edit+Work+-+Share+tab+-+Phase+1+-+UI+Wireframes) - Share Tab - contents of tab

### Usage
View and change sharing a work with a user or group.

### Implementation
* File: app/views/generic_works/_share_tab.html.erb
* save is controlled by #1562 
* this will not be wrapped in its own separate form, as is done in sufia 6 in app/views/generic_files/_permission.html.erb.

**Comment by jcoyne** [comment]
Hey UI working group. This wireframe doesn't show the access (view/edit) that you've granted to users or groups.  Should it be modified to have that?

@dt-ucsd @hackmastera @elrayle @mtribone

**Comment by jcoyne** [comment]
Oh! That must be what the pencil/eye icons are for.

**Comment by jcoyne** [comment]
So the other question is, how do we elevate or reduce access for someone who already has access?

**Comment by hectorcorrea** [comment]
@jcoyne I am working on adding the Share views back to Sufia (as part of ticket https://github.com/projecthydra/sufia/issues/1648) Thanks for surfacing this ticket!!!

**Comment by jcoyne** [comment]
@hectorcorrea I suspect we're going to have clashes then as I'm working on this ticket.

**Comment by hectorcorrea** [comment]
@jcoyne I've stopped the work on #1648 and reassigned it to you.
