### ISSUE TITLE
UI Create _relationships_tab partial

### ISSUE THREAD

**Issue by elrayle** [projecthydra/sufia#1577]
### Wireframes
* [in context of New Work](https://wiki.duraspace.org/display/hydra/New+Work+-+tab+Relationships+-+Phase+1+-+UI+Wireframes) - Relationships Tab - contents of tab
* [in context of Edit Work](https://wiki.duraspace.org/display/hydra/Edit+Work+-+Relationships+tab+-+Phase+1+-+UI+Wireframes) - Relationships Tab - contents of tab

### Usage
View and change relationships of this work to other works, collections, and external resources.

### Implementation
* File: app/views/generic_works/_relationships_tab.html.erb
* Save is controlled by by a widget defined in #1562 
* Finding works is implemented as a widget defined in #1563 
* Finding collections is implemented as a widget defined in #1572 
* This tab will not have its own form.  The page has the form and all tabs are saved together with the save widget.

**Comment by jcoyne** [comment]
Closing as this has been decomposed into constituent parts.
