### ISSUE TITLE
Create new works: _metadata_tab partial

### ISSUE THREAD

**Issue by elrayle** [projecthydra/sufia#1578]
### Wireframes
* [in context of New Work](https://wiki.duraspace.org/display/hydra/New+Work+-+Metadata+Tab+-+Phase+1+-+UI+Wireframes) - Metadata Tab - contents of tab
* [in context of Edit Work](https://wiki.duraspace.org/display/hydra/Edit+Work+-+Metadata+tab+-+Phase+1+-+UI+Wireframes) - Metadata Tab - contents of tab

### Usage
View and change metadata.

### Implementation
* File: app/views/generic_works/_metadata_tab.html.erb
* Save is controlled by by a widget defined in #1562 
* This tab will not have its own form.  The page has the form and all tabs are saved together with the save widget.

**Comment by cam156** [comment]
@elrayle are you envisioning the check marks being real time.  Aka I fill in the last metadata field and the metadata section goes green before I save.

**Comment by mtribone** [comment]
@cam156 Hrrmmmm...my first impression is yes, but when you scroll down and view the variations it looks like feedback is given after you hit save.
