### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by dt-ucsd** [projecthydra/sufia#1583]
# Wireframes
- [Toolbar with sub-menu items revealed](https://wiki.duraspace.org/pages/viewpage.action?pageId=73173754)
- [Placement on a page](https://wiki.duraspace.org/pages/viewpage.action?pageId=73173840)

# Demo
- [Bootstrap 3 w/ FA Icons (Responsive)](https://library.ucsd.edu/assets/temp/dt/sufia-toolbar.html)
  - [Gist](https://gist.github.com/dt-ucsd/d09baaa2c6626ef23b17)

# Usage
Easy access to site tools for logged in users.

# Implementation

## Visibility
- The toolbar is only visible to logged in users
- The "Admin" menu is only visible to logged in "Admin" users

## Placement
- The toolbar is always positioned at the top of the page (Upper left-hand corner at 0,0)
- The toolbar spans the entire width of the page (100%)

## Menu Items
- Top level menu items open their respective sub-menu
- Sub-menu items link to their respective Sufia content

## Mobile
- Use BS3 mobile breakpoints
- Top level menu items only display FA icon in mobile view

## Decorations
- The toolbar uses the following Font Awesome icons:
 - fa-gear (Admin)
 - fa-tachometer (Dashboard)
 - fa-cube (Works)
 - fa-cubes (Collections)
 - fa-user (User)
- The label for the "User" menu is the username of the logged in user

**Comment by cbeer** [comment]
Should we consider pushing the Sufia branding into the toolbar as well, matching the default bootstrap placement?

**Comment by dt-ucsd** [comment]
@cbeer -- This is an interesting wrinkle. Is the intention to merge the Masthead and Toolbar into a single unit?

When we designed the Toolbar, it was with the custom Masthead in mind. It was meant to be separate.

Also, to more directly answer your question, I suppose we could rename the "Admin" menu to "Sufia" and use the little globe icon there in place of the gear.

**Comment by dt-ucsd** [comment]
Oh yeah, I also wanted to mention that Lynette and I started work on adding this feature in last week at the Dev Congress. You can find our work here: https://github.com/projecthydra/sufia/tree/FIX_1583-add_toolbar

**Comment by mjgiarlo** [comment]
@elrayle @dt-ucsd may I delete [this branch](https://github.com/projecthydra/sufia/tree/FIX_1583-add_toolbar) now that this issue is closed?

**Comment by dt-ucsd** [comment]
It’s okay with me.

On Apr 13, 2016, at 1:06 PM, Michael J. Giarlo <notifications@github.com<mailto:notifications@github.com>> wrote:


@elrayle<https://github.com/elrayle> @dt-ucsd<https://github.com/dt-ucsd> may I delete this branch<https://github.com/projecthydra/sufia/tree/FIX_1583-add_toolbar> now that this issue is closed?

**Comment by mjgiarlo** [comment]
Thx!
