### ISSUE TITLE
FileSets without date_created cause error when viewed.

### ISSUE THREAD

**Issue by grosscol** [projecthydra/sufia#1584]
Navigating to /concern/file_sets/<file_set_id> as is available when viewing a work will result in an error for file sets without a date_created.

In `app/views/shared/_citations.html.erb` the call to `<meta name="citation_publication_date" content="<%= @presenter.date_created.first %>"/>` causes an error for file_sets that do not have a date_created property.

**Comment by njaffer** [comment]
@grosscol: Hopefully Gordon's PR will take care of this
https://github.com/projecthydra/sufia/pull/1570

**Comment by gordonleacock** [comment]
Yes! I've got that one covered.

**Comment by grosscol** [comment]
Likely closed by #1570
