### ISSUE TITLE
Dead code? generator template for setup_mail.rb

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#1588]
Doesn't seem to be used anywhere. Remove?

https://github.com/projecthydra/sufia/blob/master/lib/generators/sufia/templates/config/setup_mail.rb

**Comment by jcoyne** [comment]
Looks ripe for removal.

**Comment by mjgiarlo** [comment]
This *may* be used by Sufia's contact form. I'd like to hear the PSU team chime in on this before removing it.

@awead @cam156 @hectorcorrea

**Comment by awead** [comment]
@mjgiarlo thanks for the note of concern, it's like you used to be ... wait a minute! :smile: 
I checked and we have file like that under config/initializers/setup_mail.rb. If you want you could rewrite the initializer to put in a commented file for instructions, or just delete it.

**Comment by mjgiarlo** [comment]
:+1: for deleting it if @awead or @cam156 or @hectorcorrea gives the :+1:

**Comment by hackmastera** [comment]
a setting like this would also be used for devise's password reset. but it's dependent on what kind of mail server you are using. This type of setting is also likely to be environment-dependent (i just set this sort of thing up in environments/production.rb). I think the file should be deleted, and we should add a small bit of documentation about mail server configuration in the readme.

**Comment by mjgiarlo** [comment]
:+1:
