### ISSUE TITLE
Create new works: _files_tab partial

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#1591]
### Wireframes
* [in context of New Work](https://wiki.duraspace.org/display/hydra/New+Work+-+tab+Files+-+Phase+1+-+UI+Wireframes) - Files Tab - contents of tab
* [in context of Edit Work](https://wiki.duraspace.org/display/hydra/Edit+Work+-+Files+tab+-+Phase+1+-+UI+Wireframes) - Files Tab - contents of tab
* [in context of Batch Upload](https://wiki.duraspace.org/display/hydra/Batch+New+Works+-+Phase+1+-+UI+Wireframes#mockup_p1-works-batch_new-step1_upload_files) - Files Tab - contents of tab

### Usage
Upload files (as FileSet objects).

For 'New Work' and 'Edit Work' the files will be added to the work in question. For 'Batch Upload' each file will be added to its own newly-generated work.

### Implementation
* File: app/views/generic_works/_files_tab.html.erb
* Save is controlled by by a widget defined in #1562 
* This tab will not have its own form.  The page has the form and all tabs are saved together with the save widget.
* Dragging a file into the upload area (or selecting "okay" on the filepicker dialog) triggers immediate download; there is no 'download' button. Files become visible in 'Attached files' area as the progress bar begins to show progress.
* The user can specify a Display label for each file during or after upload.
* For Batch Upload, The title for each work created will be set to the same value as the Display Label for each file.
* The Batch New Works page has a message just below the tabs that is not shown on the New Work and Edit Work pages.  Additionally, the Batch New Works page has a different heading above the upload area. Check the page context to determine whether to show the message using something like...

```ruby
          if params[:controller].eql?('upload_sets_controller')
            # show message
          end
```

Similar code can determine which heading to use for the file upload area.

**Comment by hackmastera** [comment]
Question outstanding: what happens to progress bar when editing a work wherein files were downloaded long ago? Perhaps instead we display date uploaded.

Also outstanding: tweaks to Batch upload to remove 'resource type' field.

**Comment by cam156** [comment]
@hackmastera What is expected to happen when you are uploading files from the cloud?  Is this page only for local file uploads or does the page imply that you can upload files from local and the cloud simultaneously?  The process for cloud files happens in the background, which is very different from local files.

**Comment by hackmastera** [comment]
@cam156 Sorry for delayed response. It's a great question and I don't know the full answer; bouncing to UI group to see if anyone else has more experience using cloud upload tools. 

The page is definitely designed for both types of uploads -- you'll see the 'cloud providers' heading at the bottom.

I think simultaneous upload would be preferred if possible. This is the part I'm not sure about; perhaps there's a technical limitation that impacts the UI. It sounds like you're saying that the progress bar isn't possible for cloud uploads, and metadata couldn't be edited on initial upload. Once the background process is finished a refresh would show that the file is available?

Once uploaded all files will show in the 'attached files' area regardless of origin.

**Comment by elrayle** [comment]
A couple of observations from my understanding:
* The process for local upload is dependent on jquery-upload library which does allow uploads to begin immediately.
* The process for cloud upload is dependent on the process for the browse-everything gem.  I'm going to guess from @cam156 comments that it only allows background upload.
* The UI design does not require that all files complete uploading before saving.  So local files that complete uploading prior to save will be saved.  All cloud uploaded files and any remaining local files will upload in background after save.

There are technical issues that need to be addressed that may impact this.
* Where do files that upload before save go?  Is there a tmp directory or is there a tmp work?  In either case, there will need to be some cleanup if the user cancels before saving.  And potentially post-processing to move the file from the tmp directory to the work after save.
* Is it possible to have a seamless process that allows some files to be uploaded before saving and the remaining processed in background directly to the newly created work.
