### ISSUE TITLE
Refactor _show_actions into separate files for FileSet and GenericWorks

### ISSUE THREAD

**Issue by njaffer** [projecthydra/sufia#1592]
### Descriptive summary
Sufia 7: Refactor app/views/curation_concerns/base/_show_actions.html.erb into app/views/curation_concerns/file_sets/_show_actions.html.erb and app/views/curation_concerns/generic_works/_show_actions.html.erb

### Related work
https://github.com/projecthydra/sufia/pull/1590

**Comment by mjgiarlo** [comment]
:clap: Thanks, @njaffer
