### ISSUE TITLE
ordered_member_ids should not be part of attributes

### ISSUE THREAD

**Issue by njaffer** [projecthydra/sufia#1593]
### Descriptive summary

Include what version of Sufia relates to this issue (7.x, 6.x, HEAD, etc.) if appropriate, and any relevant tracebacks if you're reporting a bug.

### Expected behavior
Work should be saved

### Actual behavior
Error is generated: "GenericWork does not have an attribute `ordered_member_ids’"

### Steps to reproduce the behavior

1. Hit ' Add Work'
1. Hit 'Save'

### Related work
https://github.com/projecthydra-labs/curation_concerns/pull/625

**Comment by njaffer** [comment]
In CC, https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/actors/curation_concerns/work_actor_behavior.rb#L15

the ordered_members_ids is stripped out but for some reason, it is not stripped out when called from Sufia

**Comment by jcoyne** [comment]
Why is ordered_member_ids input field on the page that errors when you submit it?

**Comment by njaffer** [comment]
@jcoyne: good find, I didn't notice that the ordered_members_ids input fields is on the form as well.
