### ISSUE TITLE
Use Redis.current instead of $redis

### ISSUE THREAD

**Issue by barmintor** [projecthydra/sufia#1599]
### Descriptive summary

Sufia (HEAD) uses a global variable to track the redis configuration unnecessarily based on example code. It should consistently use Redis.current across the project.

**Comment by jcoyne** [comment]
I'd like to completely remove the hard dependency on Resque (because someone might use Sidekiq), so let's use Redis.current.

**Comment by barmintor** [comment]
:+1:

**Comment by barmintor** [comment]
We also initialize the redis client twice (once in the redis_config initializer and once in the resque_config initializer)

**Comment by barmintor** [comment]
https://github.com/projecthydra/sufia/blob/2c1d0d50bd91d6bd78c5a4535011f994dc92f209/lib/sufia/redis_event_store.rb
https://github.com/projecthydra/sufia/blob/2c1d0d50bd91d6bd78c5a4535011f994dc92f209/spec/jobs/event_jobs_spec.rb

**Comment by barmintor** [comment]
Depends on https://github.com/projecthydra-labs/curation_concerns/issues/639
