### ISSUE TITLE
Fields missing from GenericWork display

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1600]
### Descriptive summary

In Sufia 7, not all fields are being displayed.

### Expected behavior

All fields should appear if they have content in them.

### Actual behavior

Only these appear:

* Description
* Creator
* Contributors
* Subject
* Publisher
* Language
*Visibility

### Steps to reproduce the behavior

1. Create a work
1. Fill in all the fields

**Comment by atz** [comment]
Are you expecting all fields in the search results/ hit list page or is this ticket about the details page?

**Comment by hectorcorrea** [comment]
I am assuming this is for the details/show page only.
