### ISSUE TITLE
Depositors should be able to select representative media and thumbnail for a Work

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1601]
**Please note this ticket has been changed from a question to an enhancement. See the acceptance criteria: https://github.com/projecthydra/sufia/issues/1601#issuecomment-199954403**

If you upload multiple files as part of a work, one of them is chosen to be the representative file of the work. This seems to be the first FileSet object in the work. How does one go about changing that? It seems like it'd be a process of re-ordering the contained FileSets, but I don't see where that's done anywhere.

**Comment by jcoyne** [comment]
There is UI to make such a choice in CC. Someone may want to take a look at that.  You don't need to reorder in order to make a different choice, it's a separate pointer.

**Comment by awead** [comment]
I would just incorporate the UI bits from CC to select the representative. AFAIK, there isn't an ordering requirement... yet. This is missing from the current set of wireframes.

**Comment by mjgiarlo** [comment]
@awead :speech_balloon: 
> I would just incorporate the UI bits from CC to select the representative.

:+1:

**Comment by mtribone** [comment]
@awead The UI Working Group punted on the representative work thumbnail and just thought that the first file thumbnail gets the honor. We've been hashing through so much that we thought the conversation would slow us down...more.

**Comment by awead** [comment]
@mtribone at this point, we'll just use what's in Curation Concerns and go from there.

**Comment by mjgiarlo** [comment]
# Acceptance criteria

1. There should be a field on the form where you can set the representative file of a Work (to choose a thumbnail for a Work).
1. It's a dropdown containing the titles of all the member FileSets.
1.
