### ISSUE TITLE
Issues with the FileSet edit page

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1604]
Here's what I'm seeing with the FileSet edit page:

- [ ] <strike>maybe should have a breadcrumb trail leading back to the work</strike>
- [ ] tabs aren't hiding and showing properly: description initially displays, but is not hidden when clicking other tabs
- [ ] permission form's lease and embargo selectors are overrunning the text

**Comment by elrayle** [comment]
The UI Working Group has a fairly complete design for the Works edit page.  FileSets are manipulated through this UI.  Is this issue related to coding for the new design?  If not, and this isn't critical, I wait to apply development time to this after the new UI is under development.

**Comment by awead** [comment]
The wireframes do not include manipulation of permissions for version which are present in the file set edit views

**Comment by jcoyne** [comment]
I struck the first one, because we don't want to give the ability for the user to leave the form without saving/canceling changes.

**Comment by jcoyne** [comment]
Closing this, as it was decomposed into #1649 and #1650

**Comment by mjgiarlo** [comment]
Epic issue was broken down into smaller issues.
