### ISSUE TITLE
Issues with the FileSet show page

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1605]
Here's what I'm seeing with the FileSet show page:

* show collections information -- FileSets shouldn't be part of collections
* reports that characterization hasn't occurred, yet it has :smile:
* we should be able to display the properties created from the characterization process 
* breadcrumb is missing link to work
* are endnote, mendeley, and zotero exports appropriate here, or are they only for works?

**Comment by elrayle** [comment]
Is there a FileSet show page or is this the Work show page? The wireframes under development by the UI Working Group do not include FileSet show pages.  All FileSet information is displayed as part of the Work show page.

**Comment by awead** [comment]
There is a file set show page in master.  Will that be removed?  If so, there is characterization information, audit information, as well as file activity that will need to be displayed.

**Comment by awead** [comment]
See attached:
<img width="1232" alt="fs-show" src="https://cloud.githubusercontent.com/assets/312085/13332685/3d4bcac2-dbd1-11e5-9452-22bb37f840d0.png">

**Comment by elrayle** [comment]
I am bringing this and issue #1604 to the UI Working Group.

**Comment by atz** [comment]
Any feedback to make this ticket actionable?

**Comment by mjgiarlo** [comment]
@elrayle :arrow_heading_up: :grey_question:

**Comment by mjgiarlo** [comment]
Epic issue was broken down into smaller issues.
