### ISSUE TITLE
Confirm Permission view renders incorrectly

### ISSUE THREAD

**Issue by hectorcorrea** [projecthydra/sufia#1606]
### Descriptive summary
The `Confirm Permission` view renders raw HTML (see screenshot below), it still renders with the Curation Concernss styles rather than Sufia's. 

In addition the links to "Yes please" and "No, I'll update manually" are being rendered wrong. For example, the link for "No, I'll update manually" renders as `http://localhost:3000/concern/generic_works/%23%3CActionDispatch::Routing::RoutesProxy:0x007ff2e8063028%3E%2Fx633f101s`

### Expected behavior
The view should render without the raw HTML, using the Sufia styles, and the links should not include the ActionDispatch text.

### Actual behavior
See screenshot.

### Steps to reproduce the behavior

1. Edit a view with at least one file.
1. Change the work permissions (e.g. from Public to Private) 
1. Save your changes and you'll be presented with the "Confirm Permission" view.

### Related work
Wait until issue #1603 has been fixed.

![screen shot 2016-02-25 at 3 52 02 pm](https://cloud.githubusercontent.com/assets/568286/13334130/7a1f819e-dbd8-11e5-93d3-2df518725015.png)

**Comment by ilessing** [comment]
There is erb code is [config/locales/sufia.yml](https://github.com/projecthydra/sufia/blob/master/config/locales/sufia.en.yml#L59) which shouldn't be there.

**Comment by hectorcorrea** [comment]
@ilessing thanks for the pointer. I've replaced the ERB with tokens that can be injected during rendering which I believe was the original idea of whomever put the ERB on the YML file. See https://github.com/projecthydra/sufia/pull/1615/files

**Comment by hectorcorrea** [comment]
Fixed by PR #1615
