### ISSUE TITLE
Restructure Views

### ISSUE THREAD

**Issue by justcolin** [projecthydra/sufia#1610]
## Summary

While working on U-M's beta interface for our repository based on Sufia 7 we had a lot of trouble working with Sufia's current views. The following suggestions are centered around simplifying maintenance and making it easier for groups to customize Sufia's views as much or as little as they see fit.

**Note:** This issue should probably be dealt with as part of implementing whatever the UI working group comes up with instead of working on the current interface.
## Suggestions
1. Remove any partials that are only used once. 
   - They may it more difficult and time consuming to modify the HTML.
2. Reduce the level of nesting with views.
   - There are some pretty deeply nested views currently, which are really hard to style and rework since simple edits can require editing 4 files.
3. Clean up formatting.
   - Currently there are a lot of lines that are well over 100 characters long
4. Conditionals in views should be simple. Any complex logic should be be pushed into a method in a presenter.
5. Views should never have a conditional that branches on the value of controller.name, action or params[]
   - Added by @jcoyne 
## Related

See #1594 for the start of this discussion
See #1608 for the discussion of front-end development best practices

**Comment by justcolin** [comment]
@grosscol

**Comment by jcoyne** [comment]
> Any complex logic should be be pushed into a method in a controller.

This should probably say "presenter" instead of "controller"

**Comment by jcoyne** [comment]
May I add a \#5?  How about "views should never have a conditional that branches on the value of `controller.name`, `action` or `params[]`"

**Comment by jcoyne** [comment]
Can point 3 be just "restrict line length to N" or are there other formatting changes you want to add?

**Comment by jcoyne** [comment]
I want to reiterate that I'm against point 1 as that is the method we've been able to introduce constrained changes between implementations without having to re-validate that no partial we've overridden has changed since the last version when we upgrade.

**Comment by grosscol** [comment]
Regarding point 1, I found the number of partials staggering.  However, I conceded @jcoyne's point about constraining changes between different implementations.  Cribbing off of that, can we look across the implementations we're aware of and take a look at partials that have not been overridden?

**Comment by jcoyne** [comment]
One of the reasons leading to the profusion of partials, is that sufia is using many gems, and overriding views provided by them to have a cohesive UI. Among them are kaminari, blacklight, blacklight-gallery, blacklight-advanced_search, mailboxer, hydra-editor, hydra-collections, hydra-batch-edit, and curation_concerns.

**Comment by justcolin** [comment]
@jcoyne: Side note: keep these notes coming! This is exactly the kind of lively discussion I wanted to see.

**Comment by awead** [comment]
I'm for points 3 and 4. I'm against points 1 and 2: Having a partial, even if only used once, allows implementors to override it. Same goes for nested views. Yes, it can be confusing at first, but I'd rather have to dig through nested partials than have to duplicate a view of 100+ lines only because I want to make a 2 line change.

**Comment by jcoyne** [comment]
Have you used xray-rails for working with partials? https://rubygems.org/gems/xray-rails It's really a nice shortcut to figuring out what is rendering.

**Comment by justcolin** [comment]
@jcoyne I added that item 5. Is there a way make that recommendation more generic?

**Comment by justcolin** [comment]
I have used cray-rails and it helps a lot, but it doesn't help the editing experience.

**Comment by jcoyne** [comment]
@justcolin Those are the only problematic ones I'm concerned about as they generally indicate the need for another partial instead of a shared partial.

**Comment by mjgiarlo** [comment]
@justcolin @jcoyne @awead As we start to clarify the paths forward for Sufia and Hyrax, I want to make sure we don't lose the good discussions here. Are there any bits from the above discussion that we should write up as actionable issues?

**Comment by justcolin** [comment]
@mjgiarlo: I remember whether or not the partials should be made less granular was still a debated issue. If people can agree and decide err on the side of less granular, than that could be made into an actionable issue (identify, then inline/remove partials that are only used once).

I'd also be happy to work on that if people are interested in it.

**Comment by mjgiarlo** [comment]
@justcolin We have generally created new, more granular partials when we needed to provide smaller seams for downstream apps to inject their own behavior. I'm not eager to pursue partial nuke-ification systematically, but I'm open to targeted consolidation when we have evidence that we don't need the seam (though I admit here that making that determination is tricky, so this may have the same effect as saying `#wontfix`, which I'm not saying here).

**Comment by justcolin** [comment]
@mjgiarlo: Sounds good. This issue was created since U-M found the many little partials made it harder rather than easier to customize things, but that was just our experience.

**Comment by mjgiarlo** [comment]
Thanks, @justcolin.
