### ISSUE TITLE
Get Sufia running with CC 0.9 and HC 8.0

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1614]
New updates to Curation Concerns and Hydra Collections have broken the build resulting in these errors:
`wrong number of arguments (0 for 1)` when uploading files or creating works, and `You attempted to set the property `title' to a scalar value. However, this property is declared as being multivalued.` on collections.

**Comment by jcoyne** [comment]
I'm not sure about that first error, but the second is the result of hydra-collections going to all-multivalued metadata.
