### ISSUE TITLE
last_comment deprecation warning

### ISSUE THREAD

**Issue by atz** [projecthydra/sufia#1639]
On 7.x/master, deprecation warnings are issued during multiple steps of installation, including `rake db:migrate`:

```
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
```

For db:migrate, the warning appers 5 times in a row prior to any other output.  The string is not present in the repo, so this is probably a dependency needing updated.

**Comment by jcoyne** [comment]
I think this is due to rake 11.0.1 and another gem (rubocop maybe?) that's calling the deprecated method. There's not much we can do about it.

**Comment by rotated8** [comment]
Yep, [Rake 11.1.0](https://github.com/ruby/rake/blob/master/History.rdoc). I think the warnings are for Rails, since it shows up for me without Rubocop.

**Comment by mjgiarlo** [comment]
I have Rake 11.1.1 and I do not see those deprecations. Should we suggest updating rake, or require a newer rake?

**Comment by jcoyne** [comment]
@atz can you confirm that updating rake fixes this?

**Comment by atz** [comment]
I'm already on rake `11.1.1`, so no help there.

**Comment by cbeer** [comment]
With the current version of Rake, I'm not seeing this on travis for either Rails build.
