### ISSUE TITLE
Work Edit not saving rights field

### ISSUE THREAD

**Issue by hectorcorrea** [projecthydra/sufia#1645]
### Descriptive summary

The Work Edit screen is not saving the `rights` field. The problem seems that we are not white-listing this field and therefore the controller is rejecting it and displaying "Unpermitted parameter: rights" in the Rails console.

### Expected behavior
The `rights` field should be saved to Fedora and displayed when rendering the Work Show page. 

### Actual behavior
The `rights` field is not being saved to Fedora and therefore the Work Show page does not display the value. 

### Steps to reproduce the behavior

1. Edit a work
1. Select a value from the "Rights" dropdown
1. Save it
1. Notice how the value was not persisted to Fedora. You should also have seen in the Rails console the unpermitted message mentioned above.

### Related work
This issue was found in PR #1644

**Comment by njaffer** [comment]
@hectorcorrea: Is it related to this PR: https://github.com/projecthydra/sufia/pull/1596

**Comment by hectorcorrea** [comment]
@njaffer hum...I hadn't see the PR that you just referenced. Although that PR says that the `rights` field is now being saved that's not what I am seeing with the latest from master. In fact I see the message on the Rails console that indicates that the field is not permitted.

**Comment by hectorcorrea** [comment]
@njaffer in reading your original PR and the code that you are referencing I think yes, this is the same issue.

**Comment by njaffer** [comment]
@hectorcorrea: I closed this PR, because when I checked in master codebase, the rights were being saved, but I did  not check for editing the rights. So it seems like the bug is partial now, rights are saved initially but does not let you edit it?

**Comment by hectorcorrea** [comment]
@njaffer that could be, let me test the new vs edit scenario.

**Comment by hectorcorrea** [comment]
@njaffer I also see the "Unpermitted parameter: rights" when saving a new work and the value is indeed not being persisted to Fedora.

**Comment by hectorcorrea** [comment]
@njaffer what's interesting is that this works OK in Curation Concerns. We must be overwriting something in Sufia that is making this fail.

**Comment by njaffer** [comment]
@hectorcorrea: Right, it has been working ok in CC. The PR I referenced has a change in Sufia.

**Comment by njaffer** [comment]
@hectorcorrea: I just tested it again and it does not save the rights when saving a new work either. This is the line that needed the override in Sufia: 
https://github.com/projecthydra-labs/curation_concerns/blob/master/app/forms/curation_concerns/forms/work_form.rb#L47

**Comment by hectorcorrea** [comment]
Closed by https://github.com/projecthydra/sufia/pull/1596
