### ISSUE TITLE
Tabs should hide and show predictably on the FileSet edit page

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1650]
### Descriptive summary

On the FileSet edit page, tabs aren't hiding and showing properly.

Relates to Sufia master.

### Expected behavior

The FileSet's description is hidden when other tabs are selected, and is displayed when the initial tab is selected.

### Actual behavior

The FileSet's description initially displays, but is not hidden when clicking other tabs.

### Steps to reproduce the behavior

1. Load the FileSet edit page
1. Notice the descriptions
1. Click one of the other tabs
1. Notice the descriptions are still there

### Related work

Refs #1604 (thanks, @awead!)

**Comment by atz** [comment]
Notably, 2 of the 3 glyphicons fail to display for me:
![screen shot 2016-04-06 at 6 17 25 pm](https://cloud.githubusercontent.com/assets/109954/14337578/153a4b9e-fc24-11e5-970f-848c94f2aea5.png)

By the code, there should be `glyphicon-sitemap` and `glyphicon-key` there.  Not really sure where those are intended to be sourced from though.  

[Bootstrap's](http://getbootstrap.com/components/#glyphicons) glyphicons don't have `key` listed.  Glyphicons **used** to have one, enough to be listed on [here](http://glyphsearch.com/?query=key), but for the example to render blank on my Yosemite Macbook.  This is probably the [removal](https://github.com/twbs/bootstrap/issues/15419).  Font Awesome does have a `fa fa-key`, though it is stylistically different.  

Sitemap seems completely outside bootstrap/glypicons.  I imagine that is supposed to be `fa fa-sitemap`?

**Comment by atz** [comment]
The dimensions between glyphicons and fa icons differ: 14x16 vs. 14x14.  

Using font-awesome for all three looks like:

![screen shot 2016-04-06 at 7 25 39 pm](https://cloud.githubusercontent.com/assets/109954/14338656/73074750-fc2d-11e5-91e4-8dbab604fb79.png)


That fits the layout better ("Descriptions" isn't pressed against the icon) and the referenced icons, you know, actually exist.  Acceptable improvement?

Navbar action stuff tomorrow.

**Comment by mjgiarlo** [comment]
Looks better to me, @atz!
