### ISSUE TITLE
Remove Sufia::SingularSubresourceController

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1669]
### Descriptive summary

It's not used more than once and adds indirection without benefit

**Comment by mjgiarlo** [comment]
I'm inclined to put this on the backlog since it's not needed for the 7.0.0 release. If you've already started working on this, @jcoyne, then we can leave it in the 7.0.0 milestone.

**Comment by cbeer** [comment]
This is used by 2 classes now.
