### ISSUE TITLE
Characterization doesn't appear to run

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1676]
### Descriptive summary

In Sufia master, when uploading files using the internal test app, characterization doesn't run.

### Steps to reproduce the behavior

With redis running:

1. bundle update
1. bundle exec rake engine_cart:generate
1. bundle exec fcrepo_wrapper -p 8984
1. bundle exec solr_wrapper -d solr/config/ --collection_name hydra-development
1. bundle exec resque-pool -E development start
1. cd .internal_test_app && bundle exec rails s

Goto localhost:3000 and upload a sample file. Checking the Resque queue shows that maybe the job was never run:

```
> Resque.info
=> {:pending=>0, :processed=>0, :queues=>0, :workers=>1, :working=>0, :failed=>0, :servers=>["redis://localhost:6379/0"], :environment=>"development"}
```

**Comment by hectorcorrea** [comment]
@awead I believe the default configuration in Sufia 7 runs the jobs "inline", i.e. without using Resque. You have to enable resque in the config if you want to use a queue.

**Comment by awead** [comment]
@hectorcorrea but if it's inline, then the job should still run, right?

**Comment by hectorcorrea** [comment]
@awead yes, but the job runs in the foreground (and not through resque)

**Comment by awead** [comment]
Here's gist of the output: https://gist.github.com/awead/ae608a89731f38fce321e1b7582ec905

Jobs appear to be run, but I'm not sure what the outcome is.

**Comment by awead** [comment]
@hectorcorrea ok, so characterization is running, but the UI says it hasn't, so that's a different kind of bug. However, I'm seeing the metadata from the fits show up on the GenericWork, and thought maybe that should be on the FileSet.

**Comment by mjgiarlo** [comment]
@awead Yep, it should be. :bug: !
