### ISSUE TITLE
Sufia does not correctly report that characterization is done

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1678]
### Descriptive summary

When uploading a new file, Hydra::Works::CharacterizationService gets called via CurationConcerns' CharacterizeJob, but Sufia reports that the file has not been characterized.

### Expected behavior

Sufia should show that the file has been characterized and display relevant metadata.

### Actual behavior

UI displays "not yet characterized"

![characerization](https://cloud.githubusercontent.com/assets/312085/14121440/879865c8-f5c5-11e5-800c-b634a2522f07.png)

### Steps to reproduce the behavior

1. Upload a file via the internal test app.

### Related work

#1676

**Comment by mjgiarlo** [comment]
@jcoyne whoa! the nine-headed bird! where'd you find/get that image?

**Comment by awead** [comment]
ok, works now with the new upload UI.
