### ISSUE TITLE
FileSet technical metadata stored as properties on the GenericWork

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1679]
### Descriptive summary

When uploading a file, FITS's metadata is stored as RDF properties on the GenericWork.

### Expected behavior

It's not clear what the expected behavior is, but perhaps technical metadata for a file should appear as properties on the FileSet. You'd have to do this for multi-file works, unless the multiple files themselves are actually individual GenericWorks contained by another GenericWork.

**Comment by awead** [comment]
Bah. Nevermind, false alarm. I thought I was looking at a GenericWork in Fedora.

**Comment by mjgiarlo** [comment]
:ok:
