### ISSUE TITLE
CSS styling delivered in triplicate

### ISSUE THREAD

**Issue by atz** [projecthydra/sufia#1680]
On sufia 7.x/master, we appear to style the same selectors the exact same way three times: once from curation_concerns and twice more by sufia.  is that normal?

For example, this piece of styling:

``` css
.label {
    display: inline;
    padding: .2em .6em .3em;
    font-size: 75%;
    font-weight: bold;
    line-height: 1;
    color: #fff;
    text-align: center;
    white-space: nowrap;
    vertical-align: baseline;
    border-radius: .25em;
}
```

Appears in three places:

```
http://localhost:3000/assets/curation_concerns.self-4e4167184078d8e858eee542cdad2883700618fc5d8b5e68b33e416fd0f926f9.css?body=1
http://localhost:3000/assets/sufia.self-424a4b2fd0965b6f16b4e39f3f3ae5f763dbd4aa8c88d543edabc106464ed95f.css?body=1 (line 6517)
http://localhost:3000/assets/sufia.self-424a4b2fd0965b6f16b4e39f3f3ae5f763dbd4aa8c88d543edabc106464ed95f.css?body=1 (line 15860)
```

From crude grep analysis of **sufia.css**: 1054 selectors appear once, but 2599 appear twice.  80+ appear 5-20 times.  And for some reason `@media (min-width: 768px)` appears 51 times.

Notably, this line is appears twice:

```
/*! Source: https://github.com/h5bp/html5-boilerplate/blob/master/src/css/main.css */
```

So I think it is safe to conclude we are duplicating CSS.  While related to #1611, this is really separate.  Even if we keep the current structure we should repeat ourselves... twice, including inside the same file.

**Comment by mjgiarlo** [comment]
Thanks, @atz

**Comment by atz** [comment]
`app/views/layouts/_head_tag_content.html.erb` has:
```html
<%= stylesheet_link_tag 'application' %>
```

`application.css` is effectively:
```css
*= require_tree .
*= require_self
*= require sufia
```
Becoming:
```html
<link rel="stylesheet" media="screen" href="/assets/blacklight_gallery/default.self-7ad99de1d114859623e416195499e03d0091b1e1559f2b50b3f4f463eb49d908.css?body=1" />
<link rel="stylesheet" media="screen" href="/assets/blacklight_gallery.self-432f7642176cbbe3478c7986ce439b2c99642bf0f1a81ae971e7c7e6c1e3c3b5.css?body=1" />
<link rel="stylesheet" media="screen" href="/assets/curation_concerns.self-4e4167184078d8e858eee542cdad2883700618fc5d8b5e68b33e416fd0f926f9.css?body=1" />
<link rel="stylesheet" media="screen" href="/assets/openseadragon/openseadragon.self-59993793758f5500d22a31cb2c4f397d4cbd76059d4e3b3b22d7c4c3a1bbac68.css?body=1" />
<link rel="stylesheet" media="screen" href="/assets/openseadragon.self-432f7642176cbbe3478c7986ce439b2c99642bf0f1a81ae971e7c7e6c1e3c3b5.css?body=1" />
<link rel="stylesheet" media="screen" href="/assets/application.self-d885a0a66bd595c10edb24f8879f94e334d88be0730c4d7c7a7b57c731c09037.css?body=1" />
<link rel="stylesheet" media="screen" href="/assets/sufia.self-424a4b2fd0965b6f16b4e39f3f3ae5f763dbd4aa8c88d543edabc106464ed95f.css?body=1" />
<link rel="stylesheet" media="screen" href="/assets/file_sets.self-34980108c4a0f17b12cfaf9f0c010d99bca9f4fe443631d6fdd5b7b4f470f3f4.css?body=1" />
<link rel="stylesheet" media="screen" href="/assets/fileupload/jquery.fileupload-ui.self-5824487e6c63c1d31ef977c7810c42b0eaebfef0388de7846b5e37ca5b2ae543.css?body=1" />
<link rel="stylesheet" media="screen" href="/assets/fileupload/style.self-d27fe43e67629050e4f3a19ab022bdf57eecb27d15288c56a9ee2a426a12281e.css?body=1" />
<link rel="stylesheet" media="screen" href="/assets/fileupload/thumbnail-scaling.self-277b558bbc3ef7cc95a1f7a4b95b314ea4d82ec4e207823097a454511de3dd67.css?body=1" />
<link rel="stylesheet" media="screen" href="/assets/fileupload/application.self-693d893d78da47d80a53b6d8e23ab1eb4409eac658661bfe6b4a24ec0a9a90b1.css?body=1" />
<link rel="stylesheet" media="screen" href="/assets/video-js.self-fa5617eecc5b3325a569b2228cff69ae3229a980d686f98c46ed3bc73ce889ea.css?body=1" />
<link rel="stylesheet" media="screen" href="/assets/jquery-ui.self-b266a2dccae7e5689f0f9dee9388e3066551deeadb0ec3e41d3e0af33bb27e38.css?body=1" />
<link rel="stylesheet" media="screen" href="/assets/select2.self-e92418e5094585ea0a675963e08a16caacfa3af35caec59b82d517a23c50b3f7.css?body=1" />
<link rel="stylesheet" media="screen" href="/assets/sufia-audio-overrides.self-733f18841c371075f474f1d47eb54597969200cc989636e6dde054100b5f3553.css?body=1" />
<link rel="stylesheet" media="screen" href="/assets/nestable.self-3a25da763b6b1827dfcd545c5540bed25b3939ccc91f9dd2ac30e876fcfdeaf4.css?body=1" />

```

Isn't the point that the local app might override Sufia?  Why does Sufia get the last word?  Since the default is empty but the expectation is local installer preference will try to use the file for overrides, I propose to but the `require_self` last.  Concerns?

**Comment by atz** [comment]
Specifically, I propose to change this line:
https://github.com/projecthydra/sufia/blob/master/lib/generators/sufia/install_generator.rb#L182

to:
```ruby
insert_into_file 'app/assets/stylesheets/application.css', before: ' *= require_self' do
```

**Comment by mjgiarlo** [comment]
Tagging @jcoyne as the author of that code.

**Comment by jcoyne** [comment]
I suspect this was done to ensure sufia trumped Blacklight, but that was a long time ago. Feel free to change it.

**Comment by atz** [comment]
OK, that ordering has been changed and CurationConcerns CSS was removed elsewhere, but I still get triples of the same styling, like:

```css
.help-block {
    display: block;
    margin-top: 5px;
    margin-bottom: 10px;
    color: #737373;
}
```
Twice in `sufia.self-*.css` (lines 4338 and 13681), once in `blacklight.self-*.css`, each instance prefaced by
```
/* line 453, /Users/atz/.rvm/gems/ruby-2.2.0/gems/bootstrap-sass-3.3.6/assets/stylesheets/bootstrap/_forms.scss */
```

I conclude we are including the same bootstrap three times, once via blacklight.

**Comment by jcoyne** [comment]
If that's the case, can we count on blacklight delivering the bootstrap stuff and not include it in sufia's css? Alternatively, we could include it and blow away blacklight's generated css file.

**Comment by atz** [comment]
In the sufia CSS, the repetition starts at line 9354 with the second complete `Bootstrap v3.3.6 (http://getbootstrap.com)` header.  If I split the file at the bootstrap header, the second "half" has 4155 more lines, with a 5052 line delta.  Much of the additional content is related to `font-awesome` and `browse-everything`.  They two halves have *effectively* one line of difference in their first 8876 lines.   So at least that much can be reduced.  I would hate to duplicate ~9000 lines for one `position: absolute`.

@jcoyne I think either of those approaches is manageable.  Probably best to count on blacklight for bootstrap.  Either way we have to stay alert for upstream changes there.

**Comment by atz** [comment]
This is basically our situation: http://inside.unbounce.com/product-dev/handling-code-duplication/

Made more complicated by at least 4 layers (Sufia-app, Sufia, CurationConcerns, Blacklight) where each might be trying to use/reuse the same components.  This basically requires someone with better knowledge of Blacklight and CC to even entertain fixing.  Or sass could release 4.0.0 and fix their epic `@import-once` deficiency.

**Comment by mjgiarlo** [comment]
I believe we've made progress on this item now that we're importing styles from other components differently (not generating their assets into the containing application). I'm not ready to say this is closed, but it's probably worth another round of analysis.

**Comment by mjgiarlo** [comment]
See: #2200, #2182

**Comment by mjgiarlo** [comment]
Take this up in Hyrax.
