### ISSUE TITLE
Create new works: Sidebar lease/embargo/public

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1685]
The lease/embargo fields should be collapsed unless lease or embargo is selected as the visibility.  Then show the appropriate fields. When public is selected show a message explaining open access. This should work for create and edit.

https://wiki.duraspace.org/display/hydra/New+Work+-+Metadata+Tab+-+Phase+1+-+UI+Wireframes#NewWork-MetadataTab-Phase1-UIWireframes-VariantsofSaveWorkwidget

ref #1562

**Comment by mjgiarlo** [comment]
Re: "explaining open access," this is the text we've seen elsewhere:

```
Please note, making something visible to the world (i.e. marking this as Open Access) 
may be viewed as publishing which could impact your ability to:

- Patent your work
- Publish your work in a journal

Check out SHERPA/RoMEO for more information about publisher copyright policies.
```
