### ISSUE TITLE
Create new works: Cloud upload

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1699]
### Wireframes
* [in context of New Work](https://wiki.duraspace.org/display/hydra/New+Work+-+tab+Files+-+Phase+1+-+UI+Wireframes) - Files Tab - contents of tab
* [in context of Edit Work](https://wiki.duraspace.org/display/hydra/Edit+Work+-+Files+tab+-+Phase+1+-+UI+Wireframes) - Files Tab - contents of tab
* [in context of Batch Upload](https://wiki.duraspace.org/display/hydra/Batch+New+Works+-+Phase+1+-+UI+Wireframes#mockup_p1-works-batch_new-step1_upload_files) - Files Tab - contents of tab

**Comment by mjgiarlo** [comment]
Revisit this spec as part of this ticket: https://github.com/projecthydra/sufia/pull/1704/files#diff-eb1a4aca4414404438ba72c0832aa749R10

**Comment by mjgiarlo** [comment]
Blocked by #1817
