### ISSUE TITLE
UploadedFile should be updated with it's work_id once it's been used.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1700]
I think this is low priority for now, but it would be nice to have so that we can determine which files are used versus the abandoned files. This probably goes in `AttachFilesToWorkJob`.

**Comment by mjgiarlo** [comment]
@jcoyne Add to backlog if low priority?

**Comment by jcoyne** [comment]
I'd say this is a blocker for 7.0.0 release.

**Comment by mjgiarlo** [comment]
:ok:

**Comment by mjgiarlo** [comment]
This one is also available, @hectorcorrea
