### ISSUE TITLE
Upload Files javascript should POST when uploading files for a persisted work

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1702]
### Descriptive summary

Remove the hacked route for creating files via a `PATCH` method.
### Expected behavior

The uploaded file should be POSTed to the `UploadedFilesController`
### Actual behavior

The uploaded file is PATCHed (using `_method`) to the `UploadedFilesController`
### Steps to reproduce the behavior
1. Create a work.
2. Edit the work
3. Click to the files tab
4. Add a file and start upload.

**Comment by mjgiarlo** [comment]
@jcoyne should this be on the 7.0.0 critical path, or can we add this to the backlog?

**Comment by jcoyne** [comment]
This can be moved to the backlog.
