### ISSUE TITLE
Remove the FileSetController new and create methods

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1703]
### Descriptive summary

This is now handled by the new create workflow which is largely in `WorkControllerBehavior`

**Comment by mjgiarlo** [comment]
@jcoyne add to backlog if low priority?

**Comment by jcoyne** [comment]
I think that not removing this slows us down as we're maintaining a lot of useless code and tests.  I'd like this to be done now.

**Comment by mjgiarlo** [comment]
:ok_hand:, I'm fine with that.
