### ISSUE TITLE
Files should start uploading as soon as they are selected.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1705]
### Descriptive summary

On the create page, remove the "start upload" button. Uploads should begin as soon as they are selected.

* [in context of New Work](https://wiki.duraspace.org/display/hydra/New+Work+-+tab+Files+-+Phase+1+-+UI+Wireframes) - Files Tab - contents of tab
* [in context of Edit Work](https://wiki.duraspace.org/display/hydra/Edit+Work+-+Files+tab+-+Phase+1+-+UI+Wireframes) - Files Tab - contents of tab

**Comment by jcoyne** [comment]
@mjgiarlo backlog?

**Comment by atz** [comment]
Pushing for more context here... they should start immediately _without condition_? Please confirm: it is OK even when there is no accompanying metadata and the right sidebar has a red exclamation point saying "Enter required metadata"?

**Comment by atz** [comment]
Do they not even have to check the "deposit agreement" box?

**Comment by mjgiarlo** [comment]
Files may be uploaded prior to entering metadata and prior to checking the deposit agreement. Files are uploaded to staging space at this point and don't make it into the repository until the form is valid and submitted.
