### ISSUE TITLE
Add/edit file label on the files tab

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1707]
### Descriptive summary

User should be able to specify a label while the file is uploading.
- [in context of New Work](https://wiki.duraspace.org/display/hydra/New+Work+-+tab+Files+-+Phase+1+-+UI+Wireframes) - Files Tab - contents of tab
- [in context of Edit Work](https://wiki.duraspace.org/display/hydra/Edit+Work+-+Files+tab+-+Phase+1+-+UI+Wireframes) - Files Tab - contents of tab

**Comment by jcoyne** [comment]
@mjgiarlo backlog?

**Comment by mjgiarlo** [comment]
I believe this is already available for the batch create workflow. Closing.
