### ISSUE TITLE
Add work to another work (in_works)

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1709]
### Descriptive summary

Add the work currently being edited as a member of other works.
- [in context of New Work](https://wiki.duraspace.org/display/hydra/New+Work+-+tab+Relationships+-+Phase+1+-+UI+Wireframes) - Relationships Tab - contents of tab
- [in context of Edit Work](https://wiki.duraspace.org/display/hydra/Edit+Work+-+Relationships+tab+-+Phase+1+-+UI+Wireframes) - Relationships Tab - contents of tab

Closely related to #1710 
Ref #1577

**Comment by jcoyne** [comment]
@mjgiarlo backlog?

**Comment by jcoyne** [comment]
@dlpierce can you give us an update on the status of this work?

**Comment by mjgiarlo** [comment]
@dlpierce We're 1-2 blockers away from cutting a beta/RC for 7.3.0. Do you think you might have time to wrap this and #1710 in the coming week or two?

**Comment by dlpierce** [comment]
@mjgiarlo Yes, I'll make it a priority to get this done for 7.3.0.

**Comment by mjgiarlo** [comment]
Moved to Hyrax.
