### ISSUE TITLE
Add contained works (members)

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1710]
### Descriptive summary

Add works that are members of the work currently being edited.
- [in context of New Work](https://wiki.duraspace.org/display/hydra/New+Work+-+tab+Relationships+-+Phase+1+-+UI+Wireframes) - Relationships Tab - contents of tab
- [in context of Edit Work](https://wiki.duraspace.org/display/hydra/Edit+Work+-+Relationships+tab+-+Phase+1+-+UI+Wireframes) - Relationships Tab - contents of tab

Closely related to #1709 
Ref #1577

**Comment by jcoyne** [comment]
@mjgiarlo backlog?

**Comment by jcoyne** [comment]
@dlpierce can you give us an update on the status of this work?

**Comment by dlpierce** [comment]
I've been working on it when able, but it's not ready yet. I'll try to have a branch pushed this week.

**Comment by mjgiarlo** [comment]
Moved to Hyrax.
