### ISSUE TITLE
Add related works

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1711]
### Descriptive summary
- [in context of New Work](https://wiki.duraspace.org/display/hydra/New+Work+-+tab+Relationships+-+Phase+1+-+UI+Wireframes) - Relationships Tab - contents of tab
- [in context of Edit Work](https://wiki.duraspace.org/display/hydra/Edit+Work+-+Relationships+tab+-+Phase+1+-+UI+Wireframes) - Relationships Tab - contents of tab

Question: How are related works stored in the model?

Ref #1577

**Comment by jcoyne** [comment]
@mjgiarlo can we backlog this?

**Comment by jcoyne** [comment]
@azaroth42 @escowles @no-reply Does PCDM have "related works"?

**Comment by mjgiarlo** [comment]
Backlogging.

**Comment by jcoyne** [comment]
@mjgiarlo this ticket is linked from #2082, but I don't think it should be.
