### ISSUE TITLE
Active acceptance of deposit licence

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1714]
https://wiki.duraspace.org/display/hydra/New+Work+-+Metadata+Tab+-+Phase+1+-+UI+Wireframes#NewWork-MetadataTab-Phase1-UIWireframes-VariantsofSaveWorkwidget

Requires new configurations for `config.active_deposit_agreement_acceptance`
  * if true, show checkbox and active acceptance message for Deposit Agreement (see variant); Also show in Requirements area and set to red exclamation if acceptance is not checked or green check if acceptance is checked. Needs to be able to be changed if user checks/unchecks acceptance.
  * if false, do not show checkbox and do show passive acceptance message for Deposit Agreement (see in main New Work wireframe)

Ref #1562

**Comment by jcoyne** [comment]
@mjgiarlo backlog?

**Comment by mjgiarlo** [comment]
For the 7.0.0 release, let's make sure not to change the contract for the deposit agreement, which is that it's a checkbox that must be checked on every deposit. We can make this more configurable post-7.0.0.
