### ISSUE TITLE
UI proxy depositor

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1717]
Implement proxy controls
https://wiki.duraspace.org/display/hydra/New+Work+-+Metadata+Tab+-+Phase+1+-+UI+Wireframes#NewWork-MetadataTab-Phase1-UIWireframes-Proxycontrols

**Comment by mtribone** [comment]
@jcoyne Nope. We really only focused on the creation and editing of works, adding files, relationships, etc. To the best of my knowledge, authorizing a proxy is still on the dashboard.

**Comment by jcoyne** [comment]
@mtribone but if you already are an authorized proxy, shouldn't there be a "Deposit this work for ..." widget?

**Comment by mtribone** [comment]
@jcoyne Ah. Yes it used to be a part of the upload screen - on behalf of...Let me go back and look at what we have in the wireframe.

**Comment by mtribone** [comment]
Yeah we need to add that back to the interface:

https://wiki.duraspace.org/display/hydra/New+Work+-+tab+Files+-+Phase+1+-+UI+Wireframes#mockup_p1-works-new-tab_files

**Comment by mtribone** [comment]
I believe because we were trying to get to the admin and super admin functions it came off of the screen. However since we didn't make it that far it would be good to pop back in.

**Comment by mjgiarlo** [comment]
@jcoyne Can you add the "ready" label to this issue once we've got what we need to get started on this?

Thanks, @mtribone!

**Comment by elrayle** [comment]
We discussed this at the UI Working Group meeting today.

@dt-ucsd will be updating the wireframes showing how to select that a work is for yourself or for one of your proxies.  He will update when the wireframe is complete.

**Comment by dt-ucsd** [comment]
Find our solution to the placement of proxy controls here:

https://wiki.duraspace.org/display/hydra/New+Work+-+Metadata+Tab+-+Phase+1+-+UI+Wireframes

_It is located at the end of the page ("Save Work Control: "Proxy" controls)._

**Comment by jcoyne** [comment]
@dt-ucsd add proxy is not a required field, so I don't think we want to have it in the required steps at the top of the Save control.

**Comment by dt-ucsd** [comment]
@jcoyne Thanks for the heads up. I just added a new mockup of the control placement to the set of wireframes I referenced earlier. It is located in the "Proxy Controls" section and is labeled "Without requirement step".

**Comment by jcoyne** [comment]
@dt-ucsd Thanks. Thats great. I still don't understand why it would *ever* be a requirement to select a proxy. Is there a use case to maintain that design?

**Comment by dt-ucsd** [comment]
No, it was just us worrying that people would miss it when we discussed adding it to the new layout. We figured if we make it an item in the list of requirements, then they'll never miss it. If it helps, I'll remove it from the wireframe set to avoid confusion.

**Comment by jcoyne** [comment]
@dt-ucsd Yes please remove it. I think it's confusing to keep things we never intend to implement.

**Comment by dt-ucsd** [comment]
@jcoyne Done. I also removed the "Without requirement step" label since it is the only mockup in that section now.
