### ISSUE TITLE
Affix the create a new work status panel to the screen

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1719]
So that it doesn't move when you scroll.

Consider: 
- [ ] mobile screen sizes
- [ ] viewport is shorter than the status panel.

Ref #1562

**Comment by mtribone** [comment]
![screen shot 2016-04-01 at 9 33 38 am](https://cloud.githubusercontent.com/assets/4163828/14208366/fb1d27a8-f7ec-11e5-9cfe-993173fb0981.png)

**Comment by mtribone** [comment]
![screen shot 2016-04-01 at 9 33 57 am](https://cloud.githubusercontent.com/assets/4163828/14208370/036f61be-f7ed-11e5-8c6a-aca96fa55bc2.png)

**Comment by mtribone** [comment]
@jcoyne Will test in other browsers and validate. I'll put any refactoring recommendations into another issue.

**Comment by mtribone** [comment]
Will require mucho media queries, but doable.

**Comment by mtribone** [comment]
Fixing an error then squashing. Almost there.

![screen shot 2016-04-01 at 1 45 25 pm](https://cloud.githubusercontent.com/assets/4163828/14215338/55087b14-f810-11e5-876f-b9ed6b4846e1.png)
![screen shot 2016-04-01 at 1 45 43 pm](https://cloud.githubusercontent.com/assets/4163828/14215339/550dc9c0-f810-11e5-874e-b404deb2499f.png)
![screen shot 2016-04-01 at 1 46 11 pm](https://cloud.githubusercontent.com/assets/4163828/14215340/550df2d8-f810-11e5-93f9-fec714c77744.png)
![screen shot 2016-04-01 at 1 46 37 pm](https://cloud.githubusercontent.com/assets/4163828/14215341/55137500-f810-11e5-9cce-5fa4e6c7d7e3.png)

**Comment by mjgiarlo** [comment]
:clap: @mtribone

**Comment by mtribone** [comment]
@mjgiarlo  Well...almost not there. :-) Bootstrap 3 affix is kicking my rear. The above screen shots are from my own hand spun CSS _thinking_ that I had the plugin called correctly. Sadly once I made the height of the browser shorter the save widget cannon balled into the footer.
