### ISSUE TITLE
Masthead Refactoring: Bootlint errors

### ISSUE THREAD

**Issue by mtribone** [projecthydra/sufia#1720]
### Descriptive summary

Great clean up of the masthead! Just a few things with the usage of Bootstrap rows and columns that get flagged with the Bootlint.

### Error Output

1. Rows and columns on the same element: _controls.html.erb line 9 (https://github.com/twbs/bootlint/wiki/E005)
2. Only columns may be children of rows: _controls.html.erb line 9 and catalog/_search_form.html.erb (https://github.com/twbs/bootlint/wiki/E013)
3. Columns can only be children of rows or form-groups: _controls.html.erb line 3 and line 9 (https://github.com/twbs/bootlint/wiki/E014) 

### Related work

https://github.com/projecthydra/sufia/pull/1698

**Comment by mjgiarlo** [comment]
@mtribone is planning to pick this ticket up. If someone else gets cycles and has the interest, do assign yourself the ticket before you start work so @mtribone knows not to duplicate your work.

**Comment by mtribone** [comment]
Code has changed for the masthead many times. Gonna close it until further evaluation
