### ISSUE TITLE
Document development practice re: .internal_test_app

### ISSUE THREAD

**Issue by atz** [projecthydra/sufia#1727]
We should have a well polished set of recommended practices for developing sufia using either a sidecar repo with bundler pulling from local dev sufia repo, or operating inside `.internal_test_app`.  Probably should go in the development section of **README**.  

Among other things, the documentation should specify rake tasks for generation or regeneration.

**Comment by mjgiarlo** [comment]
I put this on the backlog, but I'm :cool: with someone working on this before 7.0.0 goes out.

**Comment by mjgiarlo** [comment]
I believe we've now covered this in the Sufia Dev Guide. Thanks for writing this up, @atz.
