### ISSUE TITLE
UI confusion for work management

### ISSUE THREAD

**Issue by atz** [projecthydra/sufia#1734]
### Files tab
-  Random checkbox with no label or known function
- "Start Upload", "Cancel Upload" and "Delete" buttons are live, have hover effect, clickable, have "active" effect when clicked... when no files have been added.  It is a whole lot of interface for nothing.  These 3 buttons are only relevant after the list is populated.  Consider making them part of the populated list.  Since each file also has start and cancel buttons, the two "list scope" counterparts are not even usefully distinct until after a 2nd file is added! 
- Buttons are *on* the tab boundary line: give separation.
- The button that is the goal of this whole tab ("Save") is buried pretty deep.

![screen shot 2016-03-31 at 5 48 46 pm](https://cloud.githubusercontent.com/assets/109954/14194987/3aa15e3c-f769-11e5-8870-2c943fa80281.png)

### Metadata tab
- "required" label has 2 asterisks, breaks layout

![screen shot 2016-03-31 at 5 51 14 pm](https://cloud.githubusercontent.com/assets/109954/14194988/452af3a4-f769-11e5-81e9-31144571d15b.png)

**Comment by mjgiarlo** [comment]
Thanks, @atz. I've included this in the 7.0.0 release. Tagging @jcoyne and @mtribone to make sure they haven't separately identified these or started to work on them.

**Comment by jcoyne** [comment]
I think this in part is a duplicate of #1705, but that ticket was moved to backlog.

**Comment by atz** [comment]
Mostly a superset of #1705.

**Comment by mjgiarlo** [comment]
#1705 is now in scope for 7.0.0.

**Comment by jcoyne** [comment]
So the one outstanding issue you raise
> The button that is the goal of this whole tab ("Save") is buried pretty deep.

I agree, but this is what was requested by the UI working group.

**Comment by mtribone** [comment]
The files buttons came from another resource, not sure how/if they can be customized, and I definitely agree that w could make the appearance/functionality a little smarter. The save button will be on the right-hand side once I finish testing the fixed positioning, so regardless of how many files are added it won't be shoved to the bottom.

Also consider all of these as _recommendations_ and will be put to the test once people can try it out locally. Improvements are always welcome. No joke.

![screen shot 2016-04-01 at 1 43 28 pm](https://cloud.githubusercontent.com/assets/4163828/14215243/c6bda596-f80f-11e5-9cf5-5de9f7c0ee65.png)

**Comment by atz** [comment]
Checkbox removed.

Auto-upload is now default-enabled, so you shouldn't really see the per-row start buttons anymore.  Cancel button needs server-side route and more robust response from UploadsController to enable functionality, so that should probably be a separate ticket.  Drop zone indicator also ticketed separately.

Dynamic button behavior also ticketed separately.  Closing this.
