### ISSUE TITLE
Publication warning comes too late

### ISSUE THREAD

**Issue by atz** [projecthydra/sufia#1736]
When we edit a FileSet we have a detailed warning:
```
Please note, making something visible to the world (i.e. marking this as Open Access) 
may be viewed as publishing which could impact your ability to:

- Patent your work
- Publish your work in a journal

Check out SHERPA/RoMEO for more information about publisher copyright policies.
```

But we have no such warning when the FileSet is created or files added.  I.E., by the time they got to this page to perform an edit, a user may have **already** compromised their ability to patent/publish.  IMHO, the warning has to appear as early in the flow as possible to be meaningful.

**Comment by mjgiarlo** [comment]
Good idea. We may also want to make this optional, since it's IR-centric and perhaps not meaningful in the digital library collections context. Marking as an enhancement for the backlog for now.

**Comment by jcoyne** [comment]
This work is already ticketed elsewhere.

**Comment by jcoyne** [comment]
Duplicate of #1685
