### ISSUE TITLE
Cannot upload Files as Works

### ISSUE THREAD

**Issue by charitha306** [projecthydra/sufia#1744]
### Descriptive summary

Error occurs when trying to create Work.

### Steps to reproduce the behavior

1. Create new work
2. Add a title
3. Upload file
4. Click on Save

**Comment by jcoyne** [comment]
When I attempt the steps you've laid out, it works fine.  Can you tell us more about what version you are using and any error you see in the logs?

**Comment by charitha306** [comment]
I am working with the latest build and the last commit no. is 987c8ec202b717b6953271ab459d61aa2b561f9d

I added the title and uploaded a file. 
<img width="1164" alt="add_files" src="https://cloud.githubusercontent.com/assets/10963725/14223953/792b4712-f859-11e5-894f-3ec7f82a91b1.png">

And I got the following error:
<img width="1101" alt="error" src="https://cloud.githubusercontent.com/assets/10963725/14223956/8729cc26-f859-11e5-871f-9ab030eed406.png">

However when I used a previous commit reference in the Gemfile, this error didn't occur;
gem 'sufia', git: 'https://github.com/projecthydra/sufia.git', branch: 'master', ref:'9b3410e4ccf6fc9afd93db4c1745ceb3dbbd832f'

Regards,
Charitha Madurangi.

**Comment by jcoyne** [comment]
That should be fixed when this pull request has been merged https://github.com/projecthydra/sufia/pull/1743 Keep in mind that master is a *very* unstable build of sufia 7. If you want something with a bit more stability, you may want to consider sufia 6.6.

**Comment by charitha306** [comment]
Thanks for the information.
