### ISSUE TITLE
Remove buttons on dashboard

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1752]
Remove the buttons on the left side.  All this functionality is in the header:

<img width="889" alt="screen shot 2016-04-04 at 4 15 43 pm" src="https://cloud.githubusercontent.com/assets/92044/14263508/9b302dcc-fa80-11e5-9be3-26964b476da6.png">

/cc @mtribone

**Comment by mjgiarlo** [comment]
:+1: (we might even be able to remove the tabs as well?)

**Comment by mjgiarlo** [comment]
When we hear from @mtribone let's either close this or label it as ready.

**Comment by mtribone** [comment]
Yes to removing the buttons on the left-hand side. Hmmmm...I feel that having the tabs is an easy way to cycle through your stuff without moving your focus from the screen. I'm reluctant  to remove the tabs.

**Comment by jcoyne** [comment]
@mtribone I think the argument that @mjgiarlo is making, is that the functionality of the tabs duplicates the functionality of the header dropdowns.

**Comment by mtribone** [comment]
@jcoyne Yup. I understand. I feel that actions like upload and create x are good to not duplicate, but things like searching, skimming, sorting, etc. in the area of focus. are better. Users would be the best judge.

**Comment by jcoyne** [comment]
@mtribone Okay :+1:  @mjgiarlo if you want to pursue that line, please open a new ticket.

**Comment by mjgiarlo** [comment]
:+1:
