### ISSUE TITLE
Collection icon is too small on gallery view.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1763]
Or maybe the default work icon is too large.

<img width="770" alt="screen shot 2016-04-05 at 9 31 17 am" src="https://cloud.githubusercontent.com/assets/92044/14285472/4b624a1e-fb11-11e5-83dc-10c32bd7faf3.png">

**Comment by mjgiarlo** [comment]
@mtribone :arrow_up: you interested in this one when you complete your current work?

**Comment by mtribone** [comment]
@mjgiarlo You bet. Ahhh...the giant blue folder. Takes me back

**Comment by mtribone** [comment]
We should make sure that the default icon is in list view, too.

<img width="890" alt="screen shot 2016-04-06 at 3 40 39 pm" src="https://cloud.githubusercontent.com/assets/4163828/14330306/fc5c23e2-fc0d-11e5-9ce2-15291c7363ce.png">

**Comment by mtribone** [comment]
Is this a good size?

<img width="875" alt="screen shot 2016-04-06 at 3 45 06 pm" src="https://cloud.githubusercontent.com/assets/4163828/14330454/9d1ff7a4-fc0e-11e5-86aa-e0f98b7c92c5.png">

**Comment by jcoyne** [comment]
This works for me. I just wanted to see parity.

**Comment by mjgiarlo** [comment]
:clap:
