### ISSUE TITLE
Create a factory method for the ActorStack

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1776]
that can be shared between BatchCreateJob and WorksControllerBehavior

Similar to `CurationConcerns::CurationConcern.actor()` https://github.com/projecthydra-labs/curation_concerns/blob/8e467913b98fb265817179ee47df39a25be4d060/app/services/curation_concerns/curation_concern.rb#L4

**Comment by mjgiarlo** [comment]
Could be for backlog or 7.1.0?

**Comment by jcoyne** [comment]
Yes, moved to 7.1.0
