### ISSUE TITLE
Add logs/status for batch and item level operations

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1779]
For BatchCreate there should be a log that shows the overall status ('processing', 'failed',  'success'). There should also be logs for each item (create work operations in this case). 

Perhaps something like this: https://github.com/curationexperts/tufts_models/blob/master/app/models/batch.rb (but do not serialize fields as it introduces race conditions).

**Comment by awead** [comment]
Possibly related to https://github.com/psu-stewardship/scholarsphere/issues/373 where we need to know when a single work is finished processing.
