### ISSUE TITLE
Remove PSU-isms

### ISSUE THREAD

**Issue by cbeer** [projecthydra/sufia#1784]
- [ ] https://github.com/projecthydra/sufia/blob/43a3271050de6db0bec82847882bf9d88640e3ad/app/views/curation_concerns/file_sets/_groups_description.html.erb

**Comment by mjgiarlo** [comment]
Heads-up re: these changes, @hectorcorrea @mtribone @cam156 @awead

**Comment by cam156** [comment]
@mjgiarlo Looks like we made it easy to override, just never remove the PSU text.  Thanks for the heads up.  This starts an interesting discussion...  It's mostly text, so it could go in an I18N file, but there is some HTML, so it should stay in the view?  What thoughts do people have?

**Comment by jcoyne** [comment]
@cam156 you could keep that partial have it calls a translation. For PSU you could keep the file override with all it's links and not use the translation at all.

**Comment by jcoyne** [comment]
Kick this to 7.1.0?

**Comment by kerchner** [comment]
I notice that `spec/fixtures/*_fits.xml` files all have references in their `<filepath>` tags to @mjgiarlo specific paths, such as `/home/mjg/workspace` etc. (and in at least one case a @jeremyf path - `/Users/jfriesen/Repositories`).  This may (or may not) be worth a look as part of the cleanup of PSU-isms.
