### ISSUE TITLE
Relocate curation concerns CSS to separate file

### ISSUE THREAD

**Issue by atz** [projecthydra/sufia#1785]
Something like `sufia/curation_concerns.scss`.  See #1781 for discussion.

**Comment by mjgiarlo** [comment]
@cbeer knows he wants to pick this one up.

**Comment by cbeer** [comment]
Not it.

**Comment by jcoyne** [comment]
:-1: to this. As a developer I don't want to look in `_file_sets.scss` *and* have to look in `_curation_concerns.scss`.  We've already determined to make a clean break with curation_concerns UI, lets keep going with that.

**Comment by cbeer** [comment]
Wait.. so we'd rather duplicate any and all css from curation concerns, and continuously reimplement any upstream changes, than try to share?

**Comment by jcoyne** [comment]
I think there is _very_ little we need to duplicate.  Presently only that visibility control, but I suspect the UI WG would want that to look like the visibility control in the form-progress widget.

**Comment by mjgiarlo** [comment]
@cbeer @jcoyne I'm moving this to the backlog for now.

**Comment by mjgiarlo** [comment]
There was never consensus on this issue, and we've now got Hyrax. Closing this issue. More analysis and related work can happen in Hyrax.
