### ISSUE TITLE
Replace Custom Collection Image

### ISSUE THREAD

**Issue by mtribone** [projecthydra/sufia#1790]
### Descriptive summary

Replace the custom collection image from the collection show page and list view with the default glyphicon.

### Related work

Refs #1763

<img width="1239" alt="screen shot 2016-04-07 at 9 28 20 am" src="https://cloud.githubusercontent.com/assets/4163828/14352696/c749a486-fca3-11e5-98ef-30848e445cc6.png">

<img width="890" alt="screen shot 2016-04-06 at 3 40 39 pm" src="https://cloud.githubusercontent.com/assets/4163828/14352700/d1ae0de0-fca3-11e5-9c5f-6eb35c149d1f.png">

**Comment by atz** [comment]
Which default glyphicon exactly?

**Comment by atz** [comment]
Might also prefer: `fa-list`, `fa-list-alt`, or my preferred choice `fa-object-group`.  

http://fortawesome.github.io/Font-Awesome/icon/object-group/

**Comment by mjgiarlo** [comment]
Any of these are fine by me.

Preferences, @mtribone @aeschylus @geisler?

**Comment by mtribone** [comment]
@atz It would be nice if it matched the icon in the toolbar.

**Comment by mtribone** [comment]
@atz Are you working on this one? If not, I'll grab it.

**Comment by mjgiarlo** [comment]
Have at it, @mtribone. The issue is currently unassigned.

**Comment by mtribone** [comment]
Search results with Collection icon

<img width="1119" alt="screen shot 2016-04-11 at 12 47 17 pm" src="https://cloud.githubusercontent.com/assets/4163828/14434973/9e9c2a84-ffe3-11e5-8826-a7bc12199f2f.png">

**Comment by mtribone** [comment]
Collection view or show page with default icon

<img width="1123" alt="screen shot 2016-04-11 at 12 46 25 pm" src="https://cloud.githubusercontent.com/assets/4163828/14435002/ba31d582-ffe3-11e5-8b27-c9a17e376f1d.png">

**Comment by mtribone** [comment]
My Collection listing with default collection icon

<img width="1123" alt="screen shot 2016-04-11 at 12 46 08 pm" src="https://cloud.githubusercontent.com/assets/4163828/14435027/d7384990-ffe3-11e5-8ff9-252ea49be2ab.png">

**Comment by mjgiarlo** [comment]
Looks good! :+1: 

Any thoughts on this, @atz @aeschylus @ggeisler @cbeer @jcoyne?
