### ISSUE TITLE
Batch upload form should let you set a resource type per uploaded file

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1796]
Ref https://github.com/projecthydra/sufia/issues/1674

Similar to #1773

https://wiki.duraspace.org/display/hydra/Batch+New+Works+-+Phase+1+-+UI+Wireframes#mockup_p1-works-batch_new-step1_upload_files

**Comment by mjgiarlo** [comment]
Do you have a ticket, @hectorcorrea? This one could be a good fit.
