### ISSUE TITLE
WorkSearchBuilder cannot be assigned a current_ability

### ISSUE THREAD

**Issue by barmintor** [projecthydra/sufia#1808]
### Descriptive summary
When attempting to view a GenericWork:

undefined method `current_ability=' for #<CurationConcerns::WorkSearchBuilder:0x007fb862f31ef8>
in the generated curation_concerns/generic_works_controller.rb

curation_concerns (0.12.0.pre4)
sufia (7.0.0.beta1)

### Expected behavior
WorkSearchBuilder can be assigned a current_ability
The class is deprecated in CurationConcerns, so I'm filing here.

### Actual behavior

See above.

**Comment by jcoyne** [comment]
What does the code to your `app/models/search_builder.rb` look like?

It ought to be like this:
```ruby
# frozen_string_literal: true
class SearchBuilder < Blacklight::SearchBuilder
  include Blacklight::Solr::SearchBuilderBehavior
  include Hydra::AccessControlsEnforcement
  include CurationConcerns::SearchFilters

end
```

**Comment by jcoyne** [comment]
I'm also not clear where you see that WorkSearchBuilder is deprecated.  I'm not seeing that.

**Comment by barmintor** [comment]
CurationConcerns::WorkSearchBuilder's base class, CurationConcerns::SearchBuilder, is deprecated.

**Comment by barmintor** [comment]
Updated with controller name.

**Comment by jcoyne** [comment]
@barmintor 
`CurationConcerns::WorkSearchBuilder`'s base class is now `::SearchBuilder`, not `CurationConcerns::SearchBuilder`
https://github.com/projecthydra-labs/curation_concerns/blob/master/app/search_builders/curation_concerns/work_search_builder.rb#L2

**Comment by barmintor** [comment]
@jcoyne ok, if that change was in pre4, I guess I should move this issue to CurationConcerns

**Comment by barmintor** [comment]
For some reason the installer didn't inject the appropriate includes into the generated search_bulder.rb, and I didn't grok that the curation_concerns search_builder inherited from my generated one.
