### ISSUE TITLE
Searching the extracted text from an uploaded file

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1813]
### Descriptive summary

Given I have a pdf with some extracted text
When I search for that text in a catalog search
Then I should see a result containing that pdf

### Details

Extracted text from a pdf or other text-based document is indexed in a FileSet object, yet these are not returned in searches. In order to search for this content, we'd either need to copy the content to the work level where it can be searched, or open up searching of FileSets, and either return the FileSets in the index view, or the GenericWorks to which they are attached.

**Comment by mjgiarlo** [comment]
For now, I lean towards indexing this information in the GenericWork.

**Comment by awead** [comment]
Yeah. This is the pattern for characterization metadata as well, yes?

**Comment by jcoyne** [comment]
@mjgiarlo So, you want to concatenate the full-text of *all* the attached files onto the GenericWork?

**Comment by mjgiarlo** [comment]
I don't *love* that as a solution; that was me with my expediency hat on. ;)

Ideally, I'd like FileSet metadata (incl. full-text) to be discoverable in a way that shows FSes as subordinate to GWs. In other words, surface FSes more in the UI but not outside of their GW context.

**Comment by awead** [comment]
Maybe we ought to think of this from a more UI point-of-view. I'm recalling a lot of conversations I've had with archivists, when it comes to synecdoche, where a part of something, i.e. the FileSet, is supposed to be representing the whole, i.e. the Work. Or, where a sub-unit of a collection is relevant to a search, but you want the top-level collection to be the unit returned in a search.

If the FileSets are to be displayable, that is, if they have the equivalent of a show view--which I think at this point they do--then it seems entirely plausible to have the FileSet as a searchable unit just like the GenericWork is.

What I'm visualizing is how the search results look like. I can see an index display from the catalog search that indicates subordinate FileSet objects in a Work. How that's executed, I have no idea, but maybe let's start with what we'd like to see and go from there.

To @mjgiarlo's point, yeah, concatenating them isn't a great solution, but it's easy. And, for us a Penn State where we have only one-file Works, it's a good solution for us right now. It only gets dicey when you start having multi-file works.

**Comment by mjgiarlo** [comment]
Agree in full, @awead
