### ISSUE TITLE
File upload limits declared but unused

### ISSUE THREAD

**Issue by atz** [projecthydra/sufia#1814]
We declare things like:
```javascript
//200 MB max file size
var max_file_size = 200000000;
var max_file_size_str = "200 MB";
//500 MB max total upload size
var max_total_file_size = 500000000;
var max_total_file_size_str = "500 MB";
var max_file_count = 100;
```

But these aren't actually used by the jQuery UI widget, or anything else.  

For robust file handling and avoidance of OOM/resource depletion, we need: 

- server side limits and proper handling there, e.g. in [CarrierWave](http://www.rubydoc.info/github/jnicklas/carrierwave/CarrierWave/Uploader/FileSize)
- should be configurable
- client side limits **actually used**
- client limits should take their values from (or be derived from) the server side ones.  

Alternatively, we can just be open to anybody crashing our processes with multi-TB web uploads and delete the js declarations.

**Comment by mjgiarlo** [comment]
Here's what we have in Sufia 6.x: https://github.com/projecthydra/sufia/blob/6.x-stable/app/assets/javascripts/sufia/uploader.js#L57-L84

**Comment by jcoyne** [comment]
While it's not perfect right now, keep in mind that anyone who is doing this maliciously has already logged in. Presumably, we can swing by their office and wack them with the clue stick.

**Comment by atz** [comment]
Once I add `jquery.fileupload-validate.js` and set the limits arbitrarily low, like:
```javascript
 maxNumberOfFiles: 2,
 maxFileSize: 1000, // bytes
```

I get:

![screen shot 2016-04-11 at 2 16 54 pm](https://cloud.githubusercontent.com/assets/109954/14442744/4cd149b6-fff0-11e5-9a67-0208a0fb7858.png)

So that is a step up in capabilities.

**Comment by mjgiarlo** [comment]
:shipit: ;)

**Comment by mjgiarlo** [comment]
@atz Are you inclined to keep working on the non-client-side portions of this ticket, or do you think we can punt that to a subsequent release (since we've never had server-side validation of upload limits)?

**Comment by mjgiarlo** [comment]
Closing this ticket. We now have #1827 scheduled for 7.1.0.
