### ISSUE TITLE
CC generator fails to create initializer

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1818]
### Descriptive summary

Running the CC generator within an existing application fails to create `config/initializers/curation_concerns.rb`.

### Expected behavior

Command should create `config/initializers/curation_concerns.rb`

### Actual behavior

Fails with:

```bash
insert  config/initializers/curation_concerns.rb
/Users/awead/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `binread': No such file or directory @ rb_sysopen - /Users/awead/Projects/Github/psu-stewardship/scholarsphere/config/initializers/curation_concerns.rb (Errno::ENOENT)
	from /Users/awead/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `replace!'
	from /Users/awead/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:59:in `invoke!'
	from /Users/awead/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
	from /Users/awead/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:30:in `insert_into_file'
	from /Users/awead/.gem/ruby/2.3.0/gems/curation_concerns-0.12.0.pre4/lib/generators/curation_concerns/work/work_generator.rb:66:in `register_work'
	from /Users/awead/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/awead/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/awead/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/awead/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/awead/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/awead/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/awead/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/awead/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/awead/.gem/ruby/2.3.0/gems/railties-4.2.6/lib/rails/generators.rb:157:in `invoke'
	from /Users/awead/.gem/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /Users/awead/.gem/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/awead/.gem/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/awead/.gem/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/awead/.gem/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/awead/.gem/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /Users/awead/.gem/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
	from /Users/awead/.gem/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /Users/awead/.gem/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/awead/.gem/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:5:in `require'
	from bin/rails:5:in `<main>'
```

### Steps to reproduce the behavior

I was using an existing

1. `cd .internal_test_app`
1. `rm config/initializers/curation_concerns.rb`
1. `rails g curation_concerns:work GenericWork`

**Comment by cbeer** [comment]
Is it really appropriate to expect `curation_concerns:work` to function without running the install generator first (which I assume is what creates the initializer)? Or does it just need better error handling?

(And, should this ticket be upstream in curation_concerns?)

**Comment by awead** [comment]
I'm just reporting the issue. In order to migration from 6.x to 7.x, you need that file, and the generator doesn't create it. The command gets run as part of the engine_cart process, so I assumed that replicating that pattern in order to migrate would be a good starting point.

**Comment by jcoyne** [comment]
@awead did you ever try running `rails g curation_concerns:install`? That should crate the file.

**Comment by awead** [comment]
@jcoyne it appears not to. I ran it within .internal_test_app and didn't see it.

**Comment by jcoyne** [comment]
Can you paste the output from running `rails g curation_concerns:install` here or in a gist?

**Comment by awead** [comment]
https://gist.github.com/awead/682b86a2649b7c26153d96eb9d9654e5

**Comment by jcoyne** [comment]
@awead it looks like the generator is bailing out here: https://gist.github.com/awead/682b86a2649b7c26153d96eb9d9654e5#file-gistfile1-txt-L502

**Comment by hackmastera** [comment]
Question outstanding: is `rails g curation_concerns:install` intended to create `config/initializers/creation_concerns.rb`? Because it fails to do this. But I believe @awead told me config values from this initializer have been integrated into the sufia initializer. So maybe it's not necessary.

Regarding the route errors, I'm able to get rid of them if I delete all devise, root, and blacklight routes from my config/routes.rb before running the install. This begs another question: Is our intended upgrade path "run the sufia install generator over your existing sufia app, then look through diffs"? If so, we need to either tell people to delete these routes first (and yes you have to delete them not comment them out) or we need to make all these installers check before writing to config/routes.rb.

**Comment by jcoyne** [comment]
I think this should be closed. You should not be running `curation_concerns:install` if you want a Sufia application.
