### ISSUE TITLE
Redirecting on access denied errors

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1829]
Sufia 6 has functionality that redirects on specific errors:

https://github.com/projecthydra/sufia/blob/6.x-stable/app/controllers/concerns/sufia/files_controller_behavior.rb#L26-36

It seems this is missing from GenericWork in Sufia 7 and CurationConcerns. There's an identical bit in CC, from the recent Hydra::Collections merge:

https://github.com/projecthydra-labs/curation_concerns/blob/master/app/controllers/concerns/curation_concerns/collections_controller_behavior.rb#L19-29

Currently, Sufia will just a return a 401 if it's unauthorized access. We could leave it that way, and let the implementor decide, or add this behavior back in, probably at the CC level, but perhaps more consciously throughout all the controllers?

**Comment by awead** [comment]
Personally, I think I prefer just returning the 401, or whatever the error is, since the old way of redirecting is actually 302, which masks what's really going on.

**Comment by mjgiarlo** [comment]
I'd like to hear from the CC folks on this one, too. Tagging @escowles @tpendragon @jpstroop

**Comment by cbeer** [comment]
I'd prefer letting the upstream application provide appropriate error handling.

**Comment by jpstroop** [comment]
I tend to agree w/ @cbeer & @awead (I believe you're saying the same thing??). A nice 4xx (i.e. with an appropriate alert message) is better for everyone than a 302 -> 200.

**Comment by awead** [comment]
I agree that the 401 is better, but current Sufia 6 adopters should be made aware of the change and (ideally) given tools to reinstate the previous method of redirects if they want to continue using them.

**Comment by escowles** [comment]
+1 to sending 401 and making it easy to revert to the old behavior, or customize to something completely different.  Do we want to have two error-handling modules: one for the Sufia 6/Collections behavior, and a second for displaying an error page?

**Comment by mjgiarlo** [comment]
:+1: to using the 401 and styling the page so users understand what it means.

I agree with @awead that
> Sufia 6 adopters should be made aware of the change
But I have reservations about spending cycles on tooling to reinstate error handling behavior. I have never heard anyone say, "I love the way Sufia 6 redirects when there are errors."

**Comment by awead** [comment]
@mjgiarlo true. But, https://www.youtube.com/watch?v=i28UEoLXVFQ

**Comment by jpstroop** [comment]
:cry:

**Comment by escowles** [comment]
I haven't heard anybody say that either, but on the other hand, I expect people to upgrade from Sufia 6 to 7, and possibly want to revert to the old behavior.

Maybe it's better to implement the new behavior, but add a comment with the old behavior, so it's clear how to revert if people want to do that locally?

**Comment by jeremyf** [comment]
:+1: for 401 instead of 302.

**Comment by awead** [comment]
@escowles yeah, something in the release notes, or "What's New" might be fine.

**Comment by mjgiarlo** [comment]
:+1: for including a blurb in the release notes. Also :+1: to not spending more than 10 minutes on that. ;)
