### ISSUE TITLE
Inline HTML cannot also use markdown: some README links broken

### ISSUE THREAD

**Issue by atz** [projecthydra/sufia#1830]
We are trying to use markdown inside inline-HTML (inside markdown).  Specifically, see the `Terminology` definition list.  We should pick one format and use it.  If HTML is really needed, it should be broken out of our mega-README and into its own semantically coherent HTML.

Other links are possibly just badly written, like `[[http:link.to.place]]`, using double brackets.

**Comment by mjgiarlo** [comment]
@atz You've diagnosed the problem admirably -- would you also list the broken links here so the person who picks up this ticket knows where to apply the suggested fixes?

**Comment by cbeer** [comment]
Or... just fix it?

**Comment by mjgiarlo** [comment]
Yes, or just fix it. :smiley:

**Comment by atz** [comment]
@mjgiarlo: Do you want the Terminology broken out as a separate HTML file?

**Comment by mjgiarlo** [comment]
Meh. I don't think we need the definition list structure badly enough to warrant breaking this apart. Best to keep the whole README as markdown for now.

**Comment by atz** [comment]
OK, will attempt to convert.  Note: there is no definition-list in markdown.
