### ISSUE TITLE
jquery-ui upload buttons dynamic behavior

### ISSUE THREAD

**Issue by atz** [projecthydra/sufia#1831]
Split from #1734.  

"Start Upload", "Cancel Upload" and "Delete" buttons are live, have hover effect, clickable, have "active" effect when clicked... when no files have been added. It is a whole lot of interface for nothing. These 3 buttons are only relevant after the list is populated. (Consider making them part of the populated list, make their visibility dependent on the list being populated or disable them until the list is populated.) Since each file also has start and cancel buttons, the two "list scope" counterparts are not even usefully distinct until after a **2nd file** is added!

How is `Cancel` different than `Delete`?  Neither actually touch the server side.

**Comment by jcoyne** [comment]
My intention was to remove most of these buttons to match the wireframe after the auto upload was enabled

**Comment by jcoyne** [comment]
Delete actually posts back to the server, there's a ticket for enabling that in the backlog somewhere

**Comment by atz** [comment]
Yeah, it posts, but it is a no-op.  Nothing is deleted AFAICT.

**Comment by jcoyne** [comment]
But when #1793 is fixed, it will.

**Comment by mjgiarlo** [comment]
It would be good to enable per-file cancel (or delete if you think that's more correct) given uploads fire off immediately now. And i suspect the top row of buttons can lose delete and possibly cancel. Cancel could trigger a cancel/delete on each file if a user wants to delete all files tossed up.



On Tue, Apr 12, 2016 at 7:29 PM -0700, "Joe Atzberger" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah, it posts, but it is a no-op. Nothing is deleted AFAICT.

-

**Comment by atz** [comment]
The longer term direction is to make many of the jquery-fileupload constraints easily configurable (ala HyBox).  Even with the defaults, it is still possible to drop 100 files at ~500 MB each and have them spool off with 6 uploads at a time.  I.E., the 99th item might be removed from the list before it's turn comes around.  Similarly, the whole list might be aborted before it progresses past the first round.  

We should not unilaterally remove pieces that a user might expect to be there for a given valid configuration of the widget.  That is to say, we should make certain behaviors dependent on the widget configuration and state.  Autoupload might reasonably be configured **off**.

**Comment by jcoyne** [comment]
According to the directions of the UI working group, autoupload is the prescribed behavior.  It is not something that is configurable.

**Comment by atz** [comment]
Whether it is configurable or not is not something a UI Working Group is empowered to decide.

**Comment by jcoyne** [comment]
I thought this sprint was about implementing the wireframes and suggestions of the UI working group.  They have made several suggestions about things that should be configurable, and this was not among them. Why do you want to make it configurable?  I'm not saying that it shouldn't be, but that it would require some effort and I'm not sure why it would be a priority.

**Comment by atz** [comment]
This constraint directly affects resource consumption in I/O, number of concurrent connections and GBs of memory/storage required.  If HyBox wants to support installations with varying resource constraints (which, as I understand it, is a core component of our mission), I don't see how configurability here is optional.  Resources will not be the same between installations.  

It's fine to push some of that out of scope for this sprint, but I don't see why we would intentionally build work for ourselves to back out later.

Lastly, when we build in the server-side constraints, the jquery widget will receive its settings from those.  It makes no sense to build the UI to break for a valid set of constraints.

**Comment by jcoyne** [comment]
> I don't see how configurability here is optional. 

Can't we just make the default constraints tight enough to be supported on the minimal hardware recommendation? The web upload is not going to be the primary ingest mechanism for people who are using very large objects anyway.  They're going to need to go to a local-file ingest via BrowseEverything or a CLI.

**Comment by mjgiarlo** [comment]
@jcoyne @atz 

Given that we already have https://github.com/projecthydra/sufia/issues/1793 for enabling deletion of uploaded files, which I've just taken the liberty of including in the 7.0.0 scope, here's my proposal:

1. Remove `Start Upload` button -- it doesn't do anything
1. Hide `Cancel Upload` button (and let re-enabling it **after files are added** be part of #1793, where the cancellation effect triggers a delete/cleanup on the back-end)
1. Hide per-file `Cancel` buttons (and let re-enabling these be part of #1793, where the cancellation effect triggers a delete/cleanup on the back-end)
1. Hide `Delete` button altogether
1. Punt configuration until we understand those needs better (write that up as a separate ticket for 7.1.0 or the backlog if someone wants it)

Good for now?
