### ISSUE TITLE
Batch upload async error

### ISSUE THREAD

**Issue by atz** [projecthydra/sufia#1832]
I used batch upload to post 2 files.  I waited and shortly thereafter received a notification via [/notifications](http://localhost:3000/notifications) :
```
Failing batch create  -- The batch create for x@y.com failed
```

This ticket has two parts:
- [ ] batch create shouldn't fail
- [ ] when it does, the error message should be more informative

**Comment by mjgiarlo** [comment]
If someone other than @atz could pick this up and try to reproduce it, that'd be a great start.

**Comment by jcoyne** [comment]
It isn't failing for me. Is there anything in the rails log when this happens? Can you reproduce it dependably? 
<img width="958" alt="screen shot 2016-04-13 at 11 01 35 pm" src="https://cloud.githubusercontent.com/assets/92044/14516748/bc481b9e-01cb-11e6-8d92-ae5d8f277235.png">

**Comment by atz** [comment]
Was dependable on Tuesday.  Will try it again tomorrow.

**Comment by atz** [comment]
Still failing in the same way.

**Comment by atz** [comment]
Hrm, on a subsequent attempt, passed.  Interesting.

**Comment by atz** [comment]
Well, if we check the first box and say "it isn't failing right now!", we still need a more informative message for when it does fail.

**Comment by atz** [comment]
We can close this, or at least backlog it.  Not really a release blocker anymore.

**Comment by mjgiarlo** [comment]
Closing per @atz's recommendation. We can re-open if we repro it later.
