### ISSUE TITLE
Update Run the test suite section of README for Sufia 7

### ISSUE THREAD

**Issue by elrayle** [projecthydra/sufia#1834]
### Descriptive summary

The 'Run the test suite' section of README is not inline with Sufia 7.

**Comment by mjgiarlo** [comment]
From another thread, @elrayle suggested the following changes:

```markdown
## Run the test suite

### Prerequisites
* Make sure all [basic prerequisites](https://github.com/projecthydra/sufia#prerequisites) are running.
* Additional prerequisite for tests: [PhantomJS](http://phantomjs.org/), version 1.9.x (NOTE: 2.1.1 has also been confirmed to work.)

### Test app
Generate the test app.  *NOTE: Run this only once.*
```
rake engine_cart:generate
```

This generates `sufia/.internal_test_app` directory.  The tests will run against this test app.

### Run tests
```
rake spec
```

### Testing FAQ
* Where is rake jetty?  It was retired.  Solr and Fedora are started on their own.
* How can I start a test instance of Solr?  **DO NOT USE FOR PRODUCTION**
```
# from sufia root in a separate terminal window
solr_wrapper -d solr/config/ --collection_name hydra-development
```
  * Test that Solr is running at: [[http://localhost:8983/]] 
  * Solr Core name:  hydra-development
* How can I start a test instance of Fedora?  **DO NOT USE FOR PRODUCTION**
```
# from sufia root in a separate terminal window
fcrepo_wrapper -p 8984
```
  * Test that Fedora is running at: [[http://localhost:8984/]] 
* The generated test app isn't doing what I expected after making changes to Sufia.  What can I do?  Generally, engine cart will pick up changes to Sufia.  If not, try the following to regenerate the test app.
```
rake engine_cart:clean
rake engine_cart:generate
```
```

**Comment by mjgiarlo** [comment]
And:

> I would also recommend removing solr_wrapper and fedora_wrapper commands from Start Solr and Start FCRepo sections. You could point them to the Run the test suite section if they want to experiment with Sufia. And this will avoid the risk of having the command different in two parts of the doc. In Start Solr and Start FCRepo, the recommendation would be to use production approaches for starting Solr and Fedora.

**Comment by mjgiarlo** [comment]
@elrayle I don't think we should remove the "Start Solr" and "Start FCRepo" sections above, because the test and development invocations are different -- they use different ports.

**Comment by mjgiarlo** [comment]
Fixed in https://github.com/projecthydra/sufia/commit/1a633d162e0dc1b6b66a3dc03d6bee7667d9d760
