### ISSUE TITLE
Search and discovery of file set metdata

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1836]
### Descriptive summary

Certain metadata, for example the term `format_label`, that was previously defined on the GenericFile in Sufia 6, has now been moved to the file set. Consequently, when searching for something via that metadata, it won't show up unless file sets are exposed in the search results or the metadata from the file set is also indexed in the work.
### Expected behavior

Unknown. **Needs discussion**
### Actual behavior

When searching for resources based on their `format_label`, there are no results.
### Related work
#1813

**Comment by cam156** [comment]
@awead Can we close this ticket?  We have file format in the facets.
