### ISSUE TITLE
Logging events with ContentEventJob

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1841]
`ContentEventJob` implies that only file set objects can have events logged via the `log_event` method, but in fact works can as well. It would make it clearer if the variable wasn't `file_set` and was something not tied to the model.

This is also meant to confirm that both FileSet and GenericWork classes can have events logged to them.

Blocks #1437

**Comment by mjgiarlo** [comment]
@awead I suspect this is a dup of #1437. Can you verify that and, if so, close this issue?

**Comment by awead** [comment]
That ticket doesn't mention ContentEventJob specifically, which is both works and file sets.

**Comment by awead** [comment]
This is just to clarify ContentEventJob. It accepts either Work or FileSet.
