### ISSUE TITLE
"-Remove" function for repeatable fields only let you remove the input box you alredy filled

### ISSUE THREAD

**Issue by simosacchi** [projecthydra/sufia#1847]
### Descriptive summary

When adding a new input box for a repeatable field after filling a first value you are presented with a "remove" button that allow you only to remove the input box you filled in the first place, not the new one you added. I do not know if this is the expected behavior, and while I believe there a no consequences if you just leave the new field empty and move forward, this seems like an odd behavior.

### Expected behavior

When adding a new input box for repeatable field you shall be able to remove the new one and/or the one already filled, not only the one you filled in the first place.

### Steps to reproduce the behavior

1. Create a work
2. Fill in a title
3. Click "+add" beside the input box

### Screenshot here

<img width="626" alt="screen shot 2016-04-14 at 2 28 15 pm" src="https://cloud.githubusercontent.com/assets/6808470/14539147/2582c09c-024d-11e6-93fa-067e564654fb.png">

**Comment by mjgiarlo** [comment]
@simosacchi The change you're suggesting here is that the bottom-most row always has both remove and add buttons? (Unless there's only one row, the default case for new forms, in which case only an add button makes sense?)

Tagging @mtribone @aeschylus @ggeisler @jcoyne @elrayle @hackmastera @sfbetz @dt-ucsd @newmanld for their impressions.

**Comment by mjgiarlo** [comment]
For now I'm marking this as "needs feedback" and tossing it on the backlog, but I'll re-label and re-milestone this after a few folks have shared their impressions.

**Comment by simosacchi** [comment]
@mjgiarlo your suggestion makes sense for me. 

The oddity was mostly that if you fill the first input box and click "+add" and you want to roll back, there is no way for you other than deleting the input box you filled in the first place and add the info again.

**Comment by cbeer** [comment]
This appears fixed, at least in master:

![screen shot 2016-08-25 at 9 39 27 am](https://cloud.githubusercontent.com/assets/111218/17977762/daf3526c-6aa7-11e6-952c-651945fdaf2b.png)
