### ISSUE TITLE
Deleting a fileset redirects to a non-existent page

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1852]
When I'm on a work show page and I click the delete button on an attached file, I get a 404 page:

From the log:
```
Redirected to http://localhost:3000/concern/generic_works/jd472w527
Completed 302 Found in 809ms (ActiveRecord: 0.9ms)
```

Once you do this, it is impossible to view the work show page.

**Comment by atz** [comment]
So it redirects to the page of the thing it just deleted?

**Comment by jcoyne** [comment]
No, it is redirecting to a page, that is attempting to load a deleted thing onto it.

**Comment by hectorcorrea** [comment]
This was tricky. The problem was that when the `FileSet` was deleted the `GenericWork` still pointed to it via the `GenericWork.thumbnail` and `GenericWork.representative` properties.

**Comment by hectorcorrea** [comment]
Fixed with CurationConcerns PR https://github.com/projecthydra-labs/curation_concerns/pull/732

**Comment by mjgiarlo** [comment]
@hectorcorrea says this has been fixed in CC, so I'm closing this ticket. :clap:
