### ISSUE TITLE
Work show page -- add padding on right column

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1853]
Add padding atop right-hand content (action buttons, last saved, representative media, sharethis widget, citations) -- top of the "edit" button should align with creator values if creator values present, otherwise align with description

**Comment by atz** [comment]
Will need to be specified differently because:

- There is no guarantee `creator` or `description` will be populated.  
- There is no guarantee *any* metadata will be displayed at all. 
- We are guaranteed a "Metadata" header.  That is about all.

**Comment by mjgiarlo** [comment]
@atz Good observations. You can see the desired behavior in a series of variant wireframes here:

https://wiki.duraspace.org/pages/viewpage.action?pageId=75104524

The specification, given what you point out, is more like "Align the top of the right widget (Edit button if present, last saved date, rep. media/thumbnail, etc.) with the bottom of the vertical space directly beneath the title block."

**Comment by mjgiarlo** [comment]
Actually, meh. I'm marking this a `#wontfix`.
