### ISSUE TITLE
Work show page -- wrap long titles

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1859]
### Descriptive summary

Make sure super-long titles wrap appropriately. See "long title variant" wireframe under "Expected UI" section below.

Pertains to Sufia master.

### Current UI

![](https://cloud.githubusercontent.com/assets/92044/14536835/fd5654ca-0239-11e6-819c-a528278a59d2.png)

### Expected UI

https://wiki.duraspace.org/x/DAF6B

### Related work

Refs #1722, #1843

**Comment by atz** [comment]
Save a click:
![image](https://cloud.githubusercontent.com/assets/109954/14549164/52f6cc1a-0272-11e6-91b7-a58835378721.png)

**Comment by atz** [comment]
OK, I think that does it for the title:
![screen shot 2016-04-14 at 7 28 15 pm](https://cloud.githubusercontent.com/assets/109954/14549705/1acbd182-0277-11e6-8577-05d25eb41e4c.png)

**Comment by atz** [comment]
Unintentionally pushed this to master directly.  Not expecting it to be controversial, but please review it as normal.
