### ISSUE TITLE
Work show page -- re-label text if no relationships exist

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1861]
### Descriptive summary

Change "no relationships" text to "No relationships to collections, works, or external resources." in the relationships section

Pertains to Sufia master.

### Current UI

![](https://cloud.githubusercontent.com/assets/92044/14536835/fd5654ca-0239-11e6-819c-a528278a59d2.png)

### Expected UI

https://wiki.duraspace.org/x/DAF6B

### Related work

Refs #1722, #1843

**Comment by jcoyne** [comment]
I don't think we should do this, at least not right now, as there is yet no way to add external resources or nest one work in another.  The text is already in i18n, so it will be easy to change when the time comes. I recommend we move this to the backlog.

**Comment by mjgiarlo** [comment]
done
