### ISSUE TITLE
Red badges for Notifications should bubble up to Dashboard

### ISSUE THREAD

**Issue by atz** [projecthydra/sufia#1866]
The point of the red badge number is to alert users to unread notifications.  For this feature, the front end constantly polls the server/DB.  So it doesn't make sense that the moment of notification (i.e., the badge displaying a number) is hidden under the "Dashboard" drop-down.  

The user should be alerted to the emergence of pending notifications at the topmost layer of the interface (without any menus or modals open).  Probably the top bar elements should aggregate the alerts from their drop-down children.  In practice, that means "Dashboard" should show "Notifications" alerts.  (I'm unaware of any other dynamic alerts.)

**Comment by cbeer** [comment]
I'd agree, although that's not the design the UI working group suggested.

**Comment by atz** [comment]
If they want to do away with that feature, fine.  But keeping the cost without delivering the benefit is unwise.

**Comment by mjgiarlo** [comment]
I'm cool with this change. Rather than implementing a general way for top-level elements to aggregate contained elements, it'd be fine to have the Dashboard element surface the Notifications badge for the 7.0.0 release, methinks.

**Comment by atz** [comment]
Ok, UI decision time.  I think we want the number badge to be invisible when there is nothing to notify.  That makes it's placement weird:

![screen shot 2016-04-21 at 5 13 07 pm](https://cloud.githubusercontent.com/assets/109954/14727886/65f083e8-07e4-11e6-9195-e792c1f2ebf0.png)

Are we OK with the unhiding shifting the whole top bar to the right?  (seems to violate the soothing reliable layout of the bar.)  If not then we need to either: 
- preallocate the badge's space or 
- overlay it (on top of the tach or the caret, for example).  

Preallocating space potentially means an otherwise useless separation between elements, so the middle positions (between tach and "Dashboard", between "Dashboard" and caret) don't work.  Preallocated space would have to go all the way to the right or left.  Both seem semantically weak.

I'm leaning towards on top or in place of the tach.  Thoughts?

**Comment by mjgiarlo** [comment]
@atz :+1: to overlaying on the tach. Don't care if it's on top or in place of -- whichever is easiest and isn't totally fugly?

Tagging @mtribone and @ggeisler for their UI-y sensibilities, though...

Thank you for the thorough analysis.

**Comment by ggeisler** [comment]
Just going by the screenshot in @atz's comment, it doesn't look like you could put it above the tach without increasing the vertical height of the menu area, which I assume we would like to avoid. So, I suppose overlaying it would be the way to go. I'd play around with it to see if you can only partially overlay it, so it doesn't look like the badge replaces the icon. 

So maybe overlay it, but try to nudge it above the icon a bit so the lower part of the icon is still visible?

Not positive - this is the kind of thing I'd just play around with in the code until I found something that feels right.

**Comment by mtribone** [comment]
I'm with @ggeisler on this one. I'd like to see it overlay the icon and have a bit of the tach peek out. We'll need to balance size and legibility.

**Comment by cbeer** [comment]
Do we need the full number badge, or maybe just a gentle indication like github uses (or, just light up the tach icon?)

**Comment by mtribone** [comment]
Perhaps above and between the word and the tach?

![red_badge_notification](https://cloud.githubusercontent.com/assets/4163828/14749205/2c709d44-088c-11e6-8924-781cfc1f0948.png)

**Comment by cbeer** [comment]
Or, maybe moving notifications out of the navbar was a bad idea, and it deserves to be a top-level item again?

**Comment by mtribone** [comment]
@cbeer We _could_ just use the little circle, but I'm concerned about color blindness without the number.

**Comment by cbeer** [comment]
Presence vs absence isn't enough?

**Comment by ggeisler** [comment]
I don't know enough about the UI details and history to be confident of this, but I have the impression that notifications are important and frequent enough (for many users, at least?) that having notifications as a first-class item in the menu might make sense. As opposed to frequently having one or more menu items decorated by whatever badge/notification symbol we'd otherwise use.

If a typical user often interacts with Sufia and depends on notifications to know what to do next, etc., then it feels like notifications might be better called out as a menu item itself.

Otherwise, maybe a small round white dot above the caret to indicate notifications for that menu category? It would be subtle, but regular users who depend on notifications would figure it out soon enough, I'd think.

**Comment by jcoyne** [comment]
>  important and frequent

I'm not sure about either of those assertions.

**Comment by jcoyne** [comment]
> a small round white dot above the caret to indicate notifications for that menu
:+1:

**Comment by mjgiarlo** [comment]
:+1: to a dot, and :+1: to breaking Notifications out of the Dashboard menu, and moving it to a top-level navbar item. (Perhaps, like GitHub, it should be a bell icon over to the right, immediately left of the user dropdown?)

**Comment by mtribone** [comment]
I also have no idea how important or unimportant notifications are to people within their preferred workflow. Presence vs absence _could_ be enough as long as there is enough contrast between the dot and its background *and* it matches the users perceived level of importance. The white dot against the black background is certainly enough in terms of color contrast, but it will be up to adopters to make sure that their dot and background work well together.

**Comment by mtribone** [comment]
@mjgiarlo Yeah the bullhorn was over on the right by the persons name. Long live Sufia 6!

**Comment by mjgiarlo** [comment]
Ha. Well we could worse than imitate Sufia 6 (and GitHub and Facebook and Dropbox and Google+ and...).

**Comment by atz** [comment]
OK, I've done the baseline moving notifications up to the top level, right side.  Further refinements are available to anyone willing to take them up, but this satisfies my expectation of visibility.

![screen shot 2016-04-25 at 3 50 59 pm](https://cloud.githubusercontent.com/assets/109954/14801415/e8f96284-0afd-11e6-863a-aaab7b60c1df.png)

Note: actually doesn't satisfy for `xs` screens, where everything is buried under a hamburger icon menu. Can deal with that later.
