### ISSUE TITLE
Batch Create set resource type to all button

### ISSUE THREAD

**Issue by hectorcorrea** [projecthydra/sufia#1869]
### Descriptive summary

In Batch Create, the button to set the resource type to all files being uploaded is being displayed for every file but according to the [wire frames](https://wiki.duraspace.org/display/hydra/Batch+New+Works+-+Phase+1+-+UI+Wireframes#mockup_p1-works-batch_new-step1_upload_files) it should only be displayed for the first file. 

### Expected behavior
The "Set all to this Resource Type" button should be displayed only for the first file.

### Actual behavior
The "Set all to this Resource Type" button is currently displayed for all files being uploaded
![set_all_resource_type](https://cloud.githubusercontent.com/assets/568286/14561328/81d590e0-02e3-11e6-9f2a-0f4031ea293d.png)
.

### Steps to reproduce the behavior

1. Go to Batch Create
1. Select two files to upload
1. Notice how the "Set all to this Resource Type" button is displayed next to each file. It should only be displayed for the first file.

### Related work
Issue detected in PR https://github.com/projecthydra/sufia/pull/1838

**Comment by jcoyne** [comment]
I'm going to add a wrinkle here. What happens if the first upload is canceled?  Should the next upload get the "Set all to this resource type" button?  Perhaps it is good to leave all of them, but hide them, and have css to only reveal only the first one.

**Comment by mjgiarlo** [comment]
Shout me down if you think this is awful, but I'm comfy having this button next to every upload in the 7.0.0 release. I'm moving this to 7.1.0.

**Comment by awead** [comment]
So, can we close this?

**Comment by mjgiarlo** [comment]
@awead Close this because it's fixed or because we stopped caring about it?

**Comment by awead** [comment]
@mjgiarlo I'm with you, having the button on each download is fine with me. So, close it?

**Comment by mjgiarlo** [comment]
Good call.
