### ISSUE TITLE
Editing a work and the Deposit Agreement

### ISSUE THREAD

**Issue by hectorcorrea** [projecthydra/sufia#1870]
### Descriptive summary

When users edit a Work they shouldn't have to acknowledge the Deposit Agreement again unless they are adding a new file. In the current version, even changing the title of a Work or any of the metadata fields forces the user to check the "I have read and do agree to the Deposit Agreement" checkbox. 

### Expected behavior
When editing a Work, only force users to check the Deposit Agreement if files are added to the work.

### Actual behavior
Currently users must check the Deposit Agreement on any change to the work.

### Steps to reproduce the behavior

1. Click Edit on a Work
1. Change any field (e.g. the title)
1. Try to click Save, you'll see the button is disabled until you agree to the Deposit Agreement.

**Comment by jcoyne** [comment]
I agree that this is an issue, but I don't think it should block 7.0.0. Can we move to 7.1.0?

**Comment by jcoyne** [comment]
@hectorcorrea why is this marked "question"?

**Comment by hectorcorrea** [comment]
@jcoyne the question was because of the 7.0.0 milestone. I've moved it to 7.1.0.

**Comment by mjgiarlo** [comment]
Ah, yes, this behavior is annoying. Thanks for flagging it, @hectorcorrea. I'm cool with moving this to the 7.1.0 release.
