### ISSUE TITLE
Add files button becomes disabled

### ISSUE THREAD

**Issue by hectorcorrea** [projecthydra/sufia#1873]
### Descriptive summary

On certain screen widths the "Add Files" button becomes disabled. I am not sure if the button becomes disabled or just un-clickable but the net result is that under certain screen-width values the user cannot add files. 

The two screenshots below show an example of a width that worked (779) and one that does not (724)

![screen shot 2016-04-15 at 11 56 02 am](https://cloud.githubusercontent.com/assets/568286/14567371/c529ecd8-0301-11e6-873e-2a023f38d3aa.png)

![screen shot 2016-04-15 at 11 55 39 am](https://cloud.githubusercontent.com/assets/568286/14567367/bb2193a8-0301-11e6-9f24-6f55faadfc4a.png)

### Steps to reproduce the behavior

1. Click on Create New Work
1. Resize the screen width as shown in the screenshots above
1. Notice how the "Add Files" button cannot be clicked.

This happens in FireFox, I have not tested on other browsers.

**Comment by atz** [comment]
I suspect drag/drop still works on either size?

**Comment by atz** [comment]
Confirmed same behavior in Chrome/OSX.

**Comment by jcoyne** [comment]
I was able to fix this by changing the `col-lg-7` to `col-sm-7`

**Comment by atz** [comment]
Would this possibly relate to the reports of needing to double click in IE?

**Comment by atz** [comment]
That single fix wasn't enough for me, but if I change the other column from `lg` to `sm` also, that works.
