### ISSUE TITLE
catch-all routing for 404 should be appended in generator, not in the engine

### ISSUE THREAD

**Issue by barmintor** [projecthydra/sufia#1906]
### Descriptive summary

Sufia 7 brings down from Sufia 6 this catch all route for 404s that requires the Sufia engine to be last in the application routes. This is annoying when you start running other generators in your app, and makes for surprising behavior changes because it is only added in non-dev, non-test environments. So your app will work until it's deployed, when suddenly things 404 mysteriously.

### Expected behavior

The generator appends the catch all route to the application routes instead of including them in the engine.

### Actual behavior

It includes them in the engine.

### Steps to reproduce the behavior

1. Generate a Sufia app, then localize it with some new routes.

### Related work

None so far.

**Comment by cbeer** [comment]
I'd say, don't include a catch-all route at all. That's the application's job, not sufia's.

**Comment by barmintor** [comment]
I would be happy to escalate to deletion! It just shouldn't be squirreled away in the engine where I can't get to it.

**Comment by mjgiarlo** [comment]
Deleting works for me. I'm pretty sure that was extracted from ScholarSphere. We'll want to include a note about this in the 7.0.0 release notes when we make this change (included in #1751).

Any objections, @jcoyne @awead @cam156 @hectorcorrea?

**Comment by awead** [comment]
Yep. The downstream app might want to handle it differently anyway. 👍
