### ISSUE TITLE
Notifications should use websockets

### ISSUE THREAD

**Issue by atz** [projecthydra/sufia#1909]
The repetitive AJAX polling of every open page is a costly and distinctly unmodern approach to the notification problem.  A better fit for today's web (well, recent years' web, anyway) would be websockets.

**Comment by mjgiarlo** [comment]
Yes, we should re-implement notifications using Rails 5's Action Cable framework, if others are comfy making that jump. @cbeer is this something you'd be interested in?

**Comment by mjgiarlo** [comment]
(sorry, closed by accident on mobile.)

**Comment by mjgiarlo** [comment]
Let's do this in Hyrax.
