### ISSUE TITLE
Sufia7 routes not found when using staging environment

### ISSUE THREAD

**Issue by revgum** [projecthydra/sufia#1928]
We're using Sufia 7.0.0.beta1 with an appropriate set of configuration files for a "staging" environment. We are running solr_wrapper and fcrepo_wrapper on unconventional ports (9983 and 9984) for our Sufia7 testing, both solr and fedora seem to be getting the proper data during file deposit and characterization.

File deposit works fine, but we noticed the thumbnail images were rendering as broken links. The thumbnail images are generated and placed on the filesystem, however, the `downloads/:id?file=thumbnail` was returning a HTTP404. We also noticed that `collections/new` was returning a HTTP404.. 

`rake routes` shows both of these routes in the list.

After an extended period of testing and troubleshooting, we gave up and switched our configurations to use the "development" environment and everything seemed to be working as expected.

**Comment by mjgiarlo** [comment]
Hi, @revgum. Can you try this using the built-in "production" env? I've run into problems in the past with creating my own Rails envs, though it's been so long that I can't recall any useful information to troubleshoot it.

**Comment by revgum** [comment]
Oddly, the production environment gives me the same problems with those two routes.

**Comment by mjgiarlo** [comment]
I'm adding this to the 7.0.0 milestone. If someone could verify this behavior, that'd be great.

**Comment by jcoyne** [comment]
I'm seeing:
```
I, [2016-04-27T10:42:14.793290 #26867]  INFO -- : Started GET "/concern/file_sets/rv042t67q" for ::1 at 2016-04-27 10:42:14 -0500
I, [2016-04-27T10:42:14.794292 #26867]  INFO -- : Processing by ErrorsController#routing as HTML
I, [2016-04-27T10:42:14.794341 #26867]  INFO -- :   Parameters: {"error"=>"concern/file_sets/rv042t67q"}
E, [2016-04-27T10:42:14.794753 #26867] ERROR -- : Rendering 404 page due to exception: "Route not found: /concern/file_sets/rv042t67q" -
```

**Comment by revgum** [comment]
@jcoyne Indeed, that's what we see in the logs as well.

**Comment by jcoyne** [comment]
For the time being, you can fix this by updating `config/routes.rb` move these lines:
```ruby
  # This must be the very last route in the file because it has a catch-all route for 404 errors.
  # This behavior seems to show up only in production mode.
  mount Sufia::Engine => '/'
```

After this line:
```ruby
  concern :exportable, Blacklight::Routes::Exportable.new
```

I will work on a fix for the generators.
