### ISSUE TITLE
Posting a new version of a FileSet should work

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1933]
In Sufia master, when I upload a new version of a FileSet, a new version of the file is not posted. The form submits A-OK, but the prior FileSet is still there and the version history only has one entry (for the original upload).

Probably worth testing restoration of past versions once this is fixed.

This is partially blocking #1437.

**Comment by jcoyne** [comment]
I'm seeing
```
Completed 422 Unprocessable Entity in 1337ms (Views: 1218.3ms | ActiveRecord: 0.4ms)
```

In the logs.

**Comment by jcoyne** [comment]
It appears that the form on the page is not submitting `params[:file_set][:files]`, it is submitting `params[:files]`.
