### ISSUE TITLE
Ditch CurationConcernsHelper

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1936]
### Descriptive summary

We have `CurationConcernsHelper` and `SufiaHelper` both generated into the app. Both are requiring `BlacklightHelper`. Can we just have `SufiaHelper` and have it do the inclusion of all the modules and get rid of `CurationConcernsHelper`?

**Comment by jcoyne** [comment]
It may be easer to just not generate the SufiaHelper rather than remove the CurationConcerns helper.

**Comment by awead** [comment]
Agreed. Except, it's required here: 
https://github.com/projecthydra/sufia/blob/master/app/jobs/event_job.rb#L10

**Comment by awead** [comment]
Perhaps just change the event job to use CurationConcernsHelper

**Comment by mjgiarlo** [comment]
Backloggable, or are you in need of tickets to work on, @awead?

**Comment by mjgiarlo** [comment]
Not worth doing now that Hyrax is a thing, I don't think. Closing.
