### ISSUE TITLE
Metadata does not display on Work show page

### ISSUE THREAD

**Issue by elrayle** [projecthydra/sufia#1942]
### Descriptive summary

Sufia 7.0.0.beta1; Ruby 2.2.0

Setting metadata fields for a New Work does not display metadata on work show page after saving.

### Expected behavior

Setting values for metadata fields of a new work should display those fields and their values on the work show page in the Metadata section.

### Actual behavior

When setting values for metadata fields of a new work and saving, the work show page has "No metadata is defined for this work." in the Metadata section.

### Steps to reproduce the behavior

1. Works -> New Work
1. Metadata Tab:  Set Title
1. Metadata Tab: View additional fields and set Language = English
1. File Tab:  Add one file
1. Save
1. NOTICE: Title is correct
1. NOTICE: Metadata section should show Language: English, but actually shows "No metadata is defined for this work."  (I reproduced this with Tag, Publisher, and several other fields)
1. Edit
1. Metadata Tab: View additional fields and NOTICE Language does equal English

### Related work

#1943, #1944

**Comment by jcoyne** [comment]
It looks like this was introduced by https://github.com/projecthydra/sufia/commit/a5c69cb1baa01f676e429ca12817c514b7b5d436 

@atz I'm not exactly sure what your intention was with that code. Currently if `:embargo_release_date`, `:lease_expiration_date`, and `:rights` are empty, then it displays "No metadata".  But it's often true that none of these three fields are set. Why aren't we looking for `:creator`, `:description`, etc?

**Comment by jcoyne** [comment]
Two suggested ways to fix this: 
1. Never check for empty metadata.  All records have metadata. Just display it.
1. Make "rights" a required field on the create page. We recently made it have an empty default value, which is probably why this shows up now.

**Comment by mjgiarlo** [comment]
IIRC, the required fields in Sufia 6 were:

1. Title (which we defaulted to the original filename)
2. Creator (which we default to the depositor's name)
3. Rights
4. Keyword(s)

In the PCDM/Works/CC shuffle, I missed that this changed.
