### ISSUE TITLE
Collection relationship is lost when editing a work

### ISSUE THREAD

**Issue by elrayle** [projecthydra/sufia#1944]
### Descriptive summary

Sufia 7.0.0.beta1; Ruby 2.2.2

Editing a work and changing metadata wipes out previous metadata and relationships.

### Expected behavior

Editing a work and adding metadata should add the new metadata value AND should leave all other existing metadata and relationships the same.

### Actual behavior

Editing a work and adding metadata fails to display the new metadata AND removes relationships.

### Steps to reproduce the behavior
Prereq:  Create a collection with name Test Collection 1

1. Works -> New Work
1. Metadata Tab:  Set Title
1. File Tab:  Add one file
1. Relationships Tab: Select Test Collection 1
1. Save
1. Confirm Title is correct and Relationships sections has In collections: Test Collection 1
1. Edit
1. Metadata Tab: Set Tag = foo  (I don't think it matters which metadata field you change. I got the same behavior for Description.)
1. Save
1. NOTICE:  Metadata section does not have Tag = foo AND Relationships section no longer shows the work in Test Collection 1
1. Edit
1. Metadata Tab: NOTICE Tag = foo
1. Relationships Tab:  NOTICE: Test Collection 1 is no longer selected

### Related work

#1942

**Comment by jcoyne** [comment]
It looks to me like the collection widget is not preselecting the items (collection_ids) for which it is already a member.
