### ISSUE TITLE
Title should not display twice in index view

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1948]
<img width="801" alt="screen shot 2016-04-29 at 3 39 21 pm" src="https://cloud.githubusercontent.com/assets/92044/14928990/c25022f0-0e20-11e6-9cb9-57966c062971.png">

Since it's the header, no need to display it in the table too.

**Comment by atz** [comment]
Can you specify a URL where this would display?

**Comment by mjgiarlo** [comment]
@atz Do a search. It's in the `/catalog` views, I believe.

**Comment by atz** [comment]
OK.  Note: I see it in the "Gallery" view also.

**Comment by atz** [comment]
OK, that template `app/views/shared/_attributes.html.erb` is very static.  It displays:

- Title
- Owner
- Depositor
- Creator
- Description
- Keywords
- Date Uploaded

Many of those can be empty.  Do we want to always display them anyway?

It uses a table for layout.  Would we prefer a bootstrapism?

**Comment by mjgiarlo** [comment]
My take: do not display if empty. I'm ambivalent on table v. bootstrapism. @mtribone @ggeisler @aeschylus ?

**Comment by ggeisler** [comment]
I agree with not showing any field that is empty. I also agree that I wouldn't show the title field in the metadata area, given it is shown as the title of the main content area.

I'd suggest a `dl` is more appropriate for presenting metadata like this, but one *could* make an argument that it's tabular data so a table isn't terrible.

**Comment by jcoyne** [comment]
@ggeisler I think a `dl` is a particularly poor choice.  The definition of "Creator" is "a person or thing that brings something into existence".  When we are talking about the creator of a particular object, it's data about the object.

https://www.w3.org/MarkUp/html3/deflists.html

**Comment by mtribone** [comment]
@jcoyne In HTML5 it has been reborn as the description list and is good for key value pairs like metadata.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl

**Comment by jcoyne** [comment]
Yes, I was just noticing I was looking at a very old spec.  It' is permissible.

**Comment by ggeisler** [comment]
Thanks for providing the reference @mtribone. We use it all the time for just this purpose (SearchWorks, Spotlight) and it seems like a fine solution to me.

**Comment by jcoyne** [comment]
I believe the current design was @mtribone's so please discuss between yourselves if this should be changed.    If we decide to go with `<dl>` I believe we can just use the Blacklight provided views (as that's what it uses)

**Comment by mjgiarlo** [comment]
If @mtribone is down with the `<dl>`, it will be great to better align our views with Blacklight's.

**Comment by mtribone** [comment]
@jcoyne @mjgiarlo I am indeed down with the `<dl>` and aligning more with Blacklight

**Comment by mjgiarlo** [comment]
Fixed by https://github.com/projecthydra/sufia/pull/1950
