### ISSUE TITLE
Verify we're not broken with turbolinks turned on

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1949]
See: https://github.com/projecthydra/sufia/pull/1932#discussion_r61469566

Test that in particular to see if turbolinks causes problems. Also, verify whether this step is still accurate and needed:

https://github.com/projecthydra/sufia/wiki/Sufia-Management-Guide#user-interface

**Comment by jcoyne** [comment]
Why is this tagged "needs feedback"?  Who are we waiting on to provide it?

**Comment by mjgiarlo** [comment]
Removed that label.

**Comment by jcoyne** [comment]
I have confirmed that the issue I raised on #1932 is in fact broken with turbolinks enabled.  You can see in this screenshot that an incorrect template for batch upload has been used (no field for label or resource type):

<img width="1248" alt="screen shot 2016-05-02 at 7 24 35 am" src="https://cloud.githubusercontent.com/assets/92044/14965418/f3203dee-1072-11e6-98fa-a39e4434e2ac.png">

**Comment by jcoyne** [comment]
TinyMCE (for the admin), is also broken with Turbolinks.

**Comment by jcoyne** [comment]
@mjgiarlo close this?
