### ISSUE TITLE
Metadata verification JS busted

### ISSUE THREAD

**Issue by atz** [projecthydra/sufia#1962]
Apparently we now require 4 fields for a New Work (Title, Creator, Tag, Rights):
![screen shot 2016-05-02 at 5 18 51 pm](https://cloud.githubusercontent.com/assets/109954/14971822/ee99f96e-108a-11e6-9c0d-e0bb983616c3.png)

But the green checkmark in the screenshot shows the form validation that we used to have has been broken.  User can save a file with empty rights, for example.  Other screens possibly affected also.

**Comment by atz** [comment]
Note also the style difference between the "legend" asterisk and the per-field asterisks (size and color).  They should be visually the same.

**Comment by jcoyne** [comment]
How did you get to this state? It works correctly for me.

**Comment by atz** [comment]
Same as ever: nuke, checkout master, pull and rebuild (bundle, generate, etc).

**Comment by jcoyne** [comment]
I see this too now. It's because the fields are no longer marked with the "required" attribute.

**Comment by jcoyne** [comment]
It's because in the generated test application:
```
# config/initializers/simple_form.rb
config.browser_validations = false
```
