### ISSUE TITLE
Get rid of upgrade 6.0.0 generator

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1967]
https://github.com/projecthydra/sufia/blob/master/lib/generators/sufia/upgrade600_generator.rb

Can we merge that back into the install generator?  I'm not sure we want to support a Sufia 5 -> Sufia 7 upgrade. Having an extra generator slows the install process, and adds unnecessary indirection that makes it complicated to understand how it works.

**Comment by mjgiarlo** [comment]
I would like to keep the generator around for folks going from Sufia 4/5 -> 6, but I'm also happy to disentangle the bits of it used in the install generator so that the install tool doesn't need to call the upgrade generator.

**Comment by atz** [comment]
If they are going to 6, won't they be using a 6.x release to do it?

**Comment by mjgiarlo** [comment]
good point, @atz!
