### ISSUE TITLE
Batch Create New Works – Display of Works

### ISSUE THREAD

**Issue by mtribone** [projecthydra/sufia#1970]
### Descriptive summary

Containing element for the listing and display of batch files after adding files displays incorrectly. The containing element is too small for the content and wraps and bunches content together. (Sufia 7.0.0)

### Expected behavior

Expected the listing of batch files for new works to fill the amount of space in the min column.

### Actual behavior

Listing of batch files for new works is contained in a small containing element and wraps and bunches content together.

### Steps to reproduce the behavior

1. Create a batch of new works
1. Add files
1. After files load, display of new works is incorrect 

### Related work

Link to related tickets or prior related work here.

**Comment by mtribone** [comment]
![screen shot 2016-05-04 at 10 56 55 am](https://cloud.githubusercontent.com/assets/4163828/15023916/8c69674e-1200-11e6-8166-6e50aeb59d66.png)

**Comment by mtribone** [comment]
@mjgiarlo Looks like we are back in business...

<img width="1253" alt="screen shot 2016-06-02 at 8 20 09 am" src="https://cloud.githubusercontent.com/assets/4163828/15744614/ea904116-289a-11e6-90c2-aca6527818d1.png">

**Comment by mjgiarlo** [comment]
:clap: think we can close this issue?

**Comment by mtribone** [comment]
Can we get another person to verify?

**Comment by mjgiarlo** [comment]
Verified. We can close this. Thanks!
