### ISSUE TITLE
User profile throws Exception when not logged in

### ISSUE THREAD

**Issue by jhallida** [projecthydra/sufia#1977]
When logged out, I click on “Recently Uploaded” from the home page, then click on a username. The resultant URL (http://localhost:3000/users/jhallida@indiana-dot-edu) works when logged in, but when logged out it gives a NoMethodError in Users#show

**Comment by randalldfloyd** [comment]
So far I am unable to replicate locally - going to vary my environment in subtle ways and keep trying...

**Comment by randalldfloyd** [comment]
Unable to replicate, even when trying to intentionally create inconsistent states between Solr, Fedora, and Devise user in the database. Confirmed that reporter @jhallida also unable to replicate again.
