### ISSUE TITLE
Only the first title and the first description display on the work show page

### ISSUE THREAD

**Issue by jhallida** [projecthydra/sufia#1979]
Entering multiple titles and descriptions is allowed and entries beyond the first can be edited, but they do not display in the show interface.

**Comment by mtribone** [comment]
Partial overlap with this ticket, but is just for title only:

https://github.com/projecthydra/sufia/issues/1969

**Comment by atz** [comment]
I don't understand the use case of having multiple undifferentiated contributors with the same name.  Certainly the publication (or work) has to identify the individuals separately.

**Comment by mjgiarlo** [comment]
@atz What I heard was that it's possible to have two "John Smith"s as contributors, for example. For this ticket, I'm inclined to say we should continue the behavior of Sufia 6.x. Hey, @awead and @cam156, can you see what Sufia 6-based ScholarSphere does with multiple contributors with the same exact string?

**Comment by cam156** [comment]
I will give it a spin on ScholarSphere and get back to you...

**Comment by cam156** [comment]
Here is the current behavior:
I Type in "Smith, John" into contributor
And I click Add
And I Type in "Smith, John"
And I click Save
When the page loads
I should see ONE "Smith, John" entry in contributor

**Comment by mjgiarlo** [comment]
Thank you, @cam156! I'm re-focusing this ticket on display of multiple titles and descriptions.

**Comment by mtribone** [comment]
@mjgiarlo Got the descriptions figured out. Problem was behind keyboard. Will investigate failing tests and then PR.

![screen shot 2016-05-11 at 1 45 09 pm](https://cloud.githubusercontent.com/assets/4163828/15190590/bbc61a4a-177e-11e6-86a7-b8004cb25b80.png)
