### ISSUE TITLE
bugs with create / edit collection page

### ISSUE THREAD

**Issue by jhallida** [projecthydra/sufia#1980]
1. Putting anything in location, thumbnail, representative, and related URL fields throws exception NoMethodError when attempting to save.

2. Title is a required field but it isn’t asterisked

**Comment by mtribone** [comment]
Canceling an edit for collections returns you to the home page and gives status message that the collection was successfully updated.

![screen shot 2016-05-05 at 12 25 42 pm](https://cloud.githubusercontent.com/assets/4163828/15049504/a5b08c2a-12bc-11e6-8d88-54d266b385f8.png)

**Comment by relaxing** [comment]
Putting a bad URI into the representative field throws an uncaught URI::InvalidURIError at /collections

**Comment by jcoyne** [comment]
There should not be any location, thumbnail, representative, and related URL that display as text fields.  These must be drop downs with valid options (as is the case for works).
