### ISSUE TITLE
Tags / keywords do not display on item display pages

### ISSUE THREAD

**Issue by jhallida** [projecthydra/sufia#1983]
I don’t see tags / keywords in the display page for a work, even though my item has keywords.

**Comment by mjgiarlo** [comment]
@njaffer Are you working on this ticket or is it available?

**Comment by njaffer** [comment]
@mjgiarlo, I put in the PR (https://github.com/projecthydra/sufia/pull/2023) to rename the tag to tags in one place, and saw your message that it will be taken care of with another PR, so I have unassigned myself!

**Comment by mjgiarlo** [comment]
thanks, @njaffer!

**Comment by hectorcorrea** [comment]
Keywords display in the Work show page. I think we should close this now. Thoughts?

![screen shot 2016-05-17 at 11 22 27 am](https://cloud.githubusercontent.com/assets/568286/15328119/d37346b6-1c21-11e6-9742-21a27a75983c.png)
