### ISSUE TITLE
Hard to un-select a collection when submitting item

### ISSUE THREAD

**Issue by jhallida** [projecthydra/sufia#1984]
It’s hard to know how to NOT put an item in a collection when submitting it. There is no ‘no collection’ choice. You can actually use CTRL-click to unselect but that's not intuitive to most users.

**Comment by atz** [comment]
Intuitive or not, that is the browser-default behavior for mutli-selects.  That makes it not a bug.  Adding a button to clear selections, for example, would be an enhancement/feature, not a bugfix.

**Comment by mtribone** [comment]
Is this issue in regards to the relationships tab of a work? Do we want to add a "clear" button?

![screen shot 2016-06-27 at 9 13 22 am](https://cloud.githubusercontent.com/assets/4163828/16380902/aff25a92-3c47-11e6-9ac6-591e1f75af39.png)
