### ISSUE TITLE
Add sharing to collections

### ISSUE THREAD

**Issue by elrayle** [projecthydra/sufia#1988]
#### Descriptive summary

Sufia 7.0.beta
##### Expected behavior

New feature: Add sharing for collections.  Depositor can share read/edit privileges with other users/groups.  For editing, this allows the sharee to perform all editing functionality for the collection including changing metadata for the collection, adding/removing works from the collection, deleting the collection.  This does _not_ modify permissions for any members of the collection.

**Comment by mjgiarlo** [comment]
If this is ready in time for the 7.0.0 release, great! :clap: Otherwise, I'm not inclined to make this a blocker.
