### ISSUE TITLE
Document how to run fcrepo_wrapper and solr_wrapper for development

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1998]
### Descriptive summary

For Sufia 7.0, describe the steps to use `solr_wrapper` and `fcrepo_wrapper` for running the test app in development mode. Do that here: https://github.com/projecthydra/sufia/wiki/Sufia-Development-Guide

**Comment by mjgiarlo** [comment]
I suggest this wiki page: https://github.com/projecthydra/sufia/wiki/Sufia-Development-Guide

**Comment by cam156** [comment]
👍  That was the page I was thinking about editing.

**Comment by mjgiarlo** [comment]
@cam156 is this issue still relevant or did we do a good enough job in Ann Arbor?

**Comment by cam156** [comment]
@mjgiarlo I think this is complete.
