### ISSUE TITLE
Can't see existing uploads in "Files" tab when editing

### ISSUE THREAD

**Issue by paulrosen** [projecthydra/sufia#2000]
### Descriptive summary

Sufia version '82e7bc903ee64aa11c7ffe0fe7c35f6e36390afc'

When editing an existing work, and going to the "files" tab, it is empty, even though some files had been uploaded previously. Those files are shown correctly on the show page under "items".

This is confusing to the user, who thinks that the previously uploaded documents where not successfully uploaded.

### Expected behavior

There should be a line for each file previously uploaded. This line should not have the "delete" button, but otherwise look similar to the line that is added for each uploaded file.

### Actual behavior

The file tab is always empty when editing a work.

### Steps to reproduce the behavior

1. Create a new work.
1. Go to the files tab and upload a file
1. Click "Save"
1. Confirm that the file is listed in the show page.
1. Click "Edit"
1. Click the "files" tab and see that the file is NOT listed.

**Comment by mjgiarlo** [comment]
Hi @paulrosen. Thanks for reporting this. This issue may be the same as https://github.com/projecthydra/sufia/issues/1943.

**Comment by paulrosen** [comment]
Sorry, I missed that one. I think it is the same issue.

**Comment by mjgiarlo** [comment]
np, @paulrosen -- there's a lot of issues to go through. :)
