### ISSUE TITLE
Be able to set the title of a file in the "file" tab.

### ISSUE THREAD

**Issue by paulrosen** [projecthydra/sufia#2001]
### Descriptive summary

Sufia version '82e7bc903ee64aa11c7ffe0fe7c35f6e36390afc'

The only way to set the title of a file is by uploading it, then clicking the edit action and setting the title there. That is not something that a user will typically stumble on, so most files will keep their default title, which is the uploaded filename.
### Expected behavior

On the file tab, when showing the line with the file, there should be an input control right there to set the title of the file.
### Actual behavior

The line that indicates that a file is being uploaded only contains the file name, its size, and a delete button.
### Steps to reproduce the behavior
1. Edit a document
2. Click the "Files" tab
3. Select a file for upload
4. Notice that there is no way to set the title.

**Comment by jcoyne** [comment]
I think you are referring to this wireframe: https://wiki.duraspace.org/display/hydra/New+Work+-+tab+Files+-+Phase+1+-+UI+Wireframes#mockup_p1-works-new-tab_files

Also interesting is that there's no way to set the filename in the batch upload:
https://wiki.duraspace.org/display/hydra/Batch+New+Works+-+Phase+1+-+UI+Wireframes#mockup_p1-works-batch_new-step1_upload_files
The label you see pictured there gets used for the work title. Do we need a new mockup, or a new ticket? @elrayle

**Comment by paulrosen** [comment]
Yes, that wireframe is exactly what I mean. I see that the milestone for that is Aug 1st. I need to demo this behavior much sooner than that. Would it be helpful if I pitch in? Is there someone actively working on this already?

**Comment by jcoyne** [comment]
> the milestone for that is Aug 1st

That's just wild speculation. No one is currently working on it, so please help out.

**Comment by mjgiarlo** [comment]
@paulrosen It'd be great if you could pitch in, yes! I'd be happy to include this earlier if you wanted to work on a PR.

In order for us to merge any code contributions, we'll first need to have a signed Contributor License Agreement on file for you as an individual. You can read more about our CLA processes here:
https://wiki.duraspace.org/display/hydra/Hydra+Project+Intellectual+Property+Licensing+and+Ownership

The process itself is fairly simple -- you just need to print out the Hydra Project iCLA and sign it and then send it to legal@projecthydra.org. Let me know if you have any questions about this process, and I'd be happy to help.

(We also require that contributors' institutions are covered by a corporate CLA. Who's your employer? University of Virginia (guessing by your GitHub profile)? If so, that part's already done.)

**Comment by paulrosen** [comment]
Ok, I just sent that. I am a contractor hired by UVA to set up an instance of Sufia.

**Comment by mjgiarlo** [comment]
Great, @paulrosen, thanks. We usually turn those around in 24-48 hours. In the meantime, don't let that get in your way of getting started. Let us know if we can help. If you'd like real-time communication, consider joining the [Hydra Slack team](https://wiki.duraspace.org/pages/viewpage.action?pageId=43910187#Getintouch!-Slack) (we're in the #software-development channel).

**Comment by mjgiarlo** [comment]
Moving to Hyrax.
