### ISSUE TITLE
Abstract/Summary or Description – Add More Duplicates First

### ISSUE THREAD

**Issue by mtribone** [projecthydra/sufia#2002]
### Descriptive summary

Whether I am creating a new work or collection, when I add another abstract or summary it duplicates the contents of the first text area. (Sufia 7.0.0)

### Expected behavior
Expected to see a blank text area after adding another
### Actual behavior
New text area is created and populated with the contents of the first text area
### Steps to reproduce the behavior

1. Create New Work
1. Add required metadata
1. Add abstract/summary or description to text area
1. Hit the +More button

### Related work

Link to related tickets or prior related work here.

**Comment by mtribone** [comment]
<img width="697" alt="screen shot 2016-05-09 at 3 01 47 pm" src="https://cloud.githubusercontent.com/assets/4163828/15125094/17a16b3a-15f9-11e6-887f-015e70cad83b.png">

**Comment by hectorcorrea** [comment]
@mtribone I cannot make this happen

![screen shot 2016-05-11 at 4 46 58 pm](https://cloud.githubusercontent.com/assets/568286/15195921/0aa9eb14-1798-11e6-8a80-342f85ee07ba.png)

**Comment by mtribone** [comment]
@hectorcorrea So far it is happening only in Chrome and it doesn't actually add the second description if you just hit save. The text from the first box displays in the second box but does not get added to the work.
