### ISSUE TITLE
Improve license selection and documentation

### ISSUE THREAD

**Issue by justcolin** [projecthydra/sufia#2007]
### Descriptive summary

A number of groups have worked on a variety of ways to redo how rights selection/documentation is done. I propose that we come up with one simple version which can be implemented in Sufia out of the box. I would prefer for it to be something simple, easy to maintain and easy to make accessible. It should also be made easy for Sufia-based app creators to add in a more complicated rights selector if they would like one.

### Related work

Some previous discussion when on with #2003, and this addresses issues related to #1612

**Comment by justcolin** [comment]
@projecthydra/sufia-ui-ux-advisors

**Comment by justcolin** [comment]
I am concerned that a big complicated wizard-style rights selector will be difficult to make accessible and will be too burdensome for people who already know which rights they want to select. It feels like good documentation on how to pick the right license for your project on a separate page would solve that problem.

That documentation could have some nice interactive widgets to take users on a guided journey to find the right license. Then all the create/edit page would need is an `<option>` selector and a link to a license guide.

Thoughts?

**Comment by justcolin** [comment]
Examples that others have shared which I think would make great documentation/help pages, but would be too heavy for the form itself:

- https://creativecommons.org/choose/
- https://ufal.github.io/public-license-selector/

**Comment by crowesn** [comment]
We have modeled an implementation of the modal [public license selector](https://ufal.github.io/public-license-selector/) tool. The modal is activated with a button below the standard license dropdown. If the user selects a license from the tool, it is populated in the dropdown. We haven't tested this with users.

This arrangement leaves the dropdown in place for users in the know, but provides a modal interface for users desiring more guidance.

**Comment by heidisb** [comment]
This is really tricky because we need to balance letting users who know what license they want zoom through and providing guidance to users with no clue. And license selection can be a beast and very overwhelming if you have limited-to-no context around copyright and author's rights.

My thoughts: provide a simple, clear prompt for those who need it as help text. Something like:
[Need help selecting the right license?] (opens in a separate window)

Link that to a separate page on selecting the right license and recommend setting the **expectation** that it will open in a separate window (since that is generally discouraged and we clearly don't want to take them away from the upload process entirely).

As Colin notes, that page could have more interactivity to help guide the user. My mind goes to the word "heavy" for having such as tool as part of the upload page. It generally feels kinder all around to move it to a separate page: stays out of the way for those who don't need it and those who do can take time away from the upload process to focus on the license selection instead of tacking stuff on stuff.

**Comment by justcolin** [comment]
@projecthydra/sufia-ui-ux-advisors: Thoughts on this?

**Comment by justcolin** [comment]
Because everyone seems to be using a different set of rights in the UI (some use a lot, some a few, some focus on CC, some provide a variety) I think the we shouldn't do too much in the default Sufia UI, maybe just write a sentence or two explaining that this field lets you select how you are licensing the content. Then if individual groups want to add more or link out to a additional resources they can do so.

That way the default is simpler and always accurate, and people can expand upon it if they would like.

**Comment by mjgiarlo** [comment]
I'd like this in the 7.0.0 release, though I don't consider this a blocker.

**Comment by heidisb** [comment]
+1 to everything Colin said. 

Other field elements have pretty universal expectations, but it's plausible that each institution will have a different approach to rights selection. Keeping it simple in the default Sufia UI makes for easier maintenance and allows everyone to make the local additions they need. Basically -- I think consensus on this is impossible and we're in a position to put forward a solution that works for everyone without undue burden (that's a legal term, yo!) on the default UI and community.

Though I do encourage everyone to consider the recommendations I made earlier and not overload the upload page with help content.

**Comment by bnhowell** [comment]
+1 for a simple framework/default UI for license selection that allows for
links to an institution's tools for rights selection guidance.



On Tuesday, June 7, 2016, Heidi Burkhardt <notifications@github.com> wrote:

> +1 to everything Colin said.
>
> Other field elements have pretty universal expectations, but it's
> plausible that each institution will have a different approach to rights
> selection. Keeping it simple in the default Sufia UI makes for easier
> maintenance and allows everyone to make the local additions they need.
> Basically -- I think consensus on this is impossible and we're in a
> position to put forward a solution that works for everyone without undue
> burden (that's a legal term, yo!) on the default UI and community.
>
> Though I do encourage everyone to consider the recommendations I made
> earlier and not overload the upload page with help content.
>
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/projecthydra/sufia/issues/2007#issuecomment-224401387>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQBqv-SzzGg1LFbUfaa-_qzX12jeAxCpks5qJdJjgaJpZM4IbWU6>
> .
>


-- 
Ben Howell | Accessibility & User Experience Specialist
Design & Discovery | LIT | University of Michigan Library
bnhowell@gmail.com

**Comment by newmanld** [comment]
+1 to @justcolin and @heidisb for a pragmatic approach that avoids having to reach consensus.  Implementors can customize as needed.  Each institution may very well have different approaches to rights selection, and different selection lists for rights statements.  

FYI, locally we are about to deploy a license wizard that gives people widget-like help (a modal) if they want it - but they can easily ignore it and choose a license from a simple drop down list if they already know what they want.  It does not display on mobile devices.  I said on #2003 that I would share screen shots.  See screenshots on our issue: https://github.com/uclibs/scholar_uc/issues/264.   

If we get strong user reaction either way I'll let people know.  @sfbetz and others in #2003 expressed how researchers have difficulty selecting a license - we hope this license wizard helps.  It's based on https://github.com/ufal/public-license-selector.

**Comment by mtribone** [comment]
+1 to a small set of core or default rights. Am I following along with previous conversations that the items in the list of rights will link to documentation replacing the modal?

**Comment by justcolin** [comment]
@mtribone: the current suggestion is no link, just a one to two sentence bit of help text like all the other fields. If people want to add a link to further documentation they can do so themselves. The argument being that because there is such a wide range of uses for the rights field from institution to institution we should probably do the very minimum and encourage everyone to customize the help text to meet their own needs.

**Comment by mtribone** [comment]
@justcolin Okay. We'll handle the documentation per @heidisb 's suggestions above and look at some of the examples that you have provided above in ScholarSphere.

**Comment by jonearley** [comment]
My vote is for a dropdown with help text that links to rights/license documentation.

**Comment by mtribone** [comment]
@justcolin So the following list will be edited to be a smaller, core set of rights and help text will be added above like the other fields. Is anyone actively working on this issue along with the other help text? Are we asking the community to define the core rights or is this something that the assignee can handle? What action needs to be taken to resolve this issue?


![screen shot 2016-06-08 at 9 27 53 am](https://cloud.githubusercontent.com/assets/4163828/15895835/5acf5c18-2d5b-11e6-95bd-70c506d49c69.png)

**Comment by justcolin** [comment]
@mtribone: Since it seems like we have consensus I will go ahead and put in a pull request to add the help text and tag you all to make sure the wording is good for everyone.

As for what rights go in the list, I am fine with the current list but am open to suggestions. Since that is separate from the original purpose of this ticket I'd recommend someone open up a seperate issue to discuss what should go in the list (unless people think the current list of rights options is good enough).

**Comment by justcolin** [comment]
(I am in a meeting for the next 1 million years, but will try to get to it over lunch.)

**Comment by newmanld** [comment]
Maybe as relevant as what goes in the default list is a straightforward way for adopters to modify it, given the discussion above re wide range of uses for the rights field likely to vary from institution to institution.  And if an institution changes the choices post implementation - say from CC 3.0 to 4.0, or CC U.S. to International, I assume that the license selected at the time of work submission will continue to be stored and display as it was selected, on that earlier submitted work?

**Comment by mjgiarlo** [comment]
A @hackmastera sighting!!!

**Comment by mjgiarlo** [comment]
@justcolin thank you for taking this on and for leading the group through a productive conversation!
