### ISSUE TITLE
Batch create error

### ISSUE THREAD

**Issue by hectorcorrea** [projecthydra/sufia#2024]
### Descriptive summary

When using Batch Create, if the process fails because a missing tool (e.g. Libre Office / soffice) we get an exception message and it seems to stop processing the rest of the files being uploaded.

### Expected behavior
The user should see a more user-friendly error message (instead of an exception) and the processing of the rest of the files should not stop.

### Actual behavior
Users see an exception message and not all the files are processed.

### Steps to reproduce the behavior

1. Make sure `soffice` is not in your path.
1. Launch Sufia (bundle exec rails server)
1. Go to Batch create
1. Add a `.docx` file and two images. Sufia will throw an error when processing the `.docx` file because if won't find `soffice`
1. Enter all the required metadata
1. Submit the form.

(Remember to add `soffice` again to your path)

**Comment by jcoyne** [comment]
I suspect the rest of the files stop because you are using the default ActiveJob "immediate runner" implementation rather than a real queuing backend.

**Comment by jcoyne** [comment]
Also, in production, they would never see an error here, the exception would be reported in the queuing framework.

**Comment by atz** [comment]
Right, it would be a different asynchronous thread (likely on a different system) in production.  There would be no "moment" for the exception to interrupt a user-facing process.  

I would categorize this as `WONTFIX`.  I want the worker to throw an exception when dependencies are not installed.  If that means the exceptions get through to the browser using `:inline` backend in development mode, that's fine.  Probably preferable.

**Comment by cam156** [comment]
@hectorcorrea I just tested this with resque turned on.  The soffice ones failed but others did work.  I think it would be ok to close the issue.  What do you think?

**Comment by hectorcorrea** [comment]
@cam156 agreed.
