### ISSUE TITLE
Admin user woes

### ISSUE THREAD

**Issue by hectorcorrea** [projecthydra/sufia#2032]
Following the instructions at https://github.com/projecthydra/sufia/wiki/Sufia-Management-Guide#admin-users to setup an admin does not work out of the box.

The problem seems to be that `current_user.admin?` returns true since it looks at the Roles database table but CurationConcerns implementation of `admin?` does something different (https://github.com/projecthydra-labs/curation_concerns/blob/master/app/models/concerns/curation_concerns/ability.rb#L40)

Currently we need to patch the `Ability` class created inside the internal_application as follow to get Sufia to recognize an editor user properly:

```
  def editor_abilities
    super
    if current_user.admin?
      can :create, TinymceAsset
      can [:create, :update], ContentBlock
    end
  end
```

@mjgiarlo @awead

**Comment by mjgiarlo** [comment]
Tagging CurationConcerns folks to see if they want this work done at that level: @tpendragon @escowles @jcoyne @jpstroop

**Comment by escowles** [comment]
It looks like the relevant models are Sufia-specific, but if there's a good way to resolve the two different ways of doing the role check, then doing that in CC sounds good to me.

**Comment by mjgiarlo** [comment]
Yeah, CC and Sufia should do the same thing w/r/t role checking.

**Comment by mjgiarlo** [comment]
Now that we've got Hyrax cooking up, and only one scheduled 7.x release, I'm not inclined to take this up in Sufia.

**Comment by mjgiarlo** [comment]
(Re-open if you're inclined to work on this.)
