### ISSUE TITLE
Test CC fix for missing collection keywords once 1.0.0.beta3 release is out

### ISSUE THREAD

**Issue by bmquinn** [projecthydra/sufia#2033]
### Descriptive summary

Creating a new Collection with a keyword produces an error

### Expected behavior

Creating a Collection with a keyword should succeed.

### Actual behavior

Receive an error: undefined method `keyword' for Sufia::CollectionPresenter

### Steps to reproduce the behavior

1. Go to Create New Collection page "/collections/new"
2. Add a title (required) and a keyword to the form.
3. Hit Create Collection button (should receive error)

### Related work

Currently working on a branch in CurationConcerns to fix this.

**Comment by mjgiarlo** [comment]
Let's point Sufia at the latest in CC and confirm this is also fixed in Sufia. Thanks, @bmquinn! I'm assigning this to you for now.

**Comment by bmquinn** [comment]
```
➜  .internal_test_app git:(master) bundle show curation_concerns 
/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/curation_concerns-e13ffd4ec22c
```
![sufia_keyword](https://cloud.githubusercontent.com/assets/1395707/15364312/b46c80dc-1ce1-11e6-94a2-48c449903a18.png)

Looks like it works!

**Comment by mjgiarlo** [comment]
Thanks, @bmquinn! Closing.
