### ISSUE TITLE
Breadcrumb on works page does not include link to my works

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2041]
### Descriptive summary

In Sufia master When I go to a Work the bread crumbs include the dashboard, but not My Works.

Old code in ScholarSphere:
![screen shot 2016-05-18 at 9 57 50 am](https://cloud.githubusercontent.com/assets/1599081/15361429/78888270-1cdf-11e6-8c45-7c7300cfffa3.png)

New Code in Sufia spec internal:
![screen shot 2016-05-18 at 9 59 54 am](https://cloud.githubusercontent.com/assets/1599081/15361430/7b5224b6-1cdf-11e6-97f3-22a86bbdc922.png)

### Expected behavior

I should see breadcrumbs at the top of the show page to get me to either my dashboard or My listing of works.

### Actual behavior

I see only a breadcrumb for the dashboard.

### Steps to reproduce the behavior

1. Create a work
1. Then click on My Works from the drop down menu
1. And I should see My Works in the bread crumbs

**Comment by mjgiarlo** [comment]
Good eye!

**Comment by cam156** [comment]
@mjgiarlo Features tests in ScholarSphere caught this...

**Comment by mjgiarlo** [comment]
Nice, @cam156. Maybe we should pull some of those back over to Sufia.
