### ISSUE TITLE
Title tag (in the html header) on work show page has brackets

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#2052]
We should join the titles or just pick the first one.
```html
<html lang="en" prefix="og:http://ogp.me/ns#">
  <head>
...
    <title>[&quot;Stanford logo&quot;]</title>
```

**Comment by atz** [comment]
IMO, primary title is enough for title element.  In a modern tabbed browser context, the screen real estate is pretty small and the primary title should be enough for semantic purposes.

**Comment by mjgiarlo** [comment]
Yes, :+1: to picking the first one.
