### ISSUE TITLE
My Works missing "show details" button

### ISSUE THREAD

**Issue by hectorcorrea** [projecthydra/sufia#2054]
### Descriptive summary

According to the wire frames the "My Works" view should include an option to allow to the user to see the details of the works in the list. The wire frames propose a ">" little icon next to each work https://wiki.duraspace.org/display/hydra/My+Works+-+Phase+1+-+UI+Wireframe#mockup_p1-works-my_works

This is how Sufia looks at the moment:

![screen shot 2016-05-19 at 9 03 10 am](https://cloud.githubusercontent.com/assets/568286/15394438/e89d6e10-1da0-11e6-8d7b-6be60cf48c2e.png)
### Expected behavior

An ">" icon should be displayed next to each work to allow the user to view the details of each work.
### Actual behavior

No ">" icon exists.
### Steps to reproduce the behavior
1. Go to My Works
2. Look at the list of works
3. Wait a long time before realizing that the icon is just not gonna show up on its own.

**Comment by jcoyne** [comment]
I wouldn't call this a bug. It was a back logged feature request.

**Comment by jcoyne** [comment]
Probably not required for 7.0.0 either

**Comment by mjgiarlo** [comment]
@hectorcorrea Can you scan the backlog for any related tickets? If we don't have any, let's keep this around, else let's :boom: it. Moving to 7.1.0.

**Comment by cam156** [comment]
Show the File Format as the representative file of the work. Only one file format is indexed.

Open close JS is in Batch Edit.

**Comment by mjgiarlo** [comment]
Review this fix from SS: https://github.com/psu-stewardship/scholarsphere/commit/f476a347ad4bf604f053e24a2256a5c798e9a10a
