### ISSUE TITLE
Collection Creator help text includes double quote and gets cut off

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2056]
### Descriptive summary

In Sufia 6 & 7 The help text for a collection creator includes double quotes which cause trouble in the html.

### Expected behavior
![screen shot 2016-05-19 at 10 29 30 am](https://cloud.githubusercontent.com/assets/1599081/15397139/fb90c4de-1dac-11e6-87c1-11b672a70988.png)

### Actual behavior
Sufia 6: Sows crazy text
![screen shot 2016-05-19 at 10 21 27 am](https://cloud.githubusercontent.com/assets/1599081/15397151/0460e58a-1dad-11e6-80d2-b1f8cb3744cf.png)

Sufia 7: Looks ok but is cut off
![screen shot 2016-05-19 at 10 28 31 am](https://cloud.githubusercontent.com/assets/1599081/15397189/29c0728c-1dad-11e6-80c2-4aac25f88838.png)

### Steps to reproduce the behavior

1. Go to collection creat page
1. And click on creator help bubble

### Related work

Patch in ScholarSphere that removes the external quotes and uses single quote
https://github.com/psu-stewardship/scholarsphere/commit/5701311f5542266d5ccf283ffc0bbf2c53a76099

**Comment by mjgiarlo** [comment]
Thx for taking this on, @atz
