### ISSUE TITLE
Collection creation layout issues

### ISSUE THREAD

**Issue by atz** [projecthydra/sufia#2063]
On collection creation page, e.g. http://localhost:3000/collections/new 

- `* indicates required fields` breaks formatting, floats to the right, big and red 
- No fields are marked as required, but at least title actually is required
- Visibility radio buttons are positioned partially off the page.  

We already fixed the visibility display on multiple other interfaces, but apparently did not do so here.  If possible, we should get rid of application specific partials and use partials from CurationConcerns.

Example 1:
![screen shot 2016-05-19 at 5 24 06 pm](https://cloud.githubusercontent.com/assets/109954/15413604/db3ca308-1de6-11e6-89e1-dd77abbed937.png)

Example 2:
![screen shot 2016-05-19 at 5 24 45 pm](https://cloud.githubusercontent.com/assets/109954/15413605/dc9e10a6-1de6-11e6-965b-d5a3147a0ed2.png)

**Comment by atz** [comment]
Similar radio button button issue in #2064

**Comment by mtribone** [comment]
@mjgiarlo  Perhaps we should hold on this one until the work by @jonearley and @justcolin has been completed and merged?

https://github.com/projecthydra/curation_concerns/pull/811#issuecomment-221060536

**Comment by justcolin** [comment]
I can also look into fixing this along with the other touch ups that we are doing to the Visibility field.

**Comment by mtribone** [comment]
@justcolin Yeah, man. I feel that this ticket overlaps your work.

**Comment by justcolin** [comment]
Just to double check that I am understanding this issue, the only thing that is wrong is that the radio buttons are moving too far to the left?

**Comment by mtribone** [comment]
That has been fixed by @jenlindner in CC and will be merged soon. I think it is important to align the collection creation page with the work creation page. The other issues that @atz references above are being addressed by your work and @jonearley 's work.

**Comment by jenlindner** [comment]
It was merged, it just hasn't been released.

On May 24, 2016, at 7:44 AM, Michael Tribone <notifications@github.com<mailto:notifications@github.com>> wrote:


That has been fixed by @jenlindner<https://github.com/jenlindner> in CC and will be merged soon. I think it is important to align the collection creation page with the work creation page. The other issues that @atz<https://github.com/atz> references above are being addressed by your work and @jonearley<https://github.com/jonearley> 's work.

-

**Comment by jcoyne** [comment]
Released in cc 1.0.0.beta4, but rubygems is having trouble now: https://status.rubygems.org/incidents/trjgn655nf6b

**Comment by jenlindner** [comment]
Ah. Thanks.

On May 24, 2016, at 7:59 AM, Justin Coyne <notifications@github.com<mailto:notifications@github.com>> wrote:


Released in cc 1.0.0.beta4, but rubygems is having trouble now: https://status.rubygems.org/incidents/trjgn655nf6b

-

**Comment by mjgiarlo** [comment]
Sounds good, @mtribone. Let's come back to this once all PRs have been merged?

**Comment by jenlindner** [comment]
Looks good with curation_concerns-1.0.0.beta4.

**Comment by jenlindner** [comment]
The PRs addressing layout and help text have been merged here and in CC so going to close this. The missing header key is also being addressed.
