### ISSUE TITLE
Passing collection_ids into GenericWorkActor

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2066]
### Descriptive summary

When uploading a file via the UI, a `collections_ids` property is passed via the params hash. This does not cause a problem if you're uploading or creating a work in the web application. However, passing this parameter in a unit test of GenericWorkActor results in `ActiveFedora::ObjectNotFoundError`. Ex:

``` ruby
let(:user)  { create(:user) }
let(:work)  { GenericWork.new }
let(:actor) { CurationConcerns::CurationConcern.actor(work, user) }

let(:parameters) do
  {
    "title"=>["Sample Title"],
    "creator"=>["test"],
    "keyword"=>["test"],
    "rights"=>["http://creativecommons.org/licenses/by-nc-sa/3.0/us/"],
    "collection_ids"=>[""]
  }
end

actor.create(parameters)
=> ActiveFedora::ObjectNotFoundError
```

The cause of the problem is:
https://github.com/projecthydra/curation_concerns/blob/master/app/actors/curation_concerns/actors/add_to_collection_actor.rb#L31

Because an empty string is getting passed. However, this problem is not present in the UI. Is there some aspect of the form or view that's omitting arrays of these empty strings?

**Comment by awead** [comment]
I can confirm this behavior in the UI as well if you alter `self.terms` in the GenericWorkForm. You must inherit all terms from `Sufia::Forms::WorkForm`.

**Comment by jcoyne** [comment]
In the form, those empty fields are typically removed by https://github.com/projecthydra/hydra-editor/blob/master/app/forms/hydra_editor/form.rb#L58-L64

**Comment by awead** [comment]
@jcoyne yeah, I think the issue is that if `collection_ids` isn't in `self.terms` it'll never get run through that method to clean it out.

**Comment by mjgiarlo** [comment]
@awead can you tag this issue with some labels? It's not clear to me whether this is a bug or what.

**Comment by awead** [comment]
@mjgiarlo I don't think it's a bug, exactly, but it pertains to how one would override and add additional properties. For example, you'll have to inherit self.terms whether you use the terms or not. So, it should be captured in documentation, perhaps a refactor of GenericWorkForm that makes it more explicit as to which terms you *have* to have in your form versus which are just optional metadata.

**Comment by jcoyne** [comment]
@awead, @mjgiarlo what milestone for this ticket?

**Comment by awead** [comment]
I think it just needs to be linked with a documentation issue, related to @mjgiarlo's customizing metadata wiki page, and then closed.
