### ISSUE TITLE
Document how to override metadata

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2072]
### Descriptive summary

Users should be able to add new properties to their Sufia 7 applications, as well as remove existing ones, with certain exceptions. We should document how developers can do this. It would include steps regarding model, form and view changes.
### Related work
#2066

**Comment by mjgiarlo** [comment]
Please use this wiki page for the documentation: https://github.com/projecthydra/sufia/wiki/Customizing-Metadata (We already have this page for 6.x doc: https://github.com/projecthydra/sufia/wiki/Customizing-Metadata-(Sufia-6.x))

And feel free to consolidate. (See: https://github.com/projecthydra/sufia/wiki/Customizing-Metadata:-nested-attributes,-part-1 and https://github.com/projecthydra/sufia/wiki/Customizing-Metadata:-nested-attributes,-part-2)

**Comment by mjgiarlo** [comment]
Tagging @jhallida
