### ISSUE TITLE
Investigate why Form#model_attributes isn't preventing issue #2051

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#2073]
Is it because it only handles empty string an not nil?  If we update our assumptions, are there any changes that should be made to the changes in https://github.com/projecthydra/sufia/pull/2070 ?

**Comment by atz** [comment]
ref: #2051

**Comment by atz** [comment]
In Sufia, we have:
- `Sufia::Forms::WorkForm < CurationConcerns::Forms::WorkForm`
- `Sufia::Forms::BatchEditForm < CurationConcerns::Forms::WorkForm`
- `Sufia::BatchUploadForm < Sufia::Forms::WorkForm`

Should `BatchUploadForm` be in the `Forms` module?  More importantly, if batch *upload* is able to inherit from `Sufia::Forms::WorkForm`, what is the reason batch *edit* doesn't as well?  Just trying to get some context here.

**Comment by jcoyne** [comment]
👍 to consistency.

**Comment by mjgiarlo** [comment]
:+1: to `BatchUploadForm` being in the `forms` module.

**Comment by mjgiarlo** [comment]
As to the inheritance hierarchy, I'm not sure why the `BatchEditForm` inherits from CC's work form rather than Sufia's form. I'd be happy to see those made consistent as well.

**Comment by atz** [comment]
@jcoyne how do I test to reproduce #2051?

**Comment by jcoyne** [comment]
@atz you need to have one of your file uploads fail and one succeed. I'm not sure how you can create that condition. Perhaps turn off fedora as you are uploading the first file?

**Comment by atz** [comment]
@jcoyne Can you describe the necessary timing and location of the failure?  My interpretation is that this is during non-batch work creation, drag-drop a couple files, while they auto-upload, first succeeds, second fails.  Is the failure specifically between the jQuery file-uploader and the webserver? To the browser, does that look like a 500 error or a dropped connection (killed socket)?

**Comment by atz** [comment]
Is it appropriate to test this at the controller level?

**Comment by jcoyne** [comment]
Yes, this could be a controller test

**Comment by atz** [comment]
On one level, the problem is about filtering the empty uploaded file "line" from the post to create the work.  But on another, it might also be about the jQuery file-uploader reacting appropriately to failure on the server side to avoid adding the empty line (or removing it if already added).  The approaches are not exclusive.

**Comment by jcoyne** [comment]
I think the jquery behaved just fine. It told me there was an error when there was one.  It was the server which didn't handle that input gracefully.  It is fixed now, but I'm just wondering if the patch in #270 was really fixing the problem in the right place.

**Comment by atz** [comment]
IMHO, this test is formulated correctly: 
https://github.com/projecthydra/sufia/pull/2070/files#diff-a30fe0504497f98d445b3145317610cfR24

I tried writing a separate test but it largely resembled that one.  I will strengthen the `allow` into an `expect`, but probably not do much more on this.
