### ISSUE TITLE
Improve UI for required field labels

### ISSUE THREAD

**Issue by bnhowell** [projecthydra/sufia#2076]
### Descriptive summary

The current required markings for required metadata fields in the create new work metadata page in Sufia 7 are overly complicated. They have some usability issues and could be made much simpler. 

### Expected behavior

Users should be able to quickly perceive if a metadata field is required or not.

### Challenges with current UI

1. Recognition over recall: Don't make users think about the meaning of symbols or hunt for a small symbol to identify required fields
2. The * symbol along with the appearing/disappearing required label distract users from their task (filling out the form) due to complicated instances of interactions/visual feedback 
3. Low vision users may miss the * symbol

### Solutions

The clearest and simplest solution for required fields would be a permanent (required) label next to each required metadata field (fig.1). This type of label would be the most perceivable and equitable way to communicate required fields to all users.
![screen shot 2016-05-18 at 4 53 59 pm](https://cloud.githubusercontent.com/assets/16804543/15441209/9ead73e2-1ea7-11e6-82a3-ab34b2198a28.png)

**Comment by mjgiarlo** [comment]
Looks good, @bnhowell. Thanks!

What do ye @projecthydra/sufia-ui-ux-advisors think?

Do you want this in CurationConcerns, @tpendragon @escowles @jpstroop @jcoyne?

**Comment by jpstroop** [comment]
I don't see why not.

**Comment by justcolin** [comment]
If we push this into Curation Concerns I believe this will just involve changing the defaults on some config files and adding a line or two of CSS.

**Comment by mjgiarlo** [comment]
And then of course we'll need to make sure we don't override this anywhere in Sufia as well. I support doing this in CC, too.

**Comment by jonearley** [comment]
Another usability win, @bnhowell. Thanks!

I will start a Curation Concerns pull request based on the support for this idea.

**Comment by mjgiarlo** [comment]
:clap:

**Comment by jonearley** [comment]
<img width="569" alt="screen shot 2016-05-24 at 10 26 51 am" src="https://cloud.githubusercontent.com/assets/1678665/15507548/183b8600-219a-11e6-9cbf-68789789317d.png">
<img width="569" alt="screen shot 2016-05-24 at 10 28 51 am" src="https://cloud.githubusercontent.com/assets/1678665/15507623/602cc2bc-219a-11e6-9bd6-e3f2f7976a04.png">
<img width="567" alt="screen shot 2016-05-24 at 10 29 02 am" src="https://cloud.githubusercontent.com/assets/1678665/15507627/61cf9464-219a-11e6-9cd5-f675c6916db3.png">

@projecthydra/sufia-ui-ux-advisors thought and suggestions on what the required tag color should be? The screenshots are using bootstrap defaults: danger, info, and primary.

**Comment by jonearley** [comment]
The light blue bootstrap info color fails a contrast check (Contrast Ratio: 2.09:1). So we can rule that one out.

**Comment by jonearley** [comment]
Red seems aggressive to me and blue looks like a tiny button.

**Comment by justcolin** [comment]
I agree that the "danger" red tends to stick out too strongly on the page, especially if there are a lot of required fields on a page so—since "info" cyan is too low contrast—my vote is for the "primary" blue color or to dull the red down to more of a maroon.

The other option is to modify the Bootstrap variables to make the colors have better contrast, then recompile or dynamically compile Bootstrap, but that's a lot of effort for one color.

**Comment by simosacchi** [comment]
I vote for Red, it might look aggressive (especially when repeated on many fields one after the other), but if these are the choices, red at least focuses the attention (and it is used many times to indicate required fields, most of the times as a red "*")

**Comment by jonearley** [comment]
<img width="568" alt="screen shot 2016-05-24 at 10 44 16 am" src="https://cloud.githubusercontent.com/assets/1678665/15508196/7da53160-219c-11e6-895a-ec2aa1fea7c9.png">

This green is the bootstrap success color.

**Comment by jonearley** [comment]
Turns out bootstrap danger red doesn't pass the contrast check either (Contrast Ratio: 3.96:1). My vote would be to use primary blue or a maroon color.

<img width="560" alt="screen shot 2016-05-24 at 10 50 45 am" src="https://cloud.githubusercontent.com/assets/1678665/15508554/f2f448ce-219d-11e6-97be-0916cd1f8ff4.png">

**Comment by jcoyne** [comment]
You should use info, and if that contrast doesn't work for you, we should
set the info color to something appropriate. It *is* info that we are
trying to convey, so use the semantically appropriate class.

**Comment by justcolin** [comment]
If we set the info color to something appropriate it means we really should be dynamically compiling Bootstrap so we can modify the color variables. Are we okay with that?

**Comment by jcoyne** [comment]
We are already compiling it dynamically

**Comment by justcolin** [comment]
Cool, then we may want to open a separate ticket to go through all the color variables to make sure they all meet WCAG 2.0 AA contrast requirements. @jonearley, do you want to work on that?

**Comment by jcoyne** [comment]
Has anyone filed a bug with bootstrap regarding the contrast ratio for the default contrast of the info label?

**Comment by justcolin** [comment]
@jcoyne: Yes, people have tried in the past. Some examples:

https://github.com/twbs/bootstrap/issues/3572

**Comment by justcolin** [comment]
@jcoyne: Yes, some people have tried in the past with varying degrees of success/failure, and there are a number of accessible extensions/themes on top Bootstrap that people have made to address these problems.

Bootstrap 4 may solve some of these issues; I haven't checked yet.

**Comment by justcolin** [comment]
https://github.com/twbs/bootstrap/pull/19693

**Comment by jcoyne** [comment]
Thanks for checking.

**Comment by justcolin** [comment]
Do we want to switch to one of the accessible Bootstrap themes? Something with only minor tweaks?

Thoughts @mjgiarlo and @projecthydra/sufia-ui-ux-advisors?

**Comment by justcolin** [comment]
I would be in favor of switching over for now, then reevaluating when we switch to Bootstrap 4.

**Comment by jonearley** [comment]
My vote would be for using the "label-info" class for the required element, but only if we open another issue to improve theme color accessibility. It should be as easy as using new variables. Similar to https://github.com/twbs/bootstrap/pull/19693 for example.

**Comment by newmanld** [comment]
Weighing in as just one of the sufia-ui-ux-advisors: 
It seems that this is a good opportunity to improve accessibility and we shouldn't let the contrast issues get past us.  Either switching to an accessible theme - per @justcolin; or making our own tweaks similar to https://github.com/twbs/bootstrap/pull/19693, per @jonearley  - whatever is most efficient prior to switching to Bootstrap 4.  

I like the Red to strongly signal required - if the contrast can be improved enough.  

Kind of surprised that just using an asterisk to indicate a required field is an accessibility issue - just because it is ubiquitous.

**Comment by bnhowell** [comment]
what about this color?

On Tue, May 24, 2016 at 10:41 AM, justcolin <notifications@github.com>
wrote:

> I agree that the "danger" red tends to stick out too strongly on the page,
> especially if there are a lot of required fields on a page so—since "info"
> cyan is too low contrast—my vote is for the "primary" blue color or to dull
> the red down to more of a maroon.
>
> The other option is to modify the Bootstrap variables to make the colors
> have better contrast, then recompile or dynamically compile Bootstrap, but
> that's a lot of effort for one color.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/projecthydra/sufia/issues/2076#issuecomment-221292988>
>



-- 
Ben Howell | Accessibility & User Experience Specialist
Design & Discovery | LIT | University of Michigan Library
bnhowell@gmail.com

**Comment by newmanld** [comment]
@bnhowell - I don't see the new color in the previous comment?

**Comment by bnhowell** [comment]
Sorry it didn't seem to upload correctly. (It looked like the maroon that
Jon Earley posted previously)

On Tue, May 24, 2016 at 12:53 PM, Linda Newman <notifications@github.com>
wrote:

> @bnhowell <https://github.com/bnhowell> - I don't see the new color in
> the previous comment?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/projecthydra/sufia/issues/2076#issuecomment-221334698>
>



-- 
Ben Howell | Accessibility & User Experience Specialist
Design & Discovery | LIT | University of Michigan Library
bnhowell@gmail.com

**Comment by newmanld** [comment]
@bnhowell - I think that the maroon that @jonearley posted works, and stands out better than the blue.  Obviously this is subjective!  

This is the maroon? 
![image](https://cloud.githubusercontent.com/assets/3521707/15513092/2140af48-21b1-11e6-9b71-b2c035fb0e6b.png)

**Comment by mtribone** [comment]
I could go either way with the color of the "required" label as long as the contrast is improved. The red is ubiquitous, but I do see the semantic value of the blue "info" class. I say, "Dealer's choice."

**Comment by justcolin** [comment]
@newmanld: Sadly a number of common UI patterns are problematic for accessibility.

**Comment by mjgiarlo** [comment]
:+1: to @jonearley's approach.

**Comment by mtribone** [comment]
@mjgiarlo Can we close this or wait until it makes it into the Collections creation UI?

**Comment by mjgiarlo** [comment]
@mtribone because #2106 is already ticketed, I'm inclined to close this. Let's make sure that's OK with the Michigan crew: @justcolin @bnhowell @jonearley ?

**Comment by bnhowell** [comment]
Unless I'm missing something in either of these tickets, it looks ok to
close #2076.

On Thu, Jun 2, 2016 at 4:33 PM, Michael J. Giarlo <notifications@github.com>
wrote:

> @mtribone <https://github.com/mtribone> because #2106
> <https://github.com/projecthydra/sufia/issues/2106> is already ticketed,
> I'm inclined to close this. Let's make sure that's OK with the Michigan
> crew: @justcolin <https://github.com/justcolin> @bnhowell
> <https://github.com/bnhowell> @jonearley <https://github.com/jonearley> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/projecthydra/sufia/issues/2076#issuecomment-223413479>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQBqv9Jc-vO4EkSyyXMzrj2UOU_LdLKCks5qHz4tgaJpZM4IjidY>
> .
>



-- 
Ben Howell | Accessibility & User Experience Specialist
Design & Discovery | LIT | University of Michigan Library
bnhowell@gmail.com

**Comment by mjgiarlo** [comment]
OK. Closing. Thanks, y'all. (Feel free to re-open if I was hasty, other Michiganders!)
