### ISSUE TITLE
locales file values should avoid double encoding

### ISSUE THREAD

**Issue by atz** [projecthydra/sufia#2077]
The locales files like `config/locales/sufia.en.yaml` should avoid double encoding values to accomplish HTML-injection.  This *should* be a default rails behavior as described here:
    http://guides.rubyonrails.org/i18n.html#using-safe-html-translations

But we are apparently working around or disabling that default.  Example:
```yaml
based_near_html: "A place name related to the file, such as its site of publication, or the city, state, or country the file's contents are about. Calls upon the GeoNames web service (&lt;a href=&quot;http://www.geonames.org&quot;&gt;http://www.geonames.org&lt;/a&gt;)."
```

In a `html` field value we should be able to use regular `<a>` values (as in the `simple_form.en.yml` example).  Instead we get strings that are html_decoded in order to inject them into HTML.  o_0

**Comment by atz** [comment]
Broader issue: in a project that aspires to be actively translated, intermingling markup and language strings is counter-productive.  Your language expert contributors should not be expected to be coders also.

**Comment by mjgiarlo** [comment]
Keys that look messed up include:

* in `sufia.metadata_help.file_set.`
  - [ ] `title`
  - [ ] `keyword`
  - [ ] `subject`
  - [ ] `creator_html`
  - [ ] `based_near_html`
  - [ ] `rights`
* in `sufia.metadata_help.collection.`
  - [ ] `creator_html`

All of these keys should end in `_html`, and there shouldn't be any `&lt;`/`&gt;` jazz. (Not sure if we need the `&quot;`s either.

**Comment by atz** [comment]
That's what's weird about that bug I just resolved: it was a `_html` field, but the fix was to encode the HTML anyway.

**Comment by atz** [comment]
Note: that isn't **`sufia.metadata_help.file_set...`**, it is **`simple_form.metadata_help.file_set...`**, which means alterations here (in the name or encoding of the value) would likely require corresponding changes upstream in the CurationConcerns/Hydra Editor code that invokes them.

**Comment by atz** [comment]
Now we can see why this method of HTML injection/encoding shifting sucks.  A consumer does not get the latitude to decide that an upstream text key should now contain html.  The encoding expectations are set by the key name.  We should attempt to avoid injecting markup this way.

**Comment by mjgiarlo** [comment]
:clap:

**Comment by justcolin** [comment]
Since @mjgiarlo asked for a comment here: I like HTML moving out of these config files, but future work will want to introduce links (no other HTML) into help text. Creating separate template files just for 80 characters of help text will be confusing for people to maintain.

**Comment by justcolin** [comment]
In all other situations I think the HTML should be removed, but the help text will need a link at some point soon (specifically the Rights field).

**Comment by justcolin** [comment]
See #2003 and #2007 for a little discussion about this.

**Comment by atz** [comment]
OK, I went back to the ticket I hit before, and it was to shift `"` to `&quot` in an HTML field, so that was legit (and required) by the rails convention.  I am less paranoid about something in the stack messing with the default rails i18n behavior now.
