### ISSUE TITLE
Work does not show any help text by default

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2080]
### Descriptive summary

In Sufia 7.0

### Expected behavior

Work help tags would show the help

![screen shot 2016-05-24 at 11 01 57 am](https://cloud.githubusercontent.com/assets/1599081/15508809/f752db3c-219e-11e6-9c7b-e76bff16b530.png)
### Actual behavior

![screen shot 2016-05-24 at 10 43 02 am](https://cloud.githubusercontent.com/assets/1599081/15508764/c831e730-219e-11e6-988b-0cfead1a4130.png)
![screen shot 2016-05-24 at 10 41 35 am](https://cloud.githubusercontent.com/assets/1599081/15508772/ca7f2070-219e-11e6-9403-364a7590757c.png)

### Steps to reproduce the behavior

1. Got to Add New Work
1. And then click on the help

### Related work

#2068
#2003

**Comment by cam156** [comment]
UNTESTED!!! https://github.com/projecthydra/sufia/blob/master/config/locales/sufia.en.yml#L239 should be `work:` instead of `file_set:`

**Comment by mjgiarlo** [comment]
@cam156 or `generic_work:` depending on how we're mapping models to the structure of the locale file.

This may be included in the work @jonearley or @fultonis are doing. Is that true, @mtribone? Or am I getting this confused with other work?

**Comment by mtribone** [comment]
@mjgiarlo Yes addressing the help text is part of their work.
