### ISSUE TITLE
Metadata no longer all linked

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2081]
### Descriptive summary

In Sufia 7 the work show page no longer links the metadata the same way that sufia 6 did.

### Expected behavior
![screen shot 2016-05-24 at 11 38 33 am](https://cloud.githubusercontent.com/assets/1599081/15510260/b461f442-21a4-11e6-942f-535b61ac7a7e.png)

### Actual behavior
![screen shot 2016-05-24 at 11 41 51 am](https://cloud.githubusercontent.com/assets/1599081/15510269/b96e5520-21a4-11e6-8e61-cc945583abbd.png)

### Steps to reproduce the behavior

1. Create a work and fill in metadata for  Language, Location, subject and keyword
1. Then visit the work show page

**Comment by cam156** [comment]
@mbklein It also looks like the links are broken.  
The facet creates this link, which finds the work:
`http://localhost:3000/catalog?f%5Bcreator_sim%5D%5B%5D=create`
The link in the show page creates this link, which does not find the work:
`http://localhost:3000/catalog?q=create&search_field=creator`

**Comment by mtribone** [comment]
@cam156 Good catch! I totally missed it when I worked on my PR for multiple titles and descriptions.

https://github.com/projecthydra/sufia/pull/2015

**Comment by mbklein** [comment]
Thanks @cam156. I'll look into that as well.

**Comment by mtribone** [comment]
Also get the `[...]` around the title of collections in relationships.

![screen shot 2016-05-31 at 10 58 22 am](https://cloud.githubusercontent.com/assets/4163828/15679123/ba76937c-271e-11e6-9c3e-035ad2038cd8.png)

**Comment by mjgiarlo** [comment]
@mbklein are you still on this ticket, or should we reassign? If the latter, do you have any in-progress branches to push?

**Comment by mbklein** [comment]
I do not have any lingering work on this, and I'm not sure when I'd be able to get to the issue @mtribone pointed out. Probably best to reassign.

**Comment by mjgiarlo** [comment]
Thanks, @mbklein!

**Comment by mjgiarlo** [comment]
Do you have cycles for this one, @mtribone?

**Comment by mtribone** [comment]
@mjgiarlo We are sprinting on the migration plan this week, but I can pick it up next week if it isn't needed this week.

**Comment by mtribone** [comment]
I'm guessing that there are some overrides in Sufia that are preventing https://github.com/projecthydra/curation_concerns/pull/819 from working properly?

**Comment by mtribone** [comment]
I'm guessing that the search results will need linked metadata, too?!

![screen shot 2016-06-07 at 12 47 12 pm](https://cloud.githubusercontent.com/assets/4163828/15866796/36ca25f8-2cae-11e6-9de7-41799e744e2b.png)

**Comment by mjgiarlo** [comment]
Yep, @mtribone, good call. If that feels scope creep-y to you, feel free to break that out into a different PR. If not, cool to include linked metadata in all the show/index contexts (work, catalog, collection, fileset, ... ?) in this PR. Up to you.
