### ISSUE TITLE
Fix help text that CC breaks

### ISSUE THREAD

**Issue by justcolin** [projecthydra/sufia#2085]
### Descriptive summary

projecthydra/curation_concerns#811 causes Sufia to break since it removes some input types that are no longer needed. A couple views have to be altered and some templates have to be moved into the locale configs to fix things and to finish #2003.

**Comment by justcolin** [comment]
Note: Sufia will not have this bug until projecthydra/curation_concerns#811 is pulled into CC and Sufia starts using that version of CC. This ticket is to note that that future bug has a fix in the works.

**Comment by mjgiarlo** [comment]
The CC PR is merged. :clap:

**Comment by justcolin** [comment]
@mjgiarlo: awesome! Now to fix the large array of bugs that PR causes...

**Comment by mbklein** [comment]
fixing_future_bugs++

**Comment by justcolin** [comment]
I am testing the UI to make sure that #2103 fixed this.

**Comment by mjgiarlo** [comment]
How goes, @justcolin?

**Comment by justcolin** [comment]
@jcoyne fixed most or all of these issues when he updated Sufia to use CC 1.0.0.beta5 a few days ago, so I scrapped my work in it.

I'm in the midst of a move but was planning on running the UI through a number of checks before closing this ticket.

**Comment by mjgiarlo** [comment]
:ok_hand:!

I'd like very much to get #2085 and #2003 closed this week if possible. Thanks, Colin.

**Comment by justcolin** [comment]
Fixed by #2103
