### ISSUE TITLE
flash message is not appropriate after work save

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2104]
### Descriptive summary

In Sufia 7.0 after you save a work you go to the work show page.  You then see a message about refreshing your dashboard.

### Expected behavior

Message should say "You may need to refresh this page to see the changes you made" rather than mentioning the dashboard.

### Actual behavior

![screen shot 2016-05-31 at 7 36 44 am](https://cloud.githubusercontent.com/assets/1599081/15673146/b837924e-2702-11e6-9ebd-86b0dea19e60.png)

### Steps to reproduce the behavior

1. Click on new work
1. Fill in Metadata
1. Choose a file
1. Click on accept
1. Click on Save
1. The flash message is shown at the top of the page

**Comment by atz** [comment]
Would we accept "you may need to refresh"?

**Comment by mjgiarlo** [comment]
I'm partial to `'You may need to refresh your browser.'`

Tagging @projecthydra/sufia-ui-ux-advisors for their input.

**Comment by atz** [comment]
The flash messages are good candidates for extraction into a template or translations file, also.  Currently duplicated in `batch_uploads_controller_behavior.rb` and `works_controller_behavior.rb`.

**Comment by newmanld** [comment]
To avoid someone thinking this means upgrade the browser (although this would of course be over-literal), how about
‘You may need to refresh this page in your browser.’

Or does ‘reload’ come across better than ‘refresh’?

If I mouse over the button in Chrome (Windows & Mac), it says ‘Reload this page’.  In Firefox (Windows & Mac), ‘Reload current page’.  In IE (Windows)‘Refresh’.  In Safari (Mac)‘Reload the current page’.

Looked for expert guidance on the web and didn’t find it.

**Comment by heidisb** [comment]
I'm partial to refresh. It feels like the more common vernacular, but I don't have any proof (other than Googling 'reload browser' and getting a lot of results with 'refresh' in it). 

I do agree with @newmanld about specifying page instead of (or in addition to) browser. In my past reference librarian life...it was shocking how many people did not know what a browser is even though they were using one.

My recommendation is: You may need to refresh this page...

**Comment by bnhowell** [comment]
+1 for: "You may need to refresh this page..."

On Wed, Jun 1, 2016 at 9:01 AM, Heidi Burkhardt <notifications@github.com>
wrote:

> I'm partial to refresh. It feels like the more common vernacular, but I
> don't have any proof (other than Googling 'reload browser' and getting a
> lot of results with 'refresh' in it).
>
> I do agree with @newmanld <https://github.com/newmanld> about specifying
> page instead of (or in addition to) browser. In my past reference librarian
> life...it was shocking how many people did not know what a browser is even
> though they were using one.
>
> My recommendation is: You may need to refresh this page...
>
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/projecthydra/sufia/issues/2104#issuecomment-222984935>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQBqv6i2i0s-k-cZe3u2jZEJSQibx2UIks5qHYKmgaJpZM4IqcQa>
> .
>



-- 
Ben Howell | Accessibility & User Experience Specialist
Design & Discovery | LIT | University of Michigan Library
bnhowell@gmail.com

**Comment by mjgiarlo** [comment]
Sounds like consensus to me. Thanks, all! :clap:
