### ISSUE TITLE
Sufia 6.x_stable Survey

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2128]
I would like to be able to survey my Sufia 6.x repository prior to migration, so that I can verify that every object has been moved.  Part of user story #2127 

I would like to create a executable I can run that creates a database table with survey information.

This will be done when I can run sufia_survey.exe in my sufia 6.x  application and I produce a database table that contains a list of my object ids and types [Collections & Files].

My executable should take the following options:
  --limit= [all (default), # of objects,]   # limit the number of items surveyed
  --id=  a list of Id (id1,id2)                 # only survey the given ids

**Comment by hackmastera** [comment]
This looks resolved. Ready to close, @cam156 ?

**Comment by cam156** [comment]
@hackmastera Since we have never run it on the production instance I left it open, but we can close it.  I'm good either way..

**Comment by hackmastera** [comment]
Absolutely keep it if it has value to you! Just thought it was ready to be cleaned up :)

**Comment by nrm149** [comment]
PSUSprint03
