### ISSUE TITLE
Import Metadata and content from Sufia 6.x to Sufia PCDM

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2137]
I would like to create an executable that reads json files created by the exporter #2136 to migrate the Sufia 6.x object to the correct Sufia PCDM representation of the object.

This will be done when I can run sufia_import.exe in my Sufia PCDM application, with a directory of json files.  The directory is expected to contain json files representing each of my Sufia 6.x objects. Each object will be migrated and translated to the correct Sufia PCDM object(s):
- Collection = Collection
- GenericFile = GenericWork & FileSet

My executable should take the following options:
--json_directory= directory                         # directory where files were exported 
--json_mapping= {class: directory_pattern, ...}   # Import the files discoverable by the directory pattern as objects of the class.  The hash defaults to { Collection:  coll__.json, GenericFile: gf__.json)

![slide5](https://cloud.githubusercontent.com/assets/1599081/15784044/c53cb81a-297e-11e6-9cda-8aac7f1fcd76.png)

**Comment by cam156** [comment]
@mjgiarlo Adding a comment here to address your question about IDs.  The PCDM version of the GenericFile (the GenericWork) should have the same ID as the Sufia 6.x version of the GenericFile.  The Sufia PCDM version of the Collection (the Collection) should have the same ID as the Sufia 6.x version of the Collection.

**Comment by mjgiarlo** [comment]
Thank you!
