### ISSUE TITLE
Generator should remove config/initializer/curation_concerns.rb

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#2139]
But we must call
```ruby
CurationConcerns.configure.register_curation_concern :generic_work
```
in some way.  Perhaps Sufia config can delegate that method to CurationConcerns?

**Comment by mjgiarlo** [comment]
Wait, why should the generator remove CC's initializer?

**Comment by jcoyne** [comment]
There's comments in there that indicates that it is the location to set the config variables.  But you should do that in `config/initializers/sufia.rb`. We don't want it to be confusing about where the configuration should go.

**Comment by mjgiarlo** [comment]
CC's configs are in the CC initializer and Sufia's are in the Sufia initializer, no? Maybe we need to do more work to clean up or disentangle the dependencies, if not. (:thought_balloon: I wonder if this mightn't be a good discussion point for the Architecture WG...)

**Comment by awead** [comment]
Also, what if I want to add additional concerns beyond just `GenericWork`?

**Comment by jcoyne** [comment]
@awead then you can't use Sufia 😉

**Comment by awead** [comment]
@jcoyne I'm doing that now: https://github.com/aic-collections/aicdams-lakeshore/blob/develop/config/initializers/curation_concerns.rb

**Comment by jcoyne** [comment]
@awead You're an edge case.

**Comment by awead** [comment]
@jcoyne at the moment perhaps, but others may wish to do similar things. I'm concerned that shutting off the options would leave adopters like AIC and @scossu with dead versions of Sufia, and no upgrade path. But with talk of a future CC/Sufia merger, this may be a moot point.

**Comment by jcoyne** [comment]
I'm absolutely not going to cut off that feature.  I was more thinking along the line that the sufia config should extend the CC config. Thus anything you can put in the CC config could go in the sufia config instead.

**Comment by awead** [comment]
OK. Sorry, I misunderstood the direction this was going. The above makes sense then.

**Comment by grosscol** [comment]
At the very least, the same config options shouldn't exist in both.  I recall changing the minter statefile location working in CC initializer but not in the sufia initializer.

**Comment by mjgiarlo** [comment]
At the very least, yes, @grosscol.
