### ISSUE TITLE
Migration::Import::GenericFileTranslator

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2141]
I would like to create an class that imports (and translates) a Sufia 6.0 exported Metadata file into a Sufia PCDM GernericWork and FileSet. See #2137 for executable.

This class should have the following methods:
* import - loops through the files found in the file_pattern and maps the GenericFile to a GenericWork and FileSet
  * parameter: file_pattern # an array of ids to process

This is done when I can:

Migration::Import::GenericFileTranslator.import produces a GenericWork and a FileSet for each file in the directory specified by the input pattern, and that each GenericWork contains the same descriptive Metadata as the GenericFile and has a FileSet with the same content as the GenericFile.

An example of an GenericFile Convertor can be found in Sufia [import_s7](https://github.com/projecthydra/sufia/blob/import_s6/lib/sufia/import/import_service.rb#L148)

**Comment by mjgiarlo** [comment]
@cam156 I haven't read these tickets in depth, but are you thinking that the import process will record the GF's ID and make sure the new GW also uses the same ID?

**Comment by cam156** [comment]
@mjgiarlo Short answer is yes. @hectorcorrea created some code to do the import export. I the export code exists in import_s6 branch.  It is old and a bit stale, but can be reused as a reference at the very least.

**Comment by mjgiarlo** [comment]
:ok_hand: I thought it might also be good to document that as a requirement in the related tickets, but if y'all already have this one accounted for, np. Thanks!

**Comment by cam156** [comment]
@mjgiarlo linked the code in the original descripotion. Not that we have to stick with what the code does, we can push the linking down if we believe that would be a better location...

**Comment by mjgiarlo** [comment]
I'm a big :+1: on providing continuity by using GF IDs for the new GWs.

**Comment by hackmastera** [comment]
> parameter: file_pattern # an array of ids to process

Not sure it's practical to loop through an array of ids, and I suspect that language is copied from the exporter design. I'd prefer to accept a directory containing files with names as output by the exporter (generic_file_[id].json). Only files in the given directory with this filename format will be processed.

objections?
