### ISSUE TITLE
Migration::Import::FileSetBuilder

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2144]
I would like to create an class that creates a Sufia PCDM Work based on Sufia 6.0 exported Metadata hash. See #2141 for calling service.

This class should have the following methods:
* Build - builds a FileSet based on the metadata passed in and attaches the content and versions history
  * parameter: options # metadata about the FileSet to be created

This is done when I can:

Migration::Import::FileSetBuilder.build produces a FileSet with the same descriptive Metadata as is passed in via options and has attached content and versions as specified in the options hash.

An example of an FileSet importer can be found in Sufia [import_s7](https://github.com/projecthydra/sufia/blob/import_s6/lib/sufia/import/import_service.rb#L35-L61)

**Comment by cam156** [comment]
How are we getting access to the content in the old F4 instance.  Do we need to open a connection using lower level connection.

**Comment by cam156** [comment]
This needs to make the connection to the work.

**Comment by cam156** [comment]
Created Date on the versions is not set correctly, otherwise this is complete

**Comment by nrm149** [comment]
PSUSprint03
