### ISSUE TITLE
Permissions form should use nested permissions

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#215]
Sufia needs to re-do how we use the permissions property. So, stop overriding it, and use the version that is in hydra-head.  Change the permissions form to use nested attributes and the associated javascript.

Nested permissions: https://github.com/projecthydra/hydra-head/blob/7b3bc48a56a93de19b2c71ac9545b1a26eb6b0bf/hydra-access-controls/app/models/concerns/hydra/access_controls/permissions.rb#L16

Here's where sufia overrides it: https://github.com/projecthydra/sufia/blob/3db966d44fd527ed624f8c6b67d09e0fcf59f2e2/sufia-models/lib/sufia/models/generic_file/permissions.rb#L20-L35

Form:
https://github.com/projecthydra/sufia/blob/208258e0f974c270e8f63af6a9a8a6daa2045137/app/views/generic_files/_permission_form.html.erb

Javascript:
https://github.com/projecthydra/sufia/blob/208258e0f974c270e8f63af6a9a8a6daa2045137/app/assets/javascripts/sufia/permissions.js

**Comment by mjgiarlo** [comment]
Code no longer in sufia.
