### ISSUE TITLE
Derivative creation fails

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2170]
### Descriptive summary

Using a newly generated internal test app, creating a new work results in a image magick failure:

```
convert /var/folders/yb/pbl7568x7073w02tyghtk3140000gp/T/mini_magick20160607-32012-gzuqee.jpg[0] /var/folders/yb/pbl7568x7073w02tyghtk3140000gp/T/mini_magick20160607-32012-1uae1i1.jpg` failed with error:
convert: unable to open image `/var/folders/yb/pbl7568x7073w02tyghtk3140000gp/T/mini_magick20160607-32012-gzuqee.jpg[0]': No such file or directory @ error/blob.c/OpenBlob/2705.
convert: no images defined `/var/folders/yb/pbl7568x7073w02tyghtk3140000gp/T/mini_magick20160607-32012-1uae1i1.jpg' @ error/convert.c/ConvertImageCommand/3257.
```

**Comment by jcoyne** [comment]
The filename and the uri are supposed to be different. `filename` is the staged upload file, and the `derivative_url` is where the generated thumbnail is.

**Comment by awead** [comment]
@jcoyne this is the error I'm seeing:
```
`convert /var/folders/yb/pbl7568x7073w02tyghtk3140000gp/T/mini_magick20160607-32012-gzuqee.jpg[0] /var/folders/yb/pbl7568x7073w02tyghtk3140000gp/T/mini_magick20160607-32012-1uae1i1.jpg` failed with error:
convert: unable to open image `/var/folders/yb/pbl7568x7073w02tyghtk3140000gp/T/mini_magick20160607-32012-gzuqee.jpg[0]': No such file or directory @ error/blob.c/OpenBlob/2705.
convert: no images defined `/var/folders/yb/pbl7568x7073w02tyghtk3140000gp/T/mini_magick20160607-32012-1uae1i1.jpg' @ error/convert.c/ConvertImageCommand/3257.
```

**Comment by jcoyne** [comment]
I'm unable to duplicate that.  Is it one particular image giving you trouble?

**Comment by awead** [comment]
@jcoyne hmm. I updated image magick today, so it's possible it's related to that. This is with a brand new Sufia app built off of master as of today.

**Comment by mjgiarlo** [comment]
@awead Ah, that's your problem! Sufia has bugs today.

It won't tomorrow.

:laughing:

**Comment by jcoyne** [comment]
Okay, let me try upgrading, but first, here's a working version:
```
$ convert --version
Version: ImageMagick 6.9.4-1 Q16 x86_64 2016-05-10 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2016 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib
```

**Comment by awead** [comment]
Minor different on my side:
```
awead@pooh .internal_test_app (master)$ convert --version
Version: ImageMagick 6.9.4-7 Q16 x86_64 2016-06-07 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2016 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules 
Delegates (built-in): bzlib fontconfig freetype jng jp2 jpeg lcms ltdl lzma png tiff webp x xml zlib
```

**Comment by jcoyne** [comment]
Updated to `6.9.4-7` and now I see the error you have.

**Comment by awead** [comment]
It seems to be adding `[0]` at the end of the file name. Because in my example, `/var/folders/yb/pbl7568x7073w02tyghtk3140000gp/T/mini_magick20160607-32012-gzuqee.jpg` is present but the error shows a file ending with `[0]`

**Comment by awead** [comment]
From my stack trace, the `[0]` is showing up for the first time in mini_magick (4.5.1) lib/mini_magick/image.rb line 349.

**Comment by jcoyne** [comment]
I suspect it's this: https://github.com/ImageMagick/ImageMagick/issues/214

**Comment by jcoyne** [comment]
Fixed in homebrew by https://github.com/Homebrew/homebrew-core/pull/1797
