### ISSUE TITLE
New Work: Move Related URL to Relationships tab

### ISSUE THREAD

**Issue by elrayle** [projecthydra/sufia#2173]
### Descriptive summary

Version: Sufia 7.x
UI change

For [New Work](http://localhost:3000/concern/generic_works/new)
- Metadata Tab:  Remove Related URL from Additional Fields
- Relationships Tab:  Add External Related URL according to the [UIWG wireframe](https://wiki.duraspace.org/x/QYZcB)
### Expected behavior

User should be able to set all relationships from the Relationship tab.  This includes relationships for the current work to a thing identified by a url (label: External Related URL)
### Actual behavior

Related URL is on the Metadata tab when Additional Fields button is pushed.
### Steps to reproduce the behavior

Current behavior:
1. Top menu -> Works -> [New Work](http://localhost:3000/concern/generic_works/new)
1. Click Metadata tab if not already selected
1. Click Additional Fields button
1. See Related URL field

Desired behavior:
1. Top menu -> Works -> [New Work](http://localhost:3000/concern/generic_works/new)
1. Click Metadata tab if not already selected
1. Click Additional Fields button
1. Verify Related URL field does not exist
1. Click Relationships tab
1. Verify Related External URL section appears as defined in [UIWG wireframe](https://wiki.duraspace.org/x/QYZcB)
### Related work
#2174 - same change for Works -> Batch Create

**Comment by mtribone** [comment]
@mjgiarlo @elrayle I'm struggling philosophically a little bit with moving Related (External) URL from the _metadata_ tab to the _relationships_ tab. The relationships tab implies to me that these are internal or system relationships–and the external URL is outside of the system. 

I need some help on this one. I can do the work, just having doubts.

**Comment by mjgiarlo** [comment]
@mtribone I'm on the fence about this change, too. I *assumed* this was a change vetted by the UI/UX WG but perhaps it's time to kick this around again. Tagging @projecthydra/sufia-ui-ux-advisors

**Comment by hackmastera** [comment]
good one to ask real users. i have a personal aversion to this as someone familiar with the data / interworkings but I fear this clouds my judgment.

**Comment by awead** [comment]
I think it belongs in metadata. As I understand it, the related URL is the equivalent of a user pasting in a link from a browser. Relationships, however, are resources identified by URIs. I would be okay if "related url" was in the relationships tab, but it should be enforced as a URI and not just a string that begins with _http_. On the other hand, I'm also with @mtribone that these relationships are intra-repo, and not inter-repo.

**Comment by bnhowell** [comment]
I tested a PI and their Graduate assistant a month and a half ago and one
of their primary requests was to have a metadata field that highlighted
links to related published works in other repositories. That was how they
understood the term 'Relationships' and related URL.



On Tue, Jun 28, 2016 at 3:14 PM, Adam Wead <notifications@github.com> wrote:

> I think it belongs in metadata. As I understand it, the related URL is the
> equivalent of a user pasting in a link from a browser. Relationships,
> however, are resources identified by URIs. I would be okay if "related url"
> was in the relationships tab, but it should be enforced as a URI and not
> just a string that begins with *http*. On the other hand, I'm also with
> @mtribone <https://github.com/mtribone> that these relationships are
> intra-repo, and not inter-repo.
>
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/projecthydra/sufia/issues/2173#issuecomment-229152567>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQBqv0YUjmQDyfzdLK7mFENpn1Ckq7yEks5qQXKxgaJpZM4Iw-yy>
> .
>



-- 
Ben Howell | Accessibility & User Experience Specialist
Design & Discovery | LIT | University of Michigan Library
bnhowell@gmail.com

**Comment by hackmastera** [comment]
my users are expressing a mild preference for keeping this on the metadata tab, and a strong preference for clarity on the front end between internal and external links.

**Comment by awead** [comment]
@hackmastera what's a "link" and what's the difference between one that is internal versus external?

**Comment by hackmastera** [comment]
i guess I meant internal / external relationships? internal being other collections / works / objects within the repository. external being anything anywhere else. does that clarify?

**Comment by hackmastera** [comment]
@awead i'm not sure we have a current use case for external relationships on a URI basis, so that distinction isn't figuring into this for us.

**Comment by mtribone** [comment]
@mjgiarlo Yeah I think that we were all cool with it at the time. Fast forward a bit and I'm learning a bit more and am looking at this and scratching my head. IF relationships are internal to the repo does this field belong there?

@bnhowell They will definitely have it. I'm struggling with its "correct" location in the interface.

**Comment by bnhowell** [comment]
@mtribone Thanks! I'm sure our researchers would appreciate being able to highlight/increase discovery of their published works. I haven't seen Sufia 7 much, but I would hope that a section for external 'related works' or something similar would be present. At the time of our testing we suggested that external links could be part of the work description field.

**Comment by atz** [comment]
@mtribone No, intermingling these two types of references (without distinction) seems inadvisable. Maybe the tab could still be used, including some delineation, but I'd still not prefer it.  I agree with your instinct to keep them separate.  

In general it seems like associations that are **in** the record should stay with the record view, vs. associations that are **with/to** the record, i.e. part of the system, collections, other records, etc.  

In particular, we need to keep "things the User can edit" separate from system internals to keep expectations aligned.

**Comment by mjgiarlo** [comment]
Given all the feedback we've received on this issue, I'm inclined to close it. I would be open to someone else reworking this ticket to, e.g., make it a configurable behavior which defaults to displaying the related URL with descriptive metadata, but the idea of doing that much work oriented around a single metadata field which may or may not be present (given that downstream adopters do customize the descriptive metadata) isn't very satisfying to me. Thoughts, @elrayle?
