### ISSUE TITLE
Works -> Batch Create: Move Related URL from Metadata tab to Relationships tab

### ISSUE THREAD

**Issue by elrayle** [projecthydra/sufia#2174]
### Descriptive summary

Version: Sufia 7.x
UI change

For Works -> [Batch Create](http://localhost:3000/batch_uploads/new)
- Metadata Tab:  Remove Related URL from Additional Fields
- Relationships Tab:  Add External Related URL according to the [UIWG wireframe](https://wiki.duraspace.org/x/5oZcB)
### Expected behavior

User should be able to set all relationships from the Relationship tab.  This includes relationships for the new works to a thing identified by a url (label: External Related URL)
### Actual behavior

Related URL is on the Metadata tab when Additional Fields button is pushed.
### Steps to reproduce the behavior

Current behavior:
1. Top menu -> Works -> [Batch Create](http://localhost:3000/batch_uploads/new)
1. Click Metadata tab
1. Click Additional Fields button
1. See Related URL field

Desired behavior:
1. Top menu -> Works -> [Batch Create](http://localhost:3000/batch_uploads/new)
1. Click Metadata tab
1. Click Additional Fields button
1. Verify Related URL field does not exist
1. Click Relationships tab
1. Verify Related External URL section appears as defined in [UIWG wireframe](https://wiki.duraspace.org/x/5oZcB)
### Related work
#2173 - same change for New Work

**Comment by mtribone** [comment]
Well batch edit looks nothing like the wireframe or the new work screen, so I'll need to punt on this until the larger issue of the batch edit rewrite is discussed.

**Comment by mjgiarlo** [comment]
Leaving the same comment here as I did on #2173:

> Given all the feedback we've received on this issue, I'm inclined to close it. I would be open to someone else reworking this ticket to, e.g., make it a configurable behavior which defaults to displaying the related URL with descriptive metadata, but the idea of doing that much work oriented around a single metadata field which may or may not be present (given that downstream adopters do customize the descriptive metadata) isn't very satisfying to me. Thoughts, @elrayle?

**Comment by mjgiarlo** [comment]
See above comment from August.
