### ISSUE TITLE
Provide documentation for using geonames search

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2222]
In order to have location auto-complete enabled, you need to have a working geonames account. We should provide some documentation for setting that up.

Visit: http://www.geonames.org/login
After registering and getting an account username, you'll need to enable the free web services by going to http://www.geonames.org/manageaccount and clicking the link to enable.

**Comment by mjgiarlo** [comment]
@awead Want to copy/paste what you wrote above (with an appropriate header and TOC entry) to https://github.com/projecthydra/sufia/wiki/Sufia-Management-Guide and close this ticket? :)

**Comment by awead** [comment]
Done.
