### ISSUE TITLE
Total Items in Collection not updated when a work is deleted

### ISSUE THREAD

**Issue by njaffer** [projecthydra/sufia#2223]
### Descriptive summary

Sufia 7 (master branch)

### Expected behavior
When a work that is part of a collection is deleted, the number of items for that collection should be updated 

### Actual behavior
Total items is showing 1, while there are no items in the collection

### Steps to reproduce the behavior

1. Create a collection 'Collection A'
2. Add a work to 'Collection A'
3. Delete the work
4. View the 'Collection A'

### Related work

Link to related tickets or prior related work here.

**Comment by njaffer** [comment]
@jcoyne: When the work is deleted here: https://github.com/projecthydra/curation_concerns/blob/master/app/controllers/concerns/curation_concerns/curation_concern_controller.rb#L96

Should the solr be reindexed, because the total_items(https://github.com/projecthydra/curation_concerns/blob/97a4ce030d628dd531c8d7aaba91d3032435881d/app/presenters/curation_concerns/collection_presenter.rb#L30) returns 1 instead of 0

**Comment by jcoyne** [comment]
Yes. I think that curation_concerns should probably have an actor for destroying, and one of the tasks the actor would have would be to reindex any collections the object may be in.

**Comment by atz** [comment]
I am not enthusiastic about the prospect of reindexing an entire 10,000-item collection just because one largely empty record was deleted... in particular if the payoff is just affecting the count.  I would support a config or heuristic for "cheap delete" that decrements the count without a sprawling reindex.

**Comment by jcoyne** [comment]
Reindex on the collection object should just reindex that collection object.  It shouldn't be a very expensive operation. It doesn't cause a reindex of all the members.

**Comment by mjgiarlo** [comment]
@njaffer Now that https://github.com/projecthydra/curation_concerns/pull/855 is merged, do you want to point your local Sufia at the updated CC and confirm this bug has been effectively fixed in Sufia as well? This issue is the only blocker we have at the moment. Thank you!

**Comment by njaffer** [comment]
@mjgiarlo: sure I will test it and let you know soon!

**Comment by njaffer** [comment]
Fixed with https://github.com/projecthydra/curation_concerns/pull/855
