### ISSUE TITLE
Adding/removing rights prevents metadata from validating

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2244]
### Descriptive summary

When entering metadata for a new work, adding an empty rights option prevents the form from validating. The fix might could be just preventing adding additional rights if you haven't selected one first.

### Steps to reproduce the behavior

1. Create a new work
1. Before entering anything, click "+ More" under rights
1. Now click "- Remove" to remove it
1. Proceed with entering all the required metadata

The red "X" will still remain after all the required metadata is present.

**Comment by jcoyne** [comment]
This is because required fields are created when the page is initialized (and never updated):
https://github.com/projecthydra/sufia/blob/master/app/assets/javascripts/sufia/save_work/required_fields.es6#L6

**Comment by jcoyne** [comment]
Fix will require us to hook into hydra-editor so that when a field is added or removed, the `SaveWorkControl` is reinitialized. This will be challenging as hydra-editor doesn't have *real* callbacks and it's pseudo-callback is already used by the autocomplete functionality.

**Comment by awead** [comment]
@mjgiarlo are we still considering this a blocker? It's possible to circumvent it by reloading the page.

**Comment by mjgiarlo** [comment]
@awead I believe @jcoyne may have already started in on this work in hydra-editor, in which case, yeah.

**Comment by jcoyne** [comment]
Yes, I'm still working on this.

**Comment by newmanld** [comment]
I think this comment is relevant:  In our local implementation (still sandboxed) of Sufia 7.2, we are changing the rights field to not be repeatable.  It will still be required - it should not be empty, although it can be the generic 'All rights reserved'.  Different, multiple rights statements don't make sense to us - we see nothing that connects different rights statements with different attached files or different parts of the work.  A good use case perhaps for multipart works.  So the @awead solution at the top of this issue wouldn't solve this bug for us?

If discussion has already taken place on why the rights field is repeatable, please point me to that.  Or is this a question for @projecthydra/sufia-ui-ux-advisors?

**Comment by newmanld** [comment]
I see now that this issue is closed, and I think the issue I am raising is covered by #1287?

**Comment by mjgiarlo** [comment]
@newmanld Yep, that is covered by #1287. Do you mind leaving the comment above on that issue?

**Comment by newmanld** [comment]
Done (briefer).  Thanks @mjgiarlo

**Comment by mjgiarlo** [comment]
@newmanld Thanks!
