### ISSUE TITLE
Use ActionMailer instead of Mailform

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2247]
Is there a reason we're using Mailform instead of ActionMailer? Do we want to change any of that?

**Comment by jcoyne** [comment]
I assume it's for the validations.  I know that Mailform doesn't support `deliver_later`, so that is one reason we may want to change, but it's not a great benefit.

**Comment by awead** [comment]
I think the validations are of more benefit than the `deliver_later` option. If we wanted that, we could create a mail delivery job with Active::Job.

**Comment by jcoyne** [comment]
@awead can we close this?
