### ISSUE TITLE
Expose model_to_create in the config template

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#2278]
I'm not entirely sure if this will be useful or clutter.  We have `model_to_create` in the configuration, but we didn't add it to the template.  This allows people to configure which model is created for a specific batch upload item.  It's certainly not necessary until we support multiple work types.

Epic: #2199

**Comment by mjgiarlo** [comment]
We also ought to document this in the Sufia Management Guide.

**Comment by mjgiarlo** [comment]
@jcoyne given we'll be using the modal for selecting a work type, can we close this issue?

**Comment by jcoyne** [comment]
Yep
