### ISSUE TITLE
Work titles are not appearing correctly in highlighted works tab

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2280]
### Descriptive summary

When I highlight a file on my profile
Then I do not see its title on the highlighted works tab

![highlight](https://cloud.githubusercontent.com/assets/312085/16310052/fff8fb3e-3938-11e6-854b-c15143f99f6d.png)

### Expected behavior

I should see the title.

### Actual behavior

I do not.

### Steps to reproduce the behavior

1. Create a work
1. Highlight it using the dropdown menu from the work's dashboard entry
1. Visit your profile

**Comment by jcoyne** [comment]
It looks like the `TrophyPresenter` needs to delegate `to_s` to something.

**Comment by awead** [comment]
solr_document.title.first does the trick
