### ISSUE TITLE
No "Attach a File" button

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2286]
### Descriptive summary

When viewing a work with no files
Then I should see a button labeled "Attach a file"

### Steps to reproduce the behavior

1. Create work
1. Delete its file

The text at the bottom of the page states: "This Work has no files associated with it. You can add one using the "Attach a File" button below." However, there is no button.

**Comment by mjgiarlo** [comment]
@jcoyne can probably confirm, but I thought the "Attach a File" workflow was the one we get from CC which we may have deleted a while back during a community sprint (because we had two competing workflows that confused the UI). Thanks for finding this, @awead.

**Comment by jcoyne** [comment]
So, the fix is to update the text to say "click edit to add more files"?

**Comment by mjgiarlo** [comment]
That would be a fine fix for 7.0.0.

**Comment by mtribone** [comment]
It looks like we used to have an "Attach a file" button? Can we just add the button back or make the "Attach a file" a hyperlink to the files tab?

![screen shot 2016-06-27 at 9 17 23 am](https://cloud.githubusercontent.com/assets/4163828/16380993/3c13c2e0-3c48-11e6-9779-49b81d02580c.png)

**Comment by mjgiarlo** [comment]
@mtribone Until now, I'd prefer to go with @jcoyne's suggestion:
> So, the fix is to update the text to say "click edit to add more files"?

**Comment by mjgiarlo** [comment]
And if @projecthydra/sufia-ui-ux-advisors have suggestions for more robust fixes in future releases, I'd love to see those in a new or existing issue.
