### ISSUE TITLE
Where do we put google_analytics_id?

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2295]
It looks like this was removed from Sufia.config, but there are still multiple references:
https://github.com/projecthydra/sufia/blob/43a3271050de6db0bec82847882bf9d88640e3ad/app/views/_ga.html.erb#L3
https://github.com/projecthydra/sufia/blob/c3e0ffda0abe9b1bd8fadc8d8d4323eb3201c3af/app/services/sufia/analytics.rb#L62

Do we follow CurationConerns?

https://github.com/projecthydra/curation_concerns/blob/a1fdf2d2deedf089f2ba52dc8a03208f26e0b344/config/locales/curation_concerns.en.yml#L13

**Comment by jcoyne** [comment]
I think we should re-add it to the config. I think that's the proper location.

**Comment by jcoyne** [comment]
Related to https://github.com/projecthydra/curation_concerns/issues/827
