### ISSUE TITLE
Error New Work View in Ruby 2.1.6

### ISSUE THREAD

**Issue by lfarrell** [projecthydra/sufia#2301]
### Descriptive summary
This is probably a minor issue, as I'm not sure what Ruby versions sufia supports, but using 7.0.0.beta4 and Ruby 2.1.6 gives the error below. Upgrading to Ruby 2.2 fixes the issue, but thought I'd make you all aware of it.
![sufia](https://cloud.githubusercontent.com/assets/436691/16422309/ec85a2c8-3d25-11e6-9cee-338942727296.png)

**Comment by atz** [comment]
As of https://github.com/projecthydra/sufia/commit/ec02fc328950f80099a77d0c8025f91b316d2dfd, we only test against 2.2 now.  Not sure how official that is as a decision re: supported/unsupported.

**Comment by mjgiarlo** [comment]
We've got `We recommend either Ruby 2.3 or the latest 2.2 version` in the README, so I'll close this issue. Thanks for reporting it, @lfarrell!
