### ISSUE TITLE
saveWorkControl should not be initializing on the batch edit form.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#2302]
When I'm on the batch edit form ([http://localhost:3000/batch_edits/edit?batch_document_ids[]=np193921h](http://localhost:3000/batch_edits/edit?batch_document_ids[]=np193921h)) and I click the "More" button to add another field

I get this message in the console:
<img width="676" alt="screen shot 2016-06-28 at 11 51 41 am" src="https://cloud.githubusercontent.com/assets/92044/16424667/be8aceba-3d26-11e6-8075-39368e5877e2.png">

And an additional field is not added.

**Comment by atz** [comment]
I'd say that's a blocker.
