### ISSUE TITLE
Link to contributor on index result produces an broken search

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#2309]
When I click on this link in the search result:

<img width="278" alt="screen shot 2016-06-28 at 8 49 26 pm" src="https://cloud.githubusercontent.com/assets/92044/16438067/0920d44c-3d72-11e6-94bd-c54a0bed4eba.png">

It takes me to:
http://localhost:3000/catalog?frank="contributor"&search_field=advanced

which isn't filtering in any way. It's returning all results.

@mtribone any ideas?

**Comment by mtribone** [comment]
Hmmmm...I'll take a look.

**Comment by mtribone** [comment]
Is there are reason this line is commented out?

https://github.com/projecthydra/sufia/blob/master/lib/generators/sufia/templates/catalog_controller.rb#L22

**Comment by mjgiarlo** [comment]
:arrow_up: @awead ?

**Comment by cam156** [comment]
@jcoyne the blacklight advanced search integration is completely 💩.  I could get to the /advanced page to load by deleting the sufia overrides and running the generator in .internal_tes_app, but it was showing fields that were not configured in the catalog controller.  I am not sure where "Number"

![screen shot 2016-06-29 at 2 09 23 pm](https://cloud.githubusercontent.com/assets/1599081/16463287/253a7fde-3e03-11e6-89f9-605e6574c1b3.png)

The links will not work if the integration is bad.

**Comment by atz** [comment]
The weirdest part about the bad link is that it reverses field name and value: `frank="contributor"`.  I wouldn't expect that to filter until I had a field named frank.

**Comment by mtribone** [comment]
@atz I think that is because of this:
https://github.com/projecthydra/sufia/blob/master/app/helpers/sufia/sufia_helper_behavior.rb#L98

**Comment by atz** [comment]
@mtribone: I agree, looks like the args are reversed according to the method declaration just 4 lines later.

**Comment by atz** [comment]
No tests added with the new methods when added (or since) https://github.com/projecthydra/sufia/commit/fb8dd99d144ea1ea95cc0ded0e12d3e04bb2a687

**Comment by mtribone** [comment]
@atz The only tests that I added were to check if the content was there.
https://github.com/projecthydra/sufia/commit/fb8dd99d144ea1ea95cc0ded0e12d3e04bb2a687#diff-d545c7328a51301b0fdc2f9234fa9437R60

Looking forward to seeing how you fix this up. I learnz.

**Comment by awead** [comment]
This is fixed in #2318.

**Comment by jcoyne** [comment]
Fixed by merge of #2318
