### ISSUE TITLE
Blacklight 6.3

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2317]
### Descriptive summary

Blacklight 6.3 fixes problems with turbolinks 5.0, but there are some breakages. Some of the expectations with `itemprop` results have changed. Particularly, the contributor term isn't rendering properly.

**Comment by atz** [comment]
Pls add milestone.  Otherwise it is unclear what the blocker is blocking.

**Comment by atz** [comment]
Note: contributor rendering may have just been our own error in a helper_method.
