### ISSUE TITLE
Support the CC file manager (integrate it into the UI)

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#2321]
Once we have nested works, we want to be able to order objects within works.

Blocked by #2199 and #2243.

**Comment by mjgiarlo** [comment]
Related to (and blocked by) #2243.

**Comment by mjgiarlo** [comment]
This *may* be an epic.

**Comment by hackmastera** [comment]
We also need to be able to order files (FileSet objects) which I gathered is part of the file manager, as well. My understanding is that Works and FileSets can be ordered (and intermingled) on a given parent.

**Comment by mjgiarlo** [comment]
@hackmastera This would be good to verify in the latest release of CC.

**Comment by mjgiarlo** [comment]
@hackmastera A good first bit of work for this ticket would be to spin up CC and see what all tools it provides around ordering (of collections, works, and filesets). A follow-up would be to see how we might enable these same features in Sufia.

**Comment by hackmastera** [comment]
Messed around with curation concerns.

Works: There's a link on a work view page 'File Manager'. The file manager (see screenshot) allows you to drag/drop reorder files and works. Each File(Set)/Work object has a little box with thumbnail, editable title, 'edit' link going to e.g. `/concern/parent/p5547r588/file_sets/vq27zn652`. Thumbnail links to e.g. `/concern/file_sets/vq27zn652`. Both links take you to identical pages except the route; I don't understand this.

There's no ordering on Collections or FileSets. FileSets also don't appear to allow manual additions at this time.

![screen shot 2016-08-09 at 11 07 26 am](https://cloud.githubusercontent.com/assets/845363/17522317/93318dac-5e24-11e6-9104-d2171cffc1ba.png)

**Comment by hackmastera** [comment]
file_manager exists in sufia but looks a little wonky.

![screen shot 2016-08-09 at 11 49 58 am](https://cloud.githubusercontent.com/assets/845363/17523099/728386ac-5e27-11e6-8b35-c9203472110c.png)

**Comment by hackmastera** [comment]
There's no drag/drop functionality in the sufia page. probably missing javascript. I guess the question is do we want this functionality separate or do we want it as part of our works edit form? In UI discussions i recall an assumption of the latter. but since ordering can intermingle files and nested works I'm not sure that's possible; they're under different tabs. Maybe that decision should be revisited, even.

**Comment by mjgiarlo** [comment]
@hackmastera Great, thanks for the investigation so far! Re: your question, what do you think about raising it on [tomorrow's Hydra Tech call](https://wiki.duraspace.org/display/hydra/Hydra+Tech+Call+2016-08-10)?

**Comment by hackmastera** [comment]
@mjgiarlo sure I'll add it to the agenda for tomorrow. see also https://github.com/projecthydra/sufia/issues/2432

**Comment by mjgiarlo** [comment]
@hackmastera yep, just dropped a comment there too. :D

**Comment by hackmastera** [comment]
Tech call revealed no strong feelings on the location of this functionality, but support for providing it.

**Comment by mjgiarlo** [comment]
@hackmastera If you have strong leanings, I'd encourage you to follow them, then! Barring that, we should look to better align Sufia and CC by having Sufia use/link to the file manager in the same place(s) if that sounds reasonable to you.

Thanks for running that by the tech call folks.

**Comment by hackmastera** [comment]
Here are the different options for this, UI-wise.

1. Integrate child works and filesets into a single list/tab on the edit page.
  1. Integrate drag/drop functionality directly into this list.
    1. pros: Most consistent UI/UX; the approach discussed in Sufia UI working group
    1. cons: Probably will take the longest. Sufia codebase drifts from cc.
  1. Put a button linking to the filemanager near this list.
    1. pros: At least the button leading to this functionality is near the list when it's being edited
    1. cons: You're linking to a form from within another form. Confusing for developers and users to sort out the implications of this.
1. Link to fileset manager from work show page for logged-in users with edit permission.
  1. pros: More achievable
  1. cons: not consistent with our UI/UX strategy. users wanting to order at upload time may be confused.

I believe 1(i) is the correct approach, but I do not have the time to make it happen. Therefore, in service of getting something working at all, I'll go for 2.

**Comment by mjgiarlo** [comment]
@hackmastera sounds good.

to confirm, 1(i) is #2459?

**Comment by hackmastera** [comment]
@mjgiarlo no, I didn't ticked 1(i). #2459 is something we have to do on the show page side regardless. because once we have these things ordered there's no view that shows their order unless we do that.

**Comment by mjgiarlo** [comment]
Ah, duh. OK!

**Comment by hackmastera** [comment]
blocked by https://github.com/projecthydra/curation_concerns/issues/896

**Comment by mjgiarlo** [comment]
@hackmastera unblocked by https://github.com/projecthydra/curation_concerns/pull/898, yay!
