### ISSUE TITLE
Human-readable dates for embargoes and leases

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2325]
### Descriptive summary

When placing a work under an embargo or lease, the date appears as a full time stamp, ex. 2016-07-27T00:00:00+00:00. It should either be just a date, or a date with a properly formatted time.

**Comment by mjgiarlo** [comment]
Are you still working on this, @mtribone, or is this work already done?

**Comment by mtribone** [comment]
@mjgiarlo Yeah made the fix in CC and waiting for it to be cut and included into Sufia.

**Comment by mjgiarlo** [comment]
@mtribone I believe the fix was released in CC 1.2.0, and Sufia should now pick up that release. Do you think you'll have cycles to check this and close the issue if it's all good?

**Comment by mtribone** [comment]
CC is still at 1.1

https://github.com/projecthydra/sufia/blob/master/sufia.gemspec#L21

**Comment by mjgiarlo** [comment]
@mtribone the `~>` there means Sufia can use CC 1.x, so 1.2.0 should work A-OK.

**Comment by mtribone** [comment]
Okay. I will look for an override that is preventing the expected behavior.

![screen shot 2016-08-02 at 2 17 32 pm](https://cloud.githubusercontent.com/assets/4163828/17340331/b334ceb4-58bd-11e6-922a-a7ece0ebd7a9.png)

**Comment by mtribone** [comment]
https://github.com/projecthydra/sufia/blob/master/app/views/curation_concerns/base/_metadata.html.erb#L8

**Comment by mtribone** [comment]
![screen shot 2016-08-02 at 2 39 05 pm](https://cloud.githubusercontent.com/assets/4163828/17340591/e9f32e9a-58be-11e6-9ab7-33bd6d743d54.png)

**Comment by mjgiarlo** [comment]
@mtribone what'd you change to get it rendering properly?

**Comment by mtribone** [comment]
metadata.html.erb ⏫  waiting for branch to go green and then PR

**Comment by mjgiarlo** [comment]
Ah, I see. Missed it. Thanks, @mtribone!
