### ISSUE TITLE
Display lease and embargo information in show view

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2327]
### Descriptive summary
The only way to view embargo and lease information is to do so in edit mode. We should also display this information when viewing the item individually, as well as in search results.

**Comment by jcoyne** [comment]
yes

**Comment by mjgiarlo** [comment]
Is this on your plate, @mtribone?

**Comment by mtribone** [comment]
@mjgiarlo Yup. As soon as the fix gets cut in CC.

**Comment by mjgiarlo** [comment]
@mtribone are you saying the fix is in CC and needs to be released, or the fix needs to be added to CC? if the former, CC 1.2.0 contains all the recent commits, and Sufia should now pick up 1.2.0. Do you think you'll have cycles soon to verify this and close the issue if it's all good?

**Comment by mtribone** [comment]
@mjgiarlo Might need to reassign this ticket. My day is filling up fast and I won't be back into the office until Tuesday.
