### ISSUE TITLE
HTTP HEAD requests for the dashboard

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2329]
### Descriptive summary

When visiting the dashboard, there are HTTP HEAD calls for work in the list. Is the HEAD request needed or can we get all this info from solr?
### Related work
#2328

**Comment by mjgiarlo** [comment]
Thoughts on this, @jcoyne?

**Comment by jcoyne** [comment]
I don't know why there would be a HEAD request.  If it's truly not necessary, it should be removed.

**Comment by mjgiarlo** [comment]
@awead Do you still see these now?
