### ISSUE TITLE
Discuss: Batch Edit redesign / overhaul

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#2330]
### Goals
- Repair / expand the usability of batch edit.
- Better integrate form fields so custom fields can be re-used from other parts of the application
- Allow both single-valued and multivalued fields to be batch edited
- Redesign UI for better usability
### Related

some discussion on #2303 
@projecthydra/sufia-ui-ux-advisors

**Comment by hackmastera** [comment]
At one point I had drawn something up, UI-wise, but I lost that and I have no memory of it (thought the memory was sufficiently outsourced!)

Just sketched this, not a proposed UI because it's too weird but a way for me to start thinking about required UI interactions. comments welcome.

![2016-07-07 14 07 17](https://cloud.githubusercontent.com/assets/845363/16663966/2d4c4c44-444c-11e6-857a-49538036d4d9.jpg)

**Comment by mjgiarlo** [comment]
Thanks for getting this started, @hackmastera!

@DanCoughlin do you happen to have the diagram we (you) did a few years ago for the batch-edit redesign? This would be a great place to share that if you can dig it up.

**Comment by hackmastera** [comment]
looks like design work is happening on https://github.com/projecthydra-labs/lerna/issues/291

**Comment by mjgiarlo** [comment]
@hackmastera indeed, we are very nearly ready to share our mock-ups.
