### ISSUE TITLE
Remove solr/conf/ from generated apps

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#2349]
Discussion on slack indicates that this is cruft since introduction of solr_wrapper. @cam156 offered this as evidence: https://github.com/projecthydra/active_fedora/blob/master/lib/generators/active_fedora/config/solr/templates/.solr_wrapper#L7

**Comment by jcoyne** [comment]
I don't think it's cruft. This is directory is where you put your solr configuration. This is what solr_wrapper uses to start solr.

**Comment by hackmastera** [comment]
@jcoyne there are two directories: solr/conf and solr/config. I could have misread the conversation on channel but I gathered that solr/config is the one in current use. solr/conf contains only a single solrconfig.xml.

**Comment by jcoyne** [comment]
@hackmastera okay, that definitely sounds like a problem then.

**Comment by jcoyne** [comment]
We should probably rename: https://github.com/projecthydra/active_fedora/tree/master/lib/generators/active_fedora/config/solr/templates/solr/config to https://github.com/projecthydra/active_fedora/tree/master/lib/generators/active_fedora/config/solr/templates/solr/conf so that follows the solr default: https://github.com/cbeer/solr_wrapper/blob/544077d5ef5666388fbf92ba36dff83b7949d2e2/spec/fixtures/basic_configs/schema.xml#L22

**Comment by jcoyne** [comment]
Should this ticket move to AF?

**Comment by atz** [comment]
Either way.  Right now sufia is expecting the AF configs to be at `.internal_test_app/solr/conf`.  It is incorrect.  They are at `.internal_test_app/solr/config`.  

I like the idea of fixing this upstream (Solr server calls the configuration directory `conf`, so we should do the same), but at this point other downstream consumers of AF (who might not have been as backwards as us) might have coded against what AF was actually generating.  

Ideally we fix this in sufia by pulling the target directory from AF, such that when we fix it in AF, nothing changes in sufia.

**Comment by atz** [comment]
Specifically, right here:
https://github.com/projecthydra/sufia/blob/786246a3c8adfab6607227b354d9e1c47bc80efd/lib/generators/sufia/install_generator.rb#L72

**Comment by atz** [comment]
Of course there is no variable to pull from, it is just hardcoded in AF:
https://github.com/projecthydra/active_fedora/blob/master/lib/generators/active_fedora/config/solr/solr_generator.rb#L9
