### ISSUE TITLE
Single-Use link to file button is broken

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2358]
### Descriptive summary

From the file set show page, clicking on the "Single-Use Link to File" button doesn't do anything.

### Expected behavior

Unknown (to me) but it should probably do something. 😄 

### Actual behavior

Button is just pressed.

**Comment by njaffer** [comment]
May be you have a pop up blocker, when I click on the button, it pops up a dialog box with the single use link

**Comment by jcoyne** [comment]
It may also be related to Turbolinks 5

**Comment by awead** [comment]
Yeah: see https://github.com/projecthydra/sufia/blob/master/app/assets/javascripts/sufia/single_use_link.js#L12

**Comment by awead** [comment]
Behavior has changed: see #2368
