### ISSUE TITLE
Error using Sidekiq with Sufia 7

### ISSUE THREAD

**Issue by electrickite** [projecthydra/sufia#2362]
### Descriptive summary

The documentation for Sufia 7 mentions that the Active Job backend can be Resque or Sidekiq, however it appears that Sidekiq will not run in a Sufia 7 application.

Sufia 7.0.0.rc1
Rails 4.2.6
Ruby 2.3.1
Sidekiq 4.1.4
OSX 10.11.5

Executing `bundle exec sidekiq` fails with the following error:

    /home/myuser/.gem/ruby/2.3.1/gems/hydra-access-controls-10.0.2/app/models/concerns/hydra/access_controls/access_right.rb:5: warning: already initialized constant Hydra::AccessControls::AccessRight::PERMISSION_TEXT_VALUE_PUBLIC
    /home/myuser/.gem/ruby/2.3.1/gems/hydra-access-controls-10.0.2/app/models/concerns/hydra/access_controls/access_right.rb:5: warning: previous definition of PERMISSION_TEXT_VALUE_PUBLIC was here
    /home/myuser/.gem/ruby/2.3.1/gems/hydra-access-controls-10.0.2/app/models/concerns/hydra/access_controls/access_right.rb:6: warning: already initialized constant Hydra::AccessControls::AccessRight::PERMISSION_TEXT_VALUE_AUTHENTICATED
    /home/myuser/.gem/ruby/2.3.1/gems/hydra-access-controls-10.0.2/app/models/concerns/hydra/access_controls/access_right.rb:6: warning: previous definition of PERMISSION_TEXT_VALUE_AUTHENTICATED was here
    /home/myuser/.gem/ruby/2.3.1/gems/hydra-access-controls-10.0.2/app/models/concerns/hydra/access_controls/access_right.rb:9: warning: already initialized constant Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_PUBLIC
    /home/myuser/.gem/ruby/2.3.1/gems/hydra-access-controls-10.0.2/app/models/concerns/hydra/access_controls/access_right.rb:9: warning: previous definition of VISIBILITY_TEXT_VALUE_PUBLIC was here
    /home/myuser/.gem/ruby/2.3.1/gems/hydra-access-controls-10.0.2/app/models/concerns/hydra/access_controls/access_right.rb:10: warning: already initialized constant Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_EMBARGO
    /home/myuser/.gem/ruby/2.3.1/gems/hydra-access-controls-10.0.2/app/models/concerns/hydra/access_controls/access_right.rb:10: warning: previous definition of VISIBILITY_TEXT_VALUE_EMBARGO was here
    /home/myuser/.gem/ruby/2.3.1/gems/hydra-access-controls-10.0.2/app/models/concerns/hydra/access_controls/access_right.rb:11: warning: already initialized constant Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_LEASE
    /home/myuser/.gem/ruby/2.3.1/gems/hydra-access-controls-10.0.2/app/models/concerns/hydra/access_controls/access_right.rb:11: warning: previous definition of VISIBILITY_TEXT_VALUE_LEASE was here
    /home/myuser/.gem/ruby/2.3.1/gems/hydra-access-controls-10.0.2/app/models/concerns/hydra/access_controls/access_right.rb:12: warning: already initialized constant Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_AUTHENTICATED
    /home/myuser/.gem/ruby/2.3.1/gems/hydra-access-controls-10.0.2/app/models/concerns/hydra/access_controls/access_right.rb:12: warning: previous definition of VISIBILITY_TEXT_VALUE_AUTHENTICATED was here
    /home/myuser/.gem/ruby/2.3.1/gems/hydra-access-controls-10.0.2/app/models/concerns/hydra/access_controls/access_right.rb:13: warning: already initialized constant Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_PRIVATE
    /home/myuser/.gem/ruby/2.3.1/gems/hydra-access-controls-10.0.2/app/models/concerns/hydra/access_controls/access_right.rb:13: warning: previous definition of VISIBILITY_TEXT_VALUE_PRIVATE was here
    Cannot define multiple 'included' blocks for a Concern
    /home/myuser/.gem/ruby/2.3.1/gems/activesupport-4.2.6/lib/active_support/concern.rb:126:in `included'
    /home/myuser/.gem/ruby/2.3.1/gems/hydra-access-controls-10.0.2/app/models/concerns/hydra/access_controls/embargoable.rb:7:in `<module:Embargoable>'
    /home/myuser/.gem/ruby/2.3.1/gems/hydra-access-controls-10.0.2/app/models/concerns/hydra/access_controls/embargoable.rb:3:in `<module:AccessControls>'
    /home/myuser/.gem/ruby/2.3.1/gems/hydra-access-controls-10.0.2/app/models/concerns/hydra/access_controls/embargoable.rb:2:in `<module:Hydra>'
    /home/myuser/.gem/ruby/2.3.1/gems/hydra-access-controls-10.0.2/app/models/concerns/hydra/access_controls/embargoable.rb:1:in `<top (required)>'
    /home/myuser/.gem/ruby/2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:457:in `load'
    /home/myuser/.gem/ruby/2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:457:in `block in load_file'
    /home/myuser/.gem/ruby/2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:647:in `new_constants_in'
    /home/myuser/.gem/ruby/2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:456:in `load_file'
    /home/myuser/.gem/ruby/2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:354:in `require_or_load'
    /home/myuser/.gem/ruby/2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:317:in `depend_on'
    /home/myuser/.gem/ruby/2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:233:in `require_dependency'
    /home/myuser/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
    /home/myuser/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/engine.rb:471:in `each'
    /home/myuser/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/engine.rb:471:in `block in eager_load!'
    /home/myuser/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/engine.rb:469:in `each'
    /home/myuser/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/engine.rb:469:in `eager_load!'
    /home/myuser/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/engine.rb:346:in `eager_load!'
    /home/myuser/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/application/finisher.rb:56:in `each'
    /home/myuser/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
    /home/myuser/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
    /home/myuser/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
    /home/myuser/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
    /home/myuser/.rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
    /home/myuser/.rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
    /home/myuser/.rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
    /home/myuser/.rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
    /home/myuser/.rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
    /home/myuser/.rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
    /home/myuser/.rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
    /home/myuser/.rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
    /home/myuser/.rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
    /home/myuser/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
    /home/myuser/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
    /home/myuser/projects/sufia7_sidekiq/config/environment.rb:5:in `<top (required)>'
    /home/myuser/.gem/ruby/2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
    /home/myuser/.gem/ruby/2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
    /home/myuser/.gem/ruby/2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
    /home/myuser/.gem/ruby/2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
    /home/myuser/.gem/ruby/2.3.1/gems/sidekiq-4.1.4/lib/sidekiq/cli.rb:237:in `boot_system'
    /home/myuser/.gem/ruby/2.3.1/gems/sidekiq-4.1.4/lib/sidekiq/cli.rb:50:in `run'
    /home/myuser/.gem/ruby/2.3.1/gems/sidekiq-4.1.4/bin/sidekiq:12:in `<top (required)>'
    /home/myuser/.gem/ruby/2.3.1/bin/sidekiq:23:in `load'
    /home/myuser/.gem/ruby/2.3.1/bin/sidekiq:23:in `<top (required)>'
    /home/myuser/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
    /home/myuser/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
    /home/myuser/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
    /home/myuser/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
    /home/myuser/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    /home/myuser/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
    /home/myuser/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
    /home/myuser/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
    /home/myuser/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
    /home/myuser/.gem/ruby/2.3.1/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
    /home/myuser/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
    /home/myuser/.gem/ruby/2.3.1/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
    /home/myuser/.gem/ruby/2.3.1/bin/bundle:23:in `load'
    /home/myuser/.gem/ruby/2.3.1/bin/bundle:23:in `<main>'

### Expected behavior

`bundle exec sidekiq` starts Sidekiq and begins processing queued background jobs.

### Actual behavior

Sidekiq fails to start with the stack trace above

### Steps to reproduce the behavior

1. Create a Sufia 7 application, following the Sufia README
2. Add `gem 'sidekiq'` to the `Gemfile`
3. Run `bundle install`
4. Add `config.active_job.queue_adapter = :sidekiq` to `config/application.rb`
5. Run `bundle exec sidekiq`

### Related work

An example application demonstrating the behavior can be found here: https://github.com/electrickite/sufia7_sidekiq

**Comment by jcoyne** [comment]
You'll need to add something like this:
https://github.com/projecthydra-labs/lerna/blob/c1c2c49a45559593c1ed5370b3df575778ff8462/config/environments/development.rb#L4-L7

Sidekiq doesn't like autoloading.

-Justin

**Comment by electrickite** [comment]
Thanks, @jcoyne !

For anyone else that runs into this issue, changing `config.cache_classes = false` to `config.cache_classes = !!Sidekiq.server?` in `config/environments/development.rb` did the trick.
