### ISSUE TITLE
BatchUploads error in 7.0.0.rc1

### ISSUE THREAD

**Issue by jamesvanmil** [projecthydra/sufia#2363]
I did a fresh install of 7.0.0.rc1 this morning, using these instructions:  https://github.com/projecthydra/sufia/tree/v7.0.0.rc1#creating-a-sufia-based-app

All is working so far, except for Batch Uploads... When I visit `batch_uploads/new`, I get:

```
NoMethodError in Sufia::BatchUploads#new
Showing /Users/vanmiljf/.rvm/gems/ruby-2.3.1@sufia-app/gems/sufia-7.0.0.rc1/app/views/curation_concerns/base/new.html.erb where line #1 raised:
undefined method `human_readable_type' for #<BatchUploadItem:0x007ff15630c628>
```

Prior to triggering these errors, I created two users, set up a proxy, and added two works.

**Comment by jcoyne** [comment]
I've confirmed this bug.
