### ISSUE TITLE
Single-use link button doesn't copy on the first try

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2368]
### Descriptive summary

Clicking the Single-Use Link to File button on the show page will create a single-use link, but there is no link returned to the UI. The alert message displays, but with a null link. Clicking the button a second time does copy the link the clipboard and show the alert message with the link.

### Expected behavior

Clicking the button once should create the link, copy it to the clipboard, and display an alert with the url in the message.

### Actual behavior

On the first click, the alert is displayed with no link and nothing is copied to the clipboard. However, a link is still created in the database. On the second click, the original link created in the first click is copied to the clipboard and displayed in the alert.

**Comment by mjgiarlo** [comment]
Should this ticket move into projecthydra/curation_concerns#278? CC has all the single-use impl except for this Javascript:

https://github.com/projecthydra/sufia/blob/master/app/assets/javascripts/sufia/single_use_link.js

and its spec:

https://github.com/projecthydra/sufia/blob/master/spec/javascripts/single_use_link_spec.js.coffee

Do the CC folks prefer those bits of the impl to stay in Sufia, or should the feature fully live in CC? @escowles @tpendragon @jcoyne @jpstroop
