### ISSUE TITLE
undefined method 'sufia__pageview' while rendering stats page

### ISSUE THREAD

**Issue by revgum** [projecthydra/sufia#2380]
In non-production environments, rendering the stats view for a work results in : `NoMethodError: undefined method `sufia__pageview' for #<Legato::Management::Profile:0x007f1c449cc1f8>
...`

We found that the PageView and Download models weren't being eager loaded in non-production environments, and the fix was very simple yet not very clear or easy to identify at first.

I'm proposing we introduce a more clear/simple configuration or initializer for models which extend the `Legato::Model` and get the dynamic `sufia__???????` method injected for all application environments.

I'll put together a PR and we can adjust the implementation as necessary.

**Comment by mjgiarlo** [comment]
@projecthydra/sufia-code-reviewers do y'all have any thoughts on why @revgum would be seeing this eager loading behavior? Is this how you would expect eager loading to vary in Rails?

**Comment by jcoyne** [comment]
I just tested this out and I'm unable to produce the issue you are seeing.   Can you link to the source code for the application that you are using?

**Comment by mjgiarlo** [comment]
Superseded by #2460, so closing. Thanks, @revgum!
