### ISSUE TITLE
Regression of Multi-field Accessibility and Usability from previous pull request in hydra-editor

### ISSUE THREAD

**Issue by bnhowell** [projecthydra/sufia#2387]
### Descriptive summary

A previous pull request [https://github.com/projecthydra/hydra-editor/pull/113] for improved multi-field accessibility and usability in the /hydra-editor repository have not been implemented in the Create New Work page of the vanilla Sufia 7 interface.  Looks like the pull request was lost when the Hydra Editor repo stopped being used. 

### Prior work

See [#2021](https://github.com/projecthydra/sufia/issues/2021) for start of the discussion
See [#113](https://github.com/projecthydra/hydra-editor/pull/113) (projecthydra/hydra-editor) for Pull Request

### Related work

Change help text to always be visible [Curation Concerns #811] (https://github.com/projecthydra/curation_concerns/pull/811)
Help Text Discussion [#2003](https://github.com/projecthydra/sufia/issues/2003)

**Comment by bnhowell** [comment]
@mjgiarlo: Could you take a look into this?

**Comment by mjgiarlo** [comment]
@bnhowell Yep, happy to. AFAIK, Sufia still uses hydra-editor, via CurationConcerns.

Can you include a screenshot of what you're seeing now, and ideally a link to a previous screenshot of what you should be seeing?

**Comment by bnhowell** [comment]
**What I'm currently seeing in default Sufia UI:**
![Current Sufia 7 Multifield UI](https://cloud.githubusercontent.com/assets/16804543/17306693/549bef22-57ff-11e6-8b64-8deb13d202ca.png)

**What I expected to see based on previous pull requests:**
![multifield_improved](https://cloud.githubusercontent.com/assets/16804543/17306732/99b34b6e-57ff-11e6-91e1-9c06709cd7a8.gif)

**Comment by mjgiarlo** [comment]
Thank you, @bnhowell!

**Comment by jcoyne** [comment]
@bnhowell the changes you are looking for are in Hydra-editor 3.0.0.beta1.  You are using hydra-editor 2.0.0

**Comment by grosscol** [comment]
Thanks for clearing that up @jcoyne.  Sufia 7.0 specifies hydra-editor < 4, but the beta1 version suffix was preventing us from picking up the gem.  I'll force the update and @bnhowell can continue this investigation.

**Comment by mtribone** [comment]
Also we replaced the asterisks with the new required badges and better help text.

**Comment by mjgiarlo** [comment]
@jcoyne should we push out a 3.0.0 release and get Sufia using it?

**Comment by jcoyne** [comment]
I see no reason not to push hydra-editor 3.0.0

**Comment by mjgiarlo** [comment]
:speech_balloon: @jcoyne 
> I see no reason not to push hydra-editor 3.0.0

I do:

```shell
$ RAILS_VERSION=4.2.5 bundle exec rake release
rake aborted!
LoadError: cannot load such file -- active_fedora/rake_support
/home/mjg/workspace/hydra-editor/Rakefile:30:in `require'
/home/mjg/workspace/hydra-editor/Rakefile:30:in `<top (required)>'
/home/mjg/.rvm/gems/ruby-2.2.4@hydra-editor/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

;) (Tried w/ and w/out `RAILS_VERSION` and `bundle exec` to no avail.)

**Comment by jcoyne** [comment]
@mjgiarlo when is the last time you did `bundle update` in that project?

**Comment by jcoyne** [comment]
@mjgiarlo make sure you remove the `.internal_test_app` first.

**Comment by mjgiarlo** [comment]
@jcoyne tried both of those first. It's picking up AF 9.0.7 or so for some reason.
