### ISSUE TITLE
Support Rails 5

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#2391]
Sufia should support Rails 5. See this commit in Spotlight for examples of changes: https://github.com/projectblacklight/spotlight/commit/caee8627241d02e6856135b0bae9e0a89b22afff

**Comment by jcoyne** [comment]
This is blocked by this PR in hydra-head which is still sort of a WIP:
https://github.com/projecthydra/hydra-head/pull/362

**Comment by mjgiarlo** [comment]
Closed by #2479
