### ISSUE TITLE
Sufia does not obey discovery permissions

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2392]
### Descriptive summary

Although discovery is not enabled as a permission option, if it is added to a generic work, the show view is permitted instead of just the index view.
### Expected behavior

With a work that is discoverable by a user, the user should be able retrieve the work in a search result, but not be able to view its full record in the show view.
### Actual behavior

A discoverable work is retrievable in a search as well as displayable in its show view.
### Steps to reproduce the behavior
1. Sign in as user1
2. Create a private work with a memorable title
3. Via the console:

``` ruby
work = GenericWork.find([work_id_you_just_created])
work.discover_groups = ["registered"]
work.save
```
1. Back in the web app, log out, and sign in as user2
2. Search for the work

You should see the work in the search results and be able to view it's record when you should not be able to. Downloading, however, is still not permitted.

**Comment by jcoyne** [comment]
I'm not sure you have the right expectation.  I think that discover means you can see it in the index and in the show page.  You just can't download the item itself (binary).  
Discover == view metadata
Read == view object.

 In any case it's confusing

**Comment by awead** [comment]
Ah, ok, I don't then. I thought the expectation was that discovery meant you could only see the items in search results (index) but **not** in the show view. Was that ever the case? I could have sworn that's the way it was at one point, but maybe I'm mistaken.

**Comment by awead** [comment]
FWIW, the fix lies in CurationConcerns::WorkSearchBuilder.

**Comment by mjgiarlo** [comment]
My understanding, wrong as it may be, matches @awead's. Maybe that's why we abandoned the feature when we were building ScholarSphere 1.0.

**Comment by jcoyne** [comment]
My understanding used to be the same as @awead's but over and over at DCE, I saw people building their own version that did as I described above.  It makes no sense at all to show people search results, but not a show page.  What is on a show page that is restricted that is not in the search results? At the very least you want to say "this item is available to look at by special appointment in XXXXX library"

**Comment by mjgiarlo** [comment]
I don't disagree, @jcoyne.

**Comment by awead** [comment]
Neither do I, @jcoyne. The use case that I'm trying to support is showing one set of metadata to a user/group, versus another. The index view would be a more restrictive view as opposed to the show view, which would have all terms. However, I think the better solution is effect a show page that shows the terms based on the user. That logic could be encapsulated into the presenter fairly easily, I would think.
