### ISSUE TITLE
An open Access Work with restricted FileSets creates broken links

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2394]
### Descriptive summary

In Sufia 7 master, when I create a work and set it to Institution, and then I later set the work access level to open access, I get broken thumbnail links, and visibility to FileSets I do not have access to.
### Expected behavior

If I am not logged in and a view an open access work with restricted files, I would not expect to see the files, and I would not expect broken links to the thumbnails if I can see the files.
### Actual behavior

I see the restricted files, but get an error when I click on them, and the thumbnail is a broken link
### Anonymous user

![screen shot 2016-08-04 at 12 23 18 pm](https://cloud.githubusercontent.com/assets/1599081/17409814/c2506d72-5a3e-11e6-9af4-fe3bb029e6b3.png)
### Logged in user

![screen shot 2016-08-04 at 12 23 09 pm](https://cloud.githubusercontent.com/assets/1599081/17409821/c50f57a8-5a3e-11e6-9f0d-25fc2164bf36.png)
### Steps to reproduce the behavior
1. Create a work that is restricted to institution
2. Then edit the work and change the permissions to public
3. Click only the work for the change (so that the files are left restricted)

**Comment by cam156** [comment]
Should be simmilar to collection only showing what the user has access to.

**Comment by mjgiarlo** [comment]
See this solution in ScholarSphere: https://github.com/psu-stewardship/scholarsphere/commit/206f1738ff6051b4634ee04f5a18fbe9310fd4b5

**Comment by mjgiarlo** [comment]
@hortongn do you think you'll have time to pick this back up this week, or were you leaning in another direction? Anything the rest of us can do to help out?

(This issue is one of the two last blockers for the 7.3.0 release.)

**Comment by mjgiarlo** [comment]
@hortongn Nevermind the above question.

**Comment by mjgiarlo** [comment]
I posted this comment in the related PR, but it should be here in the issue too for the record:

> I believe the solution we arrived at in various discussions in Slack and GitHub is that the presenter should use a default icon (`app/assets/images/default.png`) instead of a thumbnail to represent a file when the user lacks access. Thoughts on that, @jcoyne @cam156 @tpendragon @mark-dce @hackmastera @hortongn 
> 
> Assuming that is the consensus approach, are you still inclined to take this on, @hortongn?

**Comment by cam156** [comment]
@mjgiarlo is the thought to run cancan on every item to either show the thumbnail or not?   That may be very resource intensive as that queries solr for every document. 

My real concern is making sure people know this is a possible security vulnerability giving people with no access links to data they can not have.  In theory security will stop them, but for security purposes not even giving the ids seems better.

**Comment by mjgiarlo** [comment]
@cam156 I haven't thought about the implementation, myself. Tagging others for their thoughts: @jcoyne @tpendragon @mark-dce @hackmastera @hortongn

**Comment by mjgiarlo** [comment]
@jcoyne @cam156 @tpendragon It sounds like we haven't gotten consensus yet. If we don't get consensus on this by early next week on an approach we can all live with, I'm inclined to mark this as a non-blocker and deal with it in Hyrax -- it's time for the 7.3.0 release process to kick off, and I want to provide @hortongn a clear path forward since his institution has given him time to contribute to a community gem. Thanks for any help you can provide.

**Comment by cam156** [comment]
@mjgiarlo I would agree that a non broken link would be better than the current code.

**Comment by mjgiarlo** [comment]
@jcoyne @tpendragon You OK with the above solution?

**Comment by jcoyne** [comment]
@mjgiarlo what solution is that?

**Comment by mjgiarlo** [comment]
@jcoyne my bad. Here it is: https://github.com/projecthydra/sufia/pull/3017#issuecomment-275548401

**Comment by jcoyne** [comment]
@mjgiarlo my response was https://github.com/projecthydra/sufia/pull/3017/files#r98247793

**Comment by mjgiarlo** [comment]
@jcoyne OK. Is that solution clear to you, @hortongn? I don't grok it myself, since the machinery here uses `render_thumbnail_tag` which seems to use solr docs and presenters to find a suitable representation.

**Comment by jcoyne** [comment]
@mjgiarlo `render_thumbnail_tag` is a Blacklight method. It simply renders the url in the solr document.  This url should be pointing at the DownloadController.  The DownloadController is going to call `authorize! :download, params[:id]`, which presumably raises a cancan error.  If that error was caught by the downloads controller (I'm pretty sure it's not presently), we could render a default image.

**Comment by mjgiarlo** [comment]
Thanks, @jcoyne. How does that sound, @hortongn?

**Comment by hortongn** [comment]
@mjgiarlo Sounds good.  I was at Sandi's class, but I'm back in the office Tuesday and can work on @jcoyne's suggested approach.  I'm not familiar with the DownloadController, but Justin's description sounds straightforward.

I'll update my status on this issue at the end of day.

**Comment by mjgiarlo** [comment]
Thank you, @hortongn

**Comment by hortongn** [comment]
@jcoyne If I'm in DownloadController and catch a cancan error with `rescue CanCan::AccessDenied` what's the prefered way to then render a default thumbnail?

**Comment by jcoyne** [comment]
@hortongn I don't know. I might try a redirect first of all.

**Comment by hortongn** [comment]
👍

**Comment by hortongn** [comment]
@jcoyne @mjgiarlo The code below in DownloadBehavior does do what we want, but do you have any suggestions for doing it differently before I move forward?  Sufia already had CollectionThumbnailPathService and WorkThumbnailPathService with default images.  So I created one for files as well.

```
     def authorize_download!
        authorize! :read, params[asset_param_key]
      rescue CanCan::AccessDenied
        redirect_to Sufia::FileThumbnailPathService.default_image
      end
```

Also, since DownloadBehavior lives in CC right now, is it best to just copy/override the entire controller into Sufia?

**Comment by jcoyne** [comment]
If DownloadBehavior is in CC, is there some reason we can't make this change there?

**Comment by hortongn** [comment]
Making the change in CC would be easier.  I assumed that if the bug was logged in Sufia we wanted the change made there.  But if there isn't a good reason to put it in Sufia , CC makes more sense for this fix.

**Comment by mjgiarlo** [comment]
@hortongn Sounds good. Thank you!

**Comment by mjgiarlo** [comment]
@hortongn Good work!

We should cut a new release 1.x release of CC and point Sufia at it, to confirm that this is now fixed in Sufia (re-opening this ticket 'til then). Are you inclined to take that on, or to move on to other work?

**Comment by hortongn** [comment]
@mjgiarlo Yep, I should have some cycles this afternoon to cut a CC release and verify the fix.

**Comment by hortongn** [comment]
I cut a new release of curation_concerns and tested against Sufia.  It broke one Sufia test related to this default thumbnail change.  So I now have a PR that fixes that test open at https://github.com/projecthydra/sufia/pull/3053

**Comment by hortongn** [comment]
The fixed spec has been merged.  So closing this issue.
