### ISSUE TITLE
Multiple works created for one upload

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2397]
### Descriptive summary

I can not repeat this.  So I'm documenting it incase someone else sees this happen.

I uploaded one work into Sufia 7/ScholarSphere and got two works when I hit save.

This is my local copy and the works were created within milliseconds of each other so I could not have created them via the UI and no one else has access to the system.

https://gist.github.com/cam156/6636f6d2ac8f7b90520126d2054435ee

**Comment by cam156** [comment]
@mjgiarlo I can duplicate this now!  Yeah!  The save button can be hit many times and as many times as you hit it that is the number of works you get.

All these works were made by continuing to hit the save button...
![screen shot 2016-08-10 at 2 49 28 pm](https://cloud.githubusercontent.com/assets/1599081/17566507/aafd50ac-5f09-11e6-8f1c-67c60bc211b2.png)

With the jobs running inline I could hit it forever, with resque I could only hit it about 20 times before it swapped out...

**Comment by mjgiarlo** [comment]
@cam156 w00t! Changed the labels and milestone to reflect this.
