### ISSUE TITLE
Collection Show page links to itself

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2399]
### Descriptive summary

In Sufia 7 the collection icon on the show page links to the collection show page.  While this is not terribly bad it is a bit confusing.

### Expected behavior

The collection Icon on the show page would be unclickable

### Actual behavior

When I click on the collection icon I refresh the collection page.

### Steps to reproduce the behavior

1. Go to a collection show page
1. Click on the triple boxes

**Comment by mjgiarlo** [comment]
Comments on this, @projecthydra/sufia-ui-ux-advisors? Do you know which icon @cam156 describes, or would a screenshot help?

**Comment by cam156** [comment]
![screen shot 2016-08-08 at 6 52 14 am](https://cloud.githubusercontent.com/assets/1599081/17477694/a97c54de-5d34-11e6-95f2-995cfc87e3d7.png)

**Comment by hackmastera** [comment]
We noticed this the other day on our sufia 6 application, as well. I agree it's confusing and should be removed.

**Comment by newmanld** [comment]
I agree that it is confusing.  Having the collection icon be un-clickable seems better than having it act as a refresh upon click.

**Comment by mtribone** [comment]
The icon is also linked in the Collection listing.


![screen shot 2016-08-22 at 12 55 03 pm](https://cloud.githubusercontent.com/assets/4163828/17863476/c57cc7ac-6867-11e6-94f4-0bc6a9a2291c.png)

**Comment by mtribone** [comment]
Do ya'll want the icon to go back to being blue?

![screen shot 2016-08-22 at 1 09 16 pm](https://cloud.githubusercontent.com/assets/4163828/17863903/c11d6566-6869-11e6-9a62-236762bc087c.png)

**Comment by mtribone** [comment]
So I've removed the link from around the collection icon in the show view, my collections, listing, and the search index view. C'nest pas?

**Comment by hackmastera** [comment]
huh. was it blue because it was a link? not sure about this.

**Comment by mtribone** [comment]
@hackmastera Yes it was blue because it was a link.
