### ISSUE TITLE
Collections are showing options on Works that it should not

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2400]
### Descriptive summary

When I view someone else's collection I should not get the option to edit or highlight the work.

### Expected behavior

No menu items available?  Or other ones, just not edit and highlight

### Actual behavior

Options on the menu
![screen shot 2016-08-05 at 2 47 02 pm](https://cloud.githubusercontent.com/assets/1599081/17447326/d73bfff2-5b1b-11e6-9ab9-f02cc8d2217e.png)

Error screen I see when I try to edit the work
![screen shot 2016-08-05 at 2 47 26 pm](https://cloud.githubusercontent.com/assets/1599081/17447324/d5412394-5b1b-11e6-9df3-297e641f60e6.png)

**Comment by andjsmit** [comment]
PR #2567 submitted as an attempted fix.
