### ISSUE TITLE
Location or Based Near?

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2401]
### Descriptive summary

In Sufia 7 the work show page includes Based Near and the Work Edit page includes location

### Expected behavior

The wording should be the same for both pages

### Actual behavior

Edit page...
![screen shot 2016-08-08 at 9 50 38 am](https://cloud.githubusercontent.com/assets/1599081/17481994/bd2fbe4e-5d4d-11e6-98d0-d0a08533962d.png)

Show page...
![screen shot 2016-08-08 at 9 50 45 am](https://cloud.githubusercontent.com/assets/1599081/17481996/bf3531ba-5d4d-11e6-9f3f-08058fc55fcc.png)

**Comment by mtribone** [comment]
Is based near the desired default label?

@projecthydra/sufia-ui-ux-advisors

**Comment by hackmastera** [comment]
I believe it was always 'Location'. I'm not sure why it's called based_near, internally. Sort of always wondered that.

**Comment by mtribone** [comment]
Okay. So the correct label is "Location."

https://github.com/projecthydra/sufia/blob/master/lib/generators/sufia/templates/catalog_controller.rb#L73

**Comment by mjgiarlo** [comment]
I believe "based_near" is the name of the predicate we use, which is why overrode it with Location.
