### ISSUE TITLE
What is "In works ids" on the Work edit page?

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2402]
### Descriptive summary

In Sufia 7 on the work edit screen you get a text box for "In works ids".  There is no help and if I type in some works the save errors.

### Expected behavior

Something that might make sense to a user, or not to be there at all...

### Actual behavior

![screen shot 2016-08-08 at 9 49 39 am](https://cloud.githubusercontent.com/assets/1599081/17482050/ff40b64e-5d4d-11e6-8c5e-ce959c2a618b.png)

**Comment by awead** [comment]
Hmm, that looks odd. The `in_works` and `in_work_ids` are the methods a FileSet has that point it to its containing work.

**Comment by cam156** [comment]
@awead If it is for setting works within works then a selection list may be a better option than a text field.  I just typed in what I wanted and got a failure, so at the very least some sort of validation would be needed vs a stack trace.

**Comment by cam156** [comment]
@projecthydra/sufia-ui-ux-advisors Did you have a plan for what the in_works was supposed to look like on the edit page?

**Comment by mtribone** [comment]
I have no idea what `in_works` or `in_works_ids` are for in regards to a work.

**Comment by hackmastera** [comment]
I believe this is the functionality that OSU added in order to nest works within other works. I think the ui group discussed this and it's part of the wireframe, but the OSU team said they didn't have time to implement everything. It's specified as a searchbox. Current implementation requires user to enter an ID.

**Comment by jcoyne** [comment]
Does anyone know if there's s ticket for that remaining work?

**Comment by mtribone** [comment]
"In works ids" is no longer in the list of metadata fields.

**Comment by awead** [comment]
I think an autocomplete here would be best. I have some work on another project that would do this. Ideally, it could be QA-based authority that searches solr for existing works the user has access to.

**Comment by mtribone** [comment]
![screen shot 2016-08-24 at 10 30 16 am](https://cloud.githubusercontent.com/assets/4163828/17934386/c9f72244-69e5-11e6-8446-222afaa24b67.png)

**Comment by cam156** [comment]
Looks like this is solved.
