### ISSUE TITLE
Source field is shown on the edit screen for a work but not in the show

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2403]
### Descriptive summary

In Sufia 7 I see a Source field on the edit page for a work, but the show page does not display that data.  "In work id" described in #2402 also does not show on work show screen as far as I can tell...

### Expected behavior

If I Edit a work
And I add a source
And I hits save
Then I should see the source in the work view

### Actual behavior

![screen shot 2016-08-08 at 9 47 27 am](https://cloud.githubusercontent.com/assets/1599081/17482155/76f0bc5c-5d4e-11e6-8768-7c1eb0c3ac52.png)

**Comment by mtribone** [comment]
Merged #2536 
![screen shot 2016-08-29 at 3 34 22 pm](https://cloud.githubusercontent.com/assets/4163828/18064600/1a9731dc-6dfe-11e6-9097-d354252412e7.png)
