### ISSUE TITLE
When selecting a Collection the title shows up in brackets

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2405]
### Descriptive summary

In Sufia 7, when I select a collection to add works to from the works listing I see brackets around the title.

### Expected behavior

Just see the title of the collection

### Actual behavior

![screen shot 2016-08-08 at 10 29 07 am](https://cloud.githubusercontent.com/assets/1599081/17483213/262c94e4-5d53-11e6-9b11-2771d1d4a707.png)

### Steps to reproduce the behavior

When I have a collection
And I have wroks
And I go to the works listing
And I click on the box beside one or more works
And I click on Add to Collection
Then I should not see brackets around the collection title.

**Comment by andjsmit** [comment]
If a collection has multiple names, how would should it displayed?

1. First title only.
2. All titles, comma, separated.
3. First title ( additional titles, comma separated).
4. Something else?

**Comment by awead** [comment]
first only. That's what we usually do in cases like these.

**Comment by awead** [comment]
Actually, we have a special method: `title_or_label`.

**Comment by andjsmit** [comment]
OK. Sounds like the way to go. Thx.
