### ISSUE TITLE
Collection in Masonry and slide show view is not great

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2408]
### Descriptive summary

In some of the different views for blacklight in sufia 7, the collection has wither the wrong icon or a very strange one...
### Expected behavior

I'm guessing triple boxes, but not entirely certain.  That would match with other collection views.
### Actual behavior

Slide show
![screen shot 2016-08-08 at 2 05 05 pm](https://cloud.githubusercontent.com/assets/1599081/17490567/69803502-5d71-11e6-811b-cc32704cbd1f.png)

Tiles
![screen shot 2016-08-08 at 2 05 37 pm](https://cloud.githubusercontent.com/assets/1599081/17490569/6b83802a-5d71-11e6-8b00-72863db5de85.png)
### Steps to reproduce the behavior

When I have some collections in your system
Then I search the system for nothing
And I choose Collection as object type
And I click on the Masonry and Slideshow views
Then I should see the normal collection icon
### Related work

Link to related tickets or prior related work here.

**Comment by mtribone** [comment]
Okay. So both masonry and slideshow need to be updated with the correct icon for collections. As for slideshow, it only shows a portion of the representative media as a preview. If you wanted to see the "slideshow" you would see the full images. I'm guessing that you wouldn't select slideshow if the collection didn't have representative media?

**Comment by nrm149** [comment]
PSUSprint03

**Comment by mjgiarlo** [comment]
Fixed in ScholarSphere? https://github.com/psu-stewardship/scholarsphere/pull/410
