### ISSUE TITLE
Work Collection relationship does not cause size to recalculate

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2410]
### Descriptive summary

In Sufia 7, when I upload a new work and put it directly into an existing collection, the collection includes the work, but the collection size is not updated.

### Expected behavior

The collection size should include all the works

### Actual behavior

The collection size does not include the linked work.

![screen shot 2016-08-08 at 2 46 08 pm](https://cloud.githubusercontent.com/assets/1599081/17491805/29888962-5d77-11e6-930d-7354d25a3e64.png)

### Steps to reproduce the behavior

When I have an empty collection
And create a new work
And I go to the relationship tab
And I select my empty collection'
Then I go to the collection show page
Then the collection size should include the work files size.

Note: I'm not entirely sure you need the empty collection but is sure is easy to see that zero is not the correct answer...

**Comment by nrm149** [comment]
PSUSprint01

**Comment by awead** [comment]
It only happens when works are created. If an existing work is edited and added to an existing collection, the size is recalculated.

**Comment by cam156** [comment]
PSUSprint01 Done
