### ISSUE TITLE
Searching Highlights?

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2413]
I noticed that My Highlights is one of the choices in the unified search bar.  This got added at some point in sufia 6, so it is not really a Sufia 7 issue or Sufia 6 issue.  Are highlights still limited to 4?  If so would searching My Highlights really be needed?

**Comment by mjgiarlo** [comment]
Highlights are still limited to 4, so I suspect My Highlights can be removed. Would you mind ticketing that separately, @cam156?

Thanks much for the testing you're doing!
