### ISSUE TITLE
My Collections listing has all select

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2414]
### Descriptive summary

In sufia 7 the My Collections listing has the check box at the top of the list, but no corresponding check boxes beside the items.  I believe that we do not allow batch deletes or edits on collections so the check box should be removed from the top.
### Expected behavior

No check box should be available on the My Collection listing
### Actual behavior

Check box and gear are above the list.

![screen shot 2016-08-09 at 8 03 28 am](https://cloud.githubusercontent.com/assets/1599081/17515732/2b5b92c0-5e08-11e6-940c-e2d84eb20dc1.png)
### Steps to reproduce the behavior

When I have a collection
And I go to My Collections
I should not see a check box

**Comment by jcoyne** [comment]
One would think that this would be hidden due to https://github.com/projecthydra/sufia/blob/master/app/helpers/batch_edits_helper.rb#L11

**Comment by jcoyne** [comment]
Ah, that's the problem.
```
params[:controller]
"my/works"
```
but 
```
controller_name
"collections"
```

**Comment by jcoyne** [comment]
Actually, It looks like we'll have to use the `params[:controller] == "my/collections"`, because otherwise the checkbox doesn't show on the `::CollectionsController`
