### ISSUE TITLE
dashboard list views jump around when some are populated but others are not

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#2416]
### Descriptive summary

Sufia 7. When, e.g., I have added works but not collections.
### Expected behavior

When I click from 'My works' to 'my collections' I expect the tabs to stay in the same place.
### Actual behavior

The facet list disappears and the main content area, including the tabs, jump left to fill the empty space.
### Steps to reproduce the behavior
1. Add a work
2. View 'my works'
3. click tab to view 'my collections'

**Comment by mjgiarlo** [comment]
@hackmastera I'm trying to decide whether this should be a 7.3.0 blocker, or bounce over to Hyrax's backlog. Do you have leanings? How fired up are you to work on this one?

**Comment by hackmastera** [comment]
Okay to bounce; have more pressing issues over here for sure. Thanks!
