### ISSUE TITLE
'Type of work' facet on My Collections page contains single facet 'Collection'

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#2417]
### Descriptive summary

Sufia 7.
### Expected behavior

Either not have this facet or facet based on the types of works within the collections.
### Actual behavior

Looks like this facet will always only have one possible value in this view.
### Steps to reproduce the behavior
1. Create collection/s
2. go to 'my collections' list.

**Comment by cam156** [comment]
@hackmastera I just put a similar issue unto ScholarSphere: https://github.com/psu-stewardship/scholarsphere/issues/351

**Comment by mjgiarlo** [comment]
So, 'Type of work' facet should only display on My Works page. Good call.
