### ISSUE TITLE
My Shares still says files

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2418]
### Descriptive summary

In Sufia 7 the tab label for My Shares still says "Files shared with me".  This is now works and collections so files makes no sense.

![screen shot 2016-08-09 at 12 00 00 pm](https://cloud.githubusercontent.com/assets/1599081/17523560/0b73e69e-5e29-11e6-9682-7f64ce56975d.png)

**Comment by hackmastera** [comment]
What is the use case for this tab? Is it everything a person has edit access to that they are not actually the owner of? It seems like this would be more useful integrated into the works / collections tabs, with an option to filter by owner.

**Comment by cam156** [comment]
@hackmastera Yes these are the works/collections you have edit access, but are not the owner.  It is an easy way to see what other people have shared with you.  Coming up with a different option would be great, but I think that may be a separate ticket.

**Comment by mjgiarlo** [comment]
:+1: to redesigning this feature as a follow-on effort to fixing this bug.
