### ISSUE TITLE
Share listing has check boxes but no buttons

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2419]
### Descriptive summary

In Sufia 7 the shares tab includes check boxes for batch editing, but does not include buttons.  Sufia 6 used to allow edit, but not delete for shared files?
### Expected behavior

When I check a box next to a shared item
Then I should see an Edit button at the top of the page

![screen shot 2016-08-09 at 12 04 24 pm](https://cloud.githubusercontent.com/assets/1599081/17523673/750663e8-5e29-11e6-92ff-c6531b0a9033.png)
### Actual behavior

When I click the box the sort options disappear, but no button appears

![screen shot 2016-08-09 at 12 00 00 pm](https://cloud.githubusercontent.com/assets/1599081/17523708/92c2bac6-5e29-11e6-908d-b952dabbbe63.png)
### Steps to reproduce the behavior

When I have Works Shared with me by another user
And I click on the check box next to a shared work
Then I should see the Edit button, but I do not...
### Related work
#2418 The tab has the wrong name...

**Comment by cam156** [comment]
Same problem on My Highlights
![screen shot 2016-08-09 at 12 12 09 pm](https://cloud.githubusercontent.com/assets/1599081/17523961/846fb388-5e2a-11e6-9ab7-a0938a43fa2d.png)

**Comment by cam156** [comment]
This is also an issue with My Highlights.

**Comment by jcoyne** [comment]
I don’t see how this ever worked given this change 3 years ago. https://github.com/projecthydra/sufia/commit/9411a12193ac908f205cbd321853fd52805b88e6
AFACT, it only ever showed “Edit Selected” when on my/files controller.

**Comment by jcoyne** [comment]
I think this is a difference between Scholarsphere and Sufia: https://github.com/psu-stewardship/scholarsphere/blob/develop_s6/app/views/my/_sort_and_per_page.html.erb#L6-L16
