### ISSUE TITLE
Sufia should support configurable multi-step approval workflow for mediated deposit

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2420]
This is the overarching epic for supporting mediated deposit workflows in Sufia.

It holds subtasks:

- [ ] #2421 
- [ ] #2422  
- [ ] #2423 
- [ ] #2426 
- [ ] #2440 
- [ ] #2441 
- [ ] #2442 
- [ ] #2444 
- [ ] #2452 
- [ ] #2609 
- [ ] #2610 
- [ ] #2611 
- [ ] #2613 
- [ ] #2614  
- [ ] #2615 
- [ ] #2616  
- [ ] #2617 
- [ ] #2618 
- [ ] #2619 
- [ ] #2620 
- [ ] #2621 
- [ ] #2623 
- [ ] #2627
- [ ] #2628 
- [ ] #2629

# Documentation from an earlier conversation

> As a repository administrator i need to be able to create approval workflows that include one or more steps, each step with its own set of permissions, users, etc.
> 
> Comments on this User Story:
> @simosacchi : In order to better understand how Roles and Permissions can actually address these user stories it would be nice to state an initial set of permissions that can be assigned to roles and their internal dependencies. Other than the more general CRUD ones, I think it is important, just as an example, to distinguish between creating (and saving) a work (with possible distinction between "metadata only" and "metadata + files" ) and "publishing" a work. The use case I am describing is one where we have students doing mediated cataloguing and a supervisor approving and publishing their work.
> 
> @elrayle  :  https://wiki.duraspace.org/display/hydra/Feature+Inventory+Grid#FeatureInventoryGrid-UserRoles You may want to look at the User Roles section of Sufia Feature grid that I started and many others contributed to when we were originally evaluating Sufia and other Hydra apps for potential adoption. The document lists our basic requirements that we wanted Sufia to fulfill. It includes a list and descriptions of static roles that can be used as part of a mediate workflow. Click more information... for each role to see the description.
>
> @mjgiarlo : The balance I'd like to strike is that Sufia should support more roles than it does now, but not a very large list of pre-baked roles. A good first step IMO would be to define and create an administrative role, and allow that user to create other roles as need be, assign abilities to roles, assign roles to users, and assign roles to workflow steps. That way Sufia doesn't make a lot of assumptions about how its users will use it.
>
> @simosacchi : I agree with you Mike, actually I believe that an Admin role is enough as a default one. My point was about "permissions" (i.e. actions we allow a user to take, which, I believe, are similar to what you call "workflow steps" ) and the fact that having them well spelled out would allow repository managers to make informed decisions on the roles they really need. Of course we also need the mechanics to associate (new) roles with permissions in an straightforward way. In the end thinking first about roles (instead of individual, granular permissions that can be assigned to roles) might lock us down in an unexpected way.
>
> @mjgiarlo : Gotcha, Simone. Yes, it makes sense to enumerate the actions that are possible to take in a workflow and look for gaps between existing functionality and desiderata. Thanks!

**Comment by jeremyf** [comment]
When this one is further broken down, please bring me into the discussion. Much of the work I've done in Sipity has accounted for custom workflows, along with notifications, wiring in hooks on entering and existing state.

**Comment by mjgiarlo** [comment]
Thanks, @jeremyf! See above, @vantuyls :)

**Comment by vantuyls** [comment]
Repurposing this issue as the "Uber Epic" for Mediated Deposit

**Comment by mjgiarlo** [comment]
Epic is decomposed and is no longer useful. Byebye.
