### ISSUE TITLE
Administrator Role

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2421]
As an administrator, I want to have the ability to find and manage all items, so I can effectively administer all items: search and view all items (including private items not owned by me), edit all items (including items I do not own), delete all items, transfer ownership of all items (including items I do not own), share ownership of all items (including items I do not own), move items to and from all communities

Comments on this User Story:
Daniel Kerchner - I'm really happy to see the work so far captured in this document. I see the following user types referenced (explicitly and implicitly) in these user story summaries, but I think it will be important to nail down who the user types will be in the system, where a user type is given a specific set of permissions. Here's what i see so far:
- Repository Administrator
- Department/Collection Administrator
- Content Manager/Reviewer
- Administrator (/administrative user) - does this mean "any type of administrative user" (parent class) or is it some sort of sibling to the other administrator types mentioned?
- "regular" user/depositor (not mentioned here but implied)

Mike Giarlo: And of these, I am thinking now that Sufia should out-of-the-box support the depositor and uberadministrator role. And the uberadmin should have a UI to creating and managing the other roles. This means more work on the dev side, but gives us a lot more flexibility for the increasingly different use cases for which Sufia is used.

**Comment by vantuyls** [comment]
Additional Comments on this User Story:

Steve Van Tuyl: Essentially defining the role "Administrator" <- can do everything to everything

Mike Giarlo: Yes, and I think we should make this configurable; some installations will not to automatically grant admins access to all repository objects, and will prefer for that determination to be purely by the access controls persisted for each object.

Richard Green: FYI: In Hull, the first stage of our workflow (object still under construction by depositor) is not available to a repository admin (as distinct from a system admin).

Steve Van Tuyl: Good point. This speaks to the kind of configurability I think we need in the system, eg to set workflow permissions as needed by local policy or preference.

Mike Giarlo: Agreed. The difficult task of mediated deposit is allowing an administrative user to define what their workflow looks like: what are the states, what are the actions that need to take place to move a workflow from one state to another, and who is authorized to take that action. Easy to type out, hard to do in a way that isn't "let's build a new workflow framework system!"

**Comment by mjgiarlo** [comment]
Decomposed into smaller tickets, like #2614. Closing.
