### ISSUE TITLE
Metadata Edit Permissions

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2422]
If my permissions allow, I need to be able to edit all (?) metadata fields as part of a review process. Example: Library staff member needs to alter metadata for a dissertation submission to correct spelling mistakes or assign LCSH

**Comment by hannahfrost** [comment]
I agree all metadata fields should be editable by a Reviewer user.

**Comment by hannahfrost** [comment]
I should add that in the Hydra-in-a-Box repository, we'd like to make it so a collection manager can configure the editability of select metadata fields by a depositor in a given collection. The mediated deposit of student works like theses and dissertations is a use case for that kind of configurable metadata editing functionality.

**Comment by mjgiarlo** [comment]
Work on this as part of 1+-step workflow.
