### ISSUE TITLE
Advance, or send back, an item in a workflow

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2423]
As a user who is granted the ability to participate as a reviewer or publisher in a mediated deposit workflow, when a workflow task comes to me,  need to be able to act on that task in one of the following ways:

* Accept the changes made in prior steps and advance the item within the workflow
* Make additional changes myself (attach/detach files, add/edit/remove metadata, tweak permissions/sharing, add/remove relationships, etc.) and advance the item within the workflow
* Mark the item as needing more work and send it back to a prior step with an explanation of what work needs to be done.

**Comment by vantuyls** [comment]
I'll add a mockup of a review queue table ASAP.

**Comment by vantuyls** [comment]
Initial go at a UI for the review queue table. 

![review queue table mockup](https://cloud.githubusercontent.com/assets/9534576/18524204/4c04cac0-7a6c-11e6-8a94-83d175001a0b.png)

**Comment by vantuyls** [comment]
also see #2618 for details of the eventual end-goal for the Review Queue Index Page

**Comment by scholarworks** [comment]
What about a "Reject" button/action? Would it just be along side the approve?

**Comment by vantuyls** [comment]
Reject button would be alongside the approve. See mockups here (please offer feedback!): 
https://docs.google.com/presentation/d/1uMDxYuSfUr9kFswb4HzkQzYYgefL6oaZOAAmCoCQxl4/edit?usp=sharing

**Comment by mjgiarlo** [comment]
Already have this because of the Sipity CC PR.
