### ISSUE TITLE
Mediated Workflow for Batch Deposits

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2424]
As a repository administrator, I want repository objects that have been created via batch import from an external service to be manageable in mediated deposit workflow. Scenario: A weekly automated batch process creates new repository objects harvested from an external source. The newly created objects should be able to be placed in a review queue. A metadata specialist reviews the newly created items for corrections or enhancement before submitting to the repository.

Comments on this User Story:
Mike Giarlo: I'd say yes, out of scope, though we may want to make clear in writing this up that **it should not be a prerequisite that a human must initiate the workflow; a process should also be able to do so.**

**Comment by vantuyls** [comment]
This was initially deemed 'out of scope' but i believe Mike's comment on the user story threw it back into the 'in scope' category, specifically the statement that mediated deposit workflows do not need to be initiated by a human - a process should also be able to initiate mediation.

**Comment by hannahfrost** [comment]
I sure hope that bulk mediated deposit is in scope. This is key functionality for repository migration use cases, for example.

**Comment by mjgiarlo** [comment]
The requirement expressed in this user story is that bulk processes should be able to kick off an approval workflow for an object. Is that sufficient, @hannahfrost, or do you think we're missing an opportunity here?

**Comment by hannahfrost** [comment]
Understood and totally sufficient. I was simply registering a :+1: for the in-scopeness of the requirement.

**Comment by jeremyf** [comment]
My assumption is that each item in a batch deposit would be deposited "into" an Administrative Set. From there, I would assume the approval workflow would apply.

**Comment by straleyb** [comment]
This ticket applies more to batch ingest workflow rather than mediated deposit workflow.
