### ISSUE TITLE
Admin Dashboard: Administrator Can Set Permissions and Roles for All Users

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2425]
As an administrator, I need top-level access to user management, so I can control and manage user accounts and functions: restrict access to user list to administrators; search all users; view all users; sort all users by name; edit all users; delete all users; login as a user and perform all that user’s tasks

This is an admin dashboard feature. Suggest punting this over to the admin dash team for the September sprint at Penn State.
# Past Discussion

Roles & Permissions - As an administrator, I need to be able to create accounts for non institutional users (e.g. those not logged into the system via central authentication) and assign permissions for them

Comments on this User Story:
Mike Giarlo: This is a prerequisite to doing mediated deposit in Sufia. Seems like low-hanging fruit.

Richard Green: ...though, of course, this may be forbidden by institutional policy?

Steven Van Tuyl: True.

Michael Giarlo: Yes, of course. I also see this as a latter-phase story.

**Comment by vantuyls** [comment]
This was initially two user stories, one related to administrators setting permissions and the second for setting accounts for non-institutional users.

**Comment by jrgriffiniii** [comment]
There may well be cases in which defining roles (with respect to user groups) will be tightly coupled with identity management systems local to the institutions (e. g. LDAP).  This could prove to render generalizing this feature more difficult.

**Comment by mjgiarlo** [comment]
Thank you, @jrgriffiniii!
