### ISSUE TITLE
Mediated Deposit Item Status Tracking

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2426]
As a repository administrator or a reviewer, I should be able to see an overview of repository item statuses in the mediated workflow (e.g. Number of items in each step)

Comments on this User Story:
Mike Giarlo: Useful functionality that can follow the initial buildout of mediated deposit. The requirement from the mediated deposit side is that item statuses should be queryable. (I assumed they would be...)

This one also gets back to roles and the UI, because we thus far haven't defined the "admin" role very strongly in Sufia, and IMO it's time for that to happen.

Could be related to work on administrative dashboard, or could be surfaced in the existing dashboard.

**Comment by scholarworks** [comment]
I'm going to start working on this area of the admin dashboard.

**Comment by vantuyls** [comment]
take a look at #2423 for UI

**Comment by scholarworks** [comment]
That looks good. I'm starting on the admin side, but I think the reviewer idea looks good.

**Comment by vantuyls** [comment]
More review queue index page mockups!

https://docs.google.com/presentation/d/1uMDxYuSfUr9kFswb4HzkQzYYgefL6oaZOAAmCoCQxl4/edit?usp=sharing

**Comment by scholarworks** [comment]
I think this is going to lead to a few more tickets to iron out all the functionality as we move forward. More to come...

**Comment by vantuyls** [comment]
@scholarworks definitely. 

Reminder, that the initial goal, the goal of this sprint, is an über basic mediation stream - Deposits are inactive, admin is notified of inactive deposit, admin can approve deposit. There are many elements of mediation that we will work out in future weeks, but this is the starting point.

**Comment by scholarworks** [comment]
@vantuyls absolutely.

**Comment by vantuyls** [comment]
@scholarworks - need to surface this from the CC side

**Comment by vantuyls** [comment]
I need to build new UI mockups based on what is happening over on the Admin Dashboard work.

**Comment by scholarworks** [comment]
I think this is likely duplicated by #2801.

**Comment by vantuyls** [comment]
@scholarworks agreed. closing.

**Comment by mjgiarlo** [comment]
Dup of #2801.
