### ISSUE TITLE
Audio icon is suspiciously similar to the old blue document

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2427]
### Descriptive summary

In Sufia 7 most of the Blue documents have been removed.  I noticed the audio one is still around (or it looks the same)

In Sufia 7
![screen shot 2016-08-09 at 1 18 54 pm](https://cloud.githubusercontent.com/assets/1599081/17526147/0bf040e4-5e34-11e6-8f09-4288dc043fbb.png)

In Sufia 6
![screen shot 2016-08-09 at 1 15 14 pm](https://cloud.githubusercontent.com/assets/1599081/17526155/11981030-5e34-11e6-8de3-16ba19fe1548.png)

The entire work page in Sufia 7

![screen shot 2016-08-09 at 1 19 03 pm](https://cloud.githubusercontent.com/assets/1599081/17526177/2bfd57e6-5e34-11e6-8479-70e0c3b68d1b.png)

**Comment by mjgiarlo** [comment]
@projecthydra/sufia-code-reviewers @projecthydra/sufia-ui-ux-advisors how do you folks think we should handle the default icon for audio items?

**Comment by mtribone** [comment]
We should find an appropriate font awesome icon like we use for works and collections.

**Comment by hackmastera** [comment]
Is it not a work? We should either use a different icon for each resource type or the same for everything.

**Comment by mjgiarlo** [comment]
It is a work, @hackmastera, so yeah, mayhaps we should use the work icon.

**Comment by hackmastera** [comment]
oh i get it there's no way to ever generate a unique icon from the file itself.

**Comment by mjgiarlo** [comment]
That's true. One option we have is to use the support we already have for selecting a thumbnail from one of the work's file sets. (There's a dropdown in the work edit form for this.) And, barring that, use the default work icon?

**Comment by mtribone** [comment]
If I recall correctly, I swapped out the default blue icon with a font awesome icon. I don't *believe* we ever had icons for all of the resource types? Agree with @hackmastera about either one for each resource type or the same for everything.

**Comment by mjgiarlo** [comment]
:+1: to same for everything.

**Comment by mjgiarlo** [comment]
I believe the special-casing for audio comes from the following CC helper:

https://github.com/projecthydra/curation_concerns/blob/master/app/services/curation_concerns/thumbnail_path_service.rb
