### ISSUE TITLE
Configurable Access Controls

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2428]
As a department/collection administrator, i need to be able to modify and confirm acceptance by content/metadata specialist: Edit metadata or replace/adjust file; Option to reject from submission. If accepted: on to next optional step

Comments on this User Story:
Mike Giarlo: This seems like one potential flow that follows from #2420 . It can help us unpack "each step with its own set of permissions, users, etc."

**Comment by straleyb** [comment]
Steve: A grad student ingests an item, then a department head of that grad school double checks that their paper is 12 pt font and 1 inch margins, then it gets sent to the library for publication.

**Comment by mjgiarlo** [comment]
I believe this is already expressed in #2423 so I'm closing this.
