### ISSUE TITLE
FileSet action menu when I do not own the file has one item

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2429]
### Descriptive summary

In sufia 7 on the work show page the Files Set action menu only has one item when I do not own the work.  Should we make this a button instead?

![screen shot 2016-08-09 at 1 38 09 pm](https://cloud.githubusercontent.com/assets/1599081/17526802/c14400aa-5e36-11e6-9173-f0498d268ee2.png)

**Comment by mjgiarlo** [comment]
What say you, @projecthydra/sufia-code-reviewers @projecthydra/sufia-ui-ux-advisors ?

**Comment by newmanld** [comment]
If feasible, it seems it would be more elegant to give the user a button rather than a drop down menu with only one choice.  Changing to the drop-down menu when there is a choice.

**Comment by heidisb** [comment]
+1 for button. Drop-down implies choice and in this case there is none.

**Comment by nrm149** [comment]
PSUSprint01

**Comment by mjgiarlo** [comment]
See fix from SS: https://github.com/psu-stewardship/scholarsphere/commit/573a2c0ccb60fa108c6eebf6e28067f626f4793e
