### ISSUE TITLE
Multiple work types: 2 'create work' links in top bar

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#2433]
There are also 2 'New Work' links under the 'Works' menu item in the top bar.
### Expected behavior

Should there be a submenu under 'New Work' giving the different options? Some other selection mechanism? At the very least the link text should distinguish between the different work types.
### Steps to reproduce the behavior
1. Generate a 2nd curation concern using the sufia:work generator
2. Click 'works' in top menu
### Related work

umbrella ticket is https://github.com/projecthydra/sufia/issues/2199

**Comment by mjgiarlo** [comment]
This one needs design. Tagging @ggeisler and @projecthydra/sufia-ui-ux-advisors. (We should talk about this.)

**Comment by simosacchi** [comment]
My suggestion would be to minimize the information/links in the top bar. I would just keep one link for "Create New Work" and allow in the following step either on the create work page (but there might be complications to change the page behaviours according to the selection...) or in an intermediary page.

**Comment by hackmastera** [comment]
I sort of like the way it's done in curation concerns. It's a submenu but it's indented rather than hover-activated. I don't have a second work in my instance now but you can see from the screenshot how it would look:

![screen shot 2016-08-19 at 10 43 53 am](https://cloud.githubusercontent.com/assets/845363/17813603/fd22138a-65f9-11e6-8789-fc55b3ce0602.png)

**Comment by mtribone** [comment]
So if I'm following along, one would be the default Generic Work and the second is an institutionally created work that isn't a Generic Work?

**Comment by hackmastera** [comment]
That's mostly right. All works are institutionally-created, though, even generic work (if that's what a person chooses to call it). creation of the first work type is now in the README. the goal is to allow an arbitrary number of work types.

**Comment by mtribone** [comment]
So there is potential for a long list of work types?

**Comment by simosacchi** [comment]
@hackmastera @mtribone The long list was my main concern, but also that (at least in a self deposit setting) I wish my user to have the perception that whatever they will be depositing is just an instance of we call "Research output". Further qualifying how an application might behave differently because of descriptive/workflow requirements should not be places at the first step. These are my 2 cents.

**Comment by bnhowell** [comment]
+1 @simosacchi comments on keeping description/workflow simple at first steps...and throughout the process. This is feels like an extensible feature rather than a default in Sufia, no? Where multiple work types are needed I'm in favor of a clear submenu building on the screenshot by @hackmastera.

**Comment by jcoyne** [comment]
@bnhowell sufia said default is no work types. It's up to the user to generate one or more

**Comment by mjgiarlo** [comment]
If we can align Sufia's behavior with CC's here, a big :+1: from me.

**Comment by ggeisler** [comment]
A proposed solution to this that was discussed with @mjgiarlo and @hannahfrost is shown in #2434. (I didn't mean to ignore the ideas proposed in this ticket, but I was approaching it from a Lerna point of view, and i think it actually is along the lines of what @simosacchi was proposing.) The idea is to just have one link in the pull-down menu ("Add a Work"). That link triggers a modal window where the user selects the type of work they want to add. See #2434 for details.

**Comment by mjgiarlo** [comment]
Thoughts on the idea @ggeisler mocked up in #2434, @simosacchi @jcoyne @mtribone @hackmastera @bnhowell ?

**Comment by hackmastera** [comment]
@ggeisler What are the implications on batch upload?

**Comment by mtribone** [comment]
Thanks for this @ggeisler ! I'd like to look at this a little more closely tomorrow . *east coast time*

**Comment by mtribone** [comment]
@ggeisler I think this cleanly solves the creation of multiple types of works and doesn't affect the "Add New Work" page by incorporating additional programming or refactoring. I think in the future we could entertain how in-page creation could be customized by the work type, but I think that is a looong discussion.

One thing to work on is the accessibility of our modals. It's come up in the past and I think we can adapt what others have already done. http://a11yproject.com/patterns/#modals

**Comment by simosacchi** [comment]
Hello all, I very much like @ggeisler approach. If there are no accessibility issue with such a modal, I am all in favor for it. It would keep the toolbar menu clean and provide a much better context for the selection of different types of work.

**Comment by newmanld** [comment]
I agree with @simosacchi – the design is clean.  I assume we can resolve any accessibility issues.  So +1

Assume that there is still work to do with batch per @hackmastera and #2438?

Do we have work to do to define a preliminary metadata template for each work type / model?  Or is customizing the models an implementation exercise?

**Comment by mjgiarlo** [comment]
Yes, we have not yet addressed the batch uploads. I suspect we could make it follow the same pattern, though using a different label to visually call out the difference if users accidentally click one and mean the other? cc: @ggeisler

**Comment by mjgiarlo** [comment]
@newmanld In Lerna, we need to do that, yes, because we're planning to ship (in the near term) two content types ("generic" work, for complex objects, and photograph). In Sufia, which does not give you any content types by default, that is an implementation exercise (though we could provide examples/patterns in our wiki). Thanks!

**Comment by ggeisler** [comment]
Regarding batch upload, as @mjgiarlo says we haven't addressed that feature yet in Lerna so I haven't given it any thought yet. I assume it has some different/additional requirements and as @mjgiarlo said the user would probably access it via a different menu item. Beyond that, I'd have to get more familiar with the batch upload requirements/workflow before offering any ideas about it (and I'm not sure it's at the top of the design priority list in Lerna).

**Comment by hackmastera** [comment]
Okay. Yes I agree the design looks clean and easy to implement. +1. Thanks!
