### ISSUE TITLE
Multiple work types: broken facets

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#2437]
### Descriptive summary

On 'My Works' works listing, and on search results, 'filter by work type' groups all work types into the same category, called 'Work'.
### Expected behavior

Work types should each have their own facet value.
### Steps to reproduce the behavior
1. Generate a 2nd curation concern using the sufia:work generator
2. create works of both types
3.  navigate to 'my works' or submit blank search.
### Related work

umbrella ticket is #2199

**Comment by jcoyne** [comment]
This is not a bug, there are two types of facet needed. One for the general type (e.g. Work, Collection, etc.) The other is for specific type (Book, ETD, etc)

CurationConcerns has both:
https://github.com/projecthydra/curation_concerns/blob/master/lib/generators/curation_concerns/templates/catalog_controller.rb#L26
https://github.com/projecthydra/curation_concerns/blob/master/lib/generators/curation_concerns/templates/catalog_controller.rb#L33
I think sufia only has the later.
