### ISSUE TITLE
Multiple work types: batch create arbitrarily chooses a work type

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#2438]
### Descriptive summary

In Batch Create there is no way to tell what kind of work will be created.

### Expected behavior
I should be able to specify work type for each file that I upload.

### Actual behavior
Both files were put into works of the most-recently-generated type.

### Steps to reproduce the behavior

1. Generate a 2nd curation concern using the sufia:work generator
1. upload some files using 'batch create'

### Related work

umbrella ticket is #2199

**Comment by awead** [comment]
@hackmastera it should be configured here:

https://github.com/projecthydra/sufia/blob/master/lib/sufia/configuration.rb#L137

then that's called by the BatchCreateJob.

**Comment by mjgiarlo** [comment]
Related to #2278.

**Comment by jcoyne** [comment]
@mjgiarlo I think we can either fix #2278 or this ticket, but we can't fix it both ways.

**Comment by awead** [comment]
Yes, let's fix #2278, but it sounds like @hackmastera wants to be able to upload different work types in the same batch form. That seems epic to me... you'd need to configure each actor stack to run for each chosen type, and assume that each type has a shared set of metadata.

**Comment by hackmastera** [comment]
Hm, yeah I guess there is a choice here, where you can choose one work type for the whole bunch. I don't think I have needs / use cases here. The flexibility might be nice for someone but I don't have a reason to say it's required. So that was just me jumping to conclusions!

**Comment by hackmastera** [comment]
i.e. i'm happy to close this as a duplicate of 2278 and then let someone else clamor for more flexible functionality in the future if it's needed. if @mjgiarlo approves.

**Comment by mjgiarlo** [comment]
I approve. Thanks! Closing as dup of #2278.
