### ISSUE TITLE
Defining Roles and Abilities

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#2440]
As an administrative user, I need to be able to do the following via the administrative dashboard:

* Add, remove, and edit roles
* Assign and de-assign roles to users (already present in Lerna)
* Authorize and de-authorize roles to act on one or more specified workflow steps

**Comment by jeremyf** [comment]
See #2441 for some discussion concerning Groups and Roles. For the desired flexibility, those two concepts should be separate.

**Comment by mjgiarlo** [comment]
Already have this accounted for.
