### ISSUE TITLE
Create and populate roles for approval workflows

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#2441]
As an administrative user, I need to be able establish groups of users with specific roles which can then be applied across workflows (and across Admin Sets, when implemented) within the repository, which saves me the trouble of entering user names in roles multiple times.

**Comment by jcoyne** [comment]
Could this be LDAP?

**Comment by mjgiarlo** [comment]
@jcoyne I don't see why we wouldn't want to plug in with LDAP when folks rely on it.

**Comment by jeremyf** [comment]
I must emphasize that we separate groups from roles. In Sipity, we created Groups and Roles separately. Groups are proxies for users. They are described by Nouns. Roles are proxies for actions. They are described as Verbs.

"ETD Reviewers" is a group. "ETD Reviewing" is a role. The "ETD Reviewers" have "ETD Reviewing" as a Role.

**Comment by mjgiarlo** [comment]
@jeremyf I imagine we would use a gem like https://github.com/RolifyCommunity/rolify to implement roles. That's what I mean by roles, anyway. I might like to see us build out role-oriented features before we work on, say, a user-facing UI for group management.

**Comment by jeremyf** [comment]
@mjgiarlo Are we allowing implementing institutions to create custom roles? If so, I don't believe rolify will work.

If we are allowing customized roles to exist, then we need to check if the user can take the action (i.e. `:edit`). CanCanCan can work, but it breaks down if we allow custom actions (i.e. `:approve`, `:return_to_submitter`). Once that is the case we need to begin thinking instead about how we answer the following questions:

* Query for all things that I can take actions on (i.e. They are in a state in which I have one or more actions available, including `:show`)
* Given an object what all actions can I take (i.e. it is in "Submitted for Review" and I have available to me "Show", "Return with Comment", and "Approve")

If those are requirements, or even "possible future requirements" I advocate that we spend time reviewing Sipity's implementation of these things and model accordingly. It is a very flexible system with a lot of liftable material (though it may take a guide).

For further discussion on authorization take a look at [Declarative Authorization](https://github.com/stffn/declarative_authorization). It provides an excellent breakdown of the complexities.

**Comment by mjgiarlo** [comment]
@jeremyf My take is that ultimately it would be good to allow site admins to define their own roles. For the time being, I'm happy to set design constraints that assume a certain small number of roles such as superadministrator, repository administrator, depositor, admin set creator, and reviewer.

**Comment by jeremyf** [comment]
@mjgiarlo In Sipity, another indirection we added is that a Role is scoped to a given workflow. That may not be required.

**Comment by mjgiarlo** [comment]
Yeah, not sure we'd need that.

**Comment by jeremyf** [comment]
@mjgiarlo we have the analogue of admin sets, in our work areas and submission windows. Across two different work areas, we have different reviewer roles (i.e. review ETDs vs. review ULRA submissions)

We also have the concept of the depositor assigning an advisor who approves the specific submission (but not all other submissions).

**Comment by mjgiarlo** [comment]
@hannahfrost @vantuyls Do you see the above as MUST HAVE, SHOULD HAVE, COULD HAVE, or NOT NEEDED?

**Comment by vantuyls** [comment]
I think the above is Should Have - the ability to set different roles for different sets for different users. E.g. Steve should be able to edit and approve every dissertation, but should only be able to edit masters theses. 

Depositors assigning a reviewer - this also seems very useful and a use case that would be not uncommon.

**Comment by hannahfrost** [comment]
@mjgiarlo It SHOULD HAVE the ability for a depositor to assign the user who approves the submission.

**Comment by mjgiarlo** [comment]
@jeremyf I realize I never followed up to this:

> If those are requirements, or even "possible future requirements" I advocate that we spend time reviewing Sipity's implementation of these things and model accordingly. It is a very flexible system with a lot of liftable material (though it may take a guide).

Yes, let's do that! Have time next week?

**Comment by jeremyf** [comment]
I will make time to review the implementation. I can do a deep dive in the
data modeling for the team. I am off on Monday and my Tuesday is a zoo, but
I can rearrange. If you give me two times I can make one work.

Jeremy Friesen

**Comment by mjgiarlo** [comment]
We already have a ticket for this. Closing.
