### ISSUE TITLE
Grant abilities to other users/roles within an approval workflow

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#2443]
As an administrator, I need to be able to grant to other users or roles the abilities to modify (metadata or file content) and submit items in an approval workflow.

**Comment by jeremyf** [comment]
Is the ability to modify and submit based on the workflow state?

Are we allowing custom state machines (i.e. events and states)?

**Comment by mjgiarlo** [comment]
@jeremyf :speech_balloon: 
> Is the ability to modify and submit based on the workflow state?

Yes, I would say so. Is that true in Plum, @tpendragon @escowles ?

> Are we allowing custom state machines (i.e. events and states)?

For the initial implementation, anyway, I'd probably recommend not allowing this, simply for scoping purposes.

**Comment by jeremyf** [comment]
@mjgiarlo Are there proposed initial state machines? At Notre Dame we've talked about (but have not made it very far):

1) License review - We don't want to expose material for which ND licenses the material. This creates a very dangerous liability
2) Copyright review - We may or may not want to review for copyright/appropriateness
3) Metadata review - Make sure any controlled vocabularies are updated
4) Cataloging - As part of the deposit, we may want to catalog what has been added to the repository; Stamp any OCLC on the object (to link back to the catalog)
5) Visibility - If they indicate something related to this may be published or patented, we want to provide consultation to ensure they know "Open Access" could compromise their ability to advance the work through other channels.
6) Send to tape
7) File processing

Having leveraged static state machines then attempting to migrate those state machines to something more dynamic (i.e. Sipity's state machine engine), I strongly suggest looking at a database driven state machine; It may seem complicated but when I realized there were going to be two different state machines in play, having a formalized creation process for those states was invaluable. It allowed for the rapid creation of a third one.

**Comment by mjgiarlo** [comment]
@jeremyf I suspect you're right that we're going to need a database-backed state machine to allow users to define their workflows more flexibly.

**Comment by jeremyf** [comment]
@mjgiarlo Well have I got a deal for you!

**Comment by mjgiarlo** [comment]
@jeremyf 😆😆😆

**Comment by mjgiarlo** [comment]
Though the target for our initial implementation (for early sprints) may do well to limit the choices here so we can get work done and iterate while we're designing the more sophisticated functionality.

**Comment by mjgiarlo** [comment]
I believe #2440 may have already covered this ticket, so I'm closing this.
