### ISSUE TITLE
Mediated Workflow Status Overview

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#2445]
As a reviewer in a mediated workflow, I should be able to see an overview of item statuses in the mediated workflow (e.g. Number of items in each step)

Could be related to work on administrative dashboard, or could be surfaced in the existing dashboard.

**Comment by hannahfrost** [comment]
Is this essentially a duplicate of #2426 ?

**Comment by mjgiarlo** [comment]
They're closely related. The difference is the role, I believe -- the repo admin should see more than the reviewer. I think I'll collapse them into one ticket. Thanks, @hannahfrost

**Comment by mjgiarlo** [comment]
Closed as dup of #2426.
