### ISSUE TITLE
When I delete a work from My Work Listing I get forwarded to the catalog

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2447]
### Descriptive summary

In Sufia 7 when I delete a work from my work listing instead of staying on the work listing I get forwarded to the catalog.  This also occurs from my highlights, my collections and files shared with me.
### Expected behavior

I would expect that if I delete a work from a My Listing (Works, Highlights shares) that I would return to the My Listing after the deletion occurs.
### Actual behavior

What happens currently is that I get sent to the catalog index.

![screen shot 2016-08-10 at 7 31 42 am](https://cloud.githubusercontent.com/assets/1599081/17552225/a5beb21c-5ecc-11e6-91a3-1ec722798fb0.png)
### Steps to reproduce the behavior

When I have works in the system 
And I go to My Work Listing
And I select delete from the Action Menu 
And I confirm the delete
Then I should return to the work listing
### Related work

Link to related tickets or prior related work here.

**Comment by nrm149** [comment]
PSUSprint01

**Comment by mjgiarlo** [comment]
See ScholarSphere fixes above.
