### ISSUE TITLE
The links from the user profile for collections and works do not filter

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2451]
### Descriptive summary

In sufia 7 on the user profile we have the number of works and the number of collections a user has deposited.

When you click on those links they do not filter based on depositor.  The numbers seem correct, just not the catalog search.

### Expected behavior

When I have collections from multiple depositors in the system I should see only the collections 
from the selected user when I click the link.

When I have works from multiple depositors in the system I should see only the works from the selected user when I click the link.

### Actual behavior

Collections from All users

![screen shot 2016-08-10 at 12 51 36 pm](https://cloud.githubusercontent.com/assets/1599081/17562511/33f4d27e-5ef9-11e6-8853-03556118aee0.png)

### Steps to reproduce the behavior

As One user Create a Collection
As Another user Create a Collection
When I Login as the first user
And I go to their profile
And I click on the collections link
Then I should only see the logged in user's collections

Same goes for works...

**Comment by nrm149** [comment]
PSUSprint01

**Comment by cam156** [comment]
These are the same links as the dashboard
