### ISSUE TITLE
I can be my own proxy

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2454]
### Descriptive summary

In Sufia 7 I can make myself a proxy.  I can look up my user on the dashboard and assign myself to be my proxy.  Yes it really does not harm, but just saying it make my head spin...
### Expected behavior

I should not be able to make myself my proxy
### Actual behavior

I can make myself my proxy

![screen shot 2016-08-10 at 2 43 29 pm](https://cloud.githubusercontent.com/assets/1599081/17566742/a5fbf29c-5f0a-11e6-8e07-508803cfb9ec.png)
### Steps to reproduce the behavior

When I am logged into sufia
And I am on my dashboard
Then I can type my email into the proxy box
And I can be added as my own proxy
### Related work

Link to related tickets or prior related work here.

**Comment by mjgiarlo** [comment]
I suggest we fix this in Hyrax rather than block the 7.3.0 release. If a fix comes in before the release comes out, I'll be happy to include that.
