### ISSUE TITLE
I can add a proxy that already exists when I accept a transfer

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2455]
### Descriptive summary

In Sufia 7 I can add a proxy twice by creating a proxy manually and then assigning proxy rights when I accept a transfer from that proxy.
### Expected behavior

A person should only be listed as a proxy once.
### Actual behavior

![screen shot 2016-08-10 at 3 04 22 pm](https://cloud.githubusercontent.com/assets/1599081/17567087/efcd6bca-5f0b-11e6-82b3-0aee7aecb8d8.png)
### Steps to reproduce the behavior

When I am user 1 I should transfer a work to user 2
When I am user 2 I should add user one as a proxy from my dashboard
Then I should accept the transfer choosing"Accept and add proxy"
Then I will see user 1 in my proxy list twice. 
### Related work
#2454

**Comment by mjgiarlo** [comment]
I suggest we fix this in Hyrax rather than block the 7.3.0 release. If a fix comes in before the release comes out, I'll be happy to include that.
