### ISSUE TITLE
Date index fields should be rendered as human-readable

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#2461]
When we added [support for Blacklight 6.3.0](https://github.com/projecthydra/sufia/commit/c86c3dac9a93567795a8849417bc9ab563df6f99#diff-1579bbfcd2c5a06b694d172af5f86dacR76), we stopped running the `date_uploaded` and `date_modified` index fields through the `human_readable_date` helper method. We should run them through that method, and write a test that fails if those dates do not render as human-readable.

**Comment by atz** [comment]
Do we assume the correct thing to do if the date doesn't parse is just return it unmodified?

**Comment by mjgiarlo** [comment]
@atz That sounds reasonable to me.
