### ISSUE TITLE
Single-use link does not copy link to clipboard

### ISSUE THREAD

**Issue by younga3** [projecthydra/sufia#2463]
Using sufia master.
When I add a work with a file, then select a "single-use link to file" from the dropdown. The page refreshes and there is no link in clipboard.
When I copy the data-generate-single-use-link-url and paste it in browser I get a routing error
eg. 
No route matches [GET] "/single_use_link/generate_show/2514nk481"

**Comment by mjgiarlo** [comment]
Thank you for reporting this, @younga3

**Comment by cam156** [comment]
@younga3 & @mjgiarlo I think this was what @awead was working on fixing with all of his changes to curation concerns and sufia #2368.  Were you testing with the version after that issue was closed?

**Comment by younga3** [comment]
Yes, I was testing this with the version of master that I built 5 days ago (2016-08-11).

**Comment by mjgiarlo** [comment]
I was able to repro w/ the latest in `master` after @younga3 wrote this ticket up.

**Comment by awead** [comment]
I fixed the copy actions in the FileSet show view. Part of the fix was to separate the processes for creating the link and copying it to the clipboard. I think the process for creating the link via this dropdown needs to be re-evaluated.
