### ISSUE TITLE
Related url no longer displays as a link

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#2472]
### Descriptive summary

In Sufia 6 there was a view for this field which called iconify_auto_link. Since these views were replaced with renderers the behavior was lost.

### Steps to reproduce the behavior

1. create a work with a related url
1. view the work's show page

### Related work
https://github.com/projecthydra/sufia/issues/2374

**Comment by hackmastera** [comment]
I can make a new renderer easily, but i can't call iconify_auto_link (which lives in the sufia helper) from the renderer. Is there a way to import it?

**Comment by hackmastera** [comment]
More likely I should move it out of the helper.

**Comment by mjgiarlo** [comment]
@hackmastera Should CC's `LinkedAttributeRenderer` take care of this (potentially by passing in a new option), or do we need a new renderer (e.g., `IconifiedLinkedAttributeRenderer`)?

**Comment by hackmastera** [comment]
@mjgiarlo I thought LinkedAttributeRenderer assumes you want the attribute linked within the context of the repository, i.e. linked to a search result set. Did I misinterpret?

**Comment by mjgiarlo** [comment]
@hackmastera Nope, I think you're right.

**Comment by andjsmit** [comment]
I was thinking this field was no longer a link, but in testing I don't find that to be the case:
![screen shot 2016-09-01 at 2 47 07 pm](https://cloud.githubusercontent.com/assets/333335/18180265/0f608374-7054-11e6-85e7-df037d253721.png)
So what is needed is the link icon since this is an external link? Like you would find for the collection show page?
![screen shot 2016-09-01 at 2 56 52 pm](https://cloud.githubusercontent.com/assets/333335/18180350/77707398-7054-11e6-9103-6054efe30ad7.png)

**Comment by mjgiarlo** [comment]
@andjsmit That makes sense to me.

**Comment by hackmastera** [comment]
@andjsmit I thought it wasn't linking at all, too. Sorry about that. I do think it's helpful and web-standard to have the icon, though.

The link is happening here:
https://github.com/projecthydra/curation_concerns/blob/master/app/renderers/curation_concerns/renderers/attribute_renderer.rb#L65

Is it safe/helpful to assume that any link going through this renderer would be external, and therefore require an icon? Or is it better to write a renderer especially for this field and others which will contain external URLs?

Either way the renderer won't have access to iconify_auto_link, since that's in the helper. I remain  unsure as to where that logic should move. Should a renderer call a view which calls the helper? Or should the logic move to ?? some util class in /lib? or can / should the renderer include the helper itself?

It may help to note that the description does use iconify_auto_link. Which it can do because it's a view (https://github.com/projecthydra/sufia/blob/master/app/views/curation_concerns/base/_work_description.erb).

**Comment by andjsmit** [comment]
If a renderer is added (IconifiedLinkedAttributeRenderer) should it be added in Curation Concerns or be the first renderer to be placed in Sufia?

**Comment by andjsmit** [comment]
As far as assuming the link is external, it might be coded to check but that may be overdoing it I suppose.

**Comment by hackmastera** [comment]
iconified_auto_link is a sufia thing. so unless cc wants that, too, I'm guessing this should all stay in sufia.

**Comment by hackmastera** [comment]
yeah i agree that feels like overdoing it. I guess the smallest impact would be to create a new renderer. I would call it UrlAttributeRenderer or ExternalLinkAttributeRenderer; I think to make its intended use more clear.

**Comment by andjsmit** [comment]
I like ExternalLinkAttributeRenderer.  Noobie question: location should be {sufia}/app/renderer/sufia/external_link_attribute_renderer.rb ?

**Comment by hackmastera** [comment]
I think app/renderers/curation_concerns/renderers/ is the way to make it work magically. I did one in my local app. not sure if there is an argument for putting it in a sufia/ directory and if there is I don't know what hooking that up would entail

**Comment by andjsmit** [comment]
Gotta like the magic! Think I've almost got it.

**Comment by andjsmit** [comment]
Moving renderer code to Curation Concerns - PR #963
