### ISSUE TITLE
Execute some html in description field

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#2473]
### Descriptive summary

Sufia 6 allowed too much but Sufia 7 allows nothing. My users want at least italics so they can, e.g., reference book titles.

**Comment by hackmastera** [comment]
apparently paragraphs are being used here as well.

**Comment by mjgiarlo** [comment]
I believe this is now available, from https://github.com/projecthydra/sufia/commit/11521027aa85843f26dd880f397143797be0d28f

**Comment by hackmastera** [comment]
Hm, that allows links but I need maybe <cite> and <br>. It might be nice to have a configurable whitelist?

**Comment by mjgiarlo** [comment]
@hackmastera oh, shoot, I misread this. Sorry to have closed it prematurely.

I'll move this issue to Hyrax. What would a starting default whitelist look like? a, cite, and br? Toss a list at me and I'll make sure it's carried over.

**Comment by hackmastera** [comment]
@mjgiarlo Also p. I think that's all we have. Thanks!!

**Comment by mjgiarlo** [comment]
Description metadata field should render limited HTML. Whitelist of tags:

* `<a>`
* `<cite>`
* `<br>`
* `<p>`

Thanks, @hackmastera

**Comment by jcoyne** [comment]
Are there any HTML attributes we want to whitelist? We wouldn't want to allow `onclick="stealMyCookies()"`, but we might want `href="http://example.com/"`

**Comment by mjgiarlo** [comment]
Be great if there were some library out there that could do this for us.
