### ISSUE TITLE
FileSet Breadcrumbs and Work Breadcrubs disappear when you refresh the page

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2477]
### Descriptive summary

In Sufia 7 Master, when I go to a work or fileset show page the breadcrumbs appear. Once I refresh the page the breadcrumbs disappear.

### Expected behavior

I would expect the breadcrumbs to remain after I refresh the page.

### Actual behavior

Before refresh
![screen shot 2016-08-16 at 12 23 16 pm](https://cloud.githubusercontent.com/assets/1599081/17707070/ac79c062-63ac-11e6-8173-a59ccfe02134.png)

After refresh
![screen shot 2016-08-16 at 12 20 41 pm](https://cloud.githubusercontent.com/assets/1599081/17707068/aad6f19e-63ac-11e6-948b-081b3cc1abae.png)

### Steps to reproduce the behavior

When I have a work with a file attached
And I goto the show page of that work
And I hit the browser refresh button
Then the breadcrumbs disappear

When I have a work with a file attached
And I goto the show page of that work
And I goto the show page of the fileset
And I hit the browser refresh button
Then the breadcrumbs disappear

**Comment by jcoyne** [comment]
Is this because there is no referrer header once you refresh?  We have no way of knowing how you got to this page, thus the breadcrumbs can't be calculated.

**Comment by cam156** [comment]
@jcoyne with the fileset is is truely bad because you have no way to get back to the work.  I guess you could go through user activity.  I would suggest a default breadcrumb for a fileset would be the parent work.  Or maybe there needs to be some navigation links other than the breadcrumbs.

**Comment by jcoyne** [comment]
@cam156 FileSets are not all guaranteed to have a work. Think of @afred's use case where they have a bunch of FileSets uploaded first, only later do they create works.

**Comment by jcoyne** [comment]
I think within PCDM it is technically possible for two works to have a single fileset too, although I don't know if sufia would support this in practice.

**Comment by mjgiarlo** [comment]
I take @jcoyne's points, but if a FileSet is a member of a work, it would be nice for that linkage to be rendered when referrer headers are not present, especially since Sufia master does not currently allow you to upload FileSets outside the context of work. Isn't @afred doing his work in CC?

**Comment by afred** [comment]
@mjgiarlo yes, we're building off of CC.
