### ISSUE TITLE
An admin set should have a show page.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#2502]
This should look just like the collection page
- [ ] metadata: title, description
- [ ] selected thumbnail
- [ ] first 10 members, with a way to paginate and search through the members.

**Comment by jcoyne** [comment]
@ggeisler it would be good to have wireframes for this.

**Comment by mjgiarlo** [comment]
@jcoyne Gary said it may be a week or two before he can get to AS-specific UX, FYI.

**Comment by ggeisler** [comment]
Mockups of the admin set show page are shown below. The only differences between the two is one shows the admin set's works in list view and the other in gallery view. 

I'm not sure that this design matches the way things are done in Sufia; for better or worse, I'm approaching this from a HyBox point of view and trying not to be too constrained by how things are already done in Sufia.

#### List view

![visitor-show-list](https://cloud.githubusercontent.com/assets/101482/18105087/0290acfc-6eb3-11e6-9913-574ad9887b0d.png)

#### Gallery view

![vistor-show-gallery](https://cloud.githubusercontent.com/assets/101482/18105094/09a68b42-6eb3-11e6-808b-7ba000cf6cde.png)
