### ISSUE TITLE
Who should be able to assign a work to an admin set?

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#2505]
What permissions are required? Edit on the Admin Set?  Should self deposit (non-provileged users) be able to assign to an admin set?

**Comment by mjgiarlo** [comment]
Tagging @hannahfrost and @vantuyls for input

**Comment by hannahfrost** [comment]
Need to tease apart several things here. I don't understand exactly what is meant by "edit on the Admin Set"; does it mean add a work as a member to that set? 

Would it be useful to more clearly articulate permissions options on this document? There I refer to the "Depositor" as one who can add a work to an Admin Set.
https://docs.google.com/document/d/1d3_KggC84paVLM0DahUX6MvHGDVE4sM4Uld0Oxs-UHw/edit#

My understanding of Admin Sets conceptually to date is that only privileged users can assign a work to an Admin Set. In addition to batch deposit, that must also be possible through a self-deposit interaction.

**Comment by jcoyne** [comment]
Yes, on that document, I don't see anything that says which admin sets a depositor may use.  Are they free to pick from the universe of Admin sets?

>There "Depositor" is the one who can add a work to an Admin Set.

>My understanding of Admin Sets conceptually to date is that only privileged users can assign a work to an Admin Set. 

Those two statements seem to be in conflict to me unless you are saying that "privileged user" is equivalent to "depositor"

**Comment by hannahfrost** [comment]
A depositor can only add a work to an admin set for which they have those permissions. I edited the doc for clarification. And yes, a depositor is a privileged user.

**Comment by jcoyne** [comment]
How exactly are we modeling "those permissions"? Do you mean users who have "edit permissions on the admin set"?  Or do we mean something else?  If something else, we will have to explore if `http://www.w3.org/ns/auth/acl#Append` is what will sufficiently cover this case.

**Comment by atz** [comment]
The concept of "adding a work to an admin set" is probably wrong.  You add a work to a collection.  The collection *already has* an admin set.   That is the association.  Unless you are creating (and to a lesser extent editing) a collection, you aren't touching that association.  The user can set particular non-default rights on a work.  That isn't an admin set, right?

**Comment by atz** [comment]
I guess Sufia's Admin Set is comparable to Stanford's current collections.  Terminological confusion.

**Comment by mjgiarlo** [comment]
Until we have more design in place and an implementation of permissions templates (formerly known as "APOs"), I propose that we move forward with this work as follows: by default, any depositor should be allowed to assign a work any admin set. I believe that is what the current implementation permits. 

Ultimately, we may want to add a new "upload to this admin set" ability that the creator of an admin set can grant to other users (and groups) within the system. This is where design and further discussion are needed.

**Comment by hannahfrost** [comment]
I believe that the admin set UI mockups and related discussions address the questions posed above.

**Comment by ggeisler** [comment]
@mjgiarlo No additional design is needed for this, correct?
