### ISSUE TITLE
Configuration option for disabling admin sets

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#2507]
@cam156 said
> PSU would prefer for admins sets to be something we could turn on or off.

- https://github.com/projecthydra/sufia/pull/2504#issuecomment-241050514

**Comment by mjgiarlo** [comment]
Are you working on this one, @jcoyne?

**Comment by jcoyne** [comment]
well, work has stalled pending https://github.com/projecthydra/curation_concerns/pull/925
