### ISSUE TITLE
File could not be sent to SHARE Notify should not be visible on User activity

### ISSUE THREAD

**Issue by olendorf** [projecthydra/sufia#2512]
In some content where there are errors, the show page gets a potentially long list of these messages.  Seems they shouldn't be visible to your average user. Its not really user activity, it is more of a system activity/creator warning that should be visible to the owner the content and admin?

An image below shows what I'm seeing.

![share_notify](https://cloud.githubusercontent.com/assets/857767/17855137/f2e30e4a-6844-11e6-9bb6-00c1a5712b7b.png)

**Comment by mjgiarlo** [comment]
Hi, @olendorf! I agree with your assessment. I suspect this may be a ScholarSphere-level issue, since Sufia itself does not use the ShareNotify component. Pinging @cam156 @awead @mtribone too.

**Comment by awead** [comment]
All the SHARE notify stuff is gemified under https://github.com/projecthydra-labs/share_notify but the execution of actually sending things to Share is application-specific. In the above case, we use `ShareNotifyJob` in Scholarsphere, which does the sending a reporting. If there's a failure, it calls `ShareNotifyFailureEventJob` which is an extension of Suifa's `ContentEventJob`.  In fact, all the informational messages resulting from `ShareNotifyJob` are extensions of `ContentEventJob` so the easiest way to fix this would be to create a new class in place of `ContentEvetJob` that puts the messages where you'd like them.

@mjgiarlo is there a message class using the Active::Job syntax that sends messages only to the user?

**Comment by mjgiarlo** [comment]
@awead the key question here is who do you want to see this information? If it's "everyone who has access to the object," then your job is done. If it's "a select group of users (the depositor, and perhaps others who have edit access)," then you may want to use a subclass of [MessageUserService](https://github.com/projecthydra/sufia/blob/master/app/services/sufia/message_user_service.rb). (Yes, this issue now intersects with #1659, where I just commented about a pattern that I might like to see emerge when someone takes it on.)

**Comment by awead** [comment]
I'd 👍  to `MessageUserService` for simplicity but I don't have a stake in this.

**Comment by mjgiarlo** [comment]
@awead OK. Who does?

**Comment by awead** [comment]
@olendorf

**Comment by mjgiarlo** [comment]
K. Back to you, @olendorf!

**Comment by olendorf** [comment]
So, being less in the weeds with this, I may be off base, but I am liking the idea of a class or subclass, to put it in the right place. From my point of view with respect to this issue, the information is represented as **User Activity** when it is really **System Activity** or maybe **System Warning**. So a `MessageUserService` subclass does seem the right way. I think the behavior were looking for is to get **User Activity** separate from **System Activity**.

**Comment by mjgiarlo** [comment]
I think so, @olendorf, though I was taking the discussion in a more UX-y direction: who ultimately should see notifications re: SHARE integration? As in, what's the functional requirement underlying the feature as currently implemented? 

My *conjecture* is that if there are failures occurring in the system, one or more users who care about those should be alerted (using user messaging rather than activity stream) directly. This sidesteps the user v. system activity question.

**Comment by olendorf** [comment]
I think we are in agreement @mjgiarlo .  From a UX point of view its what users get messaged.  The underlying guts, it might make more sense to subclass it out, but I'm not really familiar enough with that part to really answer with more than an educated guess.

Moving forward then, I would push implementation decisions back to those with more knowledge.

**Comment by mjgiarlo** [comment]
OK, @olendorf. Then I think the right move is to change how ScholarSphere uses the ShareNotify gem, and instead of using event jobs, it should subclass `Sufia::MessageUserService`. For examples of such subclasses, look at `*_{success,failure}_service.rb` in Sufia.

**Comment by awead** [comment]
Ok, I think we have a solution. If @olendorf agrees, we can fix this in Scholarsphere by using the Sufia::MessageUserService instead of the current event jobs.

**Comment by mjgiarlo** [comment]
Thanks for writing this up and discussing the issue, @olendorf and @awead!

**Comment by olendorf** [comment]
That works for me. Thanks all.

**Comment by mjgiarlo** [comment]
:clap:

Closing since this work will be done in the 'sphere.
