### ISSUE TITLE
Admin Set creator should be allowed to set default permissions for added works

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#2516]
Note: the permissions template does **not** need to be applied to added works in this issue. That is covered by #2566. This issue is just about creating a permissions form that persists and is associated with the Admin Set.

**Comment by jcoyne** [comment]
In sufia, the work would already have permissions set (when it is deposited, by the depositor). Do these permissions get overwritten?

**Comment by mjgiarlo** [comment]
Yeah, this is tricky, because the form (incl. permissions) is already loaded when I would be selecting an AS, so we'd either need 1) javascript shenanigans, 2) an alternative UX path for AS uploads, or 3) some server-side shenanigans to deal with this. 3 seems gross, because then we're in the business of trying to reconcile the perms the user selected with the default perms from the AS's template. 1 potentially has the same issue if a user tweaks perms in advance of selecting an AS. 2 forces users to be aware of alternative paths for what seems like a single operation. Recommendations? @ggeisler @projecthydra/sufia-ui-ux-advisors

**Comment by mtribone** [comment]
It would have been nice to have the workflow for setting permissions with Admin Sets worked out before it made an appearance in the UI.

![screen shot 2016-08-24 at 9 22 14 am](https://cloud.githubusercontent.com/assets/4163828/17932510/5eeb3a6e-69de-11e6-8ed4-b4da21a33c92.png)

**Comment by mjgiarlo** [comment]
There's a subsequent ticket that will allow disabling admin set support, fwiw, and we're planning to offer some design around admin set workflow in the coming weeks. Sorry that didn't happen sooner!

**Comment by mtribone** [comment]
My gut says option #2 and also #1 and #3 have the word "shenanigans" in its description so not strong candidates for endorsement. Can admin sets be created from existing works or collections by other users?

Also is this documentation good for background about expectations and uses?
https://wiki.duraspace.org/display/hydra/User+Collections%2C+Admin+Sets%2C+Display+Sets

**Comment by hackmastera** [comment]
I vote for JS shenanigans. We could figure it out. I'm just not sure the desired inheritance / override behavior is well-defined yet?

- when admin set is select, some kind of message shows up saying "your permissions will override those of this admin set, which has X default permissions -- click to reset"
- when admin set is selected, ability to set local permissions greys out.

**Comment by mjgiarlo** [comment]
:speech_balloon: @mtribone 
> Can admin sets be created from existing works or collections by other users?

What do you mean by "created from?"

**Comment by mjgiarlo** [comment]
@mtribone re: defining Admin Sets, here's what we think they are:

An Admin Set is a top-level grouping of resources that is managed by a privileged user (e.g., a repository administrator or a curator).

* Promoted to top-level visibility in the UI
   * **MAY** display as a facet
   * **MAY** be displayed in a list of Admin Sets on the landing page
   * **SHOULD** show up as a search result
* **MAY** have some behavior (e.g., add permissions to member) when members are added to the Admin Set.
* **MAY** have some special metadata (default permissions).
* **SHOULD NOT** directly control access to its members.
* **MAY** indirectly influence access to its members by setting the default permissions on the member when the member is added to the Admin Set.
* An object contained by an Admin Set **MUST NOT** be contained by another Admin Set.
* An Admin Set **MUST NOT** be contained by any objects or collections.
* Whether Admin Sets may be contained by other Admin Sets is undefined and considered out of scope for the 2016 Hydra-in-a-Box work cycle.

**Comment by mtribone** [comment]
Perhaps my wording is off. Generate? Develop? Construct? Assign?

Scenario:

I'm someone from a college within a university who would like to group student posters together into an admin set that represents the college and not the individual. Students upload their posters to the repo and then the person from the college groups them into an admin set. I'm guessing that this grouping is only an association.

Who retains the ownership and/or editing permissions to the poster? The student? The admin? How do we control who and what is grouped into an admin set? ScholarSphere is a self-deposit service. How do we prevent someone from gobbling up all the things?

**Comment by mjgiarlo** [comment]
Ah, good questions! Thoughts on this, @hannahfrost @vantuyls ?

**Comment by jcoyne** [comment]
>ScholarSphere is a self-deposit service. How do we prevent someone from gobbling up all the things?

only admins can make admin sets, so this is restricted to a small number of (presumably well
 trained) individual

**Comment by hannahfrost** [comment]
So here we hit upon a fundamental question: is an admin set a gathering of works already deposited to the repository, unbeknownst to the depositor? or are the works managed in the set (by its admin) from their inception? I agree with @jcoyne: an admin set is created by an admin, and the admin can invite specific depositors or any depositor to add works to that set.

I think the work's depositor should retain ownership of the work itself, but has little to no control over the admin set settings. Deposit agreement terms will cover all that.

The matter of making a "collection" out of already self-deposited things is something else altogether in my mind. At Stanford we have simply referred to them as a "set" or "curated set". Any maybe this is where Spotlight steps in ...

**Comment by jcoyne** [comment]
See #2566 about how this template gets applied to the works.

**Comment by weiweishi** [comment]
Sorry @mjgiarlo to ask questions here. Just reviewing your specs on Admin sets to compare with our requirements for collection/community. And wondering how you've reached the decision of:

- An object contained by an Admin Set **MUST NOT** be contained by another Admin Set.

A scenario:

Say an article is co-authored by researchers from Faculty of Science and Faculty of Education. And both department/school have an admin set that they maintain, and both are listed on the landing page. They both rightfully would like to include this article in their sets as it is a piece of intellectual work with shared authorship. Or in a different but similar case, an adjunct professor of two departments published a report based on an interdisciplinary study, it should really belong to both departments' set. 

The assumption of one work can only belong to one admin set may not work in these cases. And these scenarios are common in an IR environment.

**Comment by mjgiarlo** [comment]
Hi, @weiweishi! Our operating assumption up until now has been that objects may be contained by one and only one Admin Set. I defer to folks like @hannahfrost and @vantuyls and @elrayle as to how they've dealt with use cases like the one above. @jcoyne may also have seen needs like this during his time at DCE, and it'd be interesting to hear how others have modeled this.

Part of why this is difficult is that an Admin Set confers upon its members a default permissions template. How do we deal with situations where multiple Admin Sets confer conflicting permissions upon a work? It gets tricky very quickly. Perhaps there's some other way we can handle this?

**Comment by hannahfrost** [comment]
Hi @weiweishi. Like @mjgiarlo says, one of the advantages of using Admin Sets is that it is an efficient way to apply and manage common attributes or default permissions across a set of items. For this reason, it makes sense that an item would a "home" Admin Set. I find the use case for Admin Sets is clearest in the context of more traditional digital library collections, as opposed to IR use cases. But nonetheless, an Admin Set can certainly be leveraged for IR content like articles written by multiple authors with different affiliations. As you suggest, a Display Set could play the role of bringing together works from any number of Admin Sets for purposes of presenting a community collection. And a work could be in any number of Display Sets. 

Display Sets offer presentation flexibility while Admin Sets offer management efficiency. The combination is pretty powerful. 

Will you be at Hydra Connect week after next? If so, stop by our poster!

**Comment by weiweishi** [comment]
thank you @hannahfrost and @mjgiarlo. I can definitely see how admin sets would fit into the digital library collection context. Has the work on display set started yet?  We have developed some communities/collections functionalities and plan to expand on those more during our phase 2 implementation. Many of our use cases intersect with both admin sets and display sets, and we are wondering what would be the best way for us to collaborate with the community. Let's connect during Hydra Connect.

**Comment by mjgiarlo** [comment]
@weiweishi No, I don't believe anyone has started work on display sets yet. We should talk more about Hydra Connect, for sure. :)

**Comment by mjgiarlo** [comment]
This is finished.
