### ISSUE TITLE
File manager: make sure 'set thumbnail' is pulling through to sufia

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#2520]
https://github.com/projecthydra/curation_concerns/commit/cbe510d756fa46a37c0a178be5fa8d32965de171

**Comment by mjgiarlo** [comment]
When I ran the demo yesterday, it seemed to reset the thumbnail in the catalog views but not in the work show view.

**Comment by hackmastera** [comment]
@mjgiarlo the behavior your observed is present in curation concerns as well.

This is because the list view renders the thunbnail, whereas the work show view renders the media display for the representative file.

It's confusing because if all you have is images then the distinction is not clear. I think one fix would be to add representative file selection to the file manager alongside thumbnail selection.

**Comment by hackmastera** [comment]
closing; filed https://github.com/projecthydra/curation_concerns/issues/958

**Comment by hackmastera** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;jZBtK76g&#x2F;1319-check-thumbnail-indexing-on-sufia"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> check thumbnail indexing on sufia</a>
