### ISSUE TITLE
Admin Sets – Required or Additional Fields

### ISSUE THREAD

**Issue by mtribone** [projecthydra/sufia#2531]
Currently, the dropdown for Admin Sets when creating or editing a Work is the last item in the base metadata. It is not marked as a required field. If it is not a required field, should we move it to the Additional Fields?

![screen shot 2016-08-24 at 9 22 14 am](https://cloud.githubusercontent.com/assets/4163828/17933010/6b12f578-69e0-11e6-888b-1add11c1ca5d.png)

**Comment by awead** [comment]
Yes, or alternatively into the relationships tab.

**Comment by awead** [comment]
ping @jcoyne, because he added it to the required part. Maybe there's a use case at work here that we don't know about.

**Comment by awead** [comment]
I think the confusion is that there is an implicit kind of expectation that all the fields in the primary fields are required. Admin set is not required, but it is in those first set of fields, so it could throw people off.

**Comment by jcoyne** [comment]
I don't think there is any expectation that primary fields are required.  Required fields are denoted with the blue label next to them.

**Comment by awead** [comment]
ping @projecthydra/sufia-ui-ux-advisors see what they have to say.

**Comment by hackmastera** [comment]
+1 relationships tab. it's a type of collection and that's where collections are.
