### ISSUE TITLE
Files appear in uploads directory twice

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2553]
### Descriptive summary

When uploading files, the binary is showing up twice in the temporary directory, under different sub-paths.

With the default `tmp/uploads` directory, when I visit the new work page and upload the file I want to ingest, it first places the file in a tmp location like:

```
tmp/uploads/sufia/uploaded_file/file/1/file.jpg
```

This is all fine and good. Next, I enter the rest of the metadata and hit Save. But, look what's in the directory now:

```
tmp/uploads/7w/62/f8/20/file.jpg
tmp/uploads/sufia/uploaded_file/file/1/file.jpg
```

Both files are identical, bit for bit.

### Expected behavior

The uploaded file should only appear once in the tmp directory,

### Actual behavior

It's getting put in there twice. Not sure how. I suspect that during characterization or derivative creation it's getting copied or re-downloaded form Fedora somehow with is id as the path.

The `tmp/derivatives` directory is fine... only one file there.

### Steps to reproduce the behavior

1. Build latest from master
1. Create a work and watch `.internal_test_app/tmp/uploads`

**Comment by awead** [comment]
I'm pretty sure this is the culprit:
https://github.com/projecthydra/curation_concerns/blob/master/app/actors/curation_concerns/actors/file_actor.rb#L23
Should this be the expected behavior, or can we adjust the call to `WorkingDirectory` so that it doesn't copy if it's already locally available. @jcoyne ?

**Comment by jcoyne** [comment]
Uh, I can't recall the reasoning for that. Perhaps for direct calls to ingest local content (not uploads)

**Comment by awead** [comment]
I've confirmed this is working with the merge into CurationConcerns, but we'll need a CC release to close this ticket.

**Comment by mjgiarlo** [comment]
@awead OK. Looking at https://github.com/projecthydra/curation_concerns/compare/v1.5.0...master ... should it be 1.6.0 (adding creator = feature?)?

**Comment by awead** [comment]
@jcoyne found a regression bug, so we've revered #944 until I can fix that.
