### ISSUE TITLE
Leverage select2 for autocompleting fields that take URIs

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2563]
### Descriptive summary

With collections, works, and now admin sets, there are classes of inputs that take existing URIs in the fedora repository as their inputs. Currently, there are dropdowns populated at render or text fields that require IDs.

To make for a better UI, we should use select2 as a means to query for existing resources that the user has access to and render them as human-readable options for these inputs, while building the URI as the value in the form. Then, an actual valid URI will be submitted without the user needing to worry.

**Comment by mjgiarlo** [comment]
I might like to see #2492 first, but :+1: to this issue.

**Comment by awead** [comment]
I agree, in fact, upgrade first before doing this.
