### ISSUE TITLE
When a work is added to an admin set it applies the permissions template

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#2566]
How does the rights template interface with the explicitly added rights?

**Comment by hannahfrost** [comment]
This question seems to assume that a work is created before it is assigned to a set instead the inverse. This could happen if a repo supports both admin sets as well as works & user collections.

If the work's rights aren't aligned with those of the admin set, but can be changed to come into alignment, is it just a matter of editing the work's rights and then re-assigning? Do we need a distinct UI for that, or just some editable metadata fields on a work's page?

We clearly need a design for adding a work to a pre-existing admin set.

**Comment by ggeisler** [comment]
See https://ggeisler.github.io/lerna-dashboard/admin-sets-new.html for mockups of the template. Screenshots below:

--
### Participants tab

* Add buttons are disabled until the user selects both a User/Group and a Role. 
* Changes to the Current Participants section (adding or removing a participant) require the Save button to be saved.

![lerna_ui_mockups](https://cloud.githubusercontent.com/assets/101482/18484992/c6206a44-799f-11e6-9893-de82562f0c87.png)

### Release and Visibility tab

* The mm/dd/yyyy options use the datepicker as currently in Sufia
* The "Varies" options for Release are disabled unless the "Varies" radio button is selected

![lerna_ui_mockups 2](https://cloud.githubusercontent.com/assets/101482/18485069/16becb44-79a0-11e6-9e8e-0929f31c0abf.png)

**Comment by mjgiarlo** [comment]
This is done.
