### ISSUE TITLE
When creating an admin set I should be able to specify a language.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#2579]
Ref #2500 also update the list view (#2501) to display it:

https://ggeisler.github.io/lerna-dashboard/sdr-admin-sets-list.html

**Comment by hannahfrost** [comment]
I'm backpeddling on the language thing. It feels odd to require this, and I want to consult with our metadata folks at Stanford (source of the requirement for our local practices)

**Comment by atz** [comment]
I don't understand at this level what the language intends to "control" or "specify" or "describe".  I don't think we are going to enforce "all content must be english only" or "all metadata must be both EN-CAN and FR-CAN", so I don't see this as controlling anything. At best I would hope have an admin set's language describe what language the governing documents (e.g. rights statements) were recorded in.  Ideally, if we use authoritative URIs (e.g. for cc-by), we can reference the rights statements in any number of languages.  So yeah, I'm missing where this really fits in.
