### ISSUE TITLE
Non-Authenticated users should not see an empty action dropdown list

### ISSUE THREAD

**Issue by andjsmit** [projecthydra/sufia#2587]
### Descriptive summary

A non-authenticated user sees a "Select an action" button on a Work while viewing a collection index page.

### Expected behavior

A different button for viewing the work or no button at all.

### Actual behavior

Users sees an empty drop down box.

![screen shot 2016-08-30 at 1 36 43 pm 3](https://cloud.githubusercontent.com/assets/333335/18100181/dd52206a-6eb7-11e6-9f67-89986daeaf49.png)

**Comment by jcoyne** [comment]
What page is this on? Can you post a screenshot?

**Comment by andjsmit** [comment]
/collections/{ID}
