### ISSUE TITLE
No help text is showing for creator or contributor on collectio new

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2589]
### Descriptive summary

In Sufia 7 master when I run the internal test app I see no help text for contributor creator, and resource_type.

The help text is defined as *_html which does not seem to be displaying. See: https://github.com/projecthydra/sufia/blob/master/config/locales/sufia.en.yml#L331-L344

### Expected behavior

I should see help for each field

### Actual behavior

![screen shot 2016-08-30 at 2 08 28 pm](https://cloud.githubusercontent.com/assets/1599081/18101184/b07042f8-6ebb-11e6-97ae-a907aaca0bfc.png)

### Steps to reproduce the behavior

When I login
And I click on create collection
Then I should see help text for creator, contributor, and resource type

### Related work

Link to related tickets or prior related work here.

**Comment by jcoyne** [comment]
@cam156 can you confirm that this worked in Sufia 6?

**Comment by jcoyne** [comment]
It doesn't look like simple_form has the behavior you are expecting:
https://github.com/plataformatec/simple_form/blob/efe1212e12b45791d9521890f774c87f00d283f4/lib/simple_form/inputs/base.rb#L172-L187

**Comment by jcoyne** [comment]
It appears that this behavior was pulled here: https://github.com/plataformatec/simple_form/commit/63fbc2d5a8a86a51f856f42a5bdb10fae7ef3912 in version 3.2.0
