### ISSUE TITLE
Create admin-only page to view all users and roles

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2609]
Create route, view, and controller that only an admin can view that displays a list of all users. 
- [ ] Create route that routes to an admin only controller
- [ ] Controller that grabs all users and sends them to view
- [ ] View which displays all users and roles associated with user.

Decomposition of #2421

**Comment by vantuyls** [comment]
Mockup here:
https://wiki.duraspace.org/display/hydra/List+Admin+Set+Roles+-+Manage+Users%2C+Groups%2C+Roles+Mockups

but it may be dated...

**Comment by mjgiarlo** [comment]
There is a similar user/role management view in Lerna that we could extract and use in Sufia. 

Out of scope for current mediated deposit sprints.
