### ISSUE TITLE
Administrator Role can modify all content

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2614]
Administrator can: 
- [ ] search and view all items (including private items not owned by me), 
- [ ] edit all items (including items I do not own), 
- [ ] delete all items, 
- [ ] transfer ownership of all items (including items I do not own), 
- [ ] share ownership of all items (including items I do not own), 
- [ ] move items to and from all communities and sets

Decomposes #2421

**Comment by mjgiarlo** [comment]
Out of scope for current mediated deposit sprints.
