### ISSUE TITLE
Create a Reviewer Role

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2615]
Reviewer Role user should be able to edit all metadata for an item even if the reviewer is not the creator.
- [ ] generate new role
- [ ] ensure that the role abilities align with ability to edit metadata
- [ ] allow the user role to mark a work as reviewed and set its state to active

Decomposes #2422

**Comment by mjgiarlo** [comment]
We believe this is already done as part of the mega-sipity PR in CC.
