### ISSUE TITLE
When an object is deposited and mediated deposit is enabled, the object state should be set to Inactive

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2616]
All works and file sets are marked as inactive (in draft form) when deposited, if the mediated deposit feature flipper is on. To mark an object as inactive, set its `state` property to `::RDF::URI('http://fedora.info/definitions/1/0/access/ObjState#inactive'`. See https://github.com/projecthydra/curation_concerns/pull/928/files for the work that enabled this feature.

Decomposes #2452. Further decomposed into

**Comment by mjgiarlo** [comment]
What does it mean for an object to be inactive? Is it discoverable via search? If so, by whom? Is the show page visible? If so, by whom? Are its stats included in administrative stats? etc. What other questions should be be asking here? @jeremyf @jcoyne

**Comment by jeremyf** [comment]
For not yet approved objects, their visibility is very different from their
visibility once approved. In Sipity I have a proxy object for a work. This
proxy object holds the work flow state. When querying for "As a reviewer,
what can I see" I use query the proxy object states and render an index of
those objects.

Items that are not approved are visible to workflow participants (and only
visible when the work flow state is applicable for the participant).

Jeremy Friesen

**Comment by vantuyls** [comment]
@mjgiarlo - Inactive object show pages are always visible to Amin Role and visible to Reviewer Role if the reviewer is part of the object's workflow.

I don't think inactive objects should be counted in admin stats, unless for some reason we want specific stats for, e.g., number of objects being processed currently.

Inactive objects are not discoverable by search.

**Comment by hortongn** [comment]
@randalldfloyd @scholarworks I'm grabbing this issue to work on tomorrow after https://github.com/projecthydra/sufia/pull/2645 is merged.

**Comment by vantuyls** [comment]
Reopening this to ensure that the issue is covered by the new Curation Concerns workflow branch and subsequent Sufia Mediated Deposit work.

**Comment by scholarworks** [comment]
FYI - I added the "CurationConcerns::Workflow::DeactivateObject" method to the new state of a workflow, and it appears to set the value properly:

ns007: objState
http://fedora.info/definitions/1/0/access/ObjState#inactive

But the item is still publicly viewable.

**Comment by mjgiarlo** [comment]
@straleyb are you working on this and #2828 together (in the work you're relocating to CC)? if so, makes sense.

**Comment by vantuyls** [comment]
closing. this is happening in both sufia and cc.
