### ISSUE TITLE
When a deposit is approved, the object state is set to Active

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2617]
Initially, we want only an Admin User to act as an approver (for simplicity) - so the Admin Role has the ability to flip the state from inactive to active or vice versa. 

Follows after #2616 
Decomposes #2452

**Comment by mjgiarlo** [comment]
See discussion on https://github.com/projecthydra/sufia/issues/2616#issuecomment-244457211 re: what it means for an object to be inactive vs. active.

**Comment by hortongn** [comment]
@vantuyls  I've got this working.  Just need to do the tests.  When mediation is flipped on AND the user is an admin, the work edit form has radio buttons to toggle the work's state between active/inactive.

**Comment by vantuyls** [comment]
Reconcile this with the Object State work in Curation Concerns.

**Comment by blancoj** [comment]
From a conversation on slack I had with @jcoyne , as long as we have this action defined in the json object, https://github.com/projecthydra/curation_concerns/blob/f55dcbafd364e4b55d60cccbe94d3b4c8c68b917/lib/generators/curation_concerns/work/templates/workflow.json.erb#L35

           "methods": [
             "CurationConcerns::Workflow::ActivateObject"
           ]

Then the Active state will be set on.  I will test to make sure.

**Comment by blancoj** [comment]
I used a json in which "CurationConcerns::Workflow::ActivateObject" is called after the complete process.  Even though this issue is in sufia, the code for this is in CC.  I stepped through the code in CC and examine the state of the generic work and saw that it was changed by ActivateObject to active, so I think it is safe to close this issue.

**Comment by mjgiarlo** [comment]
Thanks, @blancoj!
