### ISSUE TITLE
Create a Review Queue Index Page

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2618]
Review Queue Index Page shows objects that are in the Inactive Object State (ie objects needing to be published) and waiting review to become active.

Page should include:
- [x] Item Title
- [ ] Item ID (?)
- [x] Status
- [ ] Name of Workflow item was deposited into
- [ ] Workflow step the item is at (e.g. 2 of 3)

Decomposes #2426 and #2445

**Comment by vantuyls** [comment]
mockups of page are here:

**Comment by mjgiarlo** [comment]
Defer until 1+-step workflow work starts.

**Comment by vantuyls** [comment]
also - refer to any recent Lerna UI mockups or ping @ggeisler for thoughts/suggestions/new mockups

**Comment by jcoyne** [comment]
This is already done except for "Workflow step the item is at (e.g. 2 of 3)", which is impossible due to workflows not necessarily being linear.

**Comment by mjgiarlo** [comment]
True. Maybe we can list the workflow step as the name of the state the item is currently in?

**Comment by jcoyne** [comment]
@mjgiarlo that's a fine solution.

**Comment by mjgiarlo** [comment]
@vantuyls if you're cool with that idea, can you reflect the change in your mock-ups above?

**Comment by vantuyls** [comment]
yep - will update mockups.
