### ISSUE TITLE
After a reviewer has edited an items metadata and is on its show page, there should be a button on that page to mark the item as reviewed

### ISSUE THREAD

**Issue by straleyb** [projecthydra/sufia#2621]
From the review queue index page, a reviewer can go to the items show page, view the metadata and edit it. After they have edited and are back on its show page, there should a be a button to mark that item as reviewed and advance the workflow.

**Comment by jeremyf** [comment]
I'm a bit unclear on the intention of the button. Is the button something that they click to formally say "Mark as Reviewed"? Or is the button an indicator that the edit process has marked the item as reviewed?

**Comment by vantuyls** [comment]
My understanding is that this button is to formally say "mark as reviewed". This will also advance the workflow to the next step. 

What we are aiming for with this set of Review Queue Index Page issues is that the reviewer can either mark an item as reviewed (and advance the workflow to the next step) either from the Review Queue Index Page (this issue) or from the item show page (see #2620)

**Comment by jeremyf** [comment]
@vantuyls Correct me if I'm wrong. "Mark as Reviewed" is a button that requires clicking.

**Comment by vantuyls** [comment]
Yes.

**Comment by mjgiarlo** [comment]
Defer until we have 1+-step workflow working. Should this move into CC? @jcoyne
