### ISSUE TITLE
Modifications to workflows cannot happen if there are items already in the workflow

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2623]
If there are items currently in a Mediated Deposit Workflow, no changes can be made to the workflow until in-process items are cleared out. 

This is a first step towards a smarter way of being able to modify workflows with items in-process. In the future, we're hoping to be able to modify workflows with items in-process without orphaning or otherwise "screwing up" those in-process items. 

Decomposes #2442

**Comment by jeremyf** [comment]
@vantuyls There is an implication that Workflows should be time based. For a given Administrative Set and a given date there exists one associated workflow. However, for a different given date, there can be another workflow.

When we determine which workflow for a given item, we query the Workflows by Admin Set and an "As of Date" (e.g. a deposit started on this date).

I'm bringing in @mjgiarlo as this is a larger conversation regarding the longitudinal behavior of the application.

**Comment by vantuyls** [comment]
Good idea. It's a bit delicate to build out these tickets with so much parallel work happening. @mjgiarlo thoughts?

**Comment by mjgiarlo** [comment]
@jeremyf We were thinking the initial target would be a single workflow for the entire site, and it's either on or off. That lets us build out prerequisites and a first design, upon which we can iterate and make improvements. Which is to say, we'd approach admin set-related workflow in follow-up tickets. So, the first target is: there is one and only one workflow, and you can only modify it (add step, remove step, reorder steps) once 0 items are in the workflow. This gets us out of the business of, say, the items themselves needing to keep track of the state of the workflow.

Should we set up a time to chat, @jeremyf @vantuyls? Steve and I were talking yesterday about wanting to pull you in, to the extent that you are available of course.

**Comment by jeremyf** [comment]
Yes. Pull me in. I can "consult" and provide guidance. I have a ridiculous
amount of code that can be referenced and leveraged. It is also possible
that we could extract Sipity's workflow into a gem/engine.

There are points of indirection that help it be AuthN/authz agnostic as
well as object in workflow agnostic.

Jeremy Friesen

**Comment by mjgiarlo** [comment]
I can't think of a reason the 0-step workflow, the one we're currently working towards in Sufia, would change. Defer this to when 1+-step workflow is working.

**Comment by mjgiarlo** [comment]
This should probably move into CC. Confirm/deny, @jcoyne?
