### ISSUE TITLE
Send notification to user when item in workflow needs their attention

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#2627]
When an item is moved to a step in a workflow to which a user has access, the user should be notified via mailboxer that it is ready for action.

**Comment by jeremyf** [comment]
@mjgiarlo For Sipity, we configure multiple notifications per event or entering/existing state.

When an event happens, there is a lookup to find all of the registered emails for that event. Each email is associated with one or more roles (i.e. Item Reviewer, Item Submitter, etc.). Then we process each email and expand those roles into user emails.

In this way, we can keep a person up to date on the state of their submission by notifying them at each step (if we want). And only relevant people receive notifications along the way.

**Comment by scholarworks** [comment]
I've been way backlogged today, but I'm going to start reviewing how this is done in sipity and will take this one soon.

**Comment by jeremyf** [comment]
@scholarworks On Tuesday I will be presenting on Sipity modeling and am doing prep work to answer these questions.

The entry point for emailing is https://github.com/ndlib/sipity/blob/f2f6b9050bcf0034a14bd8d2cd4e5e855ed2c482/app/services/sipity/services/notifier.rb#L14

However the following slide may be helpful to orient what all is going on. https://docs.google.com/presentation/d/1P9iARlL6Y-a5t0EB-Qwkwa7Pg_3B41pvXWwWKxxa-Cc/edit#slide=id.g169be1a67d_1_58

**Comment by vantuyls** [comment]
For now, the MVP we're looking for is a notification in the Sufia inbox. Email can come later (see #2683)

**Comment by vantuyls** [comment]
This is likely (certainly?) going to be handled in Curation Concerns - https://github.com/projecthydra/curation_concerns/issues/1021

@hortongn @jcoyne @jeremyf - right?

**Comment by jcoyne** [comment]
@vantuyls the sending notifications in the abstract will be handled, but not the particular notification message for each particular state change.

**Comment by mjgiarlo** [comment]
Thanks for picking this up, @blancoj!
