### ISSUE TITLE
Enable a simple mediated deposit workflow

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#2628]
To get started on mediated deposit work, create a feature flipper that allows an admin to enable or disable mediated deposit.  When turned on, depositing a work should not immediately publish it. Rather, the work should be marked as inactive and should notify administrative users that a new item is available to review/publish.  The default setting for mediated deposit should be "off"

The feature flipper should be implemented using the flipflop gem the same way admin sets is toggled on and off (see https://github.com/projecthydra/sufia/commit/3612d5ee627e320a52bc5687179119ddf98bcc8b and https://github.com/projecthydra/sufia/commit/3b4fd55527748f053e92f382fd8491c587208ccf)

**Comment by scholarworks** [comment]
Will the option be global to the repository or applicable to select administrative_sets? I'm assuming global for the MVP, but assignable later on.

**Comment by mjgiarlo** [comment]
@scholarworks I was thinking the option would be global just to get us started, like you assumed. :)

**Comment by scholarworks** [comment]
Initially add "allow_mediated_deposit" (terminology suggestions welcome) to config/features.rb

Default: false (again, suggestions welcome)
Description: Ability to enable mediated deposit for admin sets.

**Comment by scholarworks** [comment]
or "enable_mediated_deposit" rather.

**Comment by mjgiarlo** [comment]
Suggest paring down the description to `Turn on mediation for all deposits` since the first phase will not be Admin Set-aware. Otherwise, :+1:!

**Comment by vantuyls** [comment]
Reopening this to ensure that the issue is covered by the new Curation Concerns workflow branch and subsequent Sufia Mediated Deposit work.
