### ISSUE TITLE
When an object is edited and mediated deposit is enabled, the object state should be set to Inactive and should re-enter mediation

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#2629]

**Comment by hortongn** [comment]
@vantuyls @mjgiarlo I have a few hypothetical situations that I need to understand:

1) If a work is published and can be discovered via the GUI, and someone edits that work, the work should become inactive again.  That means the work suddenly disappears from public view after re-entering mediation.  Maybe I'm thinking too far ahead here and we shouldn't worry about this yet, but it seems like you wouldn't want published content to go missing from the user's perspective.  

I would think that editing a work should create a new "inactive" copy of that work.  The inactive copy would go through mediation while the original active copy would remain discoverable to users.  Once the inactive work is approved, it becomes active and replaces the original active copy of the work.  Or do we just deal with this problem in a later issue?

2) Lets say we have a work with several files attached and someone edits just one of the the files (file_sets).  What should happen?  Generic_works currently have a "state" that can be set to inactive, but file_sets do not.  So should one of the tasks for this issue be to add a state to file_sets?  That would require us to `include CurationConcerns::Publishable` in CC's file_set_behavior.rb, correct?

**Comment by mjgiarlo** [comment]
@hortongn Great questions!

1. We touched upon this in #2452 but failed to link the relevant requirements here. Here's the blurb that addresses your first question:

> One potential complication we discussed is how far we’d want to take the notion of “draft” or inactive objects. For instance, should we aim to support “unpublishing” an object, moving it from published back to a draft state where it may be edited further? Some folks in the room had experience implementing functionality like this in the past and shared that it gets gnarly very quickly, and the task can evolve into re-inventing version control with the potentiality for multiple users to “check out” an object, work on it, and then try to re-publish it. Our sense was that it’d be sufficient to use the draft/unpublished/inactive state as a starting point, and once something is published, it’s published (until such time as someone recommends a technical design for "mediated editing" and contributes resources towards that feature).

So, I'm thinking we should deprioritize this ticket and punt it to a later sprint. @vantuyls?

2. Ha, I was just thinking about this while looking at @blancoj's PR and some discussion on Slack, and I added a "note" here: https://github.com/projecthydra/sufia/projects/1#card-31446. (See the #community-standup channel for my proposal that we give the GitHub project feature a spin.) Let's verify that FileSets are discoverable/visible independent of Works before prioritizing this work (we can turn that note into an issue automagically). Ultimately I agree with you that we ought to mix `Publishable` into the `FileSetBehavior` in CC, yes, and also to have tooling that automatically updates the `publication_state` of all FileSets within a work when the Work's `publication_state` is changed. Thanks!

**Comment by hortongn** [comment]
Thanks @mjgiarlo.  I unassigned myself from this issue and put in back in the ready column.

**Comment by mjgiarlo** [comment]
Defer working on this issue until we have an implementation of a working 1+-step workflow in Sufia.

**Comment by mjgiarlo** [comment]
Same as #2794, in which it is concluded that the entire workflow should be restarted as a first cut.

**Comment by vantuyls** [comment]
also cross reference with #2794

**Comment by vantuyls** [comment]
curse you, @mjgiarlo
