### ISSUE TITLE
Inactive objects (works and file sets) should not be discoverable via the catalog controller and their show pages should not render.

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#2640]
(May require further decomposition.)

When the mediated deposit feature flipper is on and works are deposited, said works and their file sets are marked as inactive. These inactive works and file sets should not be discoverable via the catalog controller (searches should not turn up results and facet values should not appear).

The following issues address other functionality associated with the visibility of works in inactive state due to mediated deposit.

#2727 
When mediated deposit is enabled, and a work is in inactive state because it is in the mediated deposit workflow and has not yet been approved, the work’s show views should error, regardless of the visibility specified.

#2728 
When mediated deposit is enabled, and a work is in inactive state because it is in the mediated deposit workflow and has not yet been approved, but the work has been marked as visible to other user(s), the work should not be visible by those user(s) and those user(s) should not yet receive a notification that the work is available.

#2729 
When mediated deposit is enabled, and a work is in inactive state because it is in the mediated deposit workflow and has not yet been approved, it may appear in the dashboard of the depositor. (So that the owner can find them)

Follows from #2616

**Comment by hortongn** [comment]
@blancoj Can you edit this issue's description to remove the parts that you moved into new issues?  Maybe reference those issue numbers in the description so we know they moved?

When I see your new PR for this issue, I'll review it again.  Thanks!

**Comment by blancoj** [comment]
I've updated the description, describing the decomposition of this issue into further issues.

**Comment by mjgiarlo** [comment]
Closing because it's been decomposed into non-epics.
