### ISSUE TITLE
When a field is added to a form's list of required fields, it should be required

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2643]
### Descriptive summary

In Sufia 7 master, when I add description as a required field to the test app it does not show as required on the view.  This also occurs in ScholarSphere.  I added Resource Type also and that shows as required on the form.

### Expected behavior

1. I should see the required badge next to the description
1. The "required metadata" check in the visibility bar should not go green until description (i.e., all fields marked as required in the form object) is filled out
1. The form should not be submittable until description is filled out

### Actual behavior

![screen shot 2016-09-07 at 2 16 23 pm](https://cloud.githubusercontent.com/assets/1599081/18323497/db9e3a84-7505-11e6-943f-c367c0949d56.png)

### Steps to reproduce the behavior

1. Modify .internal_test_app/app/forms/curation_concerns/generic_work_form.rb to include description as a required field

<img width="833" alt="screen shot 2016-09-07 at 2 16 49 pm" src="https://cloud.githubusercontent.com/assets/1599081/18323531/03354998-7506-11e6-9150-2f78024f3c52.png">

1. Then go to the new work form

**Comment by mjgiarlo** [comment]
@cam156 Can you submit the form without a description? That is, is the issue just that the badge fails to render, or that you can submit a form without a required field?

Good find, and thanks for taking this on!

**Comment by jcoyne** [comment]
This should be rendering this template: https://github.com/projecthydra/sufia/blob/master/app/views/collections/edit_fields/_description.html.erb#L2

**Comment by jcoyne** [comment]
It's rendering this template, which is not marking the field as required:
https://github.com/projecthydra/sufia/blob/master/app/views/records/edit_fields/_description.html.erb#L4

**Comment by cam156** [comment]
@jcoyne Thanks! I was in the process of changing that view when @mjgiarlo started asking me questions about what happens when you send the info to the server.  Unfortunately there are two bugs with adding additional required fields.  I'm going to ticket the second bug this morning and continue to work on my view test.
