### ISSUE TITLE
Separate Sufia js object from execution thereof

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#2669]
It's hard to override any of the javascript defined in https://github.com/projecthydra/sufia/blob/master/app/assets/javascripts/sufia/app.js

I propose splitting it into 2 files: leave the Sufia object where it is and move https://github.com/projecthydra/sufia/blob/master/app/assets/javascripts/sufia/app.js#L84-L86 to sufia/initialize.js or similar. Then people can override the object in their own code or override the initialize file in their local app.

**Comment by jcoyne** [comment]
@hackmastera That sounds good to me.
