### ISSUE TITLE
Notification via email should be an option

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2683]
email should be an option for sending notifications to users/admins/etc.

there are likely a number of things to unpack here (though not all are immediately in scope) including:
- [ ] How Sufia finds the email address of the user (in the user's profile? somewhere else?)
- [ ] User controls for opting in to or out of email messaging
- [ ] Possibility of receiving digest emails (e.g. if i deposit 100 items a day, i don't want 100 emails)
- [ ] Ability to edit the email message sent, or just use a stock message (e.g. "you have a new notification in Sufia")

**Comment by vantuyls** [comment]
Turns out mailboxer already supports email:
https://github.com/mailboxer/mailboxer#emails

**Comment by mjgiarlo** [comment]
Out of scope for current mediated deposit sprints.
