### ISSUE TITLE
Search My Highlights option is missing

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2695]
### Descriptive summary

When choosing what to search from in the dropdown menu, the _My Highlights_ option is no longer available.

### Expected behavior

I should be able to choose _My Highlights_ as a search option.

### Actual behavior

 _My Highlights_ is not search option.

**Comment by mjgiarlo** [comment]
I believe this was intentionally removed since there are only 5 highlights. Is that right, @jcoyne?

**Comment by jcoyne** [comment]
I recall it being intentionally removed, I didn't do it though.

**Comment by cbeer** [comment]
I did it in https://github.com/projecthydra/sufia/pull/2521, fixing https://github.com/projecthydra/sufia/issues/2470https://github.com/projecthydra/sufia/issues/2470.

**Comment by awead** [comment]
👍
