### ISSUE TITLE
Dashboard icons need help

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#2698]
- [x] Get rid of underline on hover; There's already an animation effect (this is a regression from sufia 6)
- [x] They should be reordered to either "Work Work Collection Collection" or "Work Collection Work Collection"; the current order feels really weird
- [x] They should be spaced evenly across the page when at full width (this is a regression from sufia 6)

**Comment by jcoyne** [comment]
It appears that this was caused by 80730df88b98fea99341e95402dd78582f9e3f0e.
