### ISSUE TITLE
Create db migration to change 'dsid' to 'file_id' on table "checksum_audit_logs"

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#2706]
To upgrade sufia 6 apps to sufia 7

**Comment by hackmastera** [comment]
Also update corresponding index:
```
<   add_index "checksum_audit_logs", ["file_set_id", "dsid"], name: "by_pid_and_dsid"
---
>   add_index "checksum_audit_logs", ["file_set_id", "file_id"], name: "by_file_set_id_and_file_id"
```

**Comment by mjgiarlo** [comment]
@hackmastera Is this still on your plate? https://github.com/projecthydra/sufia/pull/2717 (Doing some issue clean-up to better define what "done" looks like for 7.3.0.)

**Comment by hackmastera** [comment]
@mjgiarlo i will look for a time to revise that pr soon.

**Comment by mjgiarlo** [comment]
We're 1-2 blockers away from cutting a beta/RC for 7.3.0. Do you think you'll have time to revisit this in the coming week or so, @hackmastera?
