### ISSUE TITLE
"Works created" in user profile displays all works instead of current user's works only

### ISSUE THREAD

**Issue by njaffer** [projecthydra/sufia#2708]
### Descriptive summary
Relates to Sufia 7. Works created link shows the right number of works created by the current user, but when clicked, it shows all the works created.

### Expected behavior
When clicked, it should show only the works created by current user.

### Actual behavior

Shows all works
### Steps to reproduce the behavior

1. Login as User A
2. Deposit a work
3. Logout and Login as User B
4. Go to My Dashboard
5. Click on "Works created" (option in the left sidebar)

### Related work

Link to related tickets or prior related work here.

**Comment by jcoyne** [comment]
Same as #2451
