### ISSUE TITLE
The inactive state of mediated deposit workflow supersedes the visibility settings for the object

### ISSUE THREAD

**Issue by blancoj** [projecthydra/sufia#2728]
When mediated deposit is enabled, and a work is in inactive state because it is in the mediated deposit workflow and has not yet been approved, but the work has been marked as visible to other user(s), the work should not be visible by those user(s) and those user(s) should not yet receive a notification that the work is available.

**Comment by mjgiarlo** [comment]
Include as part of 1+-step workflow.

**Comment by mjgiarlo** [comment]
@vantuyls Should we defer this to Phase 2, operating under the assumption that Phase 1 is for 0-step?

**Comment by mjgiarlo** [comment]
@vantuyls how much do we really care about this one? I'm moving it to phase 2 for now, but it'd be good to see if this is still relevant and highly desired. (I wonder if this can collapse into the "editing an object sends it back through workflow" story?)

**Comment by vantuyls** [comment]
If we're sure that the object will remain hidden from view when it is in the workflow, then OK. Otherwise, this needs to be an issue we address explicitly.

**Comment by mjgiarlo** [comment]
If user A shares an in-workflow work with user B, the work will be hidden from B in search results and the show view assuming B lacks permission to advance the work from its current workflow state. I'm not sure if it's also hidden from B's dashboard. This would be worth testing/QAing. Might you have cycles for this, @vantuyls?
