### ISSUE TITLE
Works in mediated deposit inactive state should appear in depositor's dashboard.

### ISSUE THREAD

**Issue by blancoj** [projecthydra/sufia#2729]
When mediated deposit is enabled, and a work is in inactive state because it is in the mediated deposit workflow and has not yet been approved, it may appear in the dashboard of the depositor. (So that the owner can find them).

Whether the depositor can do anything with the item should depend on role, right?

**Comment by mjgiarlo** [comment]
@vantuyls @hannahfrost What is the right behavior here?

**Comment by vantuyls** [comment]
It makes sense to me to have the depositor be able to see the progress of their item in the mediation workflow (i just responded to 3 emails yesterday about this very question). 

I think the questions about _what_ the user can do with the things they've deposited after they deposit is more about role. 

Happy to close this if we have some agreement. If closed, i'll generate a new issue related to depositor role.

**Comment by mjgiarlo** [comment]
@vantuyls :shipit:

**Comment by hannahfrost** [comment]
what @vantuyls said

**Comment by vantuyls** [comment]
alright. closing up shop. refer to #2735
