### ISSUE TITLE
Notification of Error on Bag Export/Import

### ISSUE THREAD

**Issue by kestlund** [projecthydra/sufia#2730]
As a repository administrator, I want to have notification that a Bag Export or Import has failed and why.

Acceptance criteria:  When logged in on the activity dashboard, I can view the status of bag and if it failed or succeeded. If it failed, I will know if it is due to the selected profile or another system reason.

**Comment by mjgiarlo** [comment]
This issue was moved to projecthydra/curation_concerns#1014
