### ISSUE TITLE
Depositor Role needs to be defined

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2735]
Depositor should be able to see the progress of their deposited content through some interface (user dashboard, my works?). 
- [ ] ensure role's abilities allow depositor to see their work but not edit it
- [ ] ensure that notifications for this item are sent to the depositor

**Comment by mjgiarlo** [comment]
Defer until we have 1+-step workflow working

**Comment by mjgiarlo** [comment]
Ticket is not decomposed enough and other issues already cover the details above.

**Comment by vantuyls** [comment]
closed in favor of more granular and related tickets. e.g. #2735

**Comment by vantuyls** [comment]
late in the day on a friday, @vantuyls created a circular reference in a Github issue comment that brought down the internet. FML. issue closed. herp derp.
