### ISSUE TITLE
ActiveTriples::ParentStrategy::UnmutableParentError when changing multiple permissions

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2737]
### Descriptive summary

If there are multiple users and groups available in the permissions form, changing several in one request will raise a `ActiveTriples::ParentStrategy::UnmutableParentError` on save.
### Expected behavior

Given I have a resource with several existing user and group permissions
When I remove them and replace them with different user and group permissions
Then I should be able to save the resource
### Actual behavior

I can't save the resource/
### Steps to reproduce the behavior

This is bit hard to reproduce and doesn't always seem consistent, but here's what I did:
1. Start with a clean build
2. Edit users.rb in the internal app and add:

``` ruby
def groups
  super + ["group1", "group2"]
end
```
1. Signup three different users and stay logged in with the last
2. Create a resource with only the defaults
3. Edit the newly created resource and go to the Share tab
4. Add new permissions for one of the users and both of the added groups
5. Save
6. Re-edit the work and go back to the Share tab
7. Remove the permissions you just added, the user and both groups
8. Add back a different set of permissions
9. Save

**Comment by cam156** [comment]
You can add more roles to the RoleMapper.yml instead of step 2.

**Comment by awead** [comment]
I can't reproduce this reliably, but I think it's more related to #2821 which is easily reproducible.

**Comment by mjgiarlo** [comment]
@awead how would you feel about closing this issue in favor of #2821?

**Comment by awead** [comment]
The above linked ticket is fixed, so let's just assume this fixes this as well. If not, we can re-open.
