### ISSUE TITLE
Add Sufia::Admin::AdminControllerBehavior to the sufia generators

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2739]
Sufia::Admin::AdminControllerBehavior is not currently being included within the admin controller, but needs to be added into the generator for CurationConcerns::AdminController.

**Comment by jcoyne** [comment]
How is this a bug?

**Comment by jcoyne** [comment]
@cam156 is this still relevant?

**Comment by cam156** [comment]
@jcoyne I think this is only relevant is Sufia wants to use the new AdminDashboard from CC.

**Comment by mjgiarlo** [comment]
@jcoyne you don't think Sufia should use the Admin Dash from CC?

**Comment by jcoyne** [comment]
I think the admin dash from CC is much harder to add things to than to just use a plain erb template and make changes.
