### ISSUE TITLE
Derivative errors

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2756]
### Descriptive summary

There are two problems with derivative creation that are occurring in Hydra::Derivatives, but impact Sufia's usability:
- [x] https://github.com/projecthydra/hydra-derivatives/issues/109
- [x] https://github.com/projecthydra/hydra-derivatives/issues/110

Thumbnails for pdf files are all-black, and derivative processes for office documents fail.

**Comment by jcoyne** [comment]
@awead can this be closed now? Both referenced tickets are complete.
