### ISSUE TITLE
NoMethodError in FileDownloadStat#ga_statistics

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#2758]
If the GA credentials haven't been configured and you try to view the statistics (https://nacho.demo.hydrainabox.org/files/rr171x20k/stats) then this error occurs:
```
[GEM_ROOT]/bundler/gems/sufia-53cddc776612/app/models/file_download_stat.rb:8 :in `ga_statistics`

6   # see Legato::ProfileMethods.method_name_from_klass
7   def self.ga_statistics(start_date, file)
8     Sufia::Analytics.profile.sufia__download(sort: 'date', start_date: start_date, end_date: Date.yesterday).for_file(file.id)
9   end
```

**Comment by mjgiarlo** [comment]
@jcoyne related to #2460?

**Comment by jcoyne** [comment]
@mjgiarlo #2460 probably was closed by https://github.com/projecthydra/sufia/pull/2749

**Comment by jcoyne** [comment]
Oh. Actually, that's a totally different problem.
