### ISSUE TITLE
Need consistency in terminology for product_name/application_name

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2762]
in:
sufia/app/helpers/sufia/sufia_helper_behavior.rb

lines 7-9 there is some confusing inconsistency in the terms used to describe the application/product (see below):

def application_name
      t('sufia.product_name', default: super)
    end

It would be less confusing if the terminology was consistent.

**Comment by mjgiarlo** [comment]
@vantuyls I suspect Sufia should just use Blacklight's `application_name` helper, which looks in i18n though in a different location. In retrospect, we probably should never have duplicated this Blacklight functionality (using a different name) in Sufia. Here's what Blacklight does already:

https://github.com/projectblacklight/blacklight/blob/9c5d7ea48e9794960a578fe1512ed7609b634068/app/helpers/blacklight/blacklight_helper_behavior.rb#L14-L18

Basically: look in your app config for a different value at runtime, or fallback on i18n. If you find `sufia.product_name` confusing, Sufia's current impl does fallback to Blacklight's, so you could theoretically replace `sufia.product_name` with `blacklight.application_name`. We could end support for `sufia.product_name`, but that might trip people up so we could bundle that change into Sufia 8.0.0.

Thoughts, @jcoyne @jeremyf @cbeer?
