### ISSUE TITLE
Sufia v7.2.0 install errors

### ISSUE THREAD

**Issue by hweng** [projecthydra/sufia#2764]
Followed readme page steps to create Sufia v7.2.0 based app.  When do this step “Install Sufia”, got the following error:

```
➜  my_sufia_new rails generate sufia:install -f
/Users/hweng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie.rb:195:in `method_missing': undefined method `config_file=' for Flipflop::Engine:Class
Did you mean?  configure (NoMethodError)
```

My local environment:
OSX 10.12
Ruby 2.3.0 or 2.2.3 (Tried both versions 2.3.0 and 2.2.3, and got the same error.)
Rails 5.0
Sufia v7.2.0

I didn’t get such problem in Sufia v7.1.0.  So I’ve compared Sufia v7.2.0 to 7.1.0 gemspec. The v7.1.0 doesn’t include the ‘flipflop' gem, whereas the v7.2.0. adds the ‘flipflop' gem.

Any idea about it? Is there something missing to set up flipflop in the following file:
https://github.com/projecthydra/sufia/blob/master/lib/generators/sufia/install_generator.rb

Thank you!

**Comment by mjgiarlo** [comment]
Hi @hweng,

This is covered in the release notes, here: https://github.com/projecthydra/sufia/releases/tag/v7.2.0

Thanks for the issue. If the notes above resolve this for you, can you let us know by closing this issue?

**Comment by hweng** [comment]
Hi @mjgiarlo, 

Thanks for the link. The above issue is resolved for me by adding:
`gem 'flipflop', git: 'https://github.com/jcoyne/flipflop.git', branch: 'hydra' `

But the install generator is hanging on at the following step:
`generate "curation_concerns:install --skip-assets -f"
`
The log doesn’t show error, just stuck there:

> Bundle complete! 19 Gemfile dependencies, 178 gems now installed.
> Use `bundle show [gemname]` to see where a bundled gem is installed.
>     generate  blacklight:assets
> Running via Spring preloader in process 60443
>       create  app/assets/stylesheets/blacklight.scss
>       insert  app/assets/javascripts/application.js
>     generate  blacklight:document
> Running via Spring preloader in process 60445
>       create  app/models/solr_document.rb
>     generate  blacklight:search_builder
> Running via Spring preloader in process 60447
>       create  app/models/search_builder.rb
> 

The above issue occurs in Rails 5.0.

Then I tested to install Sufia 7.2.0 using Rails 4. 2.7, and the install generator works fine to me with Rails 4.2.7

I will close this issue as the flipflop error got fixed. Thanks!

**Comment by mjgiarlo** [comment]
Thanks, @hweng!
