### ISSUE TITLE
What does the text "A PDF is Preferred" mean on the versions tab?

### ISSUE THREAD

**Issue by mark-dce** [projecthydra/sufia#2765]
### Descriptive summary

I'm running a vanilla Sufa based app generated from v7.2.0.  When I go to the Versions tab, I see the message "A PDF is preferred" 
### Expected behavior

Not sure if this is expected or not.  Please feel free to close if it's correct or move it to CC if it belongs there.
### Actual behavior

<img width="945" alt="sufia issue" src="https://cloud.githubusercontent.com/assets/3064318/19100133/096476e2-8a8a-11e6-8688-272dae6146f0.png">
### Steps to reproduce the behavior
1. Create a work with file attached
2. Edit the work and go to the versions tab
### Related work

Link to related tickets or prior related work here.

**Comment by jcoyne** [comment]
This is a vestige of Curate. :+1: to remove

**Comment by jcoyne** [comment]
https://github.com/projecthydra/curation_concerns/blob/7264e7388cd8a435fc4174b0bfa647853340163d/config/locales/curation_concerns.en.yml#L224
