### ISSUE TITLE
Solr Reindex task throwing a NameError

### ISSUE THREAD

**Issue by grosscol** [projecthydra/sufia#2774]
### Descriptive summary

In Sufia 7.2 and HEAD. The reindex rake task errors with the a uninitialized constant.

```
∴grosscol sufia/.internal_test_app (master) $ bunx rake solr:reindex
rake aborted!
NameError: uninitialized constant ResolrizeJob
/home/grosscol/workspace/sufia/tasks/reindex.rake:4:in `block (2 levels) in <top (required)>'
/home/grosscol/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/home/grosscol/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => solr:reindex
(See full trace by running task with --trace)
```
### Expected behavior

Update solr documents from fedora contents
### Actual behavior

NameError
### Steps to reproduce the behavior
1. `generate internal test app`
2. `cd .internal_test_app`
3. `bundle exec rake solr:reindex`

**Comment by jcoyne** [comment]
That class is defined here: https://github.com/projecthydra/curation_concerns/blob/master/app/jobs/resolrize_job.rb is the rake task loading the `:environment` task first?

**Comment by grosscol** [comment]
Yes.  Digging into why invoking `solr:environment` isn't picking up the ResolrizeJob class.

**Comment by mjgiarlo** [comment]
I suggest we tackle this in Hyrax rather than blocking the 7.3.0 release. If a fix does come in before the release is cut, I'll be happy to include it.
