### ISSUE TITLE
Update README to use tagged release for template

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#2784]
The README currently recommends installing Sufia using the `template.rb` file from the `master` branch. This can be problematic over time and it would be improved by pointing at a release-specific version of the file, so if you're looking at the 7.3.0 README, you get the 7.3.0 template. Starting with the 7.3.0 release, edit the link to `template.rb` in the README to point not at `master` but at a tag, such as `https://github.com/projecthydra/sufia/blob/v7.2.0/template.rb`

**Comment by barmintor** [comment]
👍

**Comment by mjgiarlo** [comment]
Despite this saying it's a blocker for 7.3.0, this work should immediately *follow* cutting the release.
