### ISSUE TITLE
Release notes for 7.3.0

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#2790]
Sufia 7.3.0 is a feature-packed release. Now you can:

* Create and use multiple work types, not just the previously pre-packaged "GenericWork" type
* Use mediated deposit workflow -- and build your own custom workflows -- in addition to self-deposit and proxy deposit
* Configure the banner image without needing to override views
* Assign visibility and release information (automatically) to works deposited into administrative sets via "permission templates" 
* Add managers, reviewers, and viewers to administrative sets
* Add parent and child works to other works using autocomplete

Due to more and earlier quality assurance testing, this release also includes many bug fixes, including the following notable changes to the Save Work form:

* No longer submits when uploads are still in progress
* Uses optimistic locking to prevent an earlier form from submitting if the object has changed since the form was loaded

Thanks to the many folks who've contributed to this release by providing use cases, documentation, tickets, design expertise, and the myriad ways that we pull together as a community, including the following developers (and their managers) for contributing to this release:

* @scholarworks (California State)
* @awead (Penn State)
* @andjsmit (IUPUI)
* @hackmastera (CHF)
* @blancoj (Michigan)
* @cam156 (Penn State)
* @cgalarza (Columbia)
* @cbeer (Stanford)
* @danhorst (Notre Dame)
* @elrayle (Cornell)
* @elo2112 (Columbia)
* @hortongn (Cincinnati)
* @jenlindner (independent)
* @jeremyf (Notre Dame)
* @atz (Stanford)
* @revgum (Oregon State)
* @jcoyne (Stanford)
* @luisgreg99 (Oregon State)
* @mjgiarlo (Stanford)
* @randalldfloyd (Indiana)
* @scherztc (Cincinnati)
* @tdonohue (DuraSpace)

# Install Notes

Sufia 7.3.0 depends upon an unreleased version of Flipflop. Add the following to your Gemfile **below the line declaring the Sufia dependency**, before running Sufia's install generator:

```ruby
gem 'flipflop', git: 'https://github.com/jcoyne/flipflop.git', branch: 'hydra'
```

## REMINDER: Ordering changes

Sufia 7.3.0 includes Rails 5 support, and also includes support for RDF 2 which fixes a long-standing bug in ActiveFedora that returned RDF statements in a predictable, though not directly alterable, order. The new behavior, which is correct for graphs that have not been explicitly ordered, is such that if an item has (e.g.) more than one title, the first title may change whenever the item is loaded.

If your application depends upon the old behavior of predictable, but arbitrary and unchangeable, ordered RDF graphs, you can add `gem 'rdf', '~> 1.99'` to your `Gemfile`, and ordering will be "preserved" in its current form.

# Upgrade Notes

## Gemfile

Sufia 7.3.0 depends upon an unreleased version of Flipflop. Add the following to your Gemfile **below the line declaring the Sufia dependency**, before running Sufia's install generator, if you have not previously done so:

```ruby
gem 'flipflop', git: 'https://github.com/jcoyne/flipflop.git', branch: 'hydra'
```

Then, update your Gemfile to point Sufia at version 7.3.0, and run `bundle update sufia`

## Database Changes

- Create the new tables:
```bash
rake curation_concerns:install:migrations
rake sufia:install:migrations
rake db:migrate
```

## Workflows

- Grab the workflows from Sufia and CC:
```bash
mkdir config/workflows/
wget -O config/workflows/default_workflow.json https://raw.githubusercontent.com/projecthydra/curation_concerns/v1.7.4/lib/generators/curation_concerns/templates/workflow.json.erb
wget -O config/workflows/one_step_mediated_deposit_workflow.json https://raw.githubusercontent.com/projecthydra/sufia/v7.3.0.rc1/lib/generators/sufia/templates/workflow.json.erb
```
- Load the default worklows: `rake curation_concerns:workflow:load` (**note** that you'll want to run this at point of deployment as well, to make sure all your instances have the workflows loaded)

## Manual tweaks

- Re-run `rails generate sufia:work GenericWork` (and any other curation concerns you may have created) in order to generate the required i18n keys.  See #2845. 
- Refactor your `config/routes.rb` so that Sufia is mounted before CurationConcerns. See #2805
- Remove `include BlacklightAdvancedSearch::Controller` from `app/controllers/catalog_controller.rb`
- Remove any use of `include_in_advanced_search` parameter to the `add_search_field` method
- If you are extending the `BatchUploadsController`, make note of the following change: https://github.com/projecthydra/sufia/pull/2852/files#diff-cc5e3f825a6f03c044c07b27ea7ec144
- Note the following new partial: https://github.com/projecthydra/sufia/pull/2997 If you've overridden `app/views/sufia/admin/admin_sets/_form.html.erb`, you may want to update your override.

## Optional

- All deposited works now belong to an AdminSet. If you do not create any AdminSets and specify the relationship at time of creation, they will be added to a default AdminSet. There is now a rake task available to add all existing works to the default AdminSet, if you want to send those works through workflow at a later date: https://github.com/projecthydra/sufia/pull/2978

# Changes

https://github.com/projecthydra/sufia/compare/v7.2.0...v7.3.0

**Comment by hackmastera** [comment]
> Remove include BlacklightAdvancedSearch::Controller from app/controllers/catalog_controller.rb

Also remove any use of `include_in_advanced_search` parameter to the `add_search_field` method?

**Comment by hackmastera** [comment]
> Re-run rails generate sufia:model for all of your models in order to generate the required i18n keys. See #2845.

Do you mean `rails generate sufia:work [work-type]` for all work types?

**Comment by jcoyne** [comment]
@hackmastera yes

**Comment by hackmastera** [comment]
> rake curation_concerns:workflow:load

Before doing this I expect you must copy a default workflow from somewhere. recommendation?

**Comment by hackmastera** [comment]
upgraded from cc 1.6.x first; combed through the diff and the only file I needed to update was mentioned in these notes already. Might be helpful to note that people may also need to run `bin/rake curation_concerns:install:migrations`

**Comment by hackmastera** [comment]
> rake curation_concerns:workflow:load

Questions:
* Will this need to be run at deploy (i.e. I should write this into capistrano)?
* Does this need to be run separately for test / development / production, or does it load once for all?

**Comment by mjgiarlo** [comment]
@hackmastera :speech_balloon: 
> * Will this need to be run at deploy (i.e. I should write this into capistrano)?

Yes, I believe so.

> * Does this need to be run separately for test / development / production, or does it load once for all?

It only loads workflows in the current `RAILS_ENV`. Good question!

@jeremyf @jcoyne check my math.

**Comment by mjgiarlo** [comment]
Draft release notes are now available here: https://github.com/projecthydra/sufia/releases/tag/v7.3.0.rc1 Make updates directly there.
