### ISSUE TITLE
Edits to a mediated object must be mediated

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra/sufia#2794]
An object that has been through a mediated workflow may undergo subsequent edits by a user with editing privileges on that object. When this happens, the object should go through the mediated workflow again.

**Comment by vantuyls** [comment]
@hannahfrost through the entire workflow? I suppose running the object through the entire workflow again is probably the safest first cut, but I wonder if there are cases where the edits only need to be run through part of the workflow.

**Comment by hannahfrost** [comment]
@vantuyls I do think this is safest first cut. Sure, there are probably cases where full vetting of post-mediated edits are not necessary, but the alternative doesn't seem right to me, because then it undermines a primary goal of mediation in the first place.

**Comment by mjgiarlo** [comment]
:+1: for running through the whole workflow again as the first target, assuming that is a simpler implementation.

**Comment by mjgiarlo** [comment]
Defer working on this issue until we have an implementation of a 1+-step workflow in Sufia.

**Comment by vantuyls** [comment]
we won't need to consider this until we implement a something but then mjgiarlo just added the comment i was going to add so you can look at it up there ^

**Comment by mjgiarlo** [comment]
Same as #2629. Closing.
