### ISSUE TITLE
Add Workflow area to Admin Dashboard

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2801]
### Descriptive summary
In order to manage and view workflow details in Sufia, we'll need an area in the Admin Dashboard that shows workflow menu.

### Expected behavior
There should be an area in the Admin Dashboard menu for mangaing and viewing Workflows.

### Actual behavior
This isn't a thing yet.

**Comment by vantuyls** [comment]
see: https://ggeisler.github.io/lerna-dashboard/

for UI reference (though Workflow doesn't appear on that mockup, you can use the mockup as a guide for, generally, how things should look).

**Comment by vantuyls** [comment]
@blancoj sounds like, from discussion on Tech Call today (and on Slack after) that we want the Admin Dashboard stuff to be down in CC, not up in Sufia. 


Justin Coyne [9:43 AM]  
@vantuyls that will allow us to remove the bit about calling the Workflow::PermissionGenerator: https://github.com/projecthydra/curation_concerns/blob/workflow/README.md#workflow

**Comment by mjgiarlo** [comment]
Fixed by #2804.
