### ISSUE TITLE
Need UI to see what workflows exist and to investigate them

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2809]
As a repository administrator, I need to be able to get an overview of what workflows currently exist for my repository. 

information that would be useful includes: a workflow name, a brief description of the workflow, the steps in the workflow, and maybe what admin sets the workflow is currently assigned to

_edited description to reflect the below conversation and clarification_

**Comment by mjgiarlo** [comment]
This is already happening to some extent in CC, right, @jcoyne?

**Comment by jcoyne** [comment]
I'd say this is partially exposed by the workflow roles screen. I'd certainly say this ticket is not actionable without more details.

**Comment by vantuyls** [comment]
i'll rework this asap to give more detail.

**Comment by vantuyls** [comment]
The original intent here was to be able to see what workflows are available to a user with the ability to assign workflows to things. Information that would be useful includes: a workflow name, a brief description of the workflow, the steps in the workflow, and maybe what admin sets the workflow is currently assigned to. I think this can be pushed over to phase 2. 

Does that help clarify, @jcoyne @mjgiarlo ?

**Comment by mjgiarlo** [comment]
@vantuyls works for me. thanks!
