### ISSUE TITLE
Dashboard shows multiple "Create Work" icons when multiple work types are in use

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#2824]
First generate at least two work types:
```
rails generate sufia:work GenericWork
rails generate sufia:work Image
```

Then when you go to `/dashboard` you see
<img width="785" alt="screen shot 2016-10-26 at 12 31 51 pm" src="https://cloud.githubusercontent.com/assets/92044/19738192/15c1772a-9b7c-11e6-9794-6eb6ff1b9bbc.png">

**Comment by mjgiarlo** [comment]
@jcoyne duplicate of https://github.com/projecthydra/sufia/issues/2434 ?

**Comment by mjgiarlo** [comment]
Here are the existing tickets about multiple work types: https://github.com/projecthydra/sufia/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%22multiple%20work%20types%22

**Comment by jcoyne** [comment]
Duplicate of #2434
