### ISSUE TITLE
Consolidate dashboards

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#2826]
Make the current user views use the existing admin layout. This work make the design more cohesive.

**Comment by mjgiarlo** [comment]
@jcoyne Breaking change? 8.0.0?

**Comment by jcoyne** [comment]
This seems a good way to support multiple work types, I'd like it to be 7

**Comment by mjgiarlo** [comment]
@jcoyne can we do this in 7.x without violating semver?

**Comment by jcoyne** [comment]
@mjgiarlo what does semver say about making things look different? ¯\_(ツ)_/¯

**Comment by mjgiarlo** [comment]
@jcoyne Heh. What I mean is that semver for Rails engines is unclear to me. Does `backwards incompatible changes [in] the public API` include major changes to views, which downstream implementations may have overridden? (Are views and partials part of a Rails engine's public API?) If so, we should slot this into 8.0.0. If not, let's include it in a 7.x minor release.

**Comment by jcoyne** [comment]
@mjgiarlo I don't think we can account for overriding views in semver. Have we made a contract that says, we shall use the following views at these prescribed times?

**Comment by mjgiarlo** [comment]
@jcoyne let's find out. Comments, @cam156 @awead @hackmastera @narogers @elrayle @grosscol ?

**Comment by jcoyne** [comment]
@mjgiarlo Let's consider the broader implications of this.  How do we draw the line between a major and a minor change to the UI.  I would think that we wouldn't want to prohibit any UI changes, but even a very small change could hypothetically break *something* from downstream (e.g. DOM dependency in javascript)

**Comment by hackmastera** [comment]
In general I think a change in logic (recent examples have been the move from views to renderers, or adoption of es6) is more disruptive than adding views or moving existing logic around.

In this specific case I personally haven't done anything with dashboards yet and would probably benefit from a faster timeline on this consolidation, before I start getting requests to override and customize.

Sorry if that's contradictory :)

Is there a plan to rework the user dashboard more substantially, e.g. make it configurable on a per-user basis, or change its contents?

**Comment by mjgiarlo** [comment]
@hackmastera There is no plan to rework the user dashboard outside of what we see here: https://github.com/projecthydra/sufia/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20dashboard

Thanks for the feedback! I'm inclined to slot this back into the 7.x series unless someone else objects strongly in the next day or two.
