### ISSUE TITLE
Hide inactive work from search results if mediated deposit it active

### ISSUE THREAD

**Issue by straleyb** [projecthydra/sufia#2828]
If mediated deposit is active, then we want to make sure inactive objects in a workflow don't show up in the search results. This can be done via the solr document and a simple solr query.

Relates #2640 

This is simply the first step in hiding inactive objects throughout the system.

**Comment by mjgiarlo** [comment]
Documenting this here: Discussed with @straleyb and @jcoyne in light of the open PR, and decided to move this work into CurationConcerns. (Sorry, @straleyb -- we should have picked up on this sooner.)
