### ISSUE TITLE
Change text from "Enter required metadata" to "Enter required descriptions"

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#2836]
The text on the right sidebar (under "requirements") says "Enter required metadata".  The tab for the metadata is titled "Descriptions".  So we should harmonize these terms so that the user will know to use the "descriptions" tab.

<img width="983" alt="screen shot 2016-10-27 at 10 35 17 am" src="https://cloud.githubusercontent.com/assets/92044/19773962/1e0ba26a-9c31-11e6-8854-e557496a1e78.png">

**Comment by mjgiarlo** [comment]
I support this. Yay for consistency in the UI.
