### ISSUE TITLE
Use static licenses page in place of rights modal

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2849]
### Descriptive summary

The rights modal is no longer used and should be removed. Instead we should have a static page that is editable and includes any pertinent information about how to select which licenses for a work.

**Comment by mjgiarlo** [comment]
@awead is this a bug, or tech debt removal?

**Comment by awead** [comment]
You could just remove this line and be done, I suppose:

https://github.com/projecthydra/sufia/blob/master/app/views/records/edit_fields/_rights.html.erb#L7
