### ISSUE TITLE
UsersController#show needs to set @linkedInUrl

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#285]
Like this:
https://github.com/psu-stewardship/scholarsphere/blob/develop/app/controllers/users_controller.rb#L23-L25

**Comment by mjgiarlo** [comment]
Even better, consider validating and normalizing LinkedIn handles/URLs at point of entry like we do with ORCIDs:

https://github.com/projecthydra/sufia/pull/733/files
