### ISSUE TITLE
Search target dropdown text on homepage needs higher contrast

### ISSUE THREAD

**Issue by mtribone** [projecthydra/sufia#2850]
Sufia 7.2 The drop down menu on the home page for the search bar is hard to read. Solved in ScholarSphere: https://github.com/psu-stewardship/scholarsphere/pull/421/files

**Comment by mjgiarlo** [comment]
@mtribone @cam156 Hmmm, do you see this in the Sufia test app too?

**Comment by mtribone** [comment]
![screen shot 2016-11-02 at 12 53 58 pm](https://cloud.githubusercontent.com/assets/4163828/19938495/7c66d716-a0fb-11e6-9438-72944e608f3c.png)

**Comment by mjgiarlo** [comment]
@mtribone thank you!
