### ISSUE TITLE
When selecting "Delete Collection" from the "My Collections" page, the user should remain on the "My Collections" page.

### ISSUE THREAD

**Issue by scholarworks** [projecthydra/sufia#2858]
### Descriptive summary

Currently, when on "My Collections" and "Delete Collect" is selected for any collection, after the deletion, the user is redirected to /catalog. This doesn't seem like the expected behavior from an "on page" function.

### Expected behavior

Remain on "My Collections"

### Actual behavior

Redirected to /Catalog

### Steps to reproduce the behavior

1. Select "My Collections" from the "Collections" pulldown
2. For a collection, select "Delete Collection" from the action pulldown
3. Confirm deletion

**Comment by mjgiarlo** [comment]
Related to #2447.

A fix was put into ScholarSphere here: https://github.com/psu-stewardship/scholarsphere/pull/401

Thanks for writing this up, @scholarworks!

**Comment by jcoyne** [comment]
I would not say that this issue is so severe as to be a blocker, what do you think @mjgiarlo?

**Comment by mjgiarlo** [comment]
@jcoyne I made this a blocker because it's user-facing Ave I'd like it to be in 7.3.0; it doesn't need to be a blocker, though.
