### ISSUE TITLE
An admin user should be able to advance the workflow state of any work in any workflow

### ISSUE THREAD

**Issue by straleyb** [projecthydra/sufia#2860]
As an admin user, I should be able to update a work's state even if I haven't explicitly been granted a role in that workflow.

**Comment by mjgiarlo** [comment]
@vantuyls @hannahfrost I think we need to back this feature with more detail on when and why this is needed. cc: @jcoyne 

Bumping to phase 2 for now.

**Comment by mjgiarlo** [comment]
If we do decide to work on this, it may be related to the following (as yet unwritten) story: "Admins should be able to edit all repository objects regardless of stored ACLs" (related to https://github.com/projecthydra/sufia/issues/2946)

**Comment by vantuyls** [comment]
This is related to the idea that the Admin has complete control over repository functionality. Per our discussion on Slack this morning, i'm not sure that's necessarily a fair assumption and this may be more of a repository by repository role management issue. If role management allows one to set up an admin to be able to touch everything in the repository, then we're good. Are role-related issues labelled in any way?

**Comment by mjgiarlo** [comment]
@vantuyls :speech_balloon: 
> Are role-related issues labelled in any way?

No. Not yet anyway.
