### ISSUE TITLE
A work's state doesn't get set if it is in the "pending" state

### ISSUE THREAD

**Issue by straleyb** [projecthydra/sufia#2861]
A work should know that it is in the "pending" state, and should act similarly to when a work is under mediated deposit.

**Comment by jcoyne** [comment]
@straleyb would this fix it? https://github.com/projecthydra/curation_concerns/pull/1081

**Comment by mjgiarlo** [comment]
Closing this issue since works should no longer be put into a `pending` state. Reopen if you think this is still relevant, @straleyb @vantuyls
