### ISSUE TITLE
Jobs should use the CC ingest_queue_name config variable instead of "ingest"

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2862]
### Descriptive summary

CC has a config variable for the ingest queue, but Sufia doesn't seem to use it.

**Comment by awead** [comment]
Since Sufia has a named queue called "ingest" that implies it should align with CC, but maybe not?

**Comment by mjgiarlo** [comment]
Cleaning up issues to better clarify the scope of 7.3.0, future Sufia releases, and Hyrax releases. This doesn't seem actionable at the moment and the Sufia/CC boundary issues are less compelling now that we've got Hyrax going.
