### ISSUE TITLE
Document the migration executables in the wiki

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2883]
Update The documentation started in the wiki to reflect the new executables and any additional steps needed.
https://github.com/projecthydra/sufia/wiki/Sufia-6-to-Sufia-7-Migration

**Comment by hackmastera** [comment]
remember to mention:
- https://github.com/projecthydra/sufia/issues/2889#issuecomment-260729847
- https://github.com/projecthydra/sufia/issues/1373#issuecomment-168757536

**Comment by kerchner** [comment]
@cam156 Did you mean this link:

https://github.com/projecthydra/sufia/wiki/Migrate-data-from-Sufia-6-to-Sufia-7.2-%5BWork-In-Progress%5D

rather than the one in your comment above (which redirects [here](https://github.com/projecthydra/sufia/wiki))?

**Comment by hackmastera** [comment]
@kerchner Oops, I just updated the page, including the title, and I guess it changes the link. Too bad it doesn't redirect to the new location :\

**Comment by hackmastera** [comment]
If y'all think it's troublesome enough to change the title back I would be fine with that.

**Comment by cam156** [comment]
@hackmastera adding the WIP seems like a good idea.  I change the link at the top of the ticket.
