### ISSUE TITLE
Importer error message request wrong config key

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2889]
When you do not have the fedora_sufia6_user configured the error message requests you to put a sufia6_user in your config file.

```
lib/sufia/import/version_builder.rb:53:in `rescue in sufia6_user': Please configure sufia6_user in config/application.rb
```

**Comment by hackmastera** [comment]
In hindsight that's not a great location, either, since it can easily be checked into a repo.

**Comment by cam156** [comment]
@hackmastera I just created a file that included the password in an initializer:
https://github.com/psu-stewardship/scholarsphere/issues/455

Not sure if we want to change the error message, or just add the option to documentation.
