### ISSUE TITLE
File Set is not displaying a Date Uploaded or Date Modified after migration

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2892]
### Descriptive summary

In Sufia 7.2-migration after a GenericFile has been imported from Sufia 6 is does not show a date uploaded or a Date modified in the FileSet metadata

![screen shot 2016-11-15 at 1 57 06 pm](https://cloud.githubusercontent.com/assets/1599081/20319386/d70d85d0-ab3b-11e6-9ec2-51a1747d9c6e.png)

**Comment by hackmastera** [comment]
Looks like the date is in the wrong format:

Here's one that was created in the application and shows up fine:
```
> fs2.date_uploaded
=> Wed, 16 Nov 2016 18:23:33 +0000
```
Here's one that was loaded in and not showing:
```
> fs.date_uploaded
=> "2016-08-01T16:57:25.988+00:00"
```

**Comment by hackmastera** [comment]
Looks like this'll be pretty easy:

```
> fs.date_uploaded.to_datetime
=> Mon, 01 Aug 2016 16:57:25 +0000
```
