### ISSUE TITLE
The Related GenericFiles are not being related on import

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2896]
### Descriptive summary

In Sufia 7.2-migration the related Works are not getting linked.  This ticket is dependent on #2895.

After a work is imported we need to try and make the links between it and the related files.

**Comment by hackmastera** [comment]
This should definitely be optional; for us the batch is incidental and we would not want these relationships created.

**Comment by cam156** [comment]
@hackmastera Ok.  We can create a Batch process Exporter and a Batch importer that does the correct things locally in ScholarSphere
