### ISSUE TITLE
resource type label / id flipped in batch upload form

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#2905]
### Descriptive summary

Sufia 7.x. When you add a file to a batch upload you get form elements to specify the display label and resource type for each file. The resource type dropdown is filled in backwards, so that the Id is displayed and the term is saved.

See the flip here:

- https://github.com/projecthydra/sufia/blob/818cb4ca53d81fdb37835a0cd7c753d66eacd679/app/views/sufia/uploads/_js_templates.html.erb#L76
- https://github.com/projecthydra/curation_concerns/blob/master/app/services/resource_types_service.rb#L7

### Expected behavior
Form should use 'id' as options and 'term' as display values

### Actual behavior
Form uses 'term' as options and 'id' as display values

### Steps to reproduce the behavior

The problem doesn't show up in the test app because [the default config](https://github.com/projecthydra/curation_concerns/blob/master/lib/generators/curation_concerns/templates/config/authorities/resource_types.yml) file has identical string values in both places.

If you change the config file to use URIs as Ids, then you will see the problem.

There may be data migration implications to this fix for people who have customized the config file. Anyone using the default config file would not notice a difference.

**Comment by jcoyne** [comment]
Seems to work fine for me:

<img width="606" alt="screen shot 2017-01-11 at 10 11 45 am" src="https://cloud.githubusercontent.com/assets/92044/21860650/6c493262-d7e6-11e6-822d-7d6ea2e1fae6.png">

@hackmastera am I looking at the right screen?
