### ISSUE TITLE
gemspec refers to non-existent curation concerns gem release

### ISSUE THREAD

**Issue by elrayle** [projecthydra/sufia#2910]
### Descriptive summary

Sufia master gemspec refers to non-existent curation concerns gem release 1.7.0.alpha.  This causes bundle install to fail when.

### Expected behavior

When master branch is current in development environment, bundle install should complete without errors.

### Actual behavior

```
Bundler could not find compatible versions for gem "curation_concerns":
  In Gemfile:
    curation_concerns

    sufia was resolved to 7.2.0, which depends on
      hydra-batch-edit (~> 2.0) was resolved to 2.1.0, which depends on
        curation_concerns (>= 0.12.0.pre2)

    sufia was resolved to 7.2.0, which depends on
      curation_concerns (~> 1.7.0.alpha)

Could not find gem 'curation_concerns (~> 1.7.0.alpha)', which is required by gem 'sufia', in any of the sources.
```

### Steps to reproduce the behavior

1. git clone sufia
1. bundle install

**Comment by mjgiarlo** [comment]
Should be fixed by #2909. Thanks, @elrayle, for writing this up.
