### ISSUE TITLE
PermissionTemplate reset when visiting the Edit UI for an AdminSet

### ISSUE THREAD

**Issue by scholarworks** [projecthydra/sufia#2923]
### Descriptive summary

If a user creates and adminset, the permission template is first created when visiting the Edit UI for that adminset. However, this also resets the values to nil in the PermissionTemplate on subsequent visits to the edit ui. 

### Expected behavior

Unless changes are made, the PermissionTemplate should not change.

### Actual behavior

Values in Sufia::PermissionTemplate set to nil.

### Steps to reproduce the behavior

1. Create an Admin Set
2. View the admin set
3. Click "Edit"
4. In the console check `Sufia::PermissionTemplate.last` - the admin_set_id will equal the newest admin set
5. Make changes
6. Verify changes with `Sufia::PermissionTemplate.last`
7. Revisit edit page, run `Sufia::PermissionTemplate.last` notice nil values again.

**Comment by mjgiarlo** [comment]
@scholarworks Question about:
> Verify changes with Sufia::PermissionTemplate.last
> Revisit edit page, run Sufia::PermissionTemplate.last notice nil values again.

Are those two `Sufia::PermissionTemplate`s the same, or different ones? I wonder if this might be related (or identical) to #2902.

**Comment by scholarworks** [comment]
@mjgiarlo it may be related. I'll take a look, I looked to see if there were existing issues and just missed that one, sorry.

**Comment by mjgiarlo** [comment]
@scholarworks np! There are many issues in a number of related repos. :)

**Comment by scholarworks** [comment]
@mjgiarlo - Looks like you are right. When I do `Sufia::PermissionTemplate.all.to_a` I see several entries for the admin_set I'm looking at. So think this can be closed as a dupe of #2902. Thanks.

**Comment by mjgiarlo** [comment]
Thanks for following up, @scholarworks!
