### ISSUE TITLE
sufia_import creates additional file_sets when run twice on the same json file

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2925]
### Descriptive summary

In Sufia 7.2-migration, when I run the sufia_import tool twice on one json file I get a work that has twice the file sets attached.  One set for each run.

### Expected behavior

Skip the second import?  Warn?  Destroy the object before reimporting it?

### Actual behavior

Import occurs twice for the filesets.  Since the work has an id that is only generated once.

### Steps to reproduce the behavior

1. put a generic_file....json file into tmp/import
1. run `sufia_import`
1. run `sufia_import` a second time
1. view the work

**Comment by mjgiarlo** [comment]
I'd expect the behavior to be: if I'm importing a GenericFile and there's already a work with its ID, skip that GF and report the duplicate. Could also allow passing in flags  like `--force` or `--replace` for doing the import anyway or destroying and re-importing, but I don't see those are very valuable without use cases from you folks or @hackmastera or others.
