### ISSUE TITLE
Version file names do not include id

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2927]
### Descriptive summary

In Sufia 7.2-migration. Becuase the fileset has not been saved, the version file names do not include and id.  This would not be thread safe if you started more than one sufia_import at a time.

https://github.com/projecthydra/sufia/blob/7.2-migration/lib/sufia/import/version_builder.rb#L27

### Expected behavior

the file name should be 'abc123_version_1', which includes an id.

### Actual behavior

the file name is '_version_1', which does not include an id

**Comment by hackmastera** [comment]
thoughts on the solution here? Save the file_set if its id is nil before creating any versions? use something else for the filename, like the URI?

**Comment by cam156** [comment]
We could do something like use a timestamp or possibly use the work id and timestamp.  Unfortunately I do not think we have access to the work at this layer.

**Comment by hackmastera** [comment]
you're right we don't have the work here, and technically a work can have multiple filesets so i wouldn't want to set someone up for failure if they were trying to re-use this code down the line for some reason. I do like using an actual ID so a person looking at a filesystem could make a correlation if needed. I think I'll try requiring the file_set to have an ID.

**Comment by hackmastera** [comment]
looks like later code requires the fileset to be persisted anyway so this seems fine.
