### ISSUE TITLE
Work Type selector interface doesn't launch from Sufia home page button

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2932]
Selecting the "Share Your Work" button on the Sufia home page doesn't launch the Work Type selector interface.

##How to replicate:
1) Fire up Sufia
2) Select "Share Your Work" 
3) Note that the work type selector interface doesn't launch
4) ????
5) Profit

**Comment by mjgiarlo** [comment]
Do you have n > 1 curation_concerns/work types generated? If you have just 1 type, you won't see the selector modal.

**Comment by mjgiarlo** [comment]
Assuming so and closing.
