### ISSUE TITLE
Work Type selector interface spills off bottom of page

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2933]
When the number of Work Types exceeds about 5, the work type selector interface starts to spill off the bottom of the page. I wonder if a matrix of work types, rather than a list, would help alleviate this problem. Or possibly, after 4 work types, new work types are listed in a second column?

**Comment by mjgiarlo** [comment]
This needs design and I'm not sure folks are likely to create 5 types of work off the bat, so I'm not going to make this a blocker. I suggest we take this up in Hyrax.
