### ISSUE TITLE
GenericWork IDs being used for FileSets in migration

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2941]
### Descriptive summary

In Sufia 7.2-migration when I eradicate all items with the IDs that I will use for Generic Works & Collections and run the migration some of my GenericFiles do not migrate  to GenericWorks because FileSets already have their id.

I would suggest that we break the importer into two step, import and import_children.  Then we could run import on all models, and then import_children for all models.  This would mean that the main objects would get first crack at the ids before the children get them.

This happened 10 times during my migration of 6,418 collections and GenericFiles.

@hackmastera this was something you also thought you saw.  I ran the import twice just to be certain I was seeing it.

I cleaned out my repo something like...
```
files = Dir.glob('tmp/import/*')
ids = files.map{|f| f.gsub(....)}
ids.each {|id| ActiveFedora::Base.find(id).delete(eradicate: true) if ActiveFedora::Base.exists?(id)}
```

**Comment by hackmastera** [comment]
Yes I saw this, but it resolved when I migrated my minter statefile correctly. If you migrate the statefile, sufia won't attempt to mint IDs that have already been used.

**Comment by cam156** [comment]
@hackmastera I did not do anything with my minter state file, but I had already run the migration once so those ids should have been used by the first migration.  Did you just copy the file over?

**Comment by cam156** [comment]
@hackmastera I'm running for a third time and getting the same issue.  At this point Noid should really know that those ids have already been used. It may be a difference in how noid is configured, or it may be a noid bug, or it could be that we are wrapping on the noid id creation.

**Comment by hackmastera** [comment]
@cam156 Yes that's super weird. are you sure your statefile is getting changed? does it have the right permissions?

**Comment by hackmastera** [comment]
yes we just copied the file over.

**Comment by cam156** [comment]
@hackmastera it does have the correct permissions and it is getting changed.  We are using active_fedora-noid-2.90.0.beta6  What version are you using?

**Comment by hackmastera** [comment]
@cam156 2.0.0.beta6

**Comment by hackmastera** [comment]
@cam156 are you sure it's the same IDs each time? Maybe it's minting colliding IDs but they're not the same set every time you run. That could happen if you're using a brand-new statefile instead of a migrated one.

**Comment by cam156** [comment]
@hackmastera so that is the same since I typoed the 90.  It is only happening a few times in the 6k items.  I wonder if your are just not hitting it, or it is not happening for you.  I think I would feel more confident if we made a code change, but it sounds like it is not needed for your migration.

**Comment by hackmastera** [comment]
@cam156 A few times in 6k items would be consistent with the theory that a completely new statefile might happen to assign a few different IDs each time to FileSets that would have been used for not-yet-imported Works.

**Comment by hackmastera** [comment]
I think a code change like the one you outline would make it so statefile migration wasn't required, but I still think it would be safer / preferred to migrate the statefile. for example, I have a handful of non-work, non-fileset objects that I use as nested attributes and I was giving those NOID IDs (I've since stopped, since they're not top-tier / user-facing objects and it's fine for them to have ugly default fedora IDs). Probably nothing bad would happen if we hit those again and assign them to works or filesets, but it seems a little messy.

**Comment by cam156** [comment]
@hackmastera Unfortunately for PSU a statefile migration is not completely possibly.  We have our minter state file located in the /tmp directory which is not shared between our 4 servers.  That means that we can grab a state file, but that may or may not get it to the state we need to avoid id collisions.  I have a ticket into ScholarSphere to deal with our current state file issue.  On the plus side this issue should not affect you during your migration.

**Comment by hackmastera** [comment]
That's fair!

**Comment by cam156** [comment]
@hackmastera suggested just changing the noid template to have an addition character.  This seems like it should work.  Will be testing this theory.  If that works I'm thinking of closing this issue.

**Comment by mjgiarlo** [comment]
Sounds good, @cam156!

**Comment by cam156** [comment]
I have verified that changing the noid template AND deleting the current noid file solves the issue.  If you leave the minter state file around it does not pick up the new template.
