### ISSUE TITLE
Admins should be able to edit Admin Set w/o ACL

### ISSUE THREAD

**Issue by atz** [projecthydra/sufia#2946]
As an administrative user, I should be able to edit any Admin Set in the system regardless of its *other* `role_map.yml` ACLs.  

Split from #2902.

**Comment by jcoyne** [comment]
`role_map.yml` contains the list of which users are admins. Perhaps you want to rephrase the description?

**Comment by atz** [comment]
IKn Hyku the `:admin` role associated with a user is DB-persisted, as magically added for the first user here: https://github.com/projecthydra-labs/hyku/blob/master/app/models/user.rb#L19

So `role_map.yml` need not contain *any* admins in that case.

**Comment by jcoyne** [comment]
Right, Hyku  does not use the default implementation (`role_map.yml`)
