### ISSUE TITLE
Assigning workflows in admin sets without assigning roles results in error on upload

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2967]
### Descriptive summary

Off the shelf local instance of Sufia 7.2. I've created an admin user and loaded the workflows per wiki instructions. I am able to deposit content into the repository with no admin sets defined (thus using the default zero step workflow. When i create an admin set using the zero step workflow, deposits work as expected. When i create an admin set using the one step workflow, the following errors occur.

![screen shot 2016-12-09 at 2 50 05 pm](https://cloud.githubusercontent.com/assets/9534576/21067667/a1c8e704-be21-11e6-95e4-c16d3621eb33.png)

### Expected behavior

Deposit should enter workflow steps as defined in the one_step_mediated_deposit_workflow.json.

### Actual behavior

Error noted above on deposit. Also - counters for the admin set advance but the content does not appear in the admin set showpage or in the review queue (see below).

![screen shot 2016-12-09 at 2 51 54 pm](https://cloud.githubusercontent.com/assets/9534576/21067689/dd24f98c-be21-11e6-8c32-b9cd81e49ecd.png)

**Comment by mjgiarlo** [comment]
@vantuyls I spent about a half-hour on this and can't reproduce it locally. Do you have the latest from `master`? Can you pull the latest from master, regenerate the test app, and try again?

**Comment by vantuyls** [comment]
i can't seem to replicate this. @mjgiarlo shall i close it?

**Comment by mjgiarlo** [comment]
Thanks for looking into it, @vantuyls!
