### ISSUE TITLE
Two controllers for admin_sets

### ISSUE THREAD

**Issue by elrayle** [projecthydra/sufia#2972]
### Descriptive summary

Should there be two controllers for admin sets?

### Expected behavior

There are two controllers that affect admin sets.  Seems like there should be one set of behavior that is shared by both routes.

### Actual behavior

The two controllers are...

route: sufia/admin_sets
controller:  [app/controllers/sufia/admin_sets_controller.rb](https://github.com/projecthydra/sufia/blob/master/app/controllers/sufia/admin_sets_controller.rb)

route: sufia/admin/admin_sets
controller:  [app/controllers/sufia/admin/admin_sets_controller.rb](https://github.com/projecthydra/sufia/blob/master/app/controllers/sufia/admin/admin_sets_controller.rb)

### Steps to reproduce the behavior

1. http://localhost:3000/sufia/admin_sets
1. http://localhost:3000/sufia/admin/admin_sets

**Comment by elrayle** [comment]
Would it make sense to move the behaviors to app/controllers/concerns/sufia/admin_sets_controller_behavior.rb and have the other two controllers include the behaviors?

**Comment by jcoyne** [comment]
One of these controllers is only for use by the administrators (from the admin menu)  the other controller is for the general public.

**Comment by elrayle** [comment]
I see that now.  Thanks.
