### ISSUE TITLE
Update to use CC1.7.0

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#2979]
Sufia should use CC 1.7.0 but there were breaking changes. So, make sufia master work atop CC master, then you can update the gemspec.

There is at least one known breaking change in CC:
https://github.com/projecthydra/curation_concerns/pull/1105#discussion_r91798384

This should fix a workflow-related bug in master that can be reproduced as follows:
- generate/run test app
- load workflows
- create an account
- deposit a work
- Upon redirection to the work show page, you're unauthorized to view, because depositor was never given edit access.

**Comment by mjgiarlo** [comment]
Related work:

* [WIP PR that bases Sufia on CC's `1-7-stable` branch](https://github.com/projecthydra/sufia/pull/2980) (currently 4 :red_circle:)
* [Sipity-related PR that needs backporting to `1-7-stable`](https://github.com/projecthydra/curation_concerns/pull/1122)
* [SearchBuilder-related PR that needs backporting to `1-7-stable`](https://github.com/projecthydra/curation_concerns/pull/1121)
