### ISSUE TITLE
Error loading Admin Sets show page when admin user created after default admin set is created

### ISSUE THREAD

**Issue by scholarworks** [projecthydra/sufia#2981]
### Descriptive summary

Error loading Admin Sets show page.

### Steps to reproduce the behavior

1. On a new install, sign up a user and create a work.
2. Create a new admin user
3. Log in as new admin user
4. From the admin dashboard click "Admin Sets"

**Comment by jcoyne** [comment]
What's the error that appears on the admin dashboard?

**Comment by scholarworks** [comment]
@jcoyne - on the web it shows the "An unhandled lowlevel error occurred. The application logs may have details." error.

Here is what I see on the rails server console: https://gist.github.com/scholarworks/9ea614ce089cc043e350bfd8f054867c

**Comment by jcoyne** [comment]
I don't understand how that error (Malformed Solr request) would be caused by not using the `AdminSetCreateService`.  Why do you think that is the cause?

**Comment by scholarworks** [comment]
I was including @mjgiarlo comments.

**Comment by jcoyne** [comment]
It looks to me like the error is here: https://github.com/projecthydra/sufia/blob/master/app/presenters/sufia/admin_set_presenter.rb#L4 the "fl" should not be a variable. I'd expect a String like`"id"`

**Comment by mjgiarlo** [comment]
I should clarify that my speculation about AdminSet permissions and the create service was not in response to the Solr error, but to getting an unauthorized error when trying to view an admin set. Was that also happening, @scholarworks?

**Comment by scholarworks** [comment]
No, just the above error I posted. So this may be more the solr problem. I'm happy to fix this.

@jcoyne - you mention that "fl" should not be a variable.  Can you point me at what this should look like?

Thanks

**Comment by mjgiarlo** [comment]
Ah, OK! I'll edit out my baseless speculation then. :D Thanks, @scholarworks.

**Comment by mjgiarlo** [comment]
K, title and description edited.

@scholarworks when you start fresh and create an admin user **before** creating the first work, you don't get this error?

**Comment by scholarworks** [comment]
@mjgiarlo that's my next test. Sorry, rebuilding the test app here is super slow.

**Comment by mjgiarlo** [comment]
@scholarworks Np. It's getting late anyway. :smile:

**Comment by scholarworks** [comment]
Ok - this is a strange one, and I'm going to move on to testing it outside of the test app as well. It doesn't matter if you have an admin user.

This starts with the first item that is submitted to the test app before an admin set is created.  

After signing up 2 users, and setting one as that admin. Then non-admin submitting an item, I see this in the admin dashboard:

![screenshot 2016-12-19 17 16 42](https://cloud.githubusercontent.com/assets/10953399/21334823/17b1acae-c60f-11e6-931e-c5e5c35d6c8b.png)

If I click on "Administrative Sets" I get the error above.

If I stop and restart the solr_wrapper, this error goes away and submitting new items no longer causes the error. The default admin set is also no longer listed.
