### ISSUE TITLE
During migration we make a temporary file without the original_file name

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2985]
### Descriptive summary

During migration the temporary file does not include the original file name, which then means it does not include the extension.  This is needed for a few type zip vs text for one.  When characterization is run again the temporary file is created with the extension and all is well.

See this commit for access to label information: https://github.com/projecthydra/sufia/commit/bb3017d7ebc3ffe8ce9c5825c838faa64a050a9d

**Comment by hackmastera** [comment]
I think the safest thing to do would be to continue using the id/version-based filename, but pull the extension from the label and tack it on. this protects against confusion / overwrites that might result from different users uploading files that happen to have the same name.
