### ISSUE TITLE
Work inactive state ignored in public view.

### ISSUE THREAD

**Issue by scholarworks** [projecthydra/sufia#2987]
### Descriptive summary

When depositing an item to an AdminSet with an assigned workflow, the work state is properly being assigned as inactive:

```irb(main):016:0> work.state.rdf_subject
=> #<RDF::URI:0x3fa1a7ee2158 URI:http://fedora.info/definitions/1/0/access/ObjState#inactive>
```

However, the item is still visible in the public display.

### Expected behavior

The work should not be available in the public display until it has been approved.

### Steps to reproduce the behavior

1. Assign one_step_mediated_deposit to an admin set
2. Assign a user the depositor role for one_step_mediated_deposit
3. Add a work as that user.
4. Log out, item is still visible.

### Related work

Link to related tickets or prior related work here.

**Comment by scholarworks** [comment]
It looks like we are checking `suppressed_bsi` in solr (https://github.com/projecthydra/sufia/blob/7b590ba20e557a1ee66d447bcd75304d283c3366/app/search_builders/sufia/catalog_search_builder.rb#L18) but it isn't being set.

the value of a workflow item:
```"suppressed_bsi":false,```

**Comment by cam156** [comment]
@scholarworks Did you fix this bug?  From what I can see with a fresh install this seems to be working as expected.

**Comment by scholarworks** [comment]
@cam156  - Yeah, it looks like this is working fine. I'm able to reproduce my other bug, and will create a new issue for that, but this will be closed as it is working appropriately now.
