### ISSUE TITLE
Work inactive state is not being changed to active when approved.

### ISSUE THREAD

**Issue by scholarworks** [projecthydra/sufia#2988]
### Descriptive summary

When a the approving role of a workflow is used to approve an item, the state should be changed from inactive to active, currently it is not changing.

### Related work

#2987

**Comment by cam156** [comment]
@scholarworks I have also seen this working in a fresh install.  The solr document is going from 
`"suppressed_bsi":true,`
to 
`"suppressed_bsi":false,`

**Comment by scholarworks** [comment]
Confirmed, this is now working. Closing.
