### ISSUE TITLE
Error thrown when user submits an item to the default Adminset with workflow.

### ISSUE THREAD

**Issue by scholarworks** [projecthydra/sufia#2992]
### Descriptive summary

See error message here: https://gist.github.com/scholarworks/619544e43e2abf13e78374ef40de8501

After the first item is submitted and the default admin set is created, assign a workflow and depositor/approver to the adminset. The above error is thrown when a user submits a new item to any adminset going forward.

**Comment by scholarworks** [comment]
Note - I'm getting the above issue on a fresh build even when creating an admin set for deposit first. This may be a local issue, but it's quite odd.

**Comment by mjgiarlo** [comment]
@scholarworks I wonder if this may be related to what @cam156 started working on here: https://github.com/projecthydra/curation_concerns/pull/1126 (Related in terms of the root cause being `@presenter` being `nil` because an error was raised and caught before the ivar was set.)

**Comment by jcoyne** [comment]
Yes, this looks identical to @cam156's issue
