### ISSUE TITLE
Sufia wiki page for google-analytics is out of date

### ISSUE THREAD

**Issue by mark-dce** [projecthydra/sufia#2993]
It looks like this wiki page is out of date:
https://github.com/projecthydra/sufia/wiki/How-to-integrate-Sufia's-Google-Analytics-user-stats-into-your-Rails-app

And superseded by information on this page:
https://github.com/projecthydra/sufia/wiki/Sufia-Management-Guide#analytics-and-usage-statistics

Should the first page be removed from the Wiki?

**Comment by mjgiarlo** [comment]
As the contributor of that first page, what do you think, @val99erie?

**Comment by val99erie** [comment]
It's been quite a long time since I've looked at that analytics code, so I don't know how it currently works.  But, I have no objection to deleting the other wiki page if it's out of date.

**Comment by mjgiarlo** [comment]
Thanks, @val99erie. I will mark it as deprecated and not migrate it over to Hyrax when we make the big move.

**Comment by mjgiarlo** [comment]
Done. Thanks for reporting this, @mark-dce. :smiley:
