### ISSUE TITLE
Remote file upload fails if the url has spaces

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2994]
### Descriptive summary

When using Browse Everything to upload a file that has spaces in the name, the resulting url for the remote file will also have spaces and result in a `bad URI(is not URI?)` error. This appears to only happen when you're using BE with the local file system.

We should encode the url before parsing it:

https://github.com/projecthydra/sufia/blob/master/app/actors/sufia/create_with_remote_files_actor.rb#L34

**Comment by mjgiarlo** [comment]
@awead Do you think we should try to squeeze this into 7.3.0? If so, do you have cycles to work on it, or know anyone who might? If not, I'm thinking this issue should move into Hyrax.

**Comment by awead** [comment]
@mjgiarlo I'm fixing it locally in SS. It should be easy. Let me see if I can file a PR here in a sec.

**Comment by mjgiarlo** [comment]
@awead excellent! I'll be happy to include it in 7.3.0, then. :smile: Thank you, sir.
