### ISSUE TITLE
Make it easier to change metadata display for admin sets

### ISSUE THREAD

**Issue by elrayle** [projecthydra/sufia#2995]
### Descriptive summary

Currently if you want to add another metadata field to admin sets, you have to copy the entire _form partial.  This will separate the display of metadata into a _form_metadata partial that _form renders.

### Expected behavior

Display title and description on admin_sets create/edit views.

### Steps to reproduce the behavior

1. As an admin user, login and select Administration -> Administrative Sets -> Create
1. See title and description fields.

NOTE: This does not change behavior for Sufia, but does make it easier for apps to override.

**Comment by mjgiarlo** [comment]
Thanks, @elrayle
