### ISSUE TITLE
Batch upload 'set all to this resource type' button - only the first works

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#3031]
There was previously some [discussion](https://github.com/projecthydra/sufia/issues/1869) over whether only the first should show.

It turns out that issue was missing the crucial information that only the first one works. This makes sense due to the wireframe used for development, but either the others need to be hidden or the code should be changed such that they all work.

**Comment by mjgiarlo** [comment]
@hackmastera Do you think we should try to squeeze this into 7.3.0, or meh?

**Comment by hackmastera** [comment]
currently i'm trying to extract that js from the view so it can be tested, but i can't figure out how to then call it from a view. It seems like it has to be called from a view (either that _js_template one or registered as a callback in app/views/sufia/batch_uploads/_form.html.erb) because the elements aren't on the page until the upload is finished.

I don't have strong feelings on this one, but there's a bug in the fix I submitted yesterday and I'll be submitting something for that today. Since there was a bug I wanted to write a test but I might have to submit a fix without one.

**Comment by hackmastera** [comment]
I extracted the js but wasn't successful in writing a test.

https://github.com/projecthydra/sufia/commit/a1a406050004ccfb7327e3cc9168c6da939a1bc3

This method doesn't seem like a good match for jasmine. Either we need the jasmine-jquery plugin or we need to change the method to take an argument; all the ways of changing the method that I could think of felt super contrived like I was doing it just so I could test it. that didn't feel right so I am letting this go for now.

**Comment by mjgiarlo** [comment]
Have a fix now but no test. And the fix is mega-janky. (I went the other way -- instead of only showing the first button, I made all the buttons functional by passing an ID from the clicked button, to provide context to the calling function.)
