### ISSUE TITLE
Edit work shows "Browse View" breadcrumb

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#3035]
<img width="568" alt="screen shot 2017-01-25 at 11 51 21 am" src="https://cloud.githubusercontent.com/assets/92044/22302501/b6e796f6-e2f4-11e6-9652-46e4a291b09a.png">

Where it says "Browse View" it links to the show page.

It should say???

Introduced in 8806cb8797693b12bed3ef2db7864d8eb464a20b

On the show page it shows the work title, not "Browse View"

<img width="371" alt="screen shot 2017-01-25 at 11 58 21 am" src="https://cloud.githubusercontent.com/assets/92044/22302713/a410e19e-e2f5-11e6-83c1-337fa9021b9b.png">

**Comment by mjgiarlo** [comment]
@jcoyne I'm cool with using the title instead of "Browse View" here. What do you think, @ggeisler?

**Comment by ggeisler** [comment]
Yes, I would definitely use the title.

Might have to consider long titles and truncate (with `...`) after x characters, though?
