### ISSUE TITLE
In file view, citation button throws error

### ISSUE THREAD

**Issue by julesies** [projecthydra/sufia#3043]
Sufia 7.2 
If you are looking at an individual file (not work) view, clicking the Citation button throws the error "We're sorry but something went wrong". It works fine on the "Work" view. 

Expected behavior:
Either the file view citation button works as the work view does, or the citation link does not show on the file page. 

Steps to reproduce the behavior

1. Navigate to a file view page (not work)
2. Click the citation button. 

![screen shot 2017-01-31 at 3 56 19 pm](https://cloud.githubusercontent.com/assets/4356335/22484080/d7550666-e7cd-11e6-9e9d-207bd21e1377.png)

![screen shot 2017-01-31 at 3 51 26 pm](https://cloud.githubusercontent.com/assets/4356335/22484012/989859be-e7cd-11e6-8b7d-5881dee025a1.png)

Dev machine error: 
![cite_error](https://cloud.githubusercontent.com/assets/4356335/22484659/7f59e46a-e7d0-11e6-8c4e-ced69ef3c435.png)

**Comment by scherztc** [comment]
It looks like this is configurable in the master branch of sufia.

https://github.com/projecthydra/sufia/blob/master/app/views/curation_concerns/file_sets/_show_actions.html.erb#L5

It can be turned on and off in the sufia.rb file.

  # Enables a link to the citations page for a generic_file.
  # Default is false
  config.citations = false

I will try and fix the citation link next when it is set to true.

**Comment by mjgiarlo** [comment]
@julesies Do you think FileSets should have citations? We can either 1. "fix" this functionality for FileSets, or 2. remove the button altogether from the FileSets page. I'm open to either.

**Comment by julesies** [comment]
@mjgiarlo are FileSets, just single files? My first thought is that having citations available at the FileSet level would be nice (💯 !) but may be challenging to make sure the file-level citations are meaningful. Does it pull info from the work and just reference the file name if there is not addition file-level description? This is why I was checking out what information went into the file-level citation. IMO I would rather have no citation if it wasn't a good one. I see that there are no zotero, etc button on the FileSet page and so it would be consistent to not have the citation button there as well. my .02.

**Comment by mjgiarlo** [comment]
@julesies A FileSet is essentially a wrapper around an uploaded file that lets us bundle the file with its derivatives. There's no assumption about it having sufficient metadata to, e.g., give a citation sufficient context. (Agreeing with you about potentially poor file-level citations.) Work-level info does not percolate down into the FS's citation, no.

LMK how that sounds. If that sounds good, I'll copy this ticket over to Hyrax as a new feature request.

**Comment by scherztc** [comment]
@mjgiarlo For sufia, should I remove the citation button on file_sets?

**Comment by mjgiarlo** [comment]
If you want to do that in Sufia, that'd be great, @scherztc. and we can merge that over in Hyrax. Thank yoU!

**Comment by julesies** [comment]
sounds good!

**Comment by mjgiarlo** [comment]
@scherztc I've approved your PR. Once Travis goes :green_heart:, feel free to merge it.

Thanks, all. :tada:
