### ISSUE TITLE
save widget jumps around when scrolling

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#3044]
It didn't do this in 7.2

**Comment by hackmastera** [comment]
It totally does do this in 7.2; my mistake.

**Comment by mjgiarlo** [comment]
@hackmastera cool if I bounce this to Hyrax? (We may already have this ticketed. Or we did before...)

**Comment by hackmastera** [comment]
sure.

**Comment by mjgiarlo** [comment]
Closed in favor of https://github.com/projecthydra-labs/hyrax/issues/345
