### ISSUE TITLE
Files not added to a work when work is edited during background processing

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#3046]
This bug affects 7.2 and 7.3.

### Descriptive summary

If you upload a number of files to a work, then edit it and save while those files are still being processed in the background, they do not get successfully added to the work.

### Expected behavior

Background jobs and foreground jobs shouldn't mess with one another. Or, if they do, the UI shouldn't allow you to do things that will mess up your work.

### Actual behavior

Using the edit form appears to delete from the work any file added between the time the form loads and the time it saves.

### Steps to reproduce the behavior

1. Generate .internal_test_app
1. add `gem 'sidekiq'` to .internal_test_app/Gemfile; `bundle install`
1. add sidekiq routes to .internal_test_app/config/routes.rb ```require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'```
1. add `    config.active_job.queue_adapter = :sidekiq` to .internal_test_app/config/application.rb
1. run solr, fcrepo, rails server
1. in another terminal run sidekiq with `bundle exec sidekiq -q default -q ingest -q event`
1. in the browser, create a new work. upload a bunch of files to give yourself time; probably 15 is enough.
1. After you save, reload the work to see the first couple of files on the items list. click 'edit' before too many more files load.
1. make some metadata change (not sure if this is required, probably isn't) and click save (that part is required). Don't go too fast.
1. you can watch the sidekiq dashboard to see the jobs finish up.
1. reload the work to see that not all your files were added.

**Comment by jcoyne** [comment]
@hackmastera can you add logs that show the parameters passed for each request. (excerpted from `logs/development.log`)

**Comment by hackmastera** [comment]
jcoyne [14:14] 
@hackmaster.a so that event is launched here: https://github.com/projecthydra/curation_concerns/blob/5ed966284a2123a50e40414e32f1ab64a7738d5b/app/actors/curation_concerns/actors/file_set_actor.rb#L124

jcoyne [14:14] 
Fileset is added to the work here: https://github.com/projecthydra/curation_concerns/blob/5ed966284a2123a50e40414e32f1ab64a7738d5b/app/actors/curation_concerns/actors/file_set_actor.rb#L122

[14:14]  
Could that `save` be failing?

[14:15]  
want to change it to `save!`?

**Comment by hackmastera** [comment]
This error is a side effect of the bug in this issue
https://gist.github.com/hackmastera/db4015ed9f80439083e92428a1d2ffcc

When the relationship has been been botched, but the notification is still queued, the fileset has no parent to reference in the notification message.

**Comment by hackmastera** [comment]
@jcoyne is this helpful; it's a whole mess of params from the beginning of the process to the end.

https://gist.github.com/hackmastera/c139f839bc360f5f685885b54fa4c57a

**Comment by jcoyne** [comment]
@hackmastera it would be more helpful if you didn't scrub the "Processing by" or "Started" lines.  Can you get all of these?

```
Started GET "/admin/workflows?locale=en" for ::1 at 2017-02-01 14:07:44 -0600
Processing by Hyrax::Admin::WorkflowsController#index as HTML
  Parameters: {"locale"=>"en"}
```

**Comment by hackmastera** [comment]
@jcoyne but it's helpful to get rid of the solr params lines?

will try again.

**Comment by hackmastera** [comment]
@jcoyne I updated that gist.

**Comment by hackmastera** [comment]
Editing the work in the file manager also produces this bug.

**Comment by hackmastera** [comment]
Just to record this here, it's clear that the form data submitted is overwriting the files that were saved by background jobs while the form was open.

see justin's comment: https://gist.github.com/hackmastera/c139f839bc360f5f685885b54fa4c57a#gistcomment-1986172

**Comment by hackmastera** [comment]
It's also possible for two different users to edit a work at the same time resulting in one overwriting the other's edits.

**Comment by hackmastera** [comment]
Basically we have a problem of insufficient locking. I agree with @tpendragon that this sounds like a good use case for optimistic locking.

I propose we add a 'version' field to each work object. The version should be stored as a hidden field on the form. In the save method for a work:

- acquire a lock
- check the version against the stored object
  - if no version is submitted, reject the save with a relevant error
  - if the version submitted does not match the one stored, reject the save with a relevant error
  - if the version does match the one stored, increment the version and save
- release the lock.

Probably want to do this for collections and filesets, also.

**Comment by mjgiarlo** [comment]
@hackmastera @jcoyne @tpendragon I wonder if we could use AF/Fedora versioning for this, and in so doing build some of what we ultimately need to expose object versioning to users?

This feels like a deep and wide-reaching change for a bug fix, though I acknowledge this is a gnarly bug that we should fix. Are there any acceptable alternatives, or are we past those at this point?

**Comment by hackmastera** [comment]
@mjgiarlo I like the idea of seeing this as a step toward exposing object versioning to users. But I also agree that trying to do that makes the fix much bigger.

@jcoyne just suggested using last_update instead of a version field, which seems like a good way to reduce footprint here.

Also, if we can target a fix just at the file attachment / ordering conflict between background jobs and form submissions, that would be perfectly acceptable. the multiple-users-changing-metadata scenario is not as immediate of a concern for us. But I worry that trying to target a fix like that will make it more complicated / finicky to get right.
