### ISSUE TITLE
Work should not save if files are still uploading

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#3048]
### Descriptive summary

7.2 and 7.3 display this behavior. When you are creating a new work it is possible to save the work before the files have all been uploaded.

### Expected behavior

The UI shouldn't let you save a work (save should be grayed out) if it would mean that not all the files you queued for upload will be attached.

### Actual behavior
It's possible to submit the work before all files have been uploaded

### Steps to reproduce the behavior

1. Click 'create work'
1. Fill in some metadata
1. Click the deposit agreement
1. Go to files tab and add a bunch of files, or a few larger files (just to give yourself enough time)
1. Before all files have finished uploading, click 'save'

**Comment by mjgiarlo** [comment]
How is this related to #3046?

**Comment by hackmastera** [comment]
@mjgiarlo no not related. This is strictly a UI matter. Here the save button can be pressed before the uploader has actually uploaded all of the files.

**Comment by mjgiarlo** [comment]
@hackmastera Oh! Yes, good call. Thanks. :)

**Comment by jcoyne** [comment]
Reopening, because #3056 needs to be reverted.
