### ISSUE TITLE
Non-admin user can add own work to Admin set

### ISSUE THREAD

**Issue by julesies** [projecthydra/sufia#3049]
We have Sufia 7.2 and have only "regular users" and "admin users" in our test. 

As a non-admin user, I can add my own work to an Admin Set (with "Ability to assign uploaded items to an admin set" turned on)  in the Relationship tab. The Admin Set does not show up on the "full work view" but when you navigate to the Admin set, it is there. You can also see the Admin Set selected in the drop-down when you are in Edit Work view. 

Expected behavior:
With the feature turned on, I expected that non-admin users would not be able to add to Admin Sets OR if they do there is some forced review process. 
All admin users can edit Admin Sets and add content to the Admin Set not dependent on settings OR Admin Set created can enable specific users/roles to have edit permissions. 

Actual behavior:
With the feature turned on, any user can add works to the Admin Set
With the feature turned off, only the creator of the Admin Set can add works to the Admin Set. 
With the feature turned off, other admin users can edit the metadata for the Admin Set and toggle the features for the set in Settings. 

Steps to reproduce the behavior

1. Log in as admin, create admin set (with ability add uploaded items to Admin Set turned on)
2. Log is as non-admin user
3. Create work
4. Go to relationships tab
5. Select Admin Set, save
6. View Admin Set
7. As Admin Set creator, turn feature off for that set
8. As admin user (not set creator), try to add works to the set in relationship tab. 

![screen shot 2017-02-02 at 8 55 06 am](https://cloud.githubusercontent.com/assets/4356335/22554212/503e4a32-e92d-11e6-98d3-16ce3a9cc234.png)
![screen shot 2017-02-02 at 8 55 52 am](https://cloud.githubusercontent.com/assets/4356335/22554213/50409968-e92d-11e6-8043-84cf7fe7fe8f.png)

**Comment by mjgiarlo** [comment]
@hannahfrost @ggeisler @jcoyne Do we want Admin Sets to be open for deposit by default, like they currently are, or to be closed for deposit (using the Admin Set Depositor role to control who can do so)? If the latter, I'm not sure we've ticketed this yet. cc: @julesies

**Comment by ggeisler** [comment]
I can't remember if @hannahfrost and I discussed this when working on the Admin Set Participants page, but I think my assumption was that Admin Sets would be closed by default (just to prevent someone from creating an Admin Set intended to be limited in terms of deposit but forgetting to update the depositor role and thus inadvertently allowing unwanted depositors). 

For this to be feasible, it has to be easy to make an Admin Set open for deposit. I was assuming institutions would have a _group_ that could be used for that ("Institutional users" or whatever), so it's only one step to make an Admin Set open for deposit. But at least it's an explicit choice so the Admin Set Manager is aware when the Set is open to everyone.

If there was a technical way to make the default Admin Set open but not subsequent ones, that might be ideal (assumes it is a common scenario that the default Admin Set is an institution's most open and general set, and subsequent sets are created for more specific and possibly limited purposes).

@hannahfrost and @jcoyne are better suited than me to offer an opinion on this, though, so I don't feel strongly about any of the above if they have differing thoughts.

**Comment by mjgiarlo** [comment]
@julesies I have created a new feature issue for this in Hyrax: https://github.com/projecthydra-labs/hyrax/issues/357 Closing in Sufia. Thank you for writing this up!
