### ISSUE TITLE
Firefox and Safari bug in selecting different works to batch edit

### ISSUE THREAD

**Issue by hannahlwang** [projecthydra/sufia#3052]
### Descriptive summary

I'm at UNC, we're on Sufia 7.2. This problem seems to only happen on Firefox and Safari, Chrome is fine. If you select works in "My Works" and go to the Batch Edit view, then click back in your browser, deselect the selected works, select different works, and go to the Batch Edit view again, it still displays the previously selected works in addition to the newly selected works in "Changes will be applied to". The only way to truly change your selection is to refresh your browser.

### Expected behavior

When I select works to batch edit, go to Edit Selected, go back, deselect works and select new ones to batch edit, and go to Edit Selected, all works (deselected and newly selected) appear under "Changes will be applied to"

### Actual behavior

When I select works to batch edit, go to Edit Selected, go back, deselect works and select new ones to batch edit, and go to Edit Selected, I expect only the newly selected works to appear under "Changes will be applied to"

### Steps to reproduce the behavior

1. Open Firefox or Safari (not Chrome)
2. As a logged in user, go to "My Works"
3. Select multiple works and click "Edit Selected"
![screen shot 2017-02-02 at 1 07 38 pm](https://cloud.githubusercontent.com/assets/16670954/22562172/71e7cf2a-e949-11e6-9c8f-498148b036f5.png)
4. Note the works that appear under "Changes will be applied to"
![screen shot 2017-02-02 at 1 08 04 pm](https://cloud.githubusercontent.com/assets/16670954/22562181/78eeb090-e949-11e6-80c5-31754fc0e1aa.png)
5. Click "Back" in your browser
6. Deselect the selected works and select different works
![screen shot 2017-02-02 at 1 08 18 pm](https://cloud.githubusercontent.com/assets/16670954/22562212/989dde48-e949-11e6-8cc6-fd63a0548ee1.png)
7. Click "Edit Selected"
8. Note the works that appear under "Changes will be applied to"
![screen shot 2017-02-02 at 1 08 30 pm](https://cloud.githubusercontent.com/assets/16670954/22562259/c61c0e3a-e949-11e6-9062-b6218ee0c7b2.png)

**Comment by mjgiarlo** [comment]
Thanks for writing up this ticket, @hannahlwang, and I can confirm this is still an issue over in Hyrax. We're going to be radically reworking the batch edit functionality later this year in Hyrax, so I'm inclined to move this issue over to that codebase.

**Comment by mjgiarlo** [comment]
Moved to Hyrax: https://github.com/projecthydra-labs/hyrax/issues/356

Thanks, @hannahlwang!
