### ISSUE TITLE
Translation errors when edit form submission fails

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#3058]
### Descriptive summary

This is surfacing due to the work addressing #3046 .

If a form is re-loaded from the update action you get translation errors on the following

- en.sufia.works.update.header
- en.sufia.works.update.in_collections
- en.sufia.works.update.in_this_work
- en.sufia.works.update.in_other_works

They can just be copied from the edit translations.

**Comment by jcoyne** [comment]
It looks to me that this is caused by using `action_name`.  https://github.com/projecthydra/sufia/blob/fadd46344953d42701f011a4aa24e71c9fe7171e/app/views/curation_concerns/base/_form_relationships.html.erb#L10

**Comment by jcoyne** [comment]
We should probably do what Rails does here, where that part of the translation is limited to update/create: https://github.com/rails/rails/blob/058eb959bff8e43953f435bdf25d35435440d09e/actionview/lib/action_view/helpers/form_helper.rb#L2242
