### ISSUE TITLE
Collection members should not be migrated to ordered_members

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#3063]
The sufia and curation concerns code do not maintain ordered_members, so you could end up with a situation like #3062.

This line https://github.com/projecthydra/sufia/blob/7.2-migration/lib/sufia/import/collection_builder.rb#L30 needs to be changed to use `#members`.

**Comment by mjgiarlo** [comment]
@jcoyne are we going to want this in 7.3.0 and Hyrax as well?

**Comment by hackmastera** [comment]
@mjgiarlo I believe that import file will die with 7.2.x so we don't need to worry about porting it forward

**Comment by mjgiarlo** [comment]
@hackmastera okie dokie. thx!
