### ISSUE TITLE
Error when removing an existing editor from a work

### ISSUE THREAD

**Issue by hortongn** [projecthydra/sufia#3065]
Note: this bug seems to affect 7.2 and 7.3

### Descriptive summary

When editing a work, if the user removes another user from "Share work with other users" and then clicks the Save button, it throws a `Ldp::Gone in CurationConcerns::GenericWorksController#update`

It does look like the editor gets removed from the work, but the user gets the error page below instead of going back to the work show page.

![action controller exception caught](https://cloud.githubusercontent.com/assets/5639859/22710048/e6a7bdda-ed49-11e6-87e2-3c0fa1c51b03.png)

### Expected behavior

Clicking Save after removing an editor should remove the editor and return the user to the work show page.

### Steps to reproduce the behavior

1. As User1, create a new work
1. Edit the work and click on the Share tab
1. Give User2 edit access under "Share work with other users"
1. Save the work
1. Edit the work again and click on the Share tab
1. Remove User2 from "Share work with other users"
1. Click on Save (this should generate the error)

**Comment by mjgiarlo** [comment]
@hortongn I wonder if this is related to https://github.com/projecthydra/hydra-head/issues/401

**Comment by hortongn** [comment]
@mjgiarlo Ah, might be.  I checked to see if this showed up after recent changes to CC and AF, but didn't check hydra-head.  I'll try it locally using hydra-head 10.3.0 just to confirm this is the same bug.  Will report back here.

**Comment by hortongn** [comment]
Yep, confirmed that this bug only exists under hydra-head 10.4.0.  

Is it safe to just close this issue or should it stay open until we know the fix in hydra-head works in Sufia?

**Comment by mjgiarlo** [comment]
> Is it safe to just close this issue or should it stay open until we know the fix in hydra-head works in Sufia?

Let's leave it open 'til Sufia picks up the HH fix. Thank you!

**Comment by hortongn** [comment]
Reopening this bug because it still exists in Sufia 7.3.0.rc1 (using the most current hydra-head 10.4.0 and active-fedora 11.1.4)

Even with the active-fedora fix that closed this issue, when I remove an editor from a work I still get the Ldp::Gone error above.

**Comment by mjgiarlo** [comment]
@jcoyne Do you want to be assigned to this ticket?

**Comment by jcoyne** [comment]
This is https://github.com/projecthydra/hydra-head/issues/403 and there's nothing to be done for it in sufia.

**Comment by mjgiarlo** [comment]
@jcoyne I assume  we need a new AF release to make sure Sufia picks it up. Re-opening 'til that happens. Feel free to close again if that's not the case.

**Comment by hortongn** [comment]
@mjgiarlo @jcoyne I'm happy to cut a new AF first thing in the morning.  I know you both have C4L going on right now.

**Comment by mjgiarlo** [comment]
Thanks, @hortongn!

**Comment by hortongn** [comment]
Closing now that AF release with this fix has been cut.
