### ISSUE TITLE
Upgrading to 7.3.0 from 7.2.0 -- Need the Sipity db tables before loading workflows

### ISSUE THREAD

**Issue by jenlindner** [projecthydra/sufia#3074]
### Missing steps in the upgrade path release notes for loading default workflows

https://github.com/projecthydra/sufia/issues/2790

After creating new Sufia tables, you'll need to create Sipity tables because the following step, ```rake curation_concerns:workflow:load```  requires them (thanks @hackmastera and @jcoyne for surfacing the problem and solution in the #dev slack channel). You'll also need to copy a default workflow, as @hackmastera pointed out in the notes, and includes links to a few as well as how and why to do it. They're in the Curation Concerns migrations and there's already a Sufia rake task to get those. 

The steps in the release notes should be: 

``` bin/rake sufia:install:migrations ```
``` bin/rake [or bundle exec rake] curation_concerns:install:migrations ```
``` bundle exec rake db:migrate```
``` create (copy) default.json workflow in config/workflows ```
``` bundle exec rake curation_concerns:workflow:load ```

**Comment by mjgiarlo** [comment]
@jenlindner Thanks! Can you also say what you're upgrading from? 7.2.0 or something else?

**Comment by jenlindner** [comment]
Yes I can!

**Comment by mjgiarlo** [comment]
@jenlindner I've added this to the description of https://github.com/projecthydra/sufia/issues/2790. Closing.

Thanks!
