### ISSUE TITLE
Unable to access administrative workflows review page when upgrading from 7.2.0 to 7.3.0.rc1

### ISSUE THREAD

**Issue by lfarrell** [projecthydra/sufia#3076]
When upgrading from 7.2.0 to 7.3.0.rc1 I am unable to access the Administration->Workflows->Review page. It results in the following error
```
uninitialized constant CurationConcerns::AdminController
```
The Workflows->Roles page appears to be unaffected.

See the trace below. Not sure if it's a sufia or curation concerns issue.

![workflow](https://cloud.githubusercontent.com/assets/436691/22945217/6b46449a-f2c1-11e6-84ff-470991d5b39d.png)

**Comment by jcoyne** [comment]
@lfarrell would you try running `bin/rails generate curation_concerns:admin_dashboard`. This step may be missing from the upgrade guide if you are using curation_concerns 1.7+

**Comment by lfarrell** [comment]
@jcoyne That seemed to do the trick. The link now goes to a "Review and Comment" page.

**Comment by jcoyne** [comment]
@lfarrell thanks for testing! I've updated the upgrade guide with this step.
