### ISSUE TITLE
Searching on keyword (and all descriptive fields) should work

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#3081]
Instead I received 0 results. Faceting *does* work for this field and the Solr document seems to have the right keys (`keyword_tesim` and `keyword_sim`).

Discovered this after 7.2.0 :arrow_right: 7.3.0.rc1 upgrade.

**Comment by jcoyne** [comment]
I believe this is because Sufia doesn't submit `search_field=all_fields` as Blacklight does. Sufia uses a bootstrap dropdown rather than a simple html select input.

**Comment by mjgiarlo** [comment]
I don't believe ScholarSphere does either but its searches are working. (@awead said so.)

**Comment by jcoyne** [comment]
@mjgiarlo it's possible that Blacklight Advanced search is in play (in SS, but not Sufia)

**Comment by mjgiarlo** [comment]
@jcoyne Oooh, good call.

**Comment by awead** [comment]
@jcoyne yes, we still have the gem in use.
