### ISSUE TITLE
Notification stating "Files will be marked private until this process is complete" Is a lie

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#3087]
### Descriptive summary

https://github.com/projecthydra/sufia/blob/master/config/locales/sufia.en.yml#L243

With Sufia 7 this is either not true or it's not useful; As soon as they appear on the work they already have the requested visibility.

Unfortunately there's not a way to tell, really, when processing is done except that I guess all the thumbnails will appear.

### Steps to reproduce the behavior

1. Create a new work with a file. Make it publicly visible.
1. Observe the message displays but the files are open access as soon as they are attached.

![screen shot 2017-02-17 at 1 24 07 pm](https://cloud.githubusercontent.com/assets/845363/23078061/24c2e216-f515-11e6-99c9-fcd0b28b7283.png)

**Comment by mjgiarlo** [comment]
@hackmastera How do you think we ought to address this? Would a simple reword like the following suffice?

> Your files are being processed by %{application_name} in the background. The metadata and access controls you specified are being applied. You may need to refresh this page to see these updates.

:question:

**Comment by hackmastera** [comment]
@mjgiarlo That seems fine!
