### ISSUE TITLE
Broken Default Admin Set Link migrating from 7.2.0 to 7.3.0.rc1

### ISSUE THREAD

**Issue by lfarrell** [projecthydra/sufia#3088]
We have a custom admin set and objects that were created before the upgrade to 7.3

![admin-sets](https://cloud.githubusercontent.com/assets/436691/23081315/4cbca5f6-f522-11e6-9ef9-ebca862838fe.png)

Sufia 7.3 apparently generates the Default Admin Set as no creator is listed. Clicking the link for the Default Admin Set bypasses rails entirely and goes straight to Apache

![not_found](https://cloud.githubusercontent.com/assets/436691/23081443/d1576314-f522-11e6-81a8-10227ed78b75.png)

**Comment by mjgiarlo** [comment]
@lfarrell Did you run `rails generate curation_concerns:admin_dashboard` as part of the upgrade process? That was added to the release notes recently, possibly after you tried the upgrade.

**Comment by mjgiarlo** [comment]
@lfarrell I ran through the upgrade and could not reproduce this. The Default Admin Set is indeed created in 7.3.0.rc1 (and there is no creator), but I can click the link just fine.

**Comment by jcoyne** [comment]
This could be a misconfiguration if the proxy settings if you're using Apache.

**Comment by lfarrell** [comment]
@mjgiarlo I have run the dashboard generation. I'll take a look at the Apache settings as mentioned by @jcoyne

**Comment by mjgiarlo** [comment]
@lfarrell Have you had a chance yet to look into whether this is an issue related to Apache or the application itself? I don't think we've reproduced this bug yet.

Thanks.

**Comment by lfarrell** [comment]
@mjgiarlo As best as I can tell our rails is setup correctly. That said we've had issues with other bits of sufia on our test server that work just fine in my local environment. Our sufia box is pretty jerry rigged, as it's meant for a quick internal demo. I'd say go ahead and close this issue.

**Comment by mjgiarlo** [comment]
OK, thanks, @lfarrell!
