### ISSUE TITLE
Sufia::PermissionTemplate error on save work

### ISSUE THREAD

**Issue by njaffer** [projecthydra/sufia#3098]
### Descriptive summary
Related to Sufia 7.3

### Expected behavior
Can save work
### Actual behavior
Cannot save work - Sufia::PermissionTemplate is empty
https://gist.github.com/njaffer/d6142654da25c9e0148499fb45c8bf9a
### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here.

**Comment by jcoyne** [comment]
@njaffer that stack trace says you are using sufia at e79f0fb8a347, however, I'm unable to find that hash in the github repo.  Can you reproduce it using 7.3.0.rc1?

**Comment by njaffer** [comment]
@jcoyne: We are using v7.3.0.rc1 ```Using sufia 7.3.0.rc1 from git://github.com/projecthydra/sufia.git (at v7.3.0.rc1@e79f0fb)```

**Comment by jcoyne** [comment]
@njaffer v7.3.0.rc1 is cd07957 (see https://github.com/projecthydra/sufia/tree/v7.3.0.rc1)  the hash you provided does not exist: https://github.com/projecthydra/sufia/commit/e79f0fb

**Comment by njaffer** [comment]
@jcoyne: Ok, here is the new trace: https://gist.github.com/njaffer/5b5ec66bea1144e3b771c4230c4c0bd4

Is there a rake test for adding a record in Permission Template?

**Comment by mjgiarlo** [comment]
@njaffer I believe @scholarworks is working on a new rake task for adding the default admin set, and that will be part of the setup instructions. I wonder if https://github.com/projecthydra-labs/hyrax/issues/477 would resolve this issue? @scholarworks @jcoyne ?

**Comment by mjgiarlo** [comment]
It's looking like projecthydra-labs/hyrax#477 may be too labor-intensive to get into 7.3.0. Suggestions for workarounds? @jcoyne @jeremyf @scholarworks

**Comment by jeremyf** [comment]
@mjgiarlo I'm not certain what the process is for backporting, but I don't believe 477 is that labor intensive to implement.
