### ISSUE TITLE
Breadcrumb on work view is confusing

### ISSUE THREAD

**Issue by julesies** [projecthydra/sufia#3111]
Sufia 7.3.0rc1 

When logged out and viewing a work, the breadcrumb reads My Works/ Title of Work. 

See below. 

![screen shot 2017-02-23 at 3 14 31 pm](https://cloud.githubusercontent.com/assets/4356335/23278416/78864202-f9df-11e6-92d3-b9092f5df597.png)

Expected behavior: You wouldn't see the word My in the context of something not yours.

**Comment by jcoyne** [comment]
What URL are you viewing this at?

**Comment by julesies** [comment]
navigating from "recently deposited" on the home page to http://beckley.lib.unc.edu/concern/works/mw22v545k

**Comment by jcoyne** [comment]
Yep, added here: https://github.com/projecthydra/sufia/commit/8806cb8797693b12bed3ef2db7864d8eb464a20b#diff-d2074b71a438ddea924558f8a5be9acdR66 that's strange

**Comment by jcoyne** [comment]
Doesn't appear to be an issue in Hyrax.

**Comment by mjgiarlo** [comment]
@julesies I'm going to add this as a bug for the 7.3.0 milestone, though not as a blocker.

**Comment by mjgiarlo** [comment]
Since it's fixed in Hyrax and is relatively low-profile, I'm going to close this bug if that's OK.
