### ISSUE TITLE
Depositor with no roles defined can deposit to all admin sets

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#3126]
### Descriptive summary

Sufia 7.3.0rc3

### Expected behavior

Depositors can only deposit to admin sets for which their role is defined as a depositor

### Actual behavior
Depositing user can deposit content to any admin set even if they are not assigned any roles for any admin sets or workflows. 

While this may be behaving as specified and intended, this behavior is problematic in, i suspect, a not insignificant number of use cases for a repository with workflow capabilities.

**Comment by mjgiarlo** [comment]
This is a known shortcoming of the AdminSet implementation in Sufia 7.x. We have a ticket slotted for Hyrax 2.0 that will fix this: https://github.com/projecthydra-labs/hyrax/issues/357

I would call this a missing feature rather than an outright bug, so I'm not inclined to fix this in Sufia. 'Sok, @vantuyls?

**Comment by scholarworks** [comment]
@mjgiarlo I'm inclined to agree with you not being inclined....

**Comment by mjgiarlo** [comment]
If we do close this issue, we should document clearly the shortcomings of the AS/workflow implementation in 7.3.0. @vantuyls if you wanted to schlepp together a bunch of text (from this and the other issue you created), I'd be happy to find a good place to put it that folks won't miss when deciding whether or not to use 7.3.0.

**Comment by scholarworks** [comment]
@mjgiarlo I think documenting these decision is critical for the design/understanding of these. so ++

**Comment by vantuyls** [comment]
okay, i'll try putting something together and send it back to you. timeline?

**Comment by mjgiarlo** [comment]
@vantuyls next 10 days? basically, before the 7.3.0 release. (which now has 3 blocker bugs...)

**Comment by mjgiarlo** [comment]
@vantuyls and thanks!

**Comment by vantuyls** [comment]
we should look at this in hyrax to either determine it is not a problem there or fix it there.

@mjgiarlo

**Comment by mjgiarlo** [comment]
@vantuyls Does https://github.com/projecthydra-labs/hyrax/issues/357 cover it?

**Comment by vantuyls** [comment]
@mjgiarlo yep.

**Comment by mjgiarlo** [comment]
Thanks, @vantuyls
