### ISSUE TITLE
Adding a child work causes the edit form's lock to go stale

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#3127]
And then the form cannot be saved.

### Descriptive summary

7.3.rc3

### Expected behavior
Adding a child work, then submitting the form via the save button, should result in the child work being attached plus any other changes being applied.

### Actual behavior
Adding a child work then submitting the form results in the error message "Another user has made a change to that Work since you accessed the edit form."

### Steps to reproduce the behavior

1. Create 2 works
1. Edit the first work and add the second as a child.
1. Click 'save'

### Related work
https://github.com/projecthydra/sufia/pull/3066
https://github.com/projecthydra/sufia/commit/798495543e99cf84707dba64fe45de150e9548b7

**Comment by mjgiarlo** [comment]
We have some issues in Hyrax related to this, namely projecthydra-labs/hyrax#325 and projecthydra-labs/hyrax#326. It may make sense to do this in Sufia now.

**Comment by hackmastera** [comment]
I have some time today and maybe tomorrow to look at moving this from ajax submission to regular form submission. @dlpierce if you have any WIP to share please do

re: https://github.com/projecthydra-labs/hyrax/issues/325#issuecomment-278108116

**Comment by hackmastera** [comment]
Releasing this for now; I didn't get very far before having to take some time with a sick kid.
