### ISSUE TITLE
Deleting an Admin Set does not remove link to Admin Set, admin set still visible

### ISSUE THREAD

**Issue by julesies** [projecthydra/sufia#3128]
upgrade to 7.3.0.rc3

I deleted an admin set titled "Default Workflow Test Admin Set" and then navigated to the work and found the Admin Set  still visible on the record.  

I clicked on the (deleted) Admin Set link in the work and see the Admin Set still appears "to be there".

See Work View:
![screen shot 2017-03-03 at 3 35 14 pm](https://cloud.githubusercontent.com/assets/4356335/23569147/e3447828-002b-11e7-8edb-18f305220adf.png)

See Clicked Link View:
![screen shot 2017-03-03 at 3 35 24 pm](https://cloud.githubusercontent.com/assets/4356335/23569173/083e2f2a-002c-11e7-9400-e652214c3079.png)

Deleted Admin Set is removed from Admin Set List in the Administration View.

**Comment by mjgiarlo** [comment]
Thanks, @julesies.

For implementers: this was worked on here: https://github.com/projecthydra/sufia/pull/3041

Notice the question I asked here: https://github.com/projecthydra/sufia/pull/3041#pullrequestreview-19583884 That is worth adding -- this may be the test that will turn up what's missing here.

**Comment by mjgiarlo** [comment]
@julesies What would you think about pulling in the Hyrax behavior here, basically restricting deletion of Admin Sets to ones that are not empty?

**Comment by julesies** [comment]
@mjgiarlo I think that would work. I believe Avalon does this FWIW, though my knowledge is dated. For Sufia though, if an administrator needed to delete an admin set, they would have to individually delete works OR move works into another admin set. To move works, they would need to edit each one individually, correct? That is a drag, but possible. If there a way for a developer to intervene and do a bulk move for a repo manager, that would be good. Not sure if that happens or not. 
Do you think most people with Admin Set needs will skip straight to Hyrax?

**Comment by mjgiarlo** [comment]
@julesies 
> they would have to individually delete works OR move works into another admin set. To move works, they would need to edit each one individually, correct? That is a drag, but possible.

Yes, that's exactly what would need to happen until we work on bulk moving. (And, yes, a drag.) We have a ticket for that in Hyrax. It should be relatively easy to perform this operation in the Rails console, like you mentioned.

Not sure when the Sufia-to-Hyrax critical mass is going to be reached. (I hope soon!)

**Comment by mjgiarlo** [comment]
We should port this over to Sufia: https://github.com/projecthydra-labs/hyrax/pull/363

**Comment by tdonohue** [comment]
@mjgiarlo : projecthydra-labs/hyrax#363 involves updates to code that came from both Sufia (majority) and CC (namely `AdminSetBehavior`).

So, to clarify, are you talking about now overriding CC's `AdminSetBehavior` in Sufia (so that Sufia alone acts more like Hyrax)?  Or is this ticket about updating both CC and Sufia?  If you recall, CC's `AdminSetBehavior` is different from Hyrax (which was part of the reason we chose to implement this in Hyrax to start with)

**Comment by mjgiarlo** [comment]
@tdonohue I don't have a strong preference, tbh.
