### ISSUE TITLE
undefined method `permit!' for nil:NilClass

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#3132]
Sufia 7.3 RC

If I submit batch create without selecting any resource types I get an error:

https://gist.github.com/hackmastera/641336392288155a48b8e2be31e43dce

Note that resource type is not a required field.

### Expected behavior
works should save and not have a resource type

### Actual behavior
NoMethodError

**Comment by jcoyne** [comment]
Have you modified the batch upload form?  Can you post the parameters that Rails is receiving (from the log)?

**Comment by hackmastera** [comment]
This behavior was observed in a newly-generated 7.3.rc3 test app.

Here are the parameters:
