### ISSUE TITLE
As a reviewer, I can't find deposits

### ISSUE THREAD

**Issue by julesies** [projecthydra/sufia#3140]
Upgrade from 7.2 to 7.3rc3

I'm testing the one-step mediated deposit. As a depositor, I can complete the deposit as expected.

As a reviewer (non-admin), I log in and I see the notification that the deposit has been completed, but there is no way to navigate to the item. The only way I can get to the item is by constructing a URL with the ID that I can see in the User Notifications Message. When logged in, I can't see pending review items by navigating to the Admin Set, searching, etc. Am I missing something?

![screen shot 2017-03-13 at 9 24 09 am](https://cloud.githubusercontent.com/assets/4356335/23856155/ef197c48-07ce-11e7-8f36-12e4ae63008d.png)

Once I do get to the item by constructing the URL, I can see the approval box and can successfully approve it.  

To recreate:
- Make sure setting "assign admin set" is on
- Set up an admin set with 1-step mediated deposit workflow. 
- (I've tried this two ways, with assigning participants to admin sets: depositor as "depositor" and reviewer as "manager"; and I've tried not assigning participants to the admin set. Both with same results)
- Assign non-admin user accounts appropriate roles in Workflow: Roles (reviewer, depositor)
- Log in as depositor, deposit work
- Log in as reviewer, see notifications (no links)
- Try to navigate to the work via search, admin set. 
- Construct the URL for the work given the ID in the notification message
- Approve deposit 

Expected behavior:
-Some way to navigate to the deposits that need review without constructing a URL.

**Comment by julesies** [comment]
See empty admin set view reviewer Reviewer and admin set Manager 
![screen shot 2017-03-13 at 9 15 45 am](https://cloud.githubusercontent.com/assets/4356335/23857937/4705217c-07d5-11e7-936c-ce69d021ef9e.png)

**Comment by mjgiarlo** [comment]
@vantuyls @jcoyne @aaron-collier @randalldfloyd do y'all have thoughts on the above?

**Comment by jcoyne** [comment]
Same as https://github.com/projecthydra-labs/hyku/issues/726

**Comment by jcoyne** [comment]
Also the list of files under review should be at `/admin/workflows`

**Comment by julesies** [comment]
Does that mean it's restricting the list of to review items to users with admin privs? I was wondering if the link could be in the notification message for reviewers (who would likely not be admins or even manager participants). I'm not arguing for to this happen in 7.3, just to be clear.

**Comment by mjgiarlo** [comment]
@julesies I added a quick PR backported from Hyrax to linkify works in notifications. I had to rush through it, so it may be super busted. ;) Will revisit tomorrow. See https://github.com/projecthydra/sufia/pull/3151 in the meantime.
