### ISSUE TITLE
Workflow: review is always empty

### ISSUE THREAD

**Issue by julesies** [projecthydra/sufia#3141]
Ugrade Sufia 7.2 to 7.3.0rc3
As an Admin User, I never see anything under Workflow: Review. Even with active deposits that need review, it's always empty. Workflow: Roles works as expected. 

Wondering if we have something set up wrong or if this is a bug?

![screen shot 2017-03-13 at 9 01 56 am](https://cloud.githubusercontent.com/assets/4356335/23858096/bfd3bbea-07d5-11e7-8d17-b994078197e6.png)

**Comment by jcoyne** [comment]
Are you set up as a reviewer of the admin set?

**Comment by julesies** [comment]
@jcoyne ah! That was it! thank you, will close.
