### ISSUE TITLE
AdminSetCreateService.create_default! should set up the workflow

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#3157]
currently the service creates  a PermissionTemplate, but doesn't set workflow_name.  

Related to #3156 

This causes people who run `rake sufia:default_admin_set:create` and then attempt to deposit a work to get a backtrace.

**Comment by hackmastera** [comment]
looking at this

**Comment by mjgiarlo** [comment]
There was also some work done to use workflow IDs instead of names. I believe @aaron-collier did this, but can't recall where this work lives.
