### ISSUE TITLE
Harvesting lc_subjects puts them into the wrong table

### ISSUE THREAD

**Issue by bmaddy** [projecthydra/sufia#322]
lc_subjects were moved into the SubjectLocalAuthorityEntry table but LocalAuthority.harvest_rdf still puts them into the LocalAuthorityEntry table. I would expect them to be imported into the SubjectLocalAuthorityEntry table.

**Comment by hackmastera** [comment]
Does anyone have a memory of why this was closed? @awead? Or am I missing some deciding factor in the conversation thread? The table is still there so it seems like it should either be used or removed...

**Comment by awead** [comment]
@hackmastera is it still a problem? It was probably closed because it was either no longer a problem or couldn't be replicated.
