### ISSUE TITLE
Tinymce does not init if you visit the home page via a link with Turbolinks enable

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#379]
I think this is because the TinyMCE scripts are drawn inline and not in the header.

**Comment by awead** [comment]
@jcoyne is this still an issue? or did it get fixed?

**Comment by jcoyne** [comment]
Still an issue afaik

**Comment by mjgiarlo** [comment]
@jcoyne Is the solution just to tweak when TinyMCE is included in our partials?

**Comment by jcoyne** [comment]
Upstream: https://github.com/spohlenz/tinymce-rails/issues/188

This indicates we could set `<body data-no-turbolink>` on the main page if the user has edit perms

**Comment by hectorcorrea** [comment]
Replacing `<body>` with `<body data-no-turbolink>` in https://github.com/projecthydra/sufia/blob/master/app/views/layouts/homepage.html.erb#L7 seems to fix the problem.

**Comment by mjgiarlo** [comment]
I'm fine with adding that to Sufia 7.0.0 for users w/ edit perms.

You working with @mbklein, @hectorcorrea?
