### ISSUE TITLE
Should be a better way to add editable fields

### ISSUE THREAD

**Issue by dchandekstark** [projecthydra/sufia#384]
In sufia 3.7.2, to add an editable field, you have to override terms_for_editing (or terms_for_display) *and* redeclare attr_accessible (to add the new field).

**Comment by mjgiarlo** [comment]
@jcoyne This is simplified or at least streamlined in fedora-4/master, with the presenter and form classes, right?

**Comment by jcoyne** [comment]
I think so. @dchandekstark what do you think?

**Comment by mjgiarlo** [comment]
Closing because we now have form and presenter classes.
