### ISSUE TITLE
User Profile links Manage UMG and Edit LDAP info go to Penn State

### ISSUE THREAD

**Issue by kerchner** [projecthydra/sufia#448]
Genericize this or remove Penn State-ness, on the Edit User Profile page:
- the Manage UMG button takes you to https://webaccess.psu.edu/?cosign-umg.its.psu.edu&https://umg.its.psu.edu/
- the Edit Info (LDAP) button links to http://www.work.psu.edu/ldap/#update

**Comment by mjgiarlo** [comment]
The Penn State-specific stuff has been removed in #864. Closing. Thanks!
