### ISSUE TITLE
Unify Redis monkeypatches and add a #since method

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#464]
In the course of working on 

https://github.com/projecthydra/sufia/pull/463/files#r13015773

@awead observed that our current Redis monkeypatches -- https://github.com/projecthydra/sufia/blob/master/sufia-models/lib/sufia/models/active_record/redis.rb and https://github.com/projecthydra/sufia/blob/master/sufia-models/lib/sufia/models/active_fedora/redis.rb -- which add the ability to pull back associated Redis data from AR and AF objects, could use some unification (like the stream, events, and create_event methods).

In addition it's worth considering providing a convenience method such as "since" to pull back a subset of events without having to iterate over all of them.  If this requires a data comparison, we'll probably need to change the way this data is stored in Redis (because you can only really act on keys, not values, the event timestamps are currently values).  Alternatively we could simplify the approach in the above PR and pull back the most recent n events instead of pulling all since a given date.

**Comment by cbeer** [comment]
The monkey patches seem to be gone. Maybe they moved upstream?

**Comment by jcoyne** [comment]
@cbeer I think they may have moved upstream and then been deleted as they didn't seem necessary. They may need to be brought back into sufia.

**Comment by jcoyne** [comment]
@cbeer have a look at this commit: https://github.com/projecthydra/sufia/commit/9e4d8e9318d86ed94b8b6b1af5db74d006c5e002

**Comment by jcoyne** [comment]
Perhaps this ticket is fixed by 9e4d8e9. @awead ?

**Comment by awead** [comment]
:confused: I have no recollection if this at all... so, we could close it, but open another ticket for the `since` method.

**Comment by mjgiarlo** [comment]
As the person who wrote this up, I'm happy to close it and move on. We haven't had a burning need for `#since` yet, so meh.

**Comment by awead** [comment]
:tada:
