### ISSUE TITLE
permissions.js should use global named event handlers

### ISSUE THREAD

**Issue by dchandekstark** [projecthydra/sufia#488]
https://github.com/projecthydra/sufia/blob/master/app/assets/javascripts/sufia/permissions.js
It's difficult (if not impossible) to override the anonymous functions here.  Also note that addPerm is defined inside an anonymous function.

**Comment by jcoyne** [comment]
@dchandekstark should this be closed?

**Comment by dchandekstark** [comment]
@jcoyne Yes, thanks, I believe our interest in this issue has expired. @coblej
