### ISSUE TITLE
Tag cloud overflows the container, especially on narrow displays.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#506]
![screen shot 2014-06-06 at 8 18 20 am](https://cloud.githubusercontent.com/assets/92044/3200704/8891082c-ed7f-11e3-8605-8613511b854b.png)

**Comment by tonmoy18** [comment]
Hi, is this still relevant?

**Comment by mtribone** [comment]
Ahhh...the tag cloud.

https://youtu.be/oGIFublvDes

**Comment by tonmoy18** [comment]
I could create a PR if it was still relevant...

**Comment by mtribone** [comment]
@tonmoy18 Go for it. We still use it at Penn State.

**Comment by cbeer** [comment]
I think we've since removed the tag cloud?

**Comment by mjgiarlo** [comment]
Correct. :+1:
