### ISSUE TITLE
Dashboard sidebar overflows on narrow displays

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#507]
![screen shot 2014-06-06 at 8 15 39 am](https://cloud.githubusercontent.com/assets/92044/3200710/aed3f256-ed7f-11e3-8c5f-5e8d5fd13298.png)

**Comment by mtribone** [comment]
![screen shot 2015-03-19 at 9 58 18 am](https://cloud.githubusercontent.com/assets/4163828/6731891/993bfae4-ce1e-11e4-979e-bda245445180.png)
![screen shot 2015-03-19 at 9 58 46 am](https://cloud.githubusercontent.com/assets/4163828/6731893/9d2f2c7a-ce1e-11e4-9fb7-f3fc05bb9687.png)
