### ISSUE TITLE
Include Overrides for color and theme from ScholarSphere into Sufia

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#641]
Check out the changes that were made here: https://github.com/psu-stewardship/scholarsphere/pull/32

We may want some or all of these changes in Sufia.

**Comment by mtribone** [comment]
If nobody objects, we can close this issue.

**Comment by mjgiarlo** [comment]
Have we pulled the relevant changes over into Sufia so that we can dump our ScholarSphere overrides?  If so, I'm :+1: on closing!

**Comment by mtribone** [comment]
Yeah man. And we even cleaned out the relevant files in ScholarSphere.

https://github.com/psu-stewardship/scholarsphere/commit/a6a29dc2fda2150c3b58698e82e936aeab915f16

**Comment by mjgiarlo** [comment]
@mtribone :fireworks: :fist: :metal: :clap:

**Comment by mtribone** [comment]
@mjgiarlo Just you wait until I propose the plan for icons on buttons.

**Comment by mjgiarlo** [comment]
TENTERHOOKS
