### ISSUE TITLE
SolrDocument to_model may cause a slowdown.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#685]
Found load_instance_to_solr was being called many times for each result in worthwhile and I recommend we port the change to Sufia:
https://github.com/curationexperts/worthwhile/commit/7b93b7f71075bae79acb6bd582cb1ffdcb11c825

**Comment by mjgiarlo** [comment]
Fixed in 98ab84b466d408eaf (fedora-4/master branch).
