### ISSUE TITLE
Batch edit fields are not displaying

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#820]
![screen shot 2014-12-30 at 10 12 16 pm](https://cloud.githubusercontent.com/assets/92044/5585421/030e6b46-9071-11e4-98c5-9b9cde38a822.png)

For this URL: http://localhost:3000/batch_edits/edit?batch_document_ids%5B%5D=a338160a-1817-43f3-878b-acd8cdc8d3bf&batch_document_ids%5B%5D=33f29ab7-e50e-496d-9602-db5adb8eb3d0&batch_document_ids%5B%5D=ad2722b8-a1cf-41d3-8184-4e15e24335d7

**Comment by mjgiarlo** [comment]
Fixed in b515386, @jcoyne?

**Comment by jcoyne** [comment]
Yea
