### ISSUE TITLE
replace jquery-ui autocomplete with typeahead.js

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#829]
https://twitter.github.io/typeahead.js/examples/

**Comment by cam156** [comment]
@jcoyne What is the reason for the change?  Does this fix any bugs, or just better technology?

**Comment by mjgiarlo** [comment]
@jcoyne Can you provide a brief rationale for this change? Either that or close the issue.

**Comment by hackmastera** [comment]
I've played around with this locally. Primary use case is providing 2 different authority sources as autocomplete options on the same autocomplete dropdown. Unfortunately typeahead doesn't come with any styling and I didn't get it to work right before I needed to move on, so I currently don't have anything to contribute back.

**Comment by mjgiarlo** [comment]
No rationale, so I am closing for now.

**Comment by jcoyne** [comment]
Rational: Use for multiple sources.
