### ISSUE TITLE
sass-rails compatibility

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#831]
``` bash
$ bundle exec rake
You have requested:
  sass-rails ~> 5.0

The bundle currently has sass-rails locked at 4.0.5.
Try running `bundle update sass-rails`
Run `bundle install` to install missing gems.
```
Sufia has no restrictions on which version of sass-rails it can use, so this might be in another gem somewhere.

**Comment by mjgiarlo** [comment]
As a temporary workaround, try setting RAILS_VERSION to 4.1.8 in your environment.

**Comment by mjgiarlo** [comment]
@jcoyne has dealt with this a bunch of times across the Hydrasphere, too, FYI.

**Comment by jcoyne** [comment]
@awead change the Gemfile to look like this: https://github.com/projecthydra-labs/hydra-collections/blob/master/Gemfile#L22-L27
