### ISSUE TITLE
Error when accessing collections as an unauthenticated user

### ISSUE THREAD

**Issue by phebal** [projecthydra/sufia#852]
In Sufia 4.3.1 I get an error when trying to view a collection as an unauthenticated user:
```
sufia-4.3.1/app/views/collections/_show_document_list_row.html.erb where line #8 raised:

undefined method `user_key' for nil:NilClass

ActionView::Template::Error (undefined method `user_key' for nil:NilClass):
     5:     <%# This block is for adding/removing the magic wand while batch updates are processing %>
     6:     <% if gf.processing? %>
     7:       <i class="glyphicon glyphicon-time <%= 'ss-'+gf.batch.noid %>"/>
     8:     <% elsif gf.depositor != @user.user_key %>
     9:       <i class="glyphicon glyphicon-share-alt"/>
    10:     <% end %>
    11:   </td>
  app/controllers/application_controller.rb:25:in `profile'
```

Is this a bug or maybe a mis-configuration on my end?

**Comment by hectorcorrea** [comment]
@phebal This is a bug. I've fixed this issue in the branch of Sufia that targets Fedora 4 (Sufia 6.x) but didn't back ported it to 4.3 or 5.x. Here are the details of the fix: https://github.com/projecthydra/sufia/commit/0a145de12c81f82692e8f7383474b63b3bb97570

**Comment by phebal** [comment]
@hectorcorrea  Thanks for the info, sorry I missed that. I'm closing this since it's fixed in the new version. Someone can reopen if there's an interest in back-porting your fix.
