### ISSUE TITLE
Migrate data in proxy_deposit_requests.pid

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#853]
They may have namespaces (e.g. "sufia:1234").  If you load that ProxyDepositRequest and call `#deleted_file?` it will use the old namespaced pid and you'll get a fedora error.

**Comment by cam156** [comment]
I created a rake task in ScholarSphere that could be migrated (or copied) to sufia. https://github.com/psu-stewardship/scholarsphere/blob/develop/lib/tasks/migrate.rake#L25-L39
