### ISSUE TITLE
Additional updates to date_modified

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#869]
date_modified is only changed when metadata is changed:

https://github.com/projecthydra/sufia/blob/master/sufia-models/app/actors/sufia/generic_file/actor.rb

Do we want to also change the modification date when any content is reverted or created? Or is metdata updated in tandem with those processes?

**Comment by awead** [comment]
@mjgiarlo this addresses what we were talking about in IRC today.

**Comment by mjgiarlo** [comment]
:+1: to this change. Though at that point... we may as well ditch our date_modified override and just use the fcr4-supplied value.

**Comment by awead** [comment]
@mjgiarlo I'm going to close this and suggest we do this on #928 for version 6.1, after we get Fedora 4 out the door.
