### ISSUE TITLE
Characterize mp4 files

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#877]
Characterization of mp4 files causes an error in Sorl because the apsectjrt jar file is missing. The jar file should be downloaded as part of the solr configuration rake task and we should characterize the mp4 file included in our fixtures for test coverage.

**Comment by jcoyne** [comment]
How is characterizing affecting Solr?  I was under the impression that Fits did the characterizing for us.

**Comment by awead** [comment]
@jcoyne good question. All know is that when I add the jar file, characterization works. I'll need to see if I can reproduce the problem in Sufia. For now, this is just to mark the issue.

**Comment by awead** [comment]
Incorrect error report. The correct one is #931.
