### ISSUE TITLE
Extract single_use_links_viewer_controller methods into a module?

### ISSUE THREAD

**Issue by weiweishi** [projecthydra/sufia#881]
We have overridden GenericFilePresenter locally to change/add metadata field for generic files. However in single_use_link_viewer_controller.rb it calls the following method, 
def presenter
    Sufia::GenericFilePresenter.new(@asset)
end
which we need to override to call our local GenericFilePresenter that include our local metadata terms.

I wonder if it's possible to extract what is currently in this controller class into a module (pretty much like it's in files_controller_behavior), so we can easily include Sufia::SingleUseLinksViewerControllerBehavior and override.

**Comment by mjgiarlo** [comment]
That seems reasonable to me.  Would you like to have a go at that, or would you prefer that someone else take that on?

**Comment by weiweishi** [comment]
Thanks Michael. I will take on this.

Weiwei

Michael J. Giarlo

That seems reasonable to me. Would you like to have a go at that, or would
you prefer that someone else take that on?

—
Reply to this email directly or view it on GitHub
<https://github.com/projecthydra/sufia/issues/881#issuecomment-71944190>.

**Comment by mjgiarlo** [comment]
Excellent!  If you run into difficulties, feel free to ask questions here or on #projecthydra.

**Comment by cam156** [comment]
@weiweishi @mjgiarlo Can this issue be closed now that  #895 has been merged?
