### ISSUE TITLE
Documentation: How do I add another field

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#904]
This would be a nice tutorial.

**Comment by jcoyne** [comment]
### Create the GenericFile model
the GenericFile class is typically provided by Sufia, but we want to update the model, so we define it in our app instead. Since Rails finds the class in our local application, it won't load it from Sufia.
```ruby
# app/models/generic_file.rb
class GenericFile < ActiveFedora::Base
  include Sufia::GenericFile
end
```

### Add the property
Add the property declaration into the `GenericFile` class:
```ruby
  property :alternative, predicate: ::RDF::DC.alternative
```

### Extend the presenter
We create a subclass of the presenter adding `alternative` to the list of terms
```ruby
# app/presenters/my_generic_file_presenter.rb
class MyGenericFilePresenter < Sufia::GenericFilePresenter
  self.terms = [:resource_type, :title, :creator, :contributor, :description, :tag, :rights,
       :publisher, :date_created, :subject, :language, :identifier, :based_near, :related_url, :alternative]
end
```

### Set the controller to use our presenter
```ruby
# app/controllers/generic_files_controller.rb
class GenericFilesController < ApplicationController
  include Sufia::Controller
  include Sufia::FilesControllerBehavior

  def presenter
    MyGenericFilePresenter.new(@generic_file)
  end
end
```

**Comment by jeremyf** [comment]
:+1: Good directions, though as @jcoyne suggested, injecting the classes would be nice.

**Comment by jcoyne** [comment]
Updated so it'll work with #906

**Comment by weiweishi** [comment]
The following should be added to the tutorial:

Create a batch form
# app/forms/my_batch_edit_form.rb
module Sufia
  module Forms
    class MyBatchEditForm < MyFileEditForm
    end
  end
end

And
add the following line to app/controllers/batch_controller.rb

  self. edit_form_class = MyFileEditForm
The whole file should look like this:

class BatchController < ApplicationController
  include Sufia::BatchControllerBehavior
  self.edit_form_class = MyBatchEditForm
end

**Comment by mjgiarlo** [comment]
@weiweishi I have merged your changes into the document above.  Though I made a small change: I removed the module declarations from the batch form.  Is that OK?

**Comment by weiweishi** [comment]
Yes @mjgiarlo. Thanks for the correction.

**Comment by mjgiarlo** [comment]
And thank you, @weiweishi, for helping make this better!  This is going to be so useful for Sufia adopters.

**Comment by scherztc** [comment]
Thanks for the function based tutorials/documentation.  Reading through the class based injections is really helpful for seeing how good coding patterns gets applied in an application.

**Comment by mjgiarlo** [comment]
Should this tutorial also include how to indicate that fields are repeatable and required, and how to customize labels and "helps?"  That would be a formidable tutorial indeed, and I think it'd save us some time judging by the interest and needs of folks as expressed in messages sent to hydra-tech over the past couple months. The new configuration with forms, presenters, and inputs is probably new to a bunch of folks.  (I know I probably have an outdated understanding of how to do this stuff.)

**Comment by weiweishi** [comment]
@mjgiarlo that would be great! I'm still looking for the place where I can customize fields to be non-repeatable.

**Comment by escowles** [comment]
These instructions are great -- but the process is involved enough that I'm wondering whether we should work on a generator to handle this and/or add an option to the sufia:install generator to do the one-time steps.

**Comment by awead** [comment]
:+1: to the generator idea, if that's feasible.

**Comment by mjgiarlo** [comment]
I dig it -- like RDF metadata scaffolding. :)

**Comment by mephillips-durham** [comment]
In case anyone else is a real newbie, like me, the MyGenericFilePresenter needs to go in the file app/presenters/my_generic_file_presenter.rb

Great instructions: worked first time!  Where do you go if you want to customise the field labels on the form?

**Comment by weiweishi** [comment]
Mattthew, the labelling is handled in the locale files. i.e.:
config/locale/sufia.en.yml file.


On Thu, Mar 12, 2015 at 10:59 AM, Matthew Phillips <notifications@github.com

**Comment by mjgiarlo** [comment]
I stepped through this myself to add one field and here's that commit:

https://bitbucket.org/uwlib/druw/commits/5b9124dd884f00a15b82d3e60aaf0840aae47dea#chg-config/locales/sufia.en.yml

The link is to the locales file which is where you can customize labels and helps.

**Comment by mjgiarlo** [comment]
Thanks for walking through that, @mephillips-durham!  I've added that correction to the instructions above.

**Comment by mjgiarlo** [comment]
@weiweishi Have you solved your repeatability concerns or are you working on that yet?

**Comment by mjgiarlo** [comment]
I'm moving this to a GitHub wiki page, btw, and linking it to the README.

**Comment by mjgiarlo** [comment]
I recommend we close this issue now that this is created:

https://github.com/projecthydra/sufia/wiki/Customizing-Metadata

And we either create new issues for gaps/opportunities in that document, or folks can feel free to edit it in place (since GitHub wiki pages are under version control).

@jcoyne ?
