### ISSUE TITLE
GenericFile Edit is requiring Resource Type

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#913]
Even though resource type is not marked as a required field on the UI the Generic File Edit form will not save unless a resource type is selected.

When I got to a file
And I click Edit
When the Resource Type is blank
And I hit save
Then I should not get an error requiring resource type

![screen shot 2015-02-18 at 12 43 09 pm](https://cloud.githubusercontent.com/assets/1599081/6253075/d8389da6-b76c-11e4-99f4-b3eff67ee488.png)

**Comment by cam156** [comment]
Collection Edit is also requiring resource type.

**Comment by hectorcorrea** [comment]
Interesting that file upload work as expected, but file edit does not.

**Comment by hectorcorrea** [comment]
Addressed in PR #935
