### ISSUE TITLE
There are two down arrow in search sort

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#914]
When I search sufia
And I have multiple search results
And I see a sort bar
Then there should be only one down arrow
(Just blue no black one)

![screen shot 2015-02-18 at 12 53 35 pm](https://cloud.githubusercontent.com/assets/1599081/6253164/6607bc34-b76d-11e4-8491-fa6ad7c503d3.png)

**Comment by jcoyne** [comment]
Should the "10 per page" also use the blue arrow?

**Comment by cam156** [comment]
@mtribone Yes or no to per page being blue too.

@jcoyne There is a larger issue that we have different sorting bars in collections dashboard, and search, but I have not yet put a ticket in for that.

**Comment by mtribone** [comment]
@cam156 @jcoyne I would say no to the blue arrow on all of them. We want the default Blacklight/Bootstrap and don't need the background images anymore.

![screen shot 2015-02-18 at 1 29 03 pm](https://cloud.githubusercontent.com/assets/4163828/6253843/62a74b7c-b772-11e4-8a3a-e2be93319cd4.png)

**Comment by jcoyne** [comment]
@mtribone :+1: to just the black arrows ever where.
