### ISSUE TITLE
Empty Batches

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#915]
When a user goes to the upload page a batch gets create
When the user refreshes the page a new batch gets created
When the user refreshes the page 100 times 100 batches get created
Then the system should not have 100 empty batches forever

This could be tackled in two ways: 1) periodically remove batches 2) change the process too not create the empty batches

We will eventually have empty batches in the system is a user uploads files and then deletes them, but that is a different scenario (and far less likely to occur regularly).

**Comment by hectorcorrea** [comment]
PR #961 delays the creation of batch. With this PR the batch will be created only if the user actually clicks on the "upload files" button rather than by just visiting the upload page. This will reduce the frequency of users leaving empty batches.
