### ISSUE TITLE
Collections Contain Zero bytes

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#917]
When add files to a collection
That have not yet been characterized
Then I should not get the collection size as zero

Basically what happens is the collection gets created and the total size gets calculated before the files are advertising their size at the top level.  We know the contents size so we could save this off before characterization.

![screen shot 2015-02-02 at 2 50 49 pm](https://cloud.githubusercontent.com/assets/1599081/6253618/d03b7f70-b770-11e4-95ff-ba120520107c.png)

**Comment by awead** [comment]
@cam156 should size be null if characterization hasn't been performed on all the files in the collection?

**Comment by cam156** [comment]
@awead. I was thinking we know the content size we could just use that

**Comment by awead** [comment]
@cam156 do you mean the number of files in the collection?

**Comment by cam156** [comment]
the content data stream size for each file should be roughly equivalent to the characterization size, so why wait..,

**Comment by awead** [comment]
actually, the size is in the resource header in Fedora4, so we don't need to use characterization in the first place.

**Comment by cam156** [comment]
This is now a Sufia 7.0 Issue

**Comment by cam156** [comment]
Verify that there is a delay in the calculation.
There is zero bytes and the collection has members say the number is being calculated.

**Comment by awead** [comment]
There was a recent change in Sufia that may have fixed this: https://github.com/projecthydra/sufia/pull/2646

**Comment by nrm149** [comment]
PSUSprint03
