### ISSUE TITLE
Edit Selected, Delete Selected, Add to Collection Buttons Stack Vertically in My Files

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#920]
When I go to the listing of my files and select several files to add to a collection, the buttons to edit, delete or add stack vertically. Buttons should be inline or float. Screen shot attached.

![screen shot 2015-02-13 at 10 57 10 am](https://cloud.githubusercontent.com/assets/1599081/6254222/efbf569c-b774-11e4-846a-bc0e8973d31e.png)

**Comment by mtribone** [comment]
Done.

![screen shot 2015-02-25 at 11 12 02 am](https://cloud.githubusercontent.com/assets/4163828/6374483/33d23e70-bcdf-11e4-9043-7ebe2f8056dd.png)

**Comment by mtribone** [comment]
https://github.com/projecthydra/sufia/pull/909
