### ISSUE TITLE
README is unclear with regard to Solr and Fedora

### ISSUE THREAD

**Issue by dmolesUC3** [projecthydra/sufia#927]
The README states in no uncertain terms
> **!! Ensure that you have [Solr and Fedora] installed before you continue. !!**

In fact, though, Sufia ships with its own Jetty server and its own distribution of Solr and Fedora, and if you have another Solr instance running on its default port of 8913, Sufia's Jetty server (which also uses port 8913, for both Solr and Fedora) will fail to start up.

Presumably the "embedded" Jetty is optional and one can point Sufia at existing Solr and Fedora instances by editing `fedora.yml` and `solr.yml`, but this isn't obvious from the rather terse Jetty instructions, which just tell you, full stop,
> **Get a copy of jetty (Solr and Fedora)**

It would be nice if these options were spelled out in the README.

**Comment by mjgiarlo** [comment]
Thanks for bringing this to our attention, @dmolesUC3.

**Comment by mjgiarlo** [comment]
Have a look now, @dmolesUC3, and let me know if I've covered it sufficiently.  Here's the diff:

https://github.com/projecthydra/sufia/commit/9d2c524a6979734cb9221ea0ce740f7908490114

If so, feel free to close this issue. Else, let me know how I can make it better and I'm happy to oblige.

**Comment by dmolesUC3** [comment]
Looks good, thanks!
