### ISSUE TITLE
Remove RDF::DC.modified predicate in favor of lastModified

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#928]
Fedora 4 already has predicates for keeping the date and time a resource was modified. We should use those to express when a GenericFile was modified.

**Comment by awead** [comment]
We should remove this propery
https://github.com/projecthydra/sufia/blob/master/sufia-models/app/models/concerns/sufia/generic_file/metadata.rb#L62
As it seems unnecessary since Fedora should already be doing it for us.

**Comment by mjgiarlo** [comment]
@awead Would you consider moving this issue to CurationConcerns? That's where this is being asserted now (on FileSets and all curation concerns, e.g., the GenericWorks we use in Sufia): https://github.com/projecthydra-labs/curation_concerns/blob/cf0765d0f5c95a7ab95cfe8044eddd1c593ae481/curation_concerns-models/app/models/concerns/curation_concerns/basic_metadata.rb

Alternatively, given our experience migrating to F4 (depending on Fedora-stored values that changed), might there be a good reason to have this duplicated in metadata that we manage/control?
