### ISSUE TITLE
Google Analytics User Rate limit Excceeded

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#937]
We got an error this morning from google analytics to say we are pinging them too quickly.  We may need to add additional sleep into the user_stat_importer

rake aborted! OAuth2::Error: {"errors"=>[{"domain"=>"usageLimits", "reason"=>"userRateLimitExceeded", "message"=>"User Rate Limit Exceeded"}], "code"=>403, "message"=>"User Rate Limit Exceeded"}: {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User Rate Limit Exceeded"}],"code":403,"message":"User Rate Limit Exceeded"}} /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/oauth2-0.9.4/lib/oauth2/client.rb:113:in `request' /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/oauth2-0.9.4/lib/oauth2/access_token.rb:107:in `request' /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/oauth2-0.9.4/lib/oau!
 th2/access_token.rb:114:in `get' /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/legato-0.4.0/lib/legato/management/finder.rb:11:in `all' /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/legato-0.4.0/lib/legato/user.rb:47:in `profiles' /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/bundler/gems/sufia-9fa6e7e85a2d/sufia-models/app/services/sufia/analytics.rb:45:in `profile' /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/bundler/gems/sufia-9fa6e7e85a2d/sufia-models/app/models/file_download_stat.rb:15:in `ga_statistics' /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/bundler/gems/sufia-9fa6e7e85a2d/sufia-models/app/models/concerns/sufia/file_stat_utils.rb:24:in `combined_stats' /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/bundler/gems/sufia-9fa6e7e85a2d/sufia-models/app/models/file_download_stat.rb:9:in `statistics' /opt/heracles/deploy/scholarsphere/releases/20150225110756/lib/sufia/models/s!
 tats/user_stat_importer.rb:21:in `block (2 levels) in import' /opt/heracles/deploy/scholarsphere/releases/20150225110756/lib/sufia/models/stats/user_stat_importer.rb:16:in `each' /opt/heracles/deploy/scholarsphere/releases/20150225110756/lib/sufia/models/stats/user_stat_importer.rb:16:in `block in import' /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/relation/batches.rb:52:in `block (2 levels) in find_each' /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/relation/batches.rb:52:in `each' /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/relation/batches.rb:52:in `block in find_each' /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/relation/batches.rb:125:in `find_in_batches' /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/ac!
 tive_record/relation/batches.rb:51:in `find_each' /opt/heracles/deploy/!
 scholarsphere/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.7/lib/active_record/querying.rb:9:in `find_each' /opt/heracles/deploy/scholarsphere/releases/20150225110756/lib/sufia/models/stats/user_stat_importer.rb:11:in `import' /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/bundler/gems/sufia-9fa6e7e85a2d/sufia-models/lib/tasks/stats_tasks.rake:8:in `block (3 levels) in <top (required)>' Tasks: TOP => sufia:stats:user_stats (See full trace by running task with --trace) Begin import of User stats. Working on user archivist2 Working on user cam156 Working on user jgm106 Working on user mjg36 Working on user bah1 Working on user dmc186 Working on user audituser Working on user mcc171 Working on user mjf25 Working on user pmh22 Working on user lxf5 Working on user gmr159 Working on user esc10 Working on user cdc17 Working on user ajs23 Working on user cjh Working on user mum28 Working on user dvm105 Working on user sjw31 Working on user uxb5 Working on user jjm38 !
 Working on user bmg17 Working on user tlr15 Working on user lbg10 Working on user skp1 Working on user jkj2 Working on user lad304 Working on user njb2 Working on user dst5089 Working on user dgn2 Working on user peg5029 Working on user ard19 Working on user iym6 Working on user sxh36 Working on user avh3 Working on user cpl2 Working on user batchuser Working on user jxb13 Working on user bid1 Working on user rlr27 Working on user asc17 Working on user rdd3 Working on user gnf1 Working on user kfb3 Working on user rdd2 Working on user clh378 Working on user pha3 Working on user ejs236 Working on user kka1 Working on user siw101 Working on user jlh35 Working on user f13 Working on user mwr143 Working on user epd103 Working on user mam58 Working on user xxl12 Working on user ssb168 Working on user jkl1 Working on user frd1 Working on user yzz2 Working on user jlh502 Working on user jsr25 Working on user xn8 Working on user jfs126 Working on user saw36 Working on user sdq Work!
 ing on user jkc103 Working on user jcr264 Working on user bak3 Working !
 on user sxs551 Working on user tmc210 Working on user mds286 Working on user mab39 Working on user bld14 Working on user abg3 Working on user cwc5 Working on user mac17 Working on user pag191 Working on user sad220 Working on user dxf19 Working on user tdp11

**Comment by hectorcorrea** [comment]
We seem to get at least 3 kinds OAuth2:Error

    OAuth2::Error:
    "domain"=>"global", 
    "reason"=>"internalError", 
    "message"=>"There was an internal error."
    "code"=>500, 
    "message"=>"There was an internal error."

    OAuth2::Error: 
    "domain":"global",
    "reason":"backendError",
    "message":"There was a temporary error. Please try again later."
    "code":503,
    "message":"There was a temporary error. Please try again later."

    OAuth2::Error: 
    "domain":"global",
    "reason":"dailyLimitExceeded",
    "message":"Quota Error: profileId ga:NNNNNNNN has exceeded the daily request limit."
    "code":403,
    "message":"Quota Error: profileId ga:NNNNNNNN has exceeded the daily request limit."

**Comment by hectorcorrea** [comment]
First steps to address this issue have been implemented in PR #957

**Comment by carventfix** [comment]
como fuciona esto no tengo la menor idea no seria mas facil mostrar el contenido y ya  ustedes son expertos  pero yo no tengo la mas remota idea pero gracias     seguire buscando a alguin que no pida la acta de defuncion...
