### ISSUE TITLE
Metadata should not bump to the next line

### ISSUE THREAD

**Issue by mtribone** [projecthydra/sufia#939]
When I view the show page for a collection, the metadata for resource type is bumping to the next line. When I view the source, I find an empty anchor element with a partial href and a break element. I don't expect these to be there. See screen shot.

![screen shot 2015-02-26 at 2 29 00 pm](https://cloud.githubusercontent.com/assets/4163828/6400158/24fb31d6-bdc5-11e4-83a8-064923f49b38.png)

**Comment by mtribone** [comment]
Also in rights

![screen shot 2015-02-26 at 2 50 27 pm](https://cloud.githubusercontent.com/assets/4163828/6400438/daf8b70a-bdc6-11e4-8a16-958d3b3bb5c0.png)

**Comment by mtribone** [comment]
Made adjustments in the style sheet to pull dt and dd closer, but extra line needs to be resolved.

![screen shot 2015-03-03 at 9 54 52 am](https://cloud.githubusercontent.com/assets/4163828/6464920/957f148a-c18b-11e4-9f33-34ab517471ac.png)

**Comment by mtribone** [comment]
It appears that empty strings are being added when the collection is created or edited. Not likely an issue with a view. See Rails output below:

![screen shot 2015-03-11 at 10 26 25 am](https://cloud.githubusercontent.com/assets/4163828/6598319/417fbb9c-c7d9-11e4-88db-e3b5b6a897f5.png)

**Comment by mtribone** [comment]
So I think that I know how it is happening. When I create a new collection and add metadata by entering text and hitting the return key, another field appears underneath. If I decide to not add more metadata and leave the new field empty and hit save, I get an empty string.

**Comment by mtribone** [comment]
I created a new collection, entered a name for creator and hit the return key. New field appears under the one I just filled out. Hit save and an empty string appears as the first item.

![screen shot 2015-03-12 at 10 49 29 am](https://cloud.githubusercontent.com/assets/4163828/6620150/8a52895e-c8a5-11e4-8581-fb040d60e7e1.png)

**Comment by mjgiarlo** [comment]
I wonder if this is a regression related to https://github.com/projecthydra/sufia/pull/948

**Comment by mtribone** [comment]
Good question @mjgiarlo . Perhaps because if I look at my original screen shots they were affecting the select list and rights dropdown, too. I don't directly see how the use of a return key on other metadata in form would add empty strings there?

**Comment by mjgiarlo** [comment]
@mtribone Maybe there are two behaviors at play here and I just conflated them:

1. Return key adds a new field
2. New field generates an empty string when processed

**Comment by mtribone** [comment]
@mjgiarlo :metal: Right on, man.

**Comment by mjgiarlo** [comment]
I didn't complete my thought.  Ugh.  One of those days.

I don't have many opinions about number 1 -- I defer to your sensibilities on that one!  Number 2 seems like a bug to me, and one we should have tests for.  (I'm also not suggesting that you tackle this all yourself, but thanks for documenting this bug so thoroughly.)

**Comment by mtribone** [comment]
@mjgiarlo I think that I understood where you were going. Thanks! I was trying to track down the display issue and just went from there. Understood. I am not assigned and hopped over to ScholarSphere to look at removing some overrides for collections and such.

**Comment by mjgiarlo** [comment]
Related to #1040?

**Comment by mtribone** [comment]
@mjgiarlo Nope not related to #1040

**Comment by mjgiarlo** [comment]
We're now using different templates for most of this, so I'm closing until we reproduce this in master.
