### ISSUE TITLE
GenericFiles and Collections are saved with blank strings for empty form fields

### ISSUE THREAD

**Issue by phebal** [projecthydra/sufia#941]
When updating or creating GenericFiles or Collections, attributes that stem from blank fields in forms are saved as either `""` or `[""]` depending on the type. I'm not sure if this change is intentional but Sufia 4.x preserved them as either `nil` or `[]`. One side effect of this is that it breaks the `Sufia::CollectionPresenter#terms_with_values` for multi-value attributes because `[""].present?` evaluates to `true`.

**Comment by jcoyne** [comment]
@phebal can you give an example about how you are creating these?  This method should be clearing them out: https://github.com/projecthydra-labs/hydra-editor/blob/master/app/forms/hydra_editor/form.rb#L48-L54

**Comment by jcoyne** [comment]
Here's a test illustrating how `model_attributes` should work: https://github.com/projecthydra-labs/hydra-editor/blob/c9718aedb6fc7fa952efe02df2519d839eaea8bb/spec/forms/hydra_editor_form_permissions_spec.rb#L24-L30

**Comment by phebal** [comment]
Thanks for responding @jcoyne, it does look like this works as it's supposed to in the latest version of Hydra Editor. I'm running into this issue because I'm using what comes with current Sufia (1.0.1). I guess it'll be brought to the latest version by the time of final release so I'll close this ticket.

**Comment by phebal** [comment]
Wait, nevermind, I see `model_attributes`  method in 1.0.1. I'll check and re-open if I need to.

**Comment by phebal** [comment]
Ok, so I tracked it down for Collections:
https://github.com/phebal/sufia/commit/2ee92009a917df9652e16ff4691239e00666ab07

This doesn't solve the issue with params containing empty strings as `HydraEditor::Form#model_attributes` doesn't remove them.

I also see blanks being saved for file characterization stuff in GenericFile, but not other metadata.

**Comment by jcoyne** [comment]
Your fix looks good to me. Can you make a pull request?

**Comment by phebal** [comment]
@jcoyne sure, I'll try to fix a similar problem with `GenericFile` before I do though.
