### ISSUE TITLE
Auto linking urls in the description field

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#942]
As a user
When I add "http://my.link.com/" to the description field
Then I should see a link to my.link.com

**Comment by awead** [comment]
heh. Github does it...

**Comment by jcoyne** [comment]
Also, when I link to `javascript:alert('foo')` It should not be a link.

**Comment by mjgiarlo** [comment]
#943 was already merged, it looks like.  Is this a concern we should test, @jcoyne?

**Comment by jcoyne** [comment]
Maybe waiting for other institutions to review PRs is a good idea.

**Comment by jcoyne** [comment]
Anyways, it uses auto_link, so it' probably okay.

**Comment by jcoyne** [comment]
Should this be closed?

**Comment by awead** [comment]
@jcoyne This specific issue is fixed, but if there are concerns with the javascript, we should create a new issue.
