### ISSUE TITLE
Sufia not overriding Hydra::Controller::ControllerBehavior.search_builder

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#953]
Although the inclusion process looks correct, Sufia is not overriding Blacklight's `search_builder` with the one here:

https://github.com/projecthydra/hydra-head/blob/master/hydra-core/app/controllers/concerns/hydra/controller/controller_behavior.rb#L20

**Comment by mjgiarlo** [comment]
Is Sufia using the search_builder_class config as described here: https://github.com/projecthydra/hydra-head/releases/tag/v9.1.0 ?

**Comment by awead** [comment]
@mjgiarlo yes. that was added to the config generator, but it didn't work.

**Comment by jcoyne** [comment]
Here's the issue:
```
irb(main):001:0> CatalogController.ancestors
=> [CatalogController, BlacklightAdvancedSearch::Controller, Sufia::Catalog, BlacklightAdvancedSearch::ParseBasicQ, Blacklight::Catalog, Blacklight::Facet, Blacklight::Catalog::ComponentConfiguration, Blacklight::Base, Blacklight::Catalog::SearchContext, Blacklight::SearchHelper, Blacklight::RequestBuilders, Blacklight::Configurable, #<Module:0x007fbba4f4bb60>, ApplicationController, Hydra::Controller::ControllerBehavior, Sufia::Controller, Blacklight::SearchFields, Blacklight::Controller,...
```

We need Hydra::Controller::ControllerBehavior before Blacklight::Catalog.

**Comment by jcoyne** [comment]
This is caused by BlacklightAdvancedSearch doing monkeypatches: https://github.com/projectblacklight/blacklight_advanced_search/blob/bde108cfeeb26b6a808b7f7dfb81bc4b1b5433c8/lib/blacklight_advanced_search/engine.rb#L16

**Comment by jcoyne** [comment]
@awead I think this was fixed at one time by https://github.com/projectblacklight/blacklight_advanced_search/pull/24
but then it was reverted.

**Comment by awead** [comment]
@jcoyne I attempted this by cherry-picking your original commit into my fork:

https://github.com/awead/blacklight_advanced_search/commit/9e7f9e709a25531f50aa6508b8850f5ef49ce762

Then, adding `include BlacklightAdvancedSearch::Controller` to the CatalogController, but I'm still coming up with the same error.
