### ISSUE TITLE
Migration Notes from 5.x to 6.x

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#966]

**Comment by mjgiarlo** [comment]
Can we change this to migration notes from 4.3.1/5.x to 6.0.0?  I suspect that no one is using 5.0 yet since it's still in RC, and that the migration path is nearly identical.

**Comment by mjgiarlo** [comment]
IOW, I suspect the common migration path is going to be from 4.3.1 straight to 6.0.

**Comment by hectorcorrea** [comment]
I've started documenting the process to migrate from 5.x to 6.x in this page: https://github.com/projecthydra/sufia/wiki/Migration-Notes-from-5.x-to-6.x
