### ISSUE TITLE
FITS download page

### ISSUE THREAD

**Issue by alexwhitman** [projecthydra/sufia#967]
The FITS project has moved from Google Code to http://projects.iq.harvard.edu/fits/ so the link in the README should be updated.

It's a trivial change but we don't have a CLA sorted out yet otherwise I would have submitted a pull request.

**Comment by mjgiarlo** [comment]
Thank you, @alexwhitman!  I'll make the change now.

**Comment by mjgiarlo** [comment]
Closed by https://github.com/projecthydra/sufia/commit/dcd464a03a340d1ec374687cd75c6b6eb94671a7.
