### ISSUE TITLE
Required Ruby version

### ISSUE THREAD

**Issue by alexwhitman** [projecthydra/sufia#987]
The README suggests that Ruby 2.2 is preferred or the latest release of 2.1.  CentOS 7 packages Ruby 2.0.0-p353 and, after some rudimentary testing, Sufia appears to work fine.

Are there any known issues with using using that version that we should be aware of?  While we can install a newer version of Ruby with rbenv, using the OS packaged version is a lot simpler to manage.

**Comment by jcoyne** [comment]
Ruby 2.0.0 should work okay, but newer versions of Ruby should have better
garbage collection and thus perform better.

-Justin

**Comment by alexwhitman** [comment]
Thanks.  We'll keep testing with it and see if we hit any issues or performance problems.
