### ISSUE TITLE
Create a Generic Work

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#996]
It should have many GenericFiles

* Does not need to use PCDM so that we can move forward with sufia development and views

**Comment by cam156** [comment]
blah

**Comment by mtribone** [comment]
Is this related to #998?

**Comment by cam156** [comment]
Use has_members and belnongs_to relationships

**Comment by cam156** [comment]
This is a model level implementation of a Work.  This may be an opportunity to come close to worthwhile by grabbing their implementation of a work at the model level and add it into sufia: https://github.com/projecthydra-labs/worthwhile/blob/master/worthwhile-models/app/models/generic_work.rb
